<?php

namespace Database\Seeders;

use App\Models\Chapter;
use App\Models\Subchapter;
use App\Models\Lesson;
use Illuminate\Database\Seeder;

class JupyterRomanianSeeder extends Seeder
{
    private int $courseId = 5; // Informatica 8

    // Chapter/subchapter title translations
    private array $chapterTitles = [
        'Uvod u Jupyter' => 'Introducere in Jupyter',
        'Nizovi podataka i dijagrami' => 'Siruri de date si diagrame',
        'Prosek, procenti i analiza' => 'Media, procente si analiza',
        'Tabele i pandas' => 'Tabele si pandas',
        'Ucitavanje podataka i projekat' => 'Incarcarea datelor si proiect',
    ];

    private array $subchapterTitles = [
        'Upoznavanje sa Jupyterom' => 'Cunoasterea Jupyter',
        'Liste i vizuelizacija' => 'Liste si vizualizare',
        'Analiza podataka' => 'Analiza datelor',
        'Rad sa tabelama' => 'Lucrul cu tabele',
        'Spoljni podaci' => 'Date externe',
    ];

    private array $lessonTitles = [
        'Sta je Jupyter?' => 'Ce este Jupyter?',
        'Jupyter celije' => 'Celulele Jupyter',
        'Racunanje u Jupyteru' => 'Calcule in Jupyter',
        'Domaci: Moj prvi notebook' => 'Tema: Primul meu notebook',
        'Nizovi (liste) podataka' => 'Siruri (liste) de date',
        'Linijski dijagrami' => 'Diagrame liniare',
        'Stubicasti dijagrami i histogrami' => 'Diagrame cu bare si histograme',
        'Domaci: Vizuelizacija podataka' => 'Tema: Vizualizarea datelor',
        'Prosek niza brojeva' => 'Media unui sir de numere',
        'Procenti i sektorski dijagrami' => 'Procente si diagrame sectoriale',
        'Frekvencijska analiza' => 'Analiza frecventei',
        'Domaci: Analiza podataka' => 'Tema: Analiza datelor',
        'Tabelarno predstavljanje podataka' => 'Reprezentarea tabelara a datelor',
        'Filtriranje i sortiranje tabela' => 'Filtrarea si sortarea tabelelor',
        'Vizuelizacija tabela' => 'Vizualizarea tabelelor',
        'Domaci: Rad sa tabelama' => 'Tema: Lucrul cu tabele',
        'Ucitavanje iz CSV fajlova' => 'Incarcarea din fisiere CSV',
        'Modifikacija tabele' => 'Modificarea tabelelor',
        'Jupyter i Excel' => 'Jupyter si Excel',
        'Zavrsni projekat: Analiza podataka' => 'Proiect final: Analiza datelor',
    ];

    private function translateContent(string $content): string
    {
        // Large translation map: Serbian -> Romanian
        // Order matters - longer phrases first to avoid partial replacements
        $translations = [
            // === MISSED PHRASES ===
            'math.sqrt() - kvadratni koren' => 'math.sqrt() - radacina patrata',
            'math.ceil() - zaokruzi navise' => 'math.ceil() - rotunjeste in sus',
            'math.floor() - zaokruzi nanize' => 'math.floor() - rotunjeste in jos',
            '(navise!)' => '(in sus!)',
            '(nanize!)' => '(in jos!)',
            'math.pi - broj Pi' => 'math.pi - numarul Pi',
            'To je <strong>Jupyter notebook</strong> (cita se "dzupajter").' => 'Acesta este un <strong>Jupyter notebook</strong> (se citeste "giupaiter").',
            'Klikni na zeleno dugme <strong>Run All</strong>' => 'Apasa butonul verde <strong>Run All</strong>',
            ', cak i bez <code>print()</code>!' => ', chiar si fara <code>print()</code>!',
            'Python i R.' => 'Python si R.',
            '<strong>celija</strong>' => '<strong>celule</strong>',

            // === PYTHON CODE - variable names, strings, comments ===
            // Variable names (careful with word boundaries)
            "'ime'" => "'nume'",
            "'Ime'" => "'Nume'",
            "ime = '" => "nume = '",
            "ime = " => "nume = ",
            "'godine'" => "'varsta'",
            "godine = " => "varsta = ",
            "{ime}" => "{nume}",
            "{godine}" => "{varsta}",
            "'predmet'" => "'materie'",
            "predmet = " => "materie = ",
            "{predmet}" => "{materie}",
            "'ocena'" => "'nota'",
            "ocena = " => "nota = ",
            "{ocena}" => "{nota}",
            "ocene = " => "note = ",
            "'ocene'" => "'note'",
            "ocene)" => "note)",
            "ocene]" => "note]",
            "ocene," => "note,",
            "ocene." => "note.",
            "[ocene" => "[note",
            "ocene'" => "note'",
            "'razred'" => "'clasa'",
            "razred = " => "clasa = ",
            "'Razred'" => "'Clasa'",
            "'prezime'" => "'prenume'",
            "prezime = " => "prenume = ",
            "{prezime}" => "{prenume}",
            "'devojcice'" => "'fete'",
            "devojcice = " => "fete = ",
            "{devojcice}" => "{fete}",
            "devojcice /" => "fete /",
            "'decki'" => "'baieti'",
            "decki = " => "baieti = ",
            "{decki}" => "{baieti}",
            "'ukupno'" => "'total'",
            "ukupno = " => "total = ",
            "{ukupno}" => "{total}",
            "/ ukupno)" => "/ total)",
            "'predmeti'" => "'materii'",
            "predmeti = " => "materii = ",
            "'ucenici'" => "'elevi'",
            "ucenici = " => "elevi = ",
            "'temperatura'" => "'temperatura'",
            "temperature = " => "temperaturi = ",
            "temperature)" => "temperaturi)",
            "temperature]" => "temperaturi]",
            "[temperature" => "[temperaturi",
            "'meseci'" => "'luni'",
            "meseci = " => "luni = ",
            "meseci[" => "luni[",
            "'prosek'" => "'media'",
            "prosek = " => "media = ",
            "{prosek}" => "{media}",
            "prosek)" => "media)",
            "'prodaja'" => "'vanzari'",
            "prodaja = " => "vanzari = ",
            "prodaja." => "vanzari.",
            "prodaja[" => "vanzari[",
            "'podaci'" => "'date'",
            "podaci = " => "date_df = ",
            "podaci[" => "date_df[",
            "podaci)" => "date_df)",
            'podaci.' => 'date_df.',
            "'tabela'" => "'tabel'",
            "tabela = " => "tabel = ",
            "tabela[" => "tabel[",
            "tabela." => "tabel.",
            "tabela)" => "tabel)",
            "'brojevi'" => "'numere'",
            "brojevi = " => "numere = ",
            "brojevi)" => "numere)",
            "'bodovi'" => "'puncte'",
            "bodovi = " => "puncte_v = ",
            "'brojac'" => "'contor'",
            "brojac = " => "contor = ",
            "brojac." => "contor.",
            "brojac)" => "contor)",
            "'odgovori'" => "'raspunsuri'",
            "odgovori = " => "raspunsuri = ",
            "odgovori)" => "raspunsuri)",
            "len(odgovori)" => "len(raspunsuri)",
            "'fudbal'" => "'fotbal'",
            "'Fudbal'" => "'Fotbal'",
            "'sportovi'" => "'sporturi'",
            "sportovi = " => "sporturi = ",
            "'glasovi'" => "'voturi'",
            "glasovi = " => "voturi = ",
            "glasovi)" => "voturi)",
            "'polozili'" => "'promovat'",
            "polozili = " => "promovat = ",
            "'Ponasanje'" => "'Comportament'",
            "'Aktivnost'" => "'Activitate'",
            "'Domaci'" => "'Tema'",
            "'Sladoledi'" => "'Inghetate'",
            "'Cokolade'" => "'Ciocolate'",
            "'Prevoz'" => "'Transport'",
            "'Hrana'" => "'Mancare'",
            "'Ulaznice'" => "'Bilete'",
            "'Suveniri'" => "'Suveniruri'",
            "'Stanovnici'" => "'Locuitori'",
            "'Povrsina_km2'" => "'Suprafata_km2'",
            "'Gustina'" => "'Densitate'",
            "'Pobede'" => "'Victorii'",
            "'Nereseno'" => "'Egaluri'",
            "'Porazi'" => "'Infrangeri'",
            "'Golovi_dati'" => "'Goluri_marcate'",
            "'Golovi_primljeni'" => "'Goluri_primite'",
            "'Ucenik'" => "'Elev'",
            "'Bodovi'" => "'Puncte'",
            "'Grad'" => "'Oras'",
            "Ucenik" => "Elev",

            // Print strings
            "'Prvi red'" => "'Prima linie'",
            "'Drugi red'" => "'A doua linie'",
            "'Zdravo, ja sam Jupyter!'" => "'Buna, eu sunt Jupyter!'",
            "'Danas ucimo nesto novo i zanimljivo!'" => "'Astazi invatam ceva nou si interesant!'",
            "'Zdravo svete!'" => "'Salut lume!'",
            "f'Zdravo, {" => "f'Buna, {",
            "'Rezultat je:'" => "'Rezultatul este:'",
            "f'{ime} ima {godine} godina.'" => "f'{nume} are {varsta} ani.'",
            "f'Sledece godine {ime} ce imati {godine} godina.'" => "f'Anul viitor {nume} va avea {varsta} ani.'",
            "f'Iz predmeta {predmet} imam ocenu {ocena}.'" => "f'La materia {materie} am nota {nota}.'",
            "'Moje ocene:'" => "'Notele mele:'",
            "'Zaokruzeno:'" => "'Rotunjit:'",

            // f-string keys used in code
            "'Ocene:'" => "'Note:'",
            "'Broj ocena:'" => "'Numarul de note:'",
            "'Prva ocena:'" => "'Prima nota:'",
            "'Poslednja ocena:'" => "'Ultima nota:'",
            "'Prva tri:'" => "'Primele trei:'",
            "'Ucenici:'" => "'Elevi:'",
            "'Drugi ucenik:'" => "'Al doilea elev:'",
            "'Zbir:'" => "'Suma:'",
            "'Najmanji:'" => "'Cel mai mic:'",
            "'Najveci:'" => "'Cel mai mare:'",
            "'Prosek:'" => "'Media:'",
            "'Pre:'" => "'Inainte:'",
            "'Posle dodavanja:'" => "'Dupa adaugare:'",
            "'Posle brisanja:'" => "'Dupa stergere:'",
            "'Originalno:'" => "'Original:'",
            "'Sortirano:'" => "'Sortat:'",
            "'Obrnuto:'" => "'Inversat:'",
            "'Po abecedi:'" => "'Dupa alfabet:'",
            "'Temperature po danima:'" => "'Temperaturi pe zile:'",
            "'Gde je trojka?'" => "'Unde este 3?'",
            "'Gde je prva 5?'" => "'Unde este primul 5?'",
            "'Najtopliji dan:'" => "'Cea mai calda zi:'",
            "'Najhladniji dan:'" => "'Cea mai rece zi:'",
            "'Broj merenja:'" => "'Numarul de masuratori:'",
            "'Koren od'" => "'Radacina din'",
            "'Pi zaokruzeno'" => "'Pi rotunjit'",
            "'Pi ='" => "'Pi ='",
            "Koliko procenata" => "Ce procent",

            // Comments that may have been missed
            "# Upisi svoje ocene iz informatike" => "# Scrie notele tale la informatica",
            "# zameni svojim ocenama" => "# inlocuieste cu notele tale",
            "# poluprecnik u cm" => "# raza in cm",
            "# Izracunaj obim" => "# Calculeaza perimetrul",
            "# Izracunaj prosek" => "# Calculeaza media",
            "# Izracunaj" => "# Calculeaza",
            "# Napravi" => "# Creeaza",
            "# Nacrtaj" => "# Deseneaza",
            "# Sortiraj" => "# Sorteaza",
            "# Zameni" => "# Inlocuieste",
            "# dopuni" => "# completeaza",
            "# koristimo" => "# folosim",
            "# sabira" => "# aduna",
            "# jer" => "# deoarece",

            // Remaining section words
            "sekundi_u_minutu" => "secunde_pe_minut",
            "minuta_u_satu" => "minute_pe_ora",
            "sati_u_danu" => "ore_pe_zi",
            "# sekundi u jednom danu" => "# secunde intr-o zi",
            "# sekundi u jednoj nedelji" => "# secunde intr-o saptamana",
            "# sekundi u jednoj godini" => "# secunde intr-un an",
            "omiljeni_predmet" => "materia_preferata",

            // Data column names that appear as strings in DataFrames
            "'Ime'" => "'Nume'",
            "'Matematika'" => "'Matematica'",
            "'Srpski'" => "'Romana'",
            "'Informatika'" => "'Informatica'",
            "'Fizicko'" => "'Ed. fizica'",
            "'Fizika'" => "'Fizica'",
            "'Biolog.'" => "'Biolog.'",
            "'Likovno'" => "'Desen'",
            "'Muzicko'" => "'Muzica'",
            "'Engl.'" => "'Engl.'",
            "'Mesec'" => "'Luna'",
            "'Predmet'" => "'Materia'",
            "'Test_1'" => "'Test_1'",
            "'Test_2'" => "'Test_2'",

            // === REMAINING CODE FIXES ===
            // print strings inside code cells (HTML-encoded in notebook JSON)
            "print(&#039;Prvi red&#039;)" => "print(&#039;Prima linie&#039;)",
            "print(&#039;Drugi red&#039;)" => "print(&#039;A doua linie&#039;)",
            "godine + 1" => "varsta + 1",
            "Posle append(4):" => "Dupa append(4):",
            "Posle remove(3):" => "Dupa remove(3):",
            "Gde je trojka?" => "Unde este 3?",
            "Gde je prva 5?" => "Unde este primul 5?",
            "obrisana je trojka" => "a fost sters 3-ul",
            "obrisana samo prva petica" => "stearsa doar primul 5",
            "na poziciji 3" => "pe pozitia 3",
            "na poziciji 0" => "pe pozitia 0",
            "# Zdravo svete!" => "# Salut lume!",
            "Zdravo, {" => "Buna, {",

            // Remaining variable references
            "sekundi_u_minutu" => "secunde_pe_minut",
            "'prezime'" => "'prenume'",
            "prezime'" => "prenume'",
            "Ucenik'" => "Elev'",
            "'Ucenik'" => "'Elev'",
            "Bodovi'" => "Puncte'",
            "'Bodovi'" => "'Puncte'",

            // Code comments
            "# Nacrtaj stubicasti dijagram" => "# Deseneaza diagrama cu bare",
            "# Nacrtaj obe linije" => "# Deseneaza ambele linii",
            "# Nacrtaj horizontalni" => "# Deseneaza orizontal",
            "# Nacrtaj histogram" => "# Deseneaza histograma",
            "# Nacrtaj sektorski" => "# Deseneaza sectoriala",
            "# Nacrtaj oba dijagrama" => "# Deseneaza ambele diagrame",
            "# Nacrtaj" => "# Deseneaza",
            "# Izracunaj prosek" => "# Calculeaza media",
            "# Izracunaj bodove" => "# Calculeaza punctele",
            "# Izracunaj procente" => "# Calculeaza procentele",
            "# Izracunaj obim" => "# Calculeaza perimetrul",
            "# Izracunaj" => "# Calculeaza",
            "# Napravi tabelu" => "# Creeaza tabelul",
            "# Napravi fudbalsku" => "# Creeaza clasamentul",
            "# Napravi" => "# Creeaza",
            "# Sortiraj i prikazi" => "# Sorteaza si afiseaza",
            "# Sortiraj" => "# Sorteaza",

            // Remaining print format strings
            // Remaining embedded strings
            "print(&#039;Zdravo&#039;)" => "print(&#039;Buna&#039;)",
            ">Zdravo</td>" => ">Buna</td>",
            "ucenika" => "elevilor",
            "ucenici, bodovi" => "elevi, puncte_v",
            "plt.barh(ucenici" => "plt.barh(elevi",
            "ocene_odeljenja" => "note_clasa",
            "prosecne" => "medii",
            "Prosecne" => "Medii",
            "'Prezime'" => "'Prenume'",
            "'prezime'" => "'prenume'",

            // Final remaining
            "print('Zdravo')" => "print('Buna')",
            "# nacrtaj liniju" => "# deseneaza linia",
            "bodovi)" => "puncte_v)",
            "bodovi >" => "puncte_v >",
            "bodovi &gt;" => "puncte_v &gt;",
            "bodovi," => "puncte_v,",
            "(bodovi" => "(puncte_v",
            "odredi_ocenu" => "determina_nota",
            "Ime,Prezime,Ocena,Grad" => "Nume,Prenume,Nota,Oras",
            "Ime,Prezime,Ocena,Oras" => "Nume,Prenume,Nota,Oras",
            "Ana,Petrovic" => "Ana,Petrovic",
            "Marko,Jovanovic" => "Marko,Jovanovic",
            "Jovana,Nikolic" => "Jovana,Nikolic",
            '<strong>celije</strong>' => '<strong>celule</strong>',

            // === HTML HEADINGS AND PARAGRAPHS ===
            // Lesson titles in h2
            'Sta je Jupyter?' => 'Ce este Jupyter?',
            'Jupyter celije' => 'Celulele Jupyter',
            'Racunanje u Jupyteru' => 'Calcule in Jupyter',
            'Domaci: Moj prvi notebook' => 'Tema: Primul meu notebook',
            'Nizovi (liste) podataka' => 'Siruri (liste) de date',
            'Linijski dijagrami' => 'Diagrame liniare',
            'Stubicasti dijagrami i histogrami' => 'Diagrame cu bare si histograme',
            'Domaci: Vizuelizacija podataka' => 'Tema: Vizualizarea datelor',
            'Prosek niza brojeva' => 'Media unui sir de numere',
            'Procenti i sektorski dijagrami' => 'Procente si diagrame sectoriale',
            'Frekvencijska analiza' => 'Analiza frecventei',
            'Domaci: Analiza podataka' => 'Tema: Analiza datelor',
            'Tabelarno predstavljanje podataka' => 'Reprezentarea tabelara a datelor',
            'Filtriranje i sortiranje tabela' => 'Filtrarea si sortarea tabelelor',
            'Vizuelizacija tabela' => 'Vizualizarea tabelelor',
            'Domaci: Rad sa tabelama' => 'Tema: Lucrul cu tabele',
            'Ucitavanje iz CSV fajlova' => 'Incarcarea din fisiere CSV',
            'Modifikacija tabele' => 'Modificarea tabelelor',
            'Zavrsni projekat: Analiza podataka' => 'Proiect final: Analiza datelor',

            // === LONG PHRASES (paragraphs, explanations) ===
            'Zamisli da imas carobnu svesku u koju mozes da pises tekst, ali i da racunas i crtas grafike - sve na jednom mestu!' => 'Imagineaza-ti ca ai un caiet magic in care poti sa scrii text, dar si sa calculezi si sa desenezi grafice - totul intr-un singur loc!',
            'Jupyter je alat koji koriste naucnici, programeri i ucenici sirom sveta da bi:' => 'Jupyter este un instrument folosit de cercetatori, programatori si elevi din intreaga lume pentru a:',
            'Pisali i pokretali Python programe korak po korak' => 'Scrie si rula programe Python pas cu pas',
            'Videli rezultate odmah ispod koda' => 'Vedea rezultatele imediat sub cod',
            'Pravili grafike i dijagrame' => 'Crea grafice si diagrame',
            'Pisali objasnjenja i beleske pored koda' => 'Scrie explicatii si notite langa cod',
            'Ime dolazi od tri programska jezika:' => 'Numele vine de la trei limbaje de programare:',
            'Mi cemo koristiti Python, koji vec znamo!' => 'Noi vom folosi Python, pe care il stim deja!',
            'Jupyter notebook se sastoji od' => 'Jupyter notebook-ul este format din',
            '(polja). Postoje dve vrste celija:' => '(campuri). Exista doua tipuri de celule:',
            'u njih pisemo Python kod i pokrecemo ga' => 'in ele scriem cod Python si il rulam',
            'u njih pisemo objasnjenja (koriste Markdown format)' => 'in ele scriem explicatii (folosesc formatul Markdown)',
            'Pogledaj primer ispod. Imas notebook sa dve celije - jednom za opis i jednom za kod.' => 'Priveste exemplul de mai jos. Ai un notebook cu doua celule - una pentru descriere si una pentru cod.',
            'da pokrenes kod!' => 'sa rulezi codul!',
            'Kao sto vidis, rezultat se pojavljuje odmah ispod koda. To je velika prednost Jupytera - ne moras da pokreces ceo program, vec mozes da testiras delove koda jedan po jedan.' => 'Dupa cum vezi, rezultatul apare imediat sub cod. Acesta este marele avantaj al Jupyter - nu trebuie sa rulezi intregul program, ci poti testa parti ale codului una cate una.',
            'Jupyter se koristi svuda:' => 'Jupyter se foloseste peste tot:',
            'za ucenje programiranja i matematike' => 'pentru invatarea programarii si a matematicii',
            'naucnici analiziraju podatke i prave grafike' => 'cercetatorii analizeaza date si creeaza grafice',
            'analiticari proucavaju prodaju, korisnike, trendove' => 'analistii studiaza vanzarile, utilizatorii, tendintele',
            'novinari analiziraju podatke za price' => 'jurnalistii analizeaza date pentru articole',

            // Celije lesson
            'Osnovna gradivna jedinica u Jupyteru je' => 'Unitatea de baza in Jupyter este',
            'Svaka celija je kao jedna kockica u Lego slagalici - mozes ih slagati jednu na drugu i svaka radi svoj posao.' => 'Fiecare celula este ca o piesa de Lego - le poti aseza una peste alta si fiecare isi face treaba.',
            'Celija sa kodom' => 'Celula cu cod',
            'U celiju sa kodom pises Python kod. Kada pokrenes celiju, Python izvrsi kod i prikaze rezultat ispod.' => 'In celula cu cod scrii cod Python. Cand rulezi celula, Python executa codul si afiseaza rezultatul dedesubt.',
            'Poslednji izraz u celiji se automatski prikazuje kao rezultat' => 'Ultima expresie din celula se afiseaza automat ca rezultat',
            'Celija sa tekstom (Markdown)' => 'Celula cu text (Markdown)',
            'Markdown celije sluze za objasnjenja. U njima mozes pisati naslove, liste, podebljani tekst i slicno.' => 'Celulele Markdown servesc pentru explicatii. In ele poti scrie titluri, liste, text bold si altele.',
            'Redosled pokretanja je bitan!' => 'Ordinea rularii este importanta!',
            'Svaka celija sa kodom ima svoj redni broj pokretanja. Ako u jednoj celiji napravis promenljivu, mozete je koristiti u sledecoj celiji. Ali paznja - celije se moraju pokretati redom!' => 'Fiecare celula cu cod are numarul sau de ordine de rulare. Daca creezi o variabila intr-o celula, o poti folosi in celula urmatoare. Dar atentie - celulele trebuie rulate in ordine!',
            'Probaj sam!' => 'Incearca singur!',
            'U notebooku ispod, dopisi kod u prazne celije:' => 'In notebook-ul de mai jos, completeaza codul in celulele goale:',

            // Racunanje lesson
            'Jupyter je savrseni digitron! Mozes da racunas sve - od prostih operacija do slozenih formula.' => 'Jupyter este calculatorul perfect! Poti calcula totul - de la operatii simple la formule complexe.',
            'Pre nego sto pocnemo da racunamo, upoznajmo nasu najvazniju funkciju:' => 'Inainte de a incepe sa calculam, sa cunoastem cea mai importanta functie:',
            'Ispisuje tekst ili vrednost na ekran. Bez nje ne bismo videli rezultate!' => 'Afiseaza text sau o valoare pe ecran. Fara ea nu am vedea rezultatele!',
            'Napisemo' => 'Scriem',
            'i u zagradu stavimo ono sto zelimo da ispisemo. Tekst ide pod navodnike, brojevi bez navodnika.' => 'si in paranteza punem ceea ce dorim sa afisam. Textul se pune intre ghilimele, numerele fara ghilimele.',
            'Python zna sve matematicke operacije. Evo ih:' => 'Python cunoaste toate operatiile matematice. Iata-le:',
            'Probaj sam u notebooku ispod:' => 'Incearca singur in notebook-ul de mai jos:',
            'zaokruzuje broj na zadati broj decimala. Ako ne napisemo broj decimala, zaokruzuje na ceo broj.' => 'rotunjeste un numar la numarul specificat de zecimale. Daca nu specificam numarul de zecimale, rotunjeste la numar intreg.',
            'Zamisli da ti digitron pokaze' => 'Imagineaza-ti ca calculatorul iti arata',
            'a tebi treba samo dve decimale' => 'iar tie iti trebuie doar doua zecimale',
            'daje apsolutnu vrednost (uklanja minus). Uvek vraca pozitivan broj.' => 'da valoarea absoluta (elimina minusul). Returneaza intotdeauna un numar pozitiv.',
            'Na primer, ako je temperatura -7 stepeni,' => 'De exemplu, daca temperatura este -7 grade,',
            'vraca 7. Korisno kada nas zanima samo koliko je daleko od nule, ne u kom smeru.' => 'returneaza 7. Util cand ne intereseaza doar cat de departe este de zero, nu in ce directie.',
            'Python ima ugradjen' => 'Python are incorporat',
            'za osnovne stvari' => 'pentru lucruri de baza',
            'ali za naprednije racunanje treba nam' => 'dar pentru calcule mai avansate avem nevoie de o',
            'Zamisli biblioteku kao kutiju sa posebnim alatima. Da bi koristio alate, prvo moras da otvoris kutiju - to radimo sa' => 'Imagineaza-ti biblioteca ca o cutie cu unelte speciale. Pentru a folosi uneltele, mai intai trebuie sa deschizi cutia - asta facem cu',
            'otvara kutiju sa matematickim alatima.' => 'deschide cutia cu unelte matematice.',
            'Racuna kvadratni koren broja. Kvadratni koren od 144 je 12, jer 12 * 12 = 144.' => 'Calculeaza radacina patrata a unui numar. Radacina patrata din 144 este 12, deoarece 12 * 12 = 144.',
            'Imas sobu povrsine 25 kvadratnih metara. Kolika je stranica ako je soba kvadratna?' => 'Ai o camera cu suprafata de 25 de metri patrati. Cat este latura daca camera este patrata?',
            'metara.' => 'metri.',
            'Broj Pi (3.14159...) koristimo za racunanje sa krugovima. Nije funkcija vec konstanta (gotova vrednost).' => 'Numarul Pi (3.14159...) il folosim pentru calcule cu cercuri. Nu este o functie, ci o constanta (valoare gata facuta).',
            'Zaokruzuje broj UVEK NAVISE na sledeci ceo broj.' => 'Rotunjeste un numar INTOTDEAUNA IN SUS la urmatorul numar intreg.',
            'Cak i 3.01 postaje 4!' => 'Chiar si 3.01 devine 4!',
            'Imas 13 drugara i u svaki auto staje 4 osobe. Koliko auta ti treba? 13 / 4 = 3.25, ali ne mozes imati 3.25 auta - treba ti 4 auta!' => 'Ai 13 prieteni si in fiecare masina incap 4 persoane. Cate masini iti trebuie? 13 / 4 = 3.25, dar nu poti avea 3.25 masini - iti trebuie 4 masini!',
            'Zato koristis' => 'De aceea folosesti',
            'Suprotno od ceil - zaokruzuje UVEK NANIZE.' => 'Opusul lui ceil - rotunjeste INTOTDEAUNA IN JOS.',
            'Cak i 3.99 postaje 3.' => 'Chiar si 3.99 devine 3.',
            'Hajde da iskoristimo sve naucene funkcije u jednom primeru:' => 'Hai sa folosim toate functiile invatate intr-un singur exemplu:',
            'Pregled svih komandi' => 'Prezentarea tuturor comenzilor',
            'Ispisuje na ekran' => 'Afiseaza pe ecran',
            'Zaokruzuje broj x na n decimala' => 'Rotunjeste numarul x la n zecimale',
            'Apsolutna vrednost (uklanja minus)' => 'Valoarea absoluta (elimina minusul)',
            'Uvozi matematicku biblioteku' => 'Importa biblioteca matematica',
            'Kvadratni koren' => 'Radacina patrata',
            'Broj Pi' => 'Numarul Pi',
            'Zaokruzi navise' => 'Rotunjeste in sus',
            'Zaokruzi nanize' => 'Rotunjeste in jos',
            'x na stepen y' => 'x la puterea y',
            'Pokazuje tip podatka' => 'Arata tipul de date',
            'Pretvara u ceo broj' => 'Converteste in numar intreg',
            'Pretvara u decimalni broj' => 'Converteste in numar zecimal',
            'Pretvara u tekst' => 'Converteste in text',

            // Domaci: Moj prvi notebook
            'Vreme je da sam napravis nesto u Jupyteru! Resi zadatke ispod.' => 'E timpul sa faci ceva singur in Jupyter! Rezolva exercitiile de mai jos.',

            // Nizovi lesson
            'U svakodnevnom zivotu stalno radimo sa nizovima podataka. Temperature tokom nedelje, ocene iz predmeta, broj golova po utakmici...' => 'In viata de zi cu zi lucram permanent cu siruri de date. Temperaturile de peste saptamana, notele la materii, numarul de goluri pe meci...',
            'U Pythonu koristimo' => 'In Python folosim',
            'da cuvamo ovakve podatke.' => 'pentru a stoca astfel de date.',
            'Lista je uredjen niz podataka u uglastim zagradama. Zamisli je kao policu za knjige - svaka knjiga ima svoje mesto (indeks), pocevsi od 0.' => 'Lista este un sir ordonat de date in paranteze patrate. Imagineaz-o ca un raft de carti - fiecare carte are locul sau (index), incepand de la 0.',
            'Broji koliko elemenata ima u listi (ili koliko slova ima u tekstu).' => 'Numara cate elemente are o lista (sau cate litere are un text).',
            'Ime dolazi od engleske reci "length" (duzina).' => 'Numele vine de la cuvantul englezesc "length" (lungime).',
            'Imas korpu sa vocem.' => 'Ai un cos cu fructe.',
            'ti kaze koliko komada voca imas.' => 'iti spune cate fructe ai.',
            'sabira sve elemente u listi. Kao kada sabiras ocene na papiru, ali mnogo brze!' => 'aduna toate elementele din lista. Ca atunci cand aduni notele pe hartie, dar mult mai repede!',
            'nalazi najmanji element. Kao kada trazis najnizu temperaturu u nedelji.' => 'gaseste cel mai mic element. Ca atunci cand cauti cea mai scazuta temperatura din saptamana.',
            'nalazi najveci element. Kao kada trazis ko ima najvise bodova.' => 'gaseste cel mai mare element. Ca atunci cand cauti cine are cele mai multe puncte.',
            'dodaje element na kraj liste. Kao kada stavis novu knjigu na kraj police.' => 'adauga un element la sfarsitul listei. Ca atunci cand pui o carte noua la sfarsitul raftului.',
            'uklanja prvo pojavljivanje elementa. Kao kada skines jednu knjigu sa police.' => 'elimina prima aparitie a elementului. Ca atunci cand scoti o carte de pe raft.',
            'Ove funkcije se pisu sa tackom posle liste' => 'Aceste functii se scriu cu punct dupa lista',
            'jer pripadaju samoj listi. To se zove' => 'deoarece apartin listei insasi. Aceasta se numeste',
            'Sortira (uredjuje) listu od najmanjeg do najveceg.' => 'Sorteaza (ordoneaza) lista de la cel mai mic la cel mai mare.',
            'sortira od najveceg do najmanjeg.' => 'sorteaza de la cel mai mare la cel mai mic.',
            'pravi NOVU listu i ne menja originalnu.' => 'creeaza o lista NOUA si nu modifica originalul.',
            'Ako hoces da promenis originalnu, koristi' => 'Daca vrei sa modifici originalul, foloseste',
            'spaja dve liste u parove. Kao kada sparujes cipele - leva sa desnom.' => 'uneste doua liste in perechi. Ca atunci cand imperechezi pantofii - stangul cu dreptul.',
            'nalazi na kojoj poziciji se element nalazi. Vraca indeks (broj mesta).' => 'gaseste pe ce pozitie se afla elementul. Returneaza indexul (numarul locului).',
            'Kada imamo listu brojeva, mozemo lako izracunati razne statistike. To je upravo ono sto naucnici i analiticari rade svaki dan!' => 'Cand avem o lista de numere, putem calcula usor diverse statistici. Exact asta fac cercetatorii si analistii in fiecare zi!',
            'Pregled svih komandi za liste' => 'Prezentarea tuturor comenzilor pentru liste',
            'Broj elemenata' => 'Numarul de elemente',
            'Zbir svih elemenata' => 'Suma tuturor elementelor',
            'Najmanji element' => 'Cel mai mic element',
            'Najveci element' => 'Cel mai mare element',
            'Nova sortirana lista' => 'Lista noua sortata',
            'Dodaj na kraj' => 'Adauga la sfarsit',
            'Ukloni prvo pojavljivanje' => 'Elimina prima aparitie',
            'Pozicija elementa' => 'Pozitia elementului',
            'Koliko puta se pojavljuje' => 'De cate ori apare',
            'Sortira originalnu listu' => 'Sorteaza lista originala',
            'Obrce redosled' => 'Inverseaza ordinea',
            'Ubaci x na poziciju i' => 'Insereaza x pe pozitia i',
            'Ukloni i vrati poslednji' => 'Elimina si returneaza ultimul',
            'Da li je x u listi?' => 'Este x in lista?',
            'Spaja dve liste u parove' => 'Uneste doua liste in perechi',

            // Linijski dijagrami
            'Sto bi rekli "slika vredi hiljadu reci".' => 'Asa cum se spune "o imagine valoreaza cat o mie de cuvinte".',
            'Umesto da gledamo dugacke liste brojeva, mozemo nacrtati' => 'In loc sa privim liste lungi de numere, putem desena un',
            'i odmah videti trendove i obrasce.' => 'si sa vedem imediat tendintele si tiparele.',
            'Za crtanje dijagrama koristimo biblioteku' => 'Pentru desenarea diagramelor folosim biblioteca',
            'najpoznatiju Python biblioteku za grafike.' => 'cea mai cunoscuta biblioteca Python pentru grafice.',
            'Uvek je uvozimo kao' => 'Intotdeauna o importam ca',
            '(skracenica) da ne bismo pisali celo ime svaki put.' => '(prescurtare) ca sa nu scriem numele intreg de fiecare data.',
            'Pravi novo prazno platno za crtanje. Kao kada uzmes prazan list papira pre nego sto pocnes da crtas.' => 'Creeaza o panza goala noua pentru desen. Ca atunci cand iei o foaie alba inainte sa incepi sa desenezi.',
            'velicina platna u incima' => 'dimensiunea panzei in inci',
            'pravi siri dijagram' => 'creeaza o diagrama mai lata',
            'Crta liniju koja povezuje tacke. Dajemo mu dve liste - jednu za X osu (horizontalnu) i jednu za Y osu (vertikalnu).' => 'Deseneaza o linie care conecteaza punctele. Ii dam doua liste - una pentru axa X (orizontala) si una pentru axa Y (verticala).',
            'Parametri koje mozemo dodati:' => 'Parametrii pe care ii putem adauga:',
            'Boja linije' => 'Culoarea liniei',
            'Oblik tacke na svakom podatku' => 'Forma punctului la fiecare data',
            '(krug)' => '(cerc)',
            '(kvadrat)' => '(patrat)',
            '(zvezdica)' => '(steluta)',
            'Debljina linije' => 'Grosimea liniei',
            'Stil linije' => 'Stilul liniei',
            '(crtica)' => '(liniuta)',
            '(tacka)' => '(punct)',
            '(puna)' => '(plina)',
            'Ime za legendu' => 'Numele pentru legenda',
            'naslov dijagrama (iznad grafika)' => 'titlul diagramei (deasupra graficului)',
            'oznaka X ose (ispod)' => 'eticheta axei X (dedesubt)',
            'oznaka Y ose (sa strane)' => 'eticheta axei Y (lateral)',
            'prikazuje legendu (objasnjenje boja/linija).' => 'afiseaza legenda (explicatia culorilor/liniilor).',
            'Radi samo ako si stavio' => 'Functioneaza doar daca ai pus',
            'u plot().' => 'in plot().',
            'dodaje mrezu (linije u pozadini za lakse citanje)' => 'adauga grila (linii in fundal pentru citire mai usoara)',
            'prikazuje dijagram. Uvek stavljamo na kraj!' => 'afiseaza diagrama. Intotdeauna o punem la sfarsit!',
            'Mozemo uporediti vise nizova podataka na istom grafiku. Samo pozovemo' => 'Putem compara mai multe siruri de date pe acelasi grafic. Doar apelam',
            'vise puta pre' => 'de mai multe ori inainte de',
            'Linijski dijagrami su najbolji kada:' => 'Diagramele liniare sunt cele mai bune cand:',
            'Podaci se menjaju tokom vremena (temperature, cene, ocene...)' => 'Datele se schimba in timp (temperaturi, preturi, note...)',
            'Zelimo da vidimo trend - da li nesto raste ili opada' => 'Dorim sa vedem tendinta - daca ceva creste sau scade',
            'Poredimo dva ili vise nizova podataka' => 'Comparam doua sau mai multe siruri de date',
            'Pregled matplotlib komandi - linijski dijagram' => 'Prezentarea comenzilor matplotlib - diagrama liniara',
            'Uvozi biblioteku za grafike' => 'Importa biblioteca pentru grafice',
            'Uvek na pocetku' => 'Intotdeauna la inceput',
            'Pravi platno zadate velicine' => 'Creeaza panza de dimensiunea specificata',
            'Crta linijski dijagram' => 'Deseneaza diagrama liniara',
            'Boja linije/elementa' => 'Culoarea liniei/elementului',
            'Oblik tacke' => 'Forma punctului',
            'Naziv za legendu' => 'Numele pentru legenda',
            'Providnost (0-1)' => 'Transparenta (0-1)',
            'Naslov dijagrama' => 'Titlul diagramei',
            'Oznaka X ose' => 'Eticheta axei X',
            'Oznaka Y ose' => 'Eticheta axei Y',
            'Prikazuje legendu' => 'Afiseaza legenda',
            'Koristi label iz plot()' => 'Foloseste label din plot()',
            'Prikazuje mrezu' => 'Afiseaza grila',
            'Boji prostor ispod linije' => 'Coloreaza spatiul sub linie',
            'Prikazuje dijagram' => 'Afiseaza diagrama',
            'Uvek na kraju' => 'Intotdeauna la sfarsit',

            // Stubicasti dijagrami
            'Linijski dijagrami su odlicni za trendove, ali ponekad zelimo da' => 'Diagramele liniare sunt excelente pentru tendinte, dar uneori dorim sa',
            'Za to koristimo stubicaste dijagrame!' => 'Pentru asta folosim diagramele cu bare!',
            'Crta vertikalne stubice. Svaki stubic predstavlja jednu kategoriju, a visina stubica pokazuje vrednost.' => 'Deseneaza bare verticale. Fiecare bara reprezinta o categorie, iar inaltimea barei arata valoarea.',
            'Kada poredimo stvari - ocene po predmetima, broj glasova, bodove ucenika...' => 'Cand comparam lucruri - note pe materii, numarul de voturi, punctajele elevilor...',
            'Boja stubica (jedna ili lista)' => 'Culoarea barelor (una sau lista)',
            'Boja ivice stubica' => 'Culoarea marginii barelor',
            'Sirina stubica' => 'Latimea barelor',
            'Isto kao' => 'La fel ca',
            'ali crta stubice horizontalno (u stranu). Preglednije je kada imas duga imena kategorija.' => 'dar deseneaza barele orizontal (in lateral). Este mai clar cand ai nume lungi de categorii.',
            'postavlja opseg Y ose.' => 'seteaza intervalul axei Y.',
            'znaci da Y osa ide od 0 do 5.5.' => 'inseamna ca axa Y merge de la 0 la 5.5.',
            'isto za X osu.' => 'la fel pentru axa X.',
            'postavlja koje oznake se prikazuju na X osi.' => 'seteaza ce etichete se afiseaza pe axa X.',
            'crta horizontalnu liniju (korisno za prikaz proseka).' => 'deseneaza o linie orizontala (util pentru afisarea mediei).',
            'Automatski grupishe podatke u intervale i prikazuje koliko ih ima u svakom intervalu.' => 'Grupeaza automat datele in intervale si afiseaza cate sunt in fiecare interval.',
            'mi biramo kategorije (predmeti, ucenici...).' => 'noi alegem categoriile (materii, elevi...).',
            'Python sam grupishe brojeve u opsege.' => 'Python grupeaza singur numerele in intervale.',
            'Kada zelimo da vidimo kako su rasporedjene vrednosti - koliko ucenika ima koju ocenu, raspodela visina, rezultati testa...' => 'Cand dorim sa vedem cum sunt distribuite valorile - cati elevi au ce nota, distributia inaltimilor, rezultatele testului...',
            'Broj intervala ili granice intervala' => 'Numarul de intervale sau limitele intervalelor',
            'Sirina stubica histograma (0-1)' => 'Latimea barelor histogramei (0-1)',
            'Kada sta koristimo?' => 'Cand ce folosim?',
            'Promena tokom vremena' => 'Schimbari in timp',
            'Temperature po danima' => 'Temperaturi pe zile',
            'Poredjenje kategorija' => 'Compararea categoriilor',
            'Ocene po predmetima' => 'Note pe materii',
            'Poredjenje (duga imena)' => 'Comparare (nume lungi)',
            'Bodovi ucenika' => 'Punctajele elevilor',
            'Raspodela vrednosti' => 'Distributia valorilor',
            'Koliko ucenika ima koju ocenu' => 'Cati elevi au ce nota',
            'Pregled novih komandi' => 'Prezentarea comenzilor noi',
            'Vertikalni stubicasti dijagram' => 'Diagrama cu bare verticale',
            'Horizontalni stubicasti dijagram' => 'Diagrama cu bare orizontale',
            'Histogram (raspodela)' => 'Histograma (distributie)',
            'Opseg Y ose' => 'Intervalul axei Y',
            'Opseg X ose' => 'Intervalul axei X',
            'Oznake na X osi' => 'Etichetele pe axa X',
            'Horizontalna linija' => 'Linie orizontala',
            'Dodaje tekst na grafik' => 'Adauga text pe grafic',

            // Procenti i sektorski
            'Procenat znaci "od sto" (per centum na latinskom).' => 'Procentul inseamna "din o suta" (per centum in latina).',
            'Ako imas 5 jabuka od ukupno 20 voca, jabuke cine 5/20 = 0.25 = 25% ukupnog voca.' => 'Daca ai 5 mere din totalul de 20 de fructe, merele reprezinta 5/20 = 0.25 = 25% din totalul fructelor.',
            'Formula je jednostavna:' => 'Formula este simpla:',
            'Crta "pitu" (krug) podeljenu na sektore (parcad). Svaki sektor pokazuje koliki deo celine zauzima neka kategorija.' => 'Deseneaza o "placinta" (cerc) impartita in sectoare (felii). Fiecare sector arata ce parte din total ocupa o categorie.',
            'Kada zelimo da vidimo koliki procenat celine zauzima svaki deo - glasovi na anketi, raspodela budzeta, sastav odeljenja...' => 'Cand dorim sa vedem ce procent din total ocupa fiecare parte - voturi in sondaj, distributia bugetului, componenta clasei...',
            'Python sam racuna procente! Ti samo das brojeve (npr. glasove), a' => 'Python calculeaza singur procentele! Tu doar dai numerele (de ex. voturile), iar',
            'sam izracuna koliki deo kruga pripada svakom.' => 'calculeaza singur ce parte din cerc apartine fiecaruia.',
            'Imena za svaki sektor' => 'Numele pentru fiecare sector',
            'Boje za svaki sektor' => 'Culorile pentru fiecare sector',
            'Format za prikaz procenata' => 'Formatul pentru afisarea procentelor',
            'prikazuje npr.' => 'afiseaza de ex.',
            'Pocetni ugao u stepenima' => 'Unghiul de start in grade',
            '(pocinje odozgo)' => '(incepe de sus)',
            'Izvlaci sektore iz centra' => 'Extrage sectoarele din centru',
            '(izvuci prvi)' => '(extrage primul)',
            'Dodaje senku' => 'Adauga umbra',
            'Podesavanje teksta' => 'Setarile textului',
            'Ovo izgleda cudno, ali je jednostavno:' => 'Arata ciudat, dar este simplu:',
            'prikazi broj sa jednom decimalom' => 'afiseaza numarul cu o zecimala',
            'prikazi znak %' => 'afiseaza semnul %',
            '(moramo dva puta jer je % specijalan karakter)' => '(trebuie de doua ori deoarece % este un caracter special)',
            'Dakle, rezultat je npr.' => 'Deci, rezultatul este de ex.',
            'Izvlaci sektore iz kruga - kao da izvadis parce torte.' => 'Extrage sectoarele din cerc - ca si cum ai scoate o felie de tort.',
            'Dajemo listu brojeva gde 0 znaci "ostavi na mestu", a 0.1 znaci "izvuci malo".' => 'Dam o lista de numere unde 0 inseamna "lasa pe loc", iar 0.1 inseamna "extrage putin".',
            'Pregled komandi za sektorski dijagram' => 'Prezentarea comenzilor pentru diagrama sectoriala',
            'Crta sektorski dijagram' => 'Deseneaza diagrama sectoriala',
            'Imena sektora' => 'Numele sectoarelor',
            'Boje sektora' => 'Culorile sectoarelor',
            'Prikazuje procente (1 decimala)' => 'Afiseaza procente (1 zecimala)',
            'Prikazuje procente (bez decimala)' => 'Afiseaza procente (fara zecimale)',
            'Pocetni ugao (90 = odozgo)' => 'Unghiul de start (90 = de sus)',
            'Izvlaci sektore (0=ne, 0.1=da)' => 'Extrage sectoare (0=nu, 0.1=da)',
            'Dodaje senku ispod dijagrama' => 'Adauga umbra sub diagrama',
            'Koji dijagram kada?' => 'Ce diagrama cand?',
            'Kako se nesto menja tokom vremena?' => 'Cum se schimba ceva in timp?',
            'Koja kategorija je najveca/najmanja?' => 'Ce categorie este cea mai mare/mica?',
            'Koliki procenat celine zauzima svaki deo?' => 'Ce procent din total ocupa fiecare parte?',
            'Kako su rasporedjene vrednosti?' => 'Cum sunt distribuite valorile?',

            // Prosek lesson
            'Prosek (aritmeticka sredina) je jedan od najvaznijih pojmova u matematici i analizi podataka.' => 'Media (media aritmetica) este unul dintre cele mai importante concepte in matematica si analiza datelor.',
            'Izracunava se tako sto saberemo sve brojeve i podelimo sa brojem elemenata.' => 'Se calculeaza adunand toate numerele si impartind la numarul de elemente.',
            'Prosek izracunavamo formulom:' => 'Media o calculam cu formula:',
            'U Pythonu vec znamo funkcije' => 'In Python deja cunoastem functiile',
            'pa je to lako:' => 'deci este usor:',
            'Python ima posebnu biblioteku' => 'Python are o biblioteca speciala',
            'koja zna sve o statistici. Uvozimo je sa' => 'care stie totul despre statistica. O importam cu',
            'Isto sto i' => 'Acelasi lucru ca',
            'ali je citljivije.' => 'dar este mai lizibil.',
            '"Mean" na engleskom znaci "srednja vrednost".' => '"Mean" in engleza inseamna "valoare medie".',
            'Nalazi srednju vrednost kada poredamo brojeve po velicini.' => 'Gaseste valoarea din mijloc cand ordonam numerele dupa marime.',
            'Ako 5 ucenika imaju ocene' => 'Daca 5 elevi au notele',
            'medijana je 4 (srednji broj).' => 'mediana este 4 (numarul din mijloc).',
            'Medijana je korisna jer je ne kvare ekstremne vrednosti' => 'Mediana este utila deoarece nu este afectata de valori extreme',
            'ako jedan ucenik ima 1, prosek pada mnogo, ali medijana ostaje slicna.' => 'daca un elev are 1, media scade mult, dar mediana ramane similara.',
            'Nalazi vrednost koja se najcesce pojavljuje.' => 'Gaseste valoarea care apare cel mai des.',
            'Ako u odeljenju ocene iz informatike idu' => 'Daca in clasa notele la informatica sunt',
            'mod je 5 jer se pojavljuje 4 puta - najcesce od svih.' => 'modul este 5 deoarece apare de 4 ori - cel mai des dintre toate.',
            'Pregled komandi za statistiku' => 'Prezentarea comenzilor pentru statistica',
            'Prosek (rucno)' => 'Media (manual)',
            'Prosek (aritmeticka sredina)' => 'Media (media aritmetica)',
            'Medijana (srednji element)' => 'Mediana (elementul din mijloc)',
            'Mod (najcesci element)' => 'Modul (elementul cel mai frecvent)',
            'Standardna devijacija (rasipanje)' => 'Deviatia standard (imprastiere)',

            // Frekvencijska analiza
            'Frekvencija znaci "koliko cesto se nesto pojavljuje".' => 'Frecventa inseamna "cat de des apare ceva".',
            'Ako bacis kockicu 100 puta, koliko cesto ce pasti svaki broj? To je frekvencijska analiza!' => 'Daca arunci un zar de 100 de ori, cat de des va cadea fiecare numar? Aceasta este analiza frecventei!',
            'Broji koliko puta se odredjeni element pojavljuje u listi.' => 'Numara de cate ori apare un anumit element in lista.',
            'Imas listu ocena i hoces da znas koliko petica imas.' => 'Ai o lista de note si vrei sa stii cate note de 5 ai.',
            'ti daje odgovor!' => 'iti da raspunsul!',
            'Kada imamo mnogo razlicitih vrednosti, rucno brojanje sa' => 'Cand avem multe valori diferite, numararea manuala cu',
            'je zamorno. Biblioteka' => 'este obositoare. Biblioteca',
            'ima alat' => 'are instrumentul',
            'koji sve izbroji odjednom!' => 'care numara totul deodata!',
            'pravi recnik gde su kljucevi elementi, a vrednosti koliko se puta pojavljuju.' => 'creeaza un dictionar unde cheile sunt elementele, iar valorile sunt de cate ori apar.',
            'vraca n najcescih elemenata, sortirano od najcesceg.' => 'returneaza cele mai frecvente n elemente, sortate de la cel mai frecvent.',
            'Pregled komandi za frekvencijsku analizu' => 'Prezentarea comenzilor pentru analiza frecventei',
            'Broji koliko puta se x pojavljuje' => 'Numara de cate ori apare x',
            'Broji sve elemente odjednom' => 'Numara toate elementele deodata',
            'Top n najcescih' => 'Top n cele mai frecvente',
            'Pretvori Counter u recnik' => 'Converteste Counter in dictionar',
            'Svi razliciti elementi' => 'Toate elementele diferite',
            'Sve frekvencije' => 'Toate frecventele',

            // Tabele lesson
            'Tabele su svuda oko nas - dnevnik, raspored casova, cenovnik u prodavnici, fudbalska tabela...' => 'Tabelele sunt peste tot in jurul nostru - catalogul, orarul, lista de preturi din magazin, clasamentul de fotbal...',
            'Pandas je Python biblioteka koja nam omogucava da radimo sa tabelama kao u Excel-u, ali sa mnogo vise mogucnosti.' => 'Pandas este o biblioteca Python care ne permite sa lucram cu tabele ca in Excel, dar cu mult mai multe posibilitati.',
            'Osnovna struktura je' => 'Structura de baza este',
            'tabela sa vrstama i kolonama.' => 'un tabel cu randuri si coloane.',
            'Informacije o tabeli' => 'Informatii despre tabel',
            'Oblik tabele:' => 'Forma tabelului:',
            'Tipovi podataka:' => 'Tipurile de date:',
            'Brza statistika sa' => 'Statistici rapide cu',

            // Filtriranje
            'Zamisli da imas tabelu sa 1000 ucenika i treba da nadjes samo one sa prosekom vecim od 4.5.' => 'Imagineaza-ti ca ai un tabel cu 1000 de elevi si trebuie sa ii gasesti doar pe cei cu media mai mare de 4.5.',
            'Rucno bi to trajalo satima, ali sa pandas-om traje jedan red koda!' => 'Manual ar dura ore intregi, dar cu pandas dureaza o singura linie de cod!',
            'Grupisemo podatke po kategorijama i racunamo statistike:' => 'Grupam datele pe categorii si calculam statistici:',

            // Vizuelizacija tabela
            'Pandas ima ugradjen sistem za crtanje dijagrama direktno iz tabele! Koristi matplotlib u pozadini, ali je mnogo jednostavniji za koriscenje.' => 'Pandas are un sistem incorporat pentru desenarea diagramelor direct din tabel! Foloseste matplotlib in fundal, dar este mult mai simplu de utilizat.',

            // CSV
            'Do sada smo podatke unosili rucno. Ali u stvarnom svetu podaci vec postoje u fajlovima!' => 'Pana acum am introdus datele manual. Dar in lumea reala datele exista deja in fisiere!',
            'Najcesci format je' => 'Cel mai comun format este',
            'obican tekst gde su vrednosti razdvojene zarezima.' => 'text simplu unde valorile sunt separate prin virgule.',
            'Svaki red je jedan podatak, a vrednosti su razdvojene zarezom. Mozes ga otvoriti i u Excel-u!' => 'Fiecare rand este o inregistrare, iar valorile sunt separate prin virgula. Il poti deschide si in Excel!',

            // Modifikacija
            'Kada ucitamo podatke, cesto ih treba prilagoditi - dodati nove kolone, obrisati nepotrebne, promeniti vrednosti...' => 'Cand incarcam datele, adesea trebuie sa le adaptam - adaugam coloane noi, stergem pe cele inutile, schimbam valori...',

            // Jupyter i Excel
            'Mnogo ljudi koristi Excel za rad sa tabelama. Jupyter moze da cita i pise Excel fajlove, sto ga cini savrsenim alatom za analizu podataka!' => 'Multi oameni folosesc Excel pentru lucrul cu tabele. Jupyter poate citi si scrie fisiere Excel, ceea ce il face un instrument perfect pentru analiza datelor!',
            'Zamisli da svake nedelje dobijas tabelu sa ocenama i treba da izracunas prosek, napravis grafike i posaljes izvestaj.' => 'Imagineaza-ti ca in fiecare saptamana primesti un tabel cu note si trebuie sa calculezi media, sa faci grafice si sa trimiti un raport.',
            'U Excel-u to radis rucno svaki put. U Jupyteru napises kod jednom i samo menjas podatke!' => 'In Excel faci asta manual de fiecare data. In Jupyter scrii codul o singura data si doar schimbi datele!',

            // Zavrsni projekat
            'Dosli smo do kraja kursa o Jupyteru! Vreme je da sve nauceno primenis u jednom velikom projektu.' => 'Am ajuns la sfarsitul cursului despre Jupyter! E timpul sa aplici tot ce ai invatat intr-un proiect mare.',
            'Izaberi' => 'Alege',
            'od sledecih tema i napravi kompletnu analizu u notebooku ispod:' => 'dintre urmatoarele teme si fa o analiza completa in notebook-ul de mai jos:',
            'Napravi tabelu sa ocenama svih ucenika iz svih predmeta. Izracunaj proseke, nadji najbolje i najlosije predmete, nacrtaj grafike.' => 'Fa un tabel cu notele tuturor elevilor la toate materiile. Calculeaza mediile, gaseste cele mai bune si cele mai slabe materii, deseneaza grafice.',
            'Napravi tabelu fudbalske (ili kosarkaske) lige. Izracunaj bodove, gol razliku, formu timova. Nacrtaj grafike.' => 'Fa un tabel al ligii de fotbal (sau baschet). Calculeaza punctele, golaverajul, forma echipelor. Deseneaza grafice.',
            'Unesi temperature za Zrenjanin za ceo mesec (ili izmisli realne podatke). Analiziraj trendove, proseke, nacrtaj grafike.' => 'Introdu temperaturile pentru Zrenjanin pe o luna intreaga (sau inventeaza date realiste). Analizeaza tendintele, mediile, deseneaza grafice.',
            'Projekat mora da sadrzi:' => 'Proiectul trebuie sa contina:',
            'Tabelu sa podacima (minimum 10 redova)' => 'Un tabel cu date (minimum 10 randuri)',
            'Izracunavanje proseka, min, max' => 'Calcularea mediei, min, max',
            'Filtriranje podataka (bar 2 razlicita filtera)' => 'Filtrarea datelor (cel putin 2 filtre diferite)',
            'Sortiranje' => 'Sortare',
            'Bar 2 razlicita tipa dijagrama' => 'Cel putin 2 tipuri diferite de diagrame',
            'Kratak zakljucak (sta si saznao iz analize)' => 'O scurta concluzie (ce ai aflat din analiza)',

            // === TABLE HEADERS ===
            'Operacija' => 'Operatia',
            'Znak' => 'Semnul',
            'Primer' => 'Exemplu',
            'Rezultat' => 'Rezultatul',
            'Sabiranje' => 'Adunarea',
            'Oduzimanje' => 'Scaderea',
            'Mnozenje' => 'Inmultirea',
            'Deljenje' => 'Impartirea',
            'Celobrojno deljenje' => 'Impartirea intreaga',
            'Ostatak pri deljenju' => 'Restul impartirii',
            'Stepenovanje' => 'Ridicarea la putere',
            'Komanda' => 'Comanda',
            'Sta radi' => 'Ce face',
            'Osobina' => 'Caracteristica',
            'Odlican' => 'Excelent',
            'Dobar' => 'Bun',
            'Ogranicena' => 'Limitata',
            'Odlicna' => 'Excelenta',
            'Velike tabele' => 'Tabele mari',
            'Spor' => 'Lent',
            'Brz' => 'Rapid',
            'Ponovljivost' => 'Repetabilitate',
            'Teska' => 'Dificila',
            'Laka' => 'Usoara',
            'Ucenje' => 'Invatare',
            'Lakse' => 'Mai usor',
            'Teze' => 'Mai dificil',
            'Pitanje' => 'Intrebarea',
            'Dijagram' => 'Diagrama',
            'Funkcija' => 'Functia',
            'Parametar' => 'Parametrul',
            'Linijski' => 'Liniara',
            'Stubicasti' => 'Cu bare',
            'Horizontalni' => 'Orizontala',
            'Sektorski' => 'Sectoriala',

            // === NOTEBOOK MARKDOWN CELLS (appear inside JSON) ===
            '# Moj prvi notebook' => '# Primul meu notebook',
            'Ovo je celija sa tekstom. Ispod je celija sa kodom.' => 'Aceasta este o celula cu text. Mai jos este o celula cu cod.',
            '## Automatski prikaz rezultata' => '## Afisarea automata a rezultatelor',
            'U Jupyteru ne moras uvek da koristis' => 'In Jupyter nu trebuie intotdeauna sa folosesti',
            'Poslednji izraz u celiji se automatski prikazuje:' => 'Ultima expresie din celula se afiseaza automat:',
            'Vidis razliku?' => 'Vezi diferenta?',
            'se prikazuje sve, a bez njega samo poslednja vrednost' => 'se afiseaza totul, iar fara el doar ultima valoare',
            '## Promenljive izmedju celija' => '## Variabile intre celule',
            'Promenljiva napravljena u jednoj celiji moze se koristiti u drugoj:' => 'O variabila creata intr-o celula poate fi folosita in alta:',
            '## Vezba: Moje promenljive' => '## Exercitiu: Variabilele mele',
            'Popuni celije ispod:' => 'Completeaza celulele de mai jos:',
            '## Jupyter kao digitron' => '## Jupyter ca calculator',
            'Probaj sve operacije:' => 'Incearca toate operatiile:',
            '## Biblioteka math' => '## Biblioteca math',
            'dobijamo pristup mnogim korisnim funkcijama:' => 'obtinem acces la multe functii utile:',
            '## Planiranje rodjendana' => '## Planificarea zilei de nastere',
            'Izracunaj koliko sve kosta:' => 'Calculeaza cat costa totul:',
            '## Funkcija print()' => '## Functia print()',
            'ispisuje ono sto stavimo u zagradu:' => 'afiseaza ceea ce punem in paranteza:',
            '## round() i abs()' => '## round() si abs()',
            '## Biblioteka math u akciji' => '## Biblioteca math in actiune',
            '## Liste u Pythonu' => '## Liste in Python',
            'Lista je niz vrednosti u uglastim zagradama' => 'Lista este un sir de valori in paranteze patrate',
            '## Korisne operacije sa listama' => '## Operatii utile cu liste',
            '## Primer: Temperature u Beogradu (jedna nedelja u martu)' => '## Exemplu: Temperaturi in Belgrad (o saptamana in martie)',
            '## Crtamo linijski dijagram' => '## Desenam o diagrama liniara',
            'Biblioteka `matplotlib.pyplot` se obicno uvozi kao `plt`:' => 'Biblioteca `matplotlib.pyplot` se importa de obicei ca `plt`:',
            '## Lepsi dijagram' => '## O diagrama mai frumoasa',
            'Mozemo dodati boje, markere i mrezu:' => 'Putem adauga culori, markere si grila:',
            'Dodajemo boju, markere, deblju liniju i mrezu:' => 'Adaugam culoare, markere, linie mai groasa si grila:',
            '## Poredjenje: Beograd vs Novi Sad' => '## Comparatie: Belgrad vs Novi Sad',
            'da oznacimo linije:' => 'sa etichetam liniile:',
            '## Stubicasti dijagram' => '## Diagrama cu bare',
            '## Horizontalni stubici' => '## Bare orizontale',
            '## Histogram' => '## Histograma',
            'Prikazuje koliko ucenika ima svaku ocenu:' => 'Afiseaza cati elevi au fiecare nota:',
            '## Sektorski dijagram - omiljeni predmeti' => '## Diagrama sectoriala - materiile preferate',
            'sam racuna procente iz brojeva:' => 'calculeaza singur procentele din numere:',
            '## Jos lepsi dijagram' => '## O diagrama si mai frumoasa',
            '## Izvlacenje sektora i senka' => '## Extragerea sectoarelor si umbra',
            'Izvucemo Informatiku iz kruga i dodamo senku:' => 'Extragem Informatica din cerc si adaugam umbra:',
            '## Budzet za izlet' => '## Bugetul pentru excursie',
            'Gde ide novac za skolski izlet?' => 'Unde se duc banii pentru excursia scolara?',
            '## Procenti u Pythonu' => '## Procente in Python',
            '## Prosek - rucni nacin' => '## Media - modul manual',
            '## Biblioteka statistics' => '## Biblioteca statistics',
            '### Zasto su razliciti?' => '### De ce sunt diferiti?',
            '## Mesecne temperature u Zrenjaninu' => '## Temperaturile lunare in Zrenjanin',
            '## count() - broji pojavljivanja' => '## count() - numara aparitiile',
            '## Counter iz collections' => '## Counter din collections',
            '## Frekvencijski dijagram' => '## Diagrama de frecventa',
            '## Mini anketa' => '## Mini sondaj',
            'Counter radi i sa tekstom, ne samo sa brojevima:' => 'Counter functioneaza si cu text, nu doar cu numere:',
            '## Pravimo prvu tabelu' => '## Cream primul tabel',
            'Tabelu pravimo od recnika (dictionary):' => 'Tabelul il cream dintr-un dictionar (dictionary):',
            '## Citamo podatke iz tabele' => '## Citim date din tabel',
            '## Sortiranje tabele' => '## Sortarea tabelului',
            '## Filtriranje - biramo samo redove koji ispunjavaju uslov' => '## Filtrare - selectam doar randurile care indeplinesc conditia',
            '## Grupiranje sa `groupby()`' => '## Gruparea cu `groupby()`',
            '## Crtanje direktno iz tabele' => '## Desenare directa din tabel',
            'Primeti kako se sladoledi prodaju vise leti, a cokolade zimi!' => 'Observa cum inghetatele se vand mai mult vara, iar ciocolatele iarna!',
            '## Pravimo CSV i ucitavamo ga' => '## Cream un CSV si il incarcam',
            'Prvo cemo napraviti CSV fajl, pa ga ucitati:' => 'Mai intai vom crea un fisier CSV, apoi il incarcam:',
            '## Cuvamo rezultate u novi CSV fajl' => '## Salvam rezultatele intr-un fisier CSV nou',
            '## Dodavanje i brisanje kolona' => '## Adaugarea si stergerea coloanelor',
            '## Menjanje vrednosti' => '## Schimbarea valorilor',
            '## Primer: Automatski izvestaj' => '## Exemplu: Raport automat',
            'Zamisli da svake nedelje dobijas nove ocene:' => 'Imagineaza-ti ca in fiecare saptamana primesti note noi:',
            '# Zavrsni projekat' => '# Proiect final',
            '## Tema: (upisi svoju temu)' => '## Tema: (scrie tema ta)',
            '### Uvod' => '### Introducere',
            '(Opisi sta ces analizirati i zasto)' => '(Descrie ce vei analiza si de ce)',
            '### Osnovna statistika' => '### Statistici de baza',
            '### Filtriranje' => '### Filtrare',
            '### Sortiranje' => '### Sortare',
            '### Dijagrami' => '### Diagrame',
            '### Zakljucak' => '### Concluzie',
            '(Sta si saznao iz analize? Koji podatak te je iznenadio?)' => '(Ce ai aflat din analiza? Ce date te-au surprins?)',

            // === DOMACI TASKS MARKDOWN ===
            '# Domaci zadatak: Moj prvi notebook' => '# Tema: Primul meu notebook',
            '# Domaci: Vizuelizacija podataka' => '# Tema: Vizualizarea datelor',
            '# Domaci: Analiza podataka' => '# Tema: Analiza datelor',
            '# Domaci: Rad sa tabelama' => '# Tema: Lucrul cu tabele',
            '## Zadatak 1:' => '## Exercitiul 1:',
            '## Zadatak 2:' => '## Exercitiul 2:',
            '## Zadatak 3:' => '## Exercitiul 3:',
            '## Zadatak 4:' => '## Exercitiul 4:',
            'Predstavi se' => 'Prezinta-te',
            'U celiji ispod napravi promenljive sa tvojim podacima i ispisi ih.' => 'In celula de mai jos creeaza variabile cu datele tale si afiseaza-le.',
            'Digitron' => 'Calculator',
            'Izracunaj koliko sekundi ima u jednom danu, jednoj nedelji i jednoj godini.' => 'Calculeaza cate secunde are o zi, o saptamana si un an.',
            'Prosek ocena' => 'Media notelor',
            'Izracunaj prosek svojih ocena iz informatike koristeci Python.' => 'Calculeaza media notelor tale la informatica folosind Python.',
            'Povrsina i obim' => 'Suprafata si perimetrul',
            'izracunaj obim i povrsinu kruga sa poluprecnikom 7 cm.' => 'calculeaza perimetrul si suprafata cercului cu raza de 7 cm.',
            'Moje ocene' => 'Notele mele',
            'Napravi stubicasti dijagram svojih ocena iz svih predmeta. Koristi razlicite boje za svaki stubic.' => 'Fa o diagrama cu bare a notelor tale la toate materiile. Foloseste culori diferite pentru fiecare bara.',
            'Temperature' => 'Temperaturi',
            'Evo temperatura u Zrenjaninu tokom dve nedelje. Nacrtaj linijski dijagram sa obe nedelje na istom grafiku.' => 'Iata temperaturile din Zrenjanin pe doua saptamani. Deseneaza o diagrama liniara cu ambele saptamani pe acelasi grafic.',
            'Anketa u odeljenju' => 'Sondaj in clasa',
            'Pitao si drugare koji im je omiljeni sport. Rezultati:' => 'I-ai intrebat pe colegi care este sportul lor preferat. Rezultatele:',
            'Prosek i statistika' => 'Media si statistica',
            'Izracunaj prosek, medijanu i mod za ocene tvog odeljenja iz matematike. Nacrtaj histogram.' => 'Calculeaza media, mediana si modul pentru notele clasei tale la matematica. Deseneaza o histograma.',
            'Procenat' => 'Procent',
            'U odeljenju od 30 ucenika, 18 je polozilo test. Koliki procenat je polozio, a koliki nije? Nacrtaj sektorski dijagram.' => 'Intr-o clasa de 30 de elevi, 18 au trecut testul. Ce procent a trecut si ce procent nu? Deseneaza o diagrama sectoriala.',
            'Anketiraj odeljenje o omiljenom godishnjem dobu (prolece, leto, jesen, zima). Unesi odgovore u listu i napravi frekvencijski dijagram i sektorski dijagram.' => 'Fa un sondaj in clasa despre anotimpul preferat (primavara, vara, toamna, iarna). Introdu raspunsurile intr-o lista si fa o diagrama de frecventa si o diagrama sectoriala.',
            'Tabela ucenika' => 'Tabelul elevilor',
            'Napravi tabelu sa imenima, ocenama iz 3 predmeta za 6 ucenika. Izracunaj prosek svakog ucenika i sortiraj po proseku.' => 'Fa un tabel cu numele si notele la 3 materii pentru 6 elevi. Calculeaza media fiecarui elev si sorteaza dupa medie.',
            'Koristeci tabelu iz Zadatka 1, nadji:' => 'Folosind tabelul din Exercitiul 1, gaseste:',
            'Ucenike sa prosekom vecim od 4' => 'Elevii cu media mai mare de 4',
            'Ucenike sa 5 iz informatike' => 'Elevii cu 5 la informatica',
            'Fudbalska tabela' => 'Clasamentul de fotbal',
            'Napravi tabelu Superlige Srbije sa 6 timova' => 'Fa un tabel al Superligii Serbiei cu 6 echipe',
            'Izracunaj bodove (pobeda=3, nereseno=1) i gol razliku. Sortiraj po bodovima.' => 'Calculeaza punctele (victorie=3, egal=1) si golaverajul. Sorteaza dupa puncte.',

            // === PYTHON COMMENTS ===
            '# Ovo je celija sa kodom - klikni Run All!' => '# Aceasta este o celula cu cod - apasa Run All!',
            '# Sa print - prikazuje sve' => '# Cu print - afiseaza totul',
            '# Bez print - samo poslednji izraz' => '# Fara print - doar ultima expresie',
            '# Koristimo promenljive iz prethodne celije' => '# Folosim variabilele din celula anterioara',
            '# Mozemo i menjati promenljive' => '# Putem si modifica variabilele',
            '# 1. Napravi promenljivu' => '# 1. Creeaza variabila',
            "sa vrednoscu 'Informatika'" => "cu valoarea 'Informatica'",
            '# 2. Napravi promenljivu' => '# 2. Creeaza variabila',
            'sa tvojom ocenom iz informatike' => 'cu nota ta la informatica',
            '# 3. Ispisi recenicu koristeci obe promenljive' => '# 3. Afiseaza o propozitie folosind ambele variabile',
            '# Ispisujemo tekst (pod navodnicima)' => '# Afisam text (intre ghilimele)',
            '# Ispisujemo broj (bez navodnika)' => '# Afisam un numar (fara ghilimele)',
            '# Ispisujemo vise stvari odjednom (razdvojeno zarezom)' => '# Afisam mai multe lucruri deodata (separate prin virgula)',
            '# f-string - ubacujemo promenljive u tekst' => '# f-string - inseram variabile in text',
            '# Sabiranje i oduzimanje' => '# Adunare si scadere',
            '# Mnozenje i deljenje' => '# Inmultire si impartire',
            '# obicno deljenje (sa decimalama)' => '# impartire normala (cu zecimale)',
            '# Celobrojno deljenje i ostatak' => '# Impartire intreaga si rest',
            '# // deli i odbacuje decimale, % daje ostatak' => '# // imparte si elimina zecimalele, % da restul',
            '# Stepenovanje - ** znaci' => '# Ridicare la putere - ** inseamna',
            '# round() - zaokruzivanje' => '# round() - rotunjire',
            '# zaokruzi na ceo broj' => '# rotunjeste la numar intreg',
            '# na 2 decimale' => '# la 2 zecimale',
            '# na 3 decimale' => '# la 3 zecimale',
            '# abs() - apsolutna vrednost (bez minusa)' => '# abs() - valoarea absoluta (fara minus)',
            '# vec je pozitivan' => '# deja pozitiv',
            '# math.sqrt() - kvadratni koren' => '# math.sqrt() - radacina patrata',
            '# jer 12*12=144' => '# deoarece 12*12=144',
            '# math.pi - broj Pi' => '# math.pi - numarul Pi',
            '# math.ceil() - zaokruzi NAVISE' => '# math.ceil() - rotunjeste IN SUS',
            '# (navise!)' => '# (in sus!)',
            '# (vec je ceo)' => '# (deja intreg)',
            '# math.floor() - zaokruzi NANIZE' => '# math.floor() - rotunjeste IN JOS',
            '# (nanize!)' => '# (in jos!)',
            '# Podaci' => '# Date',
            '# jedna pizza za 4 osobe' => '# o pizza pentru 4 persoane',
            '# sok za 3 osobe' => '# suc pentru 3 persoane',
            '# jedna torta' => '# un tort',
            '# Racunanje' => '# Calcul',
            '# zaokruzi navise!' => '# rotunjeste in sus!',
            '# Lista ocena' => '# Lista de note',
            '# Pristup elementima - indeks pocinje od 0!' => '# Accesarea elementelor - indexul incepe de la 0!',
            '# prvi element' => '# primul element',
            '# poslednji element' => '# ultimul element',
            '# od 0 do 3 (ne ukljucujuci 3)' => '# de la 0 la 3 (fara 3)',
            '# Lista moze da sadrzi razlicite tipove' => '# Lista poate contine tipuri diferite',
            '# indeks 1 = drugi element' => '# index 1 = al doilea element',
            '# broji elemente' => '# numara elemente',
            '# 5 ocena u listi' => '# 5 note in lista',
            '# 11 slova u reci' => '# 11 litere in cuvant',
            '# 0 elemenata' => '# 0 elemente',
            '# sum() sabira sve, len() broji koliko ih ima' => '# sum() aduna totul, len() numara cate sunt',
            '# :.2f znaci 2 decimale' => '# :.2f inseamna 2 zecimale',
            '# sum() - sabira sve' => '# sum() - aduna totul',
            '# min() - najmanja vrednost' => '# min() - valoarea minima',
            '# max() - najveca vrednost' => '# max() - valoarea maxima',
            '# Prosek = zbir / broj' => '# Media = suma / numar',
            '# append() - dodaj na kraj' => '# append() - adauga la sfarsit',
            '# remove() - ukloni prvo pojavljivanje' => '# remove() - elimina prima aparitie',
            '# obrisana je trojka' => '# a fost sters 3-ul',
            '# Paznja: remove brise samo PRVO pojavljivanje!' => '# Atentie: remove sterge doar PRIMA aparitie!',
            '# obrisana samo prva petica' => '# stearsa doar primul 5',
            '# sorted() pravi novu sortiranu listu' => '# sorted() creeaza o lista noua sortata',
            '# Sortiranje teksta (po abecedi)' => '# Sortarea textului (dupa alfabet)',
            '# zip() - spaja dve liste u parove' => '# zip() - uneste doua liste in perechi',
            '# Prolazimo kroz obe liste istovremeno' => '# Parcurgem ambele liste simultan',
            '# index() - gde se nalazi element?' => '# index() - unde se afla elementul?',
            '# na poziciji 3' => '# pe pozitia 3',
            '# na poziciji 0' => '# pe pozitia 0',
            '# Korisno: koji dan je bio najtopliji?' => '# Util: ce zi a fost cea mai calda?',
            '# pozicija max temperature' => '# pozitia temperaturii maxime',
            '# Dodavanje i brisanje' => '# Adaugare si stergere',
            '# dodaj na kraj' => '# adauga la sfarsit',
            '# ukloni prvo pojavljivanje broja 3' => '# elimina prima aparitie a numarului 3',
            '# Sortiranje' => '# Sortare',
            '# Nacin 1: rucno brojanje' => '# Metoda 1: numarare manuala',
            '# Nacin 2: sa collections.Counter' => '# Metoda 2: cu collections.Counter',
            '# Nacin 1: rucno' => '# Metoda 1: manual',
            '# Nacin 2: sa statistics bibliotekom' => '# Metoda 2: cu biblioteca statistics',
            '# Podaci o ucenicima' => '# Date despre elevi',
            '# Informacije o tabeli' => '# Informatii despre tabel',
            '# Jedna kolona' => '# O coloana',
            '# Vise kolona' => '# Mai multe coloane',
            '# Jedan red (po indeksu)' => '# Un rand (dupa index)',
            '# Jedna celija' => '# O celula',
            '# describe() daje prosek, min, max, itd.' => '# describe() da media, min, max, etc.',
            '# Prosecne ocene po predmetima:' => '# Notele medii pe materii:',
            '# Prosek svakog ucenika:' => '# Media fiecarui elev:',
            '# Sortiraj po bodovima (rastuce)' => '# Sorteaza dupa puncte (crescator)',
            '# Sortiraj po bodovima (opadajuce)' => '# Sorteaza dupa puncte (descrescator)',
            '# Ucenici sa vise od 90 bodova' => '# Elevi cu peste 90 de puncte',
            '# Ucenici iz Zrenjanina' => '# Elevi din Zrenjanin',
            '# Kombinovanje uslova' => '# Combinarea conditiilor',
            '# & znaci I (AND), | znaci ILI (OR)' => '# & inseamna SI (AND), | inseamna SAU (OR)',
            '# Ucenici iz Zrenjanina SA vise od 90 bodova' => '# Elevi din Zrenjanin CU peste 90 de puncte',
            '# Prosecni bodovi po gradu' => '# Punctajul mediu pe oras',
            '# Broj ucenika po gradu' => '# Numarul de elevi pe oras',
            '# Pravimo podatke i cuvamo u CSV' => '# Cream datele si le salvam in CSV',
            '# Citamo CSV fajl' => '# Citim fisierul CSV',
            '# Gustina naseljenosti' => '# Densitatea populatiei',
            '# Napravi tabelu' => '# Creeaza tabelul',
            '# Dodaj kolonu' => '# Adauga coloana',
            '# Sortiraj i prikazi' => '# Sorteaza si afiseaza',
            '# Filtriranje' => '# Filtrare',
            '# Simuliramo' => '# Simulam',
            '# Automatski izvestaj' => '# Raport automat',
            '# Automatski grafik' => '# Grafic automat',
            '# Zameni svojim predmetima i ocenama' => '# Inlocuieste cu materiile si notele tale',
            '# Nacrtaj stubicasti dijagram' => '# Deseneaza diagrama cu bare',
            '# Nacrtaj obe linije na istom grafiku' => '# Deseneaza ambele linii pe acelasi grafic',
            '# Dodaj naslov, oznake osa, legendu i mrezu' => '# Adauga titlu, etichete axe, legenda si grila',
            '# Nacrtaj horizontalni stubicasti dijagram' => '# Deseneaza diagrama cu bare orizontale',
            '# Sortiraj od najveceg do najmanjeg broja glasova' => '# Sorteaza de la cel mai mare la cel mai mic numar de voturi',
            '# Ocene tvog odeljenja iz matematike (zameni pravim ocenama)' => '# Notele clasei tale la matematica (inlocuieste cu note reale)',
            '# Izracunaj prosek, medijanu i mod' => '# Calculeaza media, mediana si modul',
            '# Nacrtaj histogram' => '# Deseneaza histograma',
            '# Izracunaj procente' => '# Calculeaza procentele',
            '# Nacrtaj sektorski dijagram' => '# Deseneaza diagrama sectoriala',
            '# Unesi odgovore ankete' => '# Introdu raspunsurile sondajului',
            '# dopuni' => '# completeaza',
            '# Frekvencijska analiza' => '# Analiza frecventei',
            '# Nacrtaj oba dijagrama' => '# Deseneaza ambele diagrame',
            '# Napravi fudbalsku tabelu' => '# Creeaza clasamentul de fotbal',
            '# Izracunaj bodove i gol razliku' => '# Calculeaza punctele si golaverajul',
            '# Zameni svojim ocenama' => '# Inlocuieste cu notele tale',

            // === PYTHON PRINT STRINGS ===
            'Zdravo, ja sam Jupyter!' => 'Buna, eu sunt Jupyter!',
            'Danas ucimo nesto novo i zanimljivo!' => 'Astazi invatam ceva nou si interesant!',
            'Rezultat je:' => 'Rezultatul este:',
            'Zdravo svete!' => 'Salut lume!',
            'Ocene:' => 'Note:',
            'Broj ocena:' => 'Numarul de note:',
            'Prva ocena:' => 'Prima nota:',
            'Poslednja ocena:' => 'Ultima nota:',
            'Prva tri:' => 'Primele trei:',
            'Ucenici:' => 'Elevi:',
            'Drugi ucenik:' => 'Al doilea elev:',
            'Zbir:' => 'Suma:',
            'Najmanji:' => 'Cel mai mic:',
            'Najveci:' => 'Cel mai mare:',
            'Prosek:' => 'Media:',
            'Pre:' => 'Inainte:',
            'Posle dodavanja:' => 'Dupa adaugare:',
            'Posle brisanja:' => 'Dupa stergere:',
            'Originalno:' => 'Original:',
            'Sortirano:' => 'Sortat:',
            'Obrnuto:' => 'Inversat:',
            'Po abecedi:' => 'Dupa alfabet:',
            'Broj merenja:' => 'Numarul de masuratori:',
            'Minimum:' => 'Minimum:',
            'Maksimum:' => 'Maximum:',
            'Temperature po danima:' => 'Temperaturi pe zile:',
            'Prosecna temperatura:' => 'Temperatura medie:',
            'Najhladniji dan:' => 'Cea mai rece zi:',
            'Najtopliji dan:' => 'Cea mai calda zi:',
            'Prosecna godisnja temperatura:' => 'Temperatura medie anuala:',
            'Medijana:' => 'Mediana:',
            'Najhladniji:' => 'Cel mai rece:',
            'Najtopliji:' => 'Cel mai cald:',
            'Frekvencije:' => 'Frecvente:',
            'Od najcesceg:' => 'De la cel mai frecvent:',
            'Najcesca ocena:' => 'Nota cea mai frecventa:',
            'Rezultati ankete:' => 'Rezultatele sondajului:',
            'Oblik tabele:' => 'Forma tabelului:',
            'Kolone:' => 'Coloane:',
            'Treci ucenik:' => 'Al treilea elev:',
            'Od najmanje do najvise:' => 'De la cel mai mic la cel mai mare:',
            'Od najvise do najmanje:' => 'De la cel mai mare la cel mai mic:',
            'Iz Zrenjanina:' => 'Din Zrenjanin:',
            'Prosek po gradu:' => 'Media pe oras:',
            'Broj ucenika po gradu:' => 'Numarul de elevi pe oras:',
            'CSV fajl sacuvan!' => 'Fisierul CSV a fost salvat!',
            'Originalna tabela:' => 'Tabelul original:',
            'Sa prosekom:' => 'Cu media:',
            'Bez fizickog:' => 'Fara educatie fizica:',
            'Sacuvano u' => 'Salvat in',
            '=== NEDELJNI IZVESTAJ ===' => '=== RAPORTUL SAPTAMANAL ===',
            'Broj ucenika:' => 'Numarul de elevi:',
            'Prosek odeljenja:' => 'Media clasei:',
            'Najbolji ucenik:' => 'Cel mai bun elev:',
            'Prosek po uceniku' => 'Media pe elev',
            'Prosek po kategoriji' => 'Media pe categorie',
            'Gustina naseljenosti (stanovnika/km2):' => 'Densitatea populatiei (locuitori/km2):',

            // === PYTHON VARIABLE NAMES IN PRINT/STRING CONTEXT ===
            'predmet' => 'materie',
            'ocena' => 'nota',
            'omiljeni_predmet' => 'materia_preferata',
            'prezime' => 'prenume',
            'razred' => 'clasa',
            'sekundi_u_minutu' => 'secunde_pe_minut',
            'minuta_u_satu' => 'minute_pe_ora',
            'sati_u_danu' => 'ore_pe_zi',
            '# sekundi u jednom danu' => '# secunde intr-o zi',
            '# sekundi u jednoj nedelji' => '# secunde intr-o saptamana',
            '# sekundi u jednoj godini (365 dana)' => '# secunde intr-un an (365 de zile)',
            '# Upisi svoje ocene iz informatike' => '# Scrie notele tale la informatica',
            '# zameni svojim ocenama' => '# inlocuieste cu notele tale',
            'Moje ocene:' => 'Notele mele:',
            'Zaokruzeno:' => 'Rotunjit:',
            '# poluprecnik u cm' => '# raza in cm',
            '# Izracunaj obim (O = 2 * pi * r) i povrsinu (P = pi * r^2)' => '# Calculeaza perimetrul (P = 2 * pi * r) si suprafata (S = pi * r^2)',
            'gostiju treba:' => 'invitati trebuie:',
            'komada' => 'bucati',
            'UKUPNO:' => 'TOTAL:',

            // City/name translations for context
            'Beograd' => 'Belgrad',
            // Keep names as they are (Ana, Marko, etc.)

            // Subject names in data
            "'Informatika'" => "'Informatica'",
            "'Matem.'" => "'Matem.'",
            "'Srpski'" => "'Romana'",
            "'Fizicko'" => "'Ed. fizica'",
            "'Biolog.'" => "'Biolog.'",
            "'Likovno'" => "'Desen'",
            "'Muzicko'" => "'Muzica'",
            "'Fizika'" => "'Fizica'",
            "'Engl.'" => "'Engl.'",

            // Sport names
            "'fudbal'" => "'fotbal'",
            "'kosarka'" => "'baschet'",
            "'tenis'" => "'tenis'",
            "'odbojka'" => "'volei'",
            "'plivanje'" => "'inot'",
            "'Fudbal'" => "'Fotbal'",
            "'Kosarka'" => "'Baschet'",
            "'Odbojka'" => "'Volei'",
            "'Tenis'" => "'Tenis'",
            "'Plivanje'" => "'Inot'",

            // Season names
            "'leto'" => "'vara'",
            "'prolece'" => "'primavara'",
            "'zima'" => "'iarna'",
            "'jesen'" => "'toamna'",

            // Food/item names in examples
            'bundeva' => 'dovleac',
            'Sladoledi' => 'Inghetate',
            'Cokolade' => 'Ciocolate',
            'sladoledi' => 'inghetate',
            'cokolade' => 'ciocolate',
            'Prevoz' => 'Transport',
            'Hrana' => 'Mancare',
            'Ulaznice' => 'Bilete',
            'Suveniri' => 'Suveniruri',
            'Ponasanje' => 'Comportament',
            'Aktivnost' => 'Activitate',
            'Domaci' => 'Tema',
            'Stanovnici' => 'Locuitori',
            'Povrsina_km2' => 'Suprafata_km2',
            'Gustina' => 'Densitate',
            'Bodovi' => 'Puncte',
            'Grad' => 'Oras',
            'Pobede' => 'Victorii',
            'Nereseno' => 'Egaluri',
            'Porazi' => 'Infrangeri',
            'Golovi_dati' => 'Goluri_marcate',
            'Golovi_primljeni' => 'Goluri_primite',
            'Ucenik' => 'Elev',

            // General words that appear in various contexts
            'Koliko procenata cini deo od celine?' => 'Ce procent reprezinta partea din total?',
            'puta' => 'ori',
            'Prosecne ocene po predmetima:' => 'Notele medii pe materii:',
            "'Mesec'" => "'Luna'",
            'nedeljni izvestaj' => 'raport saptamanal',

            // f-string translations
            'ima {' => 'are {',
            'ce imati {' => 'va avea {',
            'Sledece godine' => 'Anul viitor',
            'Iz predmeta' => 'La materia',
            'imam ocenu' => 'am nota',
            'Devojcice:' => 'Fete:',
            'Decki:' => 'Baieti:',
            'Ukupno:' => 'Total:',

            // Table content words
            'polozili' => 'promovat',
            'glasovi' => 'voturi',
            'glasova' => 'voturi',

            // Misc
            'Koren od' => 'Radacina din',
            'Pi zaokruzeno' => 'Pi rotunjit',
            'Pon' => 'Lun',
            'Uto' => 'Mar',
            'Sre' => 'Mie',
            'Cet' => 'Joi',
            'Pet' => 'Vin',
            'Sub' => 'Sam',
            'Ned' => 'Dum',
            'Jan' => 'Ian',
            'Feb' => 'Feb',
            'Mar' => 'Mar',
            'Apr' => 'Apr',
            'Maj' => 'Mai',
            'Jun' => 'Iun',
            'Jul' => 'Iul',
            'Avg' => 'Aug',
            'Sep' => 'Sep',
            'Okt' => 'Oct',
            'Nov' => 'Nov',
            'Dec' => 'Dec',

            // Section headers
            'Sta je' => 'Ce este',
            'Kako se koristi:' => 'Cum se foloseste:',
            'Primer iz zivota:' => 'Exemplu din viata:',
            'Primer iz zivota' => 'Exemplu din viata',
            'Sta radi:' => 'Ce face:',
            'Kada koristiti:' => 'Cand se foloseste:',
            'Vazno:' => 'Important:',
            'Napomena:' => 'Nota:',
            'Sta je biblioteka?' => 'Ce este o biblioteca?',
            'Sta je lista?' => 'Ce este o lista?',
            'Sta je CSV?' => 'Ce este CSV?',
            'Sta je pandas?' => 'Ce este pandas?',
            'Kada koristimo linijski dijagram?' => 'Cand folosim diagrama liniara?',
            'Kada sta koristimo?' => 'Cand ce folosim?',
            'Zasto se zove Jupyter?' => 'De ce se numeste Jupyter?',
            'Kako Jupyter radi?' => 'Cum functioneaza Jupyter?',
            'Gde se Jupyter koristi?' => 'Unde se foloseste Jupyter?',
            'Sve zajedno:' => 'Totul impreuna:',
            'Kompletna analiza temperature' => 'Analiza completa a temperaturii',
            'Naslovi i oznake' => 'Titluri si etichete',
            'Podesavanje osa' => 'Setarea axelor',
            'Isticanje sektora sa explode' => 'Evidentierea sectoarelor cu explode',
            'Racunanje procenata' => 'Calcularea procentelor',
            'Racunanje proseka rucno' => 'Calcularea mediei manual',
            'Vizuelizacija frekvencija' => 'Vizualizarea frecventelor',
            'Brojanje pojavljivanja' => 'Numararea aparitiilor',
            'Pristup podacima' => 'Accesarea datelor',
            'Statistika tabele' => 'Statistica tabelului',
            'Grupiranje podataka' => 'Gruparea datelor',
            'Zapisivanje u CSV' => 'Salvarea in CSV',
            'Operacije sa listama' => 'Operatii cu liste',
            'Liste brojeva pomazu u analizi' => 'Listele de numere ajuta in analiza',
            'Vise linija na jednom dijagramu' => 'Mai multe linii pe o singura diagrama',
            'Primer: Omiljeni predmeti' => 'Exemplu: Materiile preferate',
            'Primer: Budzet za skolski izlet' => 'Exemplu: Bugetul pentru excursia scolara',
            'Primer: Analiza temperature' => 'Exemplu: Analiza temperaturii',
            'Primer: Anketa o omiljenom sportu' => 'Exemplu: Sondaj despre sportul preferat',
            'Prvi dijagram' => 'Prima diagrama',
            'Celije sa kodom' => 'Celule cu cod',
            'Celije sa tekstom' => 'Celule cu text',
            'Funkcije' => 'Functiile',
            'Metode' => 'Metodele',
            'Funkcija' => 'Functia',
            'Biblioteka' => 'Biblioteca',
            'Osnovne operacije' => 'Operatii de baza',
            'Pregled' => 'Prezentarea',

            // Safety: these single words at end
            'U skolama' => 'In scoli',
            'U nauci' => 'In stiinta',
            'U firmama' => 'In companii',
            'U novinarstvu' => 'In jurnalism',
        ];

        // Apply translations (longest first for safety)
        $keys = array_keys($translations);
        $values = array_values($translations);

        // Sort by length descending to avoid partial replacements
        array_multisort(array_map('strlen', $keys), SORT_DESC, $keys, $values);

        return str_replace($keys, $values, $content);
    }

    public function run(): void
    {
        // Clean existing content for course 5
        $chapters = Chapter::where('course_id', $this->courseId)->get();
        foreach ($chapters as $ch) {
            foreach ($ch->subchapters as $sub) {
                $sub->lessons()->delete();
            }
            $ch->subchapters()->delete();
        }
        $chapters->each->delete();

        // Get Serbian course structure
        $srbChapters = Chapter::where('course_id', 4)->orderBy('order')->get();

        foreach ($srbChapters as $srbCh) {
            $roTitle = $this->chapterTitles[$srbCh->title] ?? $srbCh->title;
            $roCh = Chapter::create([
                'course_id' => $this->courseId,
                'title' => $roTitle,
                'order' => $srbCh->order,
            ]);

            foreach ($srbCh->subchapters()->orderBy('order')->get() as $srbSub) {
                $roSubTitle = $this->subchapterTitles[$srbSub->title] ?? $srbSub->title;
                $roSub = Subchapter::create([
                    'chapter_id' => $roCh->id,
                    'title' => $roSubTitle,
                    'order' => $srbSub->order,
                ]);

                foreach ($srbSub->lessons()->orderBy('order')->get() as $srbLesson) {
                    $roLessonTitle = $this->lessonTitles[$srbLesson->title] ?? $srbLesson->title;
                    $roContent = $this->translateContent($srbLesson->content);

                    Lesson::create([
                        'course_id' => $this->courseId,
                        'subchapter_id' => $roSub->id,
                        'title' => $roLessonTitle,
                        'content' => $roContent,
                        'order' => $srbLesson->order,
                        'is_assignment' => $srbLesson->is_assignment,
                    ]);
                }
            }
        }

        echo "Curs Jupyter in romana creat cu succes!\n";
    }
}
