<?php

namespace Database\Seeders;

use App\Models\Chapter;
use App\Models\Subchapter;
use App\Models\Lesson;
use Illuminate\Database\Seeder;

class PygameRomanianSeeder extends Seeder
{
    private int $srcCourseId = 12; // Informatika 7
    private int $dstCourseId = 13; // Informatica 7

    private array $chapterTitles = [
        'Uvod u Pygame' => 'Introducere in Pygame',
        'Napredni oblici i tekst' => 'Forme avansate si text',
        'Crtanje pomocu petlji' => 'Desenarea cu ajutorul buclelor',
        'Funkcije za crtanje' => 'Functii pentru desenare',
    ];

    private array $subchapterTitles = [
        'Prve korake' => 'Primii pasi',
        'Elipse, poligoni, tekst' => 'Elipse, poligoane, text',
        'Ponavljanje oblika' => 'Repetarea formelor',
        'Organizovanje koda' => 'Organizarea codului',
    ];

    private array $lessonTitles = [
        'Sta je Pygame?' => 'Ce este Pygame?',
        'Crtanje linija' => 'Desenarea liniilor',
        'Pravougaonici i krugovi' => 'Dreptunghiuri si cercuri',
        'Domaci: Moj prvi crtez' => 'Tema: Primul meu desen',
        'Elipse i poligoni' => 'Elipse si poligoane',
        'Pisanje teksta' => 'Scrierea textului',
        'Racunanje koordinata' => 'Calcularea coordonatelor',
        'Domaci: Kreativni crtez' => 'Tema: Desen creativ',
        'Ponavljanje oblika sa for petljom' => 'Repetarea formelor cu bucla for',
        'Slozeni oblici i obrasci' => 'Forme complexe si modele',
        'Grananje u crtanju (if/else)' => 'Ramificarea in desenare (if/else)',
        'Domaci: Petlje u crtanju' => 'Tema: Bucle in desenare',
        'Pravljenje funkcija za crtanje' => 'Crearea functiilor pentru desenare',
        'Slozeni crtezi sa funkcijama' => 'Desene complexe cu functii',
        'Pregled svih Pygame komandi' => 'Prezentarea tuturor comenzilor Pygame',
        'Zavrsni projekat: Moja slika' => 'Proiect final: Imaginea mea',
    ];

    private function translateContent(string $content): string
    {
        $t = [
            // === MISSED PHRASES ===
            'Kako radi Pygame program?' => 'Cum functioneaza un program Pygame?',
            'Tacka' => 'Punctul',
            'Kako se pise tekst?' => 'Cum se scrie textul?',
            'Sta je funkcija?' => 'Ce este o functie?',
            'Sta je Pygame?' => 'Ce este Pygame?',

            // === LONG HTML PARAGRAPHS (most specific first) ===
            'Pygame je Python biblioteka za pravljenje igara i grafickih programa. Sa njom mozes da crtas oblike, pravis animacije, a kasnije i prave igre!' => 'Pygame este o biblioteca Python pentru crearea jocurilor si a programelor grafice. Cu ea poti desena forme, crea animatii, iar mai tarziu si jocuri adevarate!',
            'U nasem LMS-u Pygame radi direktno u browseru - ne moras nista da instaliras. Samo napises kod i kliknes <strong>Run</strong>.' => 'In LMS-ul nostru Pygame functioneaza direct in browser - nu trebuie sa instalezi nimic. Doar scrii codul si apesi <strong>Run</strong>.',
            'Svaki Pygame program ima istu strukturu:' => 'Fiecare program Pygame are aceeasi structura:',
            'Uvoz biblioteke' => 'Importarea bibliotecii',
            'Pravljenje prozora' => 'Crearea ferestrei',
            'Bojenje pozadine' => 'Colorarea fundalului',
            'Crtanje oblika' => 'Desenarea formelor',
            'razne draw funkcije' => 'diverse functii draw',
            'Prikaz' => 'Afisare',
            'Pygame koristi koordinatni sistem koji je malo drugaciji od onog u matematici:' => 'Pygame foloseste un sistem de coordonate putin diferit de cel din matematica:',
            'je u <strong>gornjem levom uglu</strong> (ne u donjem levom!)' => 'este in <strong>coltul din stanga sus</strong> (nu in cel din stanga jos!)',
            'raste udesno (kao u matematici)' => 'creste spre dreapta (ca in matematica)',
            'raste nadole (suprotno od matematike!)' => 'creste in jos (opus matematicii!)',
            'Zamisli da je ekran list papira na zidu. Vrh papira je y=0, a dno je y=400.' => 'Imagineaza-ti ca ecranul este o foaie de hartie pe perete. Partea de sus a foii este y=0, iar partea de jos este y=400.',
            'Boje se zadaju kao tri broja: <strong>(R, G, B)</strong> - crvena, zelena, plava. Svaki broj ide od 0 do 255.' => 'Culorile se specifica ca trei numere: <strong>(R, G, B)</strong> - rosu, verde, albastru. Fiecare numar merge de la 0 la 255.',
            'Pokreni kod ispod - videces beli prozor sa plavom pozadinom:' => 'Ruleaza codul de mai jos - vei vedea o fereastra cu fundal albastru deschis:',

            // Lines lesson
            'Linija je najjednostavniji oblik. Zadajemo joj pocetnu i krajnju tacku.' => 'Linia este cea mai simpla forma. Ii specificam punctul de inceput si punctul de sfarsit.',
            'Crta pravu liniju od jedne tacke do druge.' => 'Deseneaza o linie dreapta de la un punct la altul.',
            'gde crtamo' => 'unde desenam',
            'trojka' => 'triplet',
            'pocetna tacka' => 'punctul de inceput',
            'krajnja tacka' => 'punctul de sfarsit',
            'koliko je linija debela (u pikselima)' => 'cat de groasa este linia (in pixeli)',
            'Hajde da nacrtamo jednostavnu kucu koristeci samo linije:' => 'Hai sa desenam o casa simpla folosind doar linii:',

            // Rectangles and circles
            'Linije su korisne, ali za vecinu crteza koristimo oblike - pravougaonike i krugove.' => 'Liniile sunt utile, dar pentru majoritatea desenelor folosim forme - dreptunghiuri si cercuri.',
            'gornji levi ugao pravougaonika' => 'coltul din stanga sus al dreptunghiului',
            'dimenzije' => 'dimensiunile',
            '0 znaci popunjen, broj > 0 znaci samo okvir te debljine' => '0 inseamna umplut, un numar > 0 inseamna doar conturul de acea grosime',
            'centar kruga' => 'centrul cercului',
            'velicina kruga' => 'marimea cercului',
            '0 = popunjen, > 0 = samo kruznica' => '0 = umplut, > 0 = doar circumferinta',

            // Ellipses and polygons
            'Crta elipsu (izduzeni krug) unutar zadatog pravougaonika.' => 'Deseneaza o elipsa (cerc alungit) in interiorul dreptunghiului specificat.',
            'Elipsa se upisuje u nevidljivi pravougaonik. Ako je sirina = visina, dobijamo krug!' => 'Elipsa se inscrie intr-un dreptunghi invizibil. Daca latimea = inaltimea, obtinem un cerc!',
            'Crta oblik sa proizvoljnim brojem temena (uglova). Zadajemo listu tacaka.' => 'Deseneaza o forma cu un numar arbitrar de varfuri (colturi). Specificam o lista de puncte.',
            'Sa 3 tacke crtamo trougao, sa 5 petougao, sa 6 sestougao...' => 'Cu 3 puncte desenam un triunghi, cu 5 un pentagon, cu 6 un hexagon...',

            // Text lesson
            'Osim oblika, mozemo pisati i tekst na ekranu. Za to koristimo Pygame fontove.' => 'Pe langa forme, putem scrie si text pe ecran. Pentru asta folosim fonturile Pygame.',
            'Pisanje teksta u Pygame-u ima tri koraka:' => 'Scrierea textului in Pygame are trei pasi:',
            'Napravi font' => 'Creeaza fontul',
            'Renderuj tekst' => 'Randeaza textul',
            'Nacrtaj na prozoru' => 'Deseneaza pe fereastra',
            'Inicijalizuje font sistem (obavezno pre koriscenja)' => 'Initializeaza sistemul de fonturi (obligatoriu inainte de utilizare)',
            'Pravi font sa zadatim imenom i velicinom' => 'Creeaza un font cu numele si marimea specificate',
            'Pretvara tekst u sliku (True = glatke ivice)' => 'Converteste textul in imagine (True = margini netede)',
            'Crta sliku/tekst na poziciji (x, y)' => 'Deseneaza imaginea/textul la pozitia (x, y)',

            // Coordinates lesson
            'Do sada smo koordinate pisali rucno. Ali sta ako hoces da crtez bude uvek centriran, ili da se prilagodi velicini prozora? Za to koristimo <strong>promenljive i racunanje</strong>.' => 'Pana acum am scris coordonatele manual. Dar ce facem daca vrem ca desenul sa fie mereu centrat, sau sa se adapteze la dimensiunea ferestrei? Pentru asta folosim <strong>variabile si calcule</strong>.',
            'Ako je prozor 400x300, centar je na (200, 150). Ali bolje je da izracunamo:' => 'Daca fereastra este 400x300, centrul este la (200, 150). Dar este mai bine sa calculam:',
            'Umesto fiksnih brojeva, mozemo racunati pozicije relativno - npr. "50% od sirine", "treci deo visine"...' => 'In loc de numere fixe, putem calcula pozitiile relativ - de ex. "50% din latime", "o treime din inaltime"...',

            // Loops lesson
            'Sta ako treba da nacrtas 10 krugova u redu? Ili 20 linija? Rucno bi trajalo predugo. Sa <strong>for petljom</strong> mozemo to uraditi u par redova!' => 'Ce faci daca trebuie sa desenezi 10 cercuri in rand? Sau 20 de linii? Manual ar dura prea mult. Cu <strong>bucla for</strong> putem face asta in cateva randuri!',
            'Mozemo menjati ne samo poziciju, vec i boju, velicinu i oblik u svakoj iteraciji:' => 'Putem schimba nu doar pozitia, ci si culoarea, marimea si forma la fiecare iteratie:',
            'Sa <strong>dve ugnjezdene petlje</strong> mozemo crtati u redovima i kolonama:' => 'Cu <strong>doua bucle imbricate</strong> putem desena in randuri si coloane:',
            'Kombinovanjem petlji i matematike mozemo praviti fascinantne obrasce!' => 'Combinand buclele si matematica putem crea modele fascinante!',
            'Sa <code>if</code> i <code>else</code> u petlji mozemo crtati razlicite oblike na razlicitim mestima.' => 'Cu <code>if</code> si <code>else</code> in bucla putem desena forme diferite in locuri diferite.',

            // Functions lesson
            'Kada crtas slozenije crteze, kod postaje dugacak i nepregledan. <strong>Funkcije</strong> nam pomazu da organizujemo kod - napisemo crtez jednom, pa ga pozovemo koliko god puta zelimo.' => 'Cand desenezi desene mai complexe, codul devine lung si greu de citit. <strong>Functiile</strong> ne ajuta sa organizam codul - scriem desenul o data, apoi il apelam de cate ori dorim.',
            'Funkcija je blok koda koji ima ime i moze da primi parametre. Definisemo je sa <code>def</code>:' => 'Functia este un bloc de cod care are un nume si poate primi parametri. O definim cu <code>def</code>:',
            'Sada mozemo nacrtati drvo gde god zelimo pozivanjem' => 'Acum putem desena un copac oriunde dorim apeland',
            'Sada kada znamo da pravimo funkcije, mozemo praviti veoma slozene crteze koji su i dalje pregledni.' => 'Acum ca stim sa cream functii, putem face desene foarte complexe care raman totusi clare.',
            'Evo kompletnog pregleda svega sto smo naucili u Pygame kursu.' => 'Iata o prezentare completa a tot ce am invatat in cursul Pygame.',
            'Vreme je da napravis svoju veliku sliku! Koristi <strong>sve sto si naucio</strong>: oblike, boje, petlje, funkcije i tekst.' => 'E timpul sa iti faci propria imagine mare! Foloseste <strong>tot ce ai invatat</strong>: forme, culori, bucle, functii si text.',

            // Domaci tasks
            'Koristi sve sto si naucio - linije, pravougaonike i krugove - da nacrtas zadatke ispod.' => 'Foloseste tot ce ai invatat - linii, dreptunghiuri si cercuri - pentru a desena exercitiile de mai jos.',
            'Nacrtaj zastavu Srbije: tri horizontalne trake (crvena, plava, bela) pomocu tri pravougaonika.' => 'Deseneaza steagul Serbiei: trei dungi orizontale (rosu, albastru, alb) folosind trei dreptunghiuri.',
            'Nacrtaj smajlija: veliki zuti krug za glavu, dva manja crna kruga za oci, i crvenu liniju za osmeh.' => 'Deseneaza un smiley: un cerc mare galben pentru cap, doua cercuri mici negre pentru ochi si o linie rosie pentru zambet.',
            'Nacrtaj robota koristeci pravougaonike (telo, glava, ruke, noge) i krugove (oci, dugmad).' => 'Deseneaza un robot folosind dreptunghiuri (corp, cap, maini, picioare) si cercuri (ochi, butoane).',
            'Nacrtaj sneska od tri kruga (veliki, srednji, mali), sa ocima, nosom (narandzasti trougao), dugmadima i sesiricem.' => 'Deseneaza un om de zapada din trei cercuri (mare, mediu, mic), cu ochi, nas (triunghi portocaliu), butoane si palarie.',
            'Nacrtaj tamno plavo nebo sa mescem (zuti krug) i zvezdama (mali zuti krugovi ili poligoni).' => 'Deseneaza un cer albastru inchis cu luna (cerc galben) si stele (cercuri mici galbene sau poligoane).',
            'Nacrtaj sta god zelis! Koristi sve naucene oblike: linije, pravougaonike, krugove, elipse, poligone i tekst.' => 'Deseneaza orice doresti! Foloseste toate formele invatate: linii, dreptunghiuri, cercuri, elipse, poligoane si text.',
            'Nacrtaj ogradu: 10 vertikalnih linija (stubovi) spojenih sa dve horizontalne linije (precke). Koristi for petlju.' => 'Deseneaza un gard: 10 linii verticale (stalpi) unite cu doua linii orizontale (traverse). Foloseste bucla for.',
            'Nacrtaj piramidu: prvi red ima 7 blokova, drugi 5, treci 3, cetvrti 1. Koristi dve ugnjezdene petlje.' => 'Deseneaza o piramida: primul rand are 7 blocuri, al doilea 5, al treilea 3, al patrulea 1. Foloseste doua bucle imbricate.',
            'Napravi sopstveni obrazac koristeci petlje! Ideje: koncentricni kvadrati, spirala pravougaonika, sahovska tabla u boji, mozaik...' => 'Creeaza propriul model folosind bucle! Idei: patrate concentrice, spirala de dreptunghiuri, tabla de sah colorata, mozaic...',

            // Zavrsni projekat requirements
            'Minimum 5 razlicitih oblika (linija, pravougaonik, krug, elipsa, poligon)' => 'Minimum 5 forme diferite (linie, dreptunghi, cerc, elipsa, poligon)',
            'Bar jedna for petlja' => 'Cel putin o bucla for',
            'Bar jedna funkcija koju definises sam' => 'Cel putin o functie definita de tine',
            'Tekst (naslov ili potpis)' => 'Text (titlu sau semnatura)',
            'Minimum 5 razlicitih boja' => 'Minimum 5 culori diferite',
            'Pejzaz' => 'Peisaj',
            'planine, reka, drvo, sunce, oblaci' => 'munti, rau, copac, soare, nori',
            'Svemirska scena' => 'Scena spatiala',
            'planete, zvezde, svemirski brod' => 'planete, stele, nava spatiala',
            'Podvodni svet' => 'Lumea subacvatica',
            'ribe, korali, morsko dno' => 'pesti, corali, fundul marii',
            'Grad noci' => 'Orasul noptii',
            'zgrade, svetla, mesec' => 'cladiri, lumini, luna',
            'Tvoja soba' => 'Camera ta',
            'sto, racunar, polica sa knjigama' => 'birou, calculator, raft de carti',

            // === TABLE CONTENT ===
            'Boja' => 'Culoare',
            'RGB vrednost' => 'Valoarea RGB',
            'Kako zapamtiti' => 'Cum sa retii',
            'Crna' => 'Negru',
            'Bela' => 'Alb',
            'Crvena' => 'Rosu',
            'Zelena' => 'Verde',
            'Plava' => 'Albastru',
            'Zuta' => 'Galben',
            'Narandzasta' => 'Portocaliu',
            'Ljubicasta' => 'Violet',
            'Siva' => 'Gri',
            'Svetlo plava' => 'Albastru deschis',
            'Sve ugaseno' => 'Totul stins',
            'Sve upaljeno' => 'Totul aprins',
            'Samo R' => 'Doar R',
            'Samo G' => 'Doar G',
            'Samo B' => 'Doar B',
            'R + G' => 'R + G',
            'R + malo G' => 'R + putin G',
            'R + B' => 'R + B',
            'Sve na pola' => 'Totul la jumatate',
            'Nebo' => 'Cer',
            'Komanda' => 'Comanda',
            'Sta radi' => 'Ce face',
            'Primer' => 'Exemplu',
            'Sta crta' => 'Ce deseneaza',
            'Kljucni parametri' => 'Parametri cheie',
            'Uvozi Pygame biblioteku' => 'Importa biblioteca Pygame',
            'Uvek na pocetku' => 'Intotdeauna la inceput',
            'Pravi prozor sirine w i visine h' => 'Creeaza o fereastra de latime w si inaltime h',
            'Boji ceo prozor zadatom bojom' => 'Coloreaza intreaga fereastra cu culoarea specificata',
            'Prikazuje sve sto smo nacrtali' => 'Afiseaza tot ce am desenat',
            'Uvek na kraju' => 'Intotdeauna la sfarsit',
            'Liniju' => 'Linie',
            'Pravougaonik' => 'Dreptunghi',
            'Krug' => 'Cerc',
            'Elipsu' => 'Elipsa',
            'Poligon' => 'Poligon',
            'pocetna tacka, krajnja tacka, debljina' => 'punct de inceput, punct de sfarsit, grosime',
            '(x, y, sirina, visina), debljina (0=popunjen)' => '(x, y, latime, inaltime), grosime (0=umplut)',
            'centar (cx,cy), poluprecnik, debljina (0=popunjen)' => 'centru (cx,cy), raza, grosime (0=umplut)',
            'Pravougaonik u koji se upisuje' => 'Dreptunghiul in care se inscrie',
            'Lista tacaka (3=trougao, 5=petougao...)' => 'Lista de puncte (3=triunghi, 5=pentagon...)',
            'Inicijalizuje font sistem' => 'Initializeaza sistemul de fonturi',
            'Pravi font' => 'Creeaza fontul',
            'Pretvara tekst u sliku' => 'Converteste textul in imagine',
            'Crta sliku na prozor' => 'Deseneaza imaginea pe fereastra',
            'Pozicija, dimenzije' => 'Pozitie, dimensiuni',
            'Centar, poluprecnik' => 'Centru, raza',
            'Popunjen oblik' => 'Forma umpluta',
            'Samo okvir' => 'Doar contur',
            'Ponavlja oblike' => 'Repeta formele',
            'Slozen oblik' => 'Forma complexa',
            'Centar prozora' => 'Centrul ferestrei',
            'Debljina 0' => 'Grosime 0',
            'Debljina > 0' => 'Grosime > 0',
            'Petlja za crtanje' => 'Bucla pentru desenare',
            'Funkcija' => 'Functie',
            'Trik' => 'Truc',
            'Objasnjenje' => 'Explicatie',
            'Osnovno' => 'Bazele',
            'Crtanje oblika' => 'Desenarea formelor',
            'Tekst' => 'Text',
            'Korisni trikovi' => 'Trucuri utile',
            'crvena' => 'rosu',
            'Uvozi biblioteku' => 'Importa biblioteca',
            'Prikazuje crtez' => 'Afiseaza desenul',
            'Boji pozadinu' => 'Coloreaza fundalul',
            'Pravi prozor' => 'Creeaza fereastra',

            // === SECTION HEADINGS ===
            'Koordinatni sistem' => 'Sistemul de coordonate',
            'Boje u Pygame-u' => 'Culorile in Pygame',
            'Tvoj prvi Pygame program' => 'Primul tau program Pygame',
            'Pregled komandi' => 'Prezentarea comenzilor',
            'Pregled komandi za crtanje' => 'Prezentarea comenzilor de desenare',
            'Pregled komandi za tekst' => 'Prezentarea comenzilor pentru text',
            'Pregled svih Pygame komandi' => 'Prezentarea tuturor comenzilor Pygame',
            'Primer: Kuca od linija' => 'Exemplu: Casa din linii',
            'Primer: Semafor' => 'Exemplu: Semafor',
            'Primer: Jelka' => 'Exemplu: Bradul de Craciun',
            'Primer: Vizit karta' => 'Exemplu: Carte de vizita',
            'Primer: Olimpijski krugovi' => 'Exemplu: Cercurile olimpice',
            'Primer: Sahovska tabla' => 'Exemplu: Tabla de sah',
            'Primer: Duga' => 'Exemplu: Curcubeul',
            'Primer: Grad' => 'Exemplu: Orasul',
            'Primer: Akvariium' => 'Exemplu: Acvariul',
            'Centar prozora' => 'Centrul ferestrei',
            'Relativne koordinate' => 'Coordonate relative',
            'Osnovni primer: Red krugova' => 'Exemplu de baza: Rand de cercuri',
            'Promena boje u petlji' => 'Schimbarea culorii in bucla',
            'Mreza (grid)' => 'Retea (grid)',
            'Koncentricni krugovi' => 'Cercuri concentrice',
            'Spiralna tacka' => 'Punct in spirala',
            'Naizmenicni oblici' => 'Forme alternante',
            'Funkcija sa vise parametara' => 'Functie cu mai multi parametri',
            'Kako se pise tekst?' => 'Cum se scrie textul?',
            'Ideje za temu' => 'Idei pentru tema',
            'Zahtevi' => 'Cerinte',

            // h2 titles
            'Sta je Pygame?' => 'Ce este Pygame?',
            'Crtanje linija' => 'Desenarea liniilor',
            'Pravougaonici i krugovi' => 'Dreptunghiuri si cercuri',
            'Domaci: Moj prvi crtez' => 'Tema: Primul meu desen',
            'Elipse i poligoni' => 'Elipse si poligoane',
            'Pisanje teksta' => 'Scrierea textului',
            'Racunanje koordinata' => 'Calcularea coordonatelor',
            'Domaci: Kreativni crtez' => 'Tema: Desen creativ',
            'Ponavljanje oblika sa for petljom' => 'Repetarea formelor cu bucla for',
            'Slozeni oblici i obrasci' => 'Forme complexe si modele',
            'Grananje u crtanju (if/else)' => 'Ramificarea in desenare (if/else)',
            'Domaci: Petlje u crtanju' => 'Tema: Bucle in desenare',
            'Pravljenje funkcija za crtanje' => 'Crearea functiilor pentru desenare',
            'Slozeni crtezi sa funkcijama' => 'Desene complexe cu functii',
            'Zavrsni projekat: Moja slika' => 'Proiect final: Imaginea mea',

            // === CODE EXERCISE INSTRUCTIONS ===
            'Pokreni program. Probaj da promenis boju pozadine - stavi (255, 200, 200) za roze ili (200, 255, 200) za svetlo zelenu.' => 'Ruleaza programul. Incearca sa schimbi culoarea fundalului - pune (255, 200, 200) pentru roz sau (200, 255, 200) pentru verde deschis.',
            'Pokreni pa probaj da promenis koordinate i boje linija.' => 'Ruleaza si incearca sa schimbi coordonatele si culorile liniilor.',
            'Nacrtali smo kucu sa krovom. Probaj da dodas prozor na kucu (dva horizontalna i dva vertikalna para linija).' => 'Am desenat o casa cu acoperis. Incearca sa adaugi o fereastra pe casa (doua perechi de linii orizontale si verticale).',
            'Popunjeni oblik ima debljinu 0 (ili bez parametra). Okvir ima debljinu > 0. Probaj oba!' => 'Forma umpluta are grosimea 0 (sau fara parametru). Conturul are grosimea > 0. Incearca ambele!',
            'Centar kruga je (cx, cy), a poluprecnik je koliko je krug velik. Probaj razne velicine!' => 'Centrul cercului este (cx, cy), iar raza este cat de mare este cercul. Incearca diverse marimi!',
            'Semafor sa tri svetla. Probaj da promenis velicinu semafora ili da dodas okvire oko svetala.' => 'Semafor cu trei lumini. Incearca sa schimbi marimea semaforului sau sa adaugi contururi in jurul luminilor.',
            'Elipsa se upisuje u pravougaonik (x, y, sirina, visina). Siroka elipsa = sirina > visina.' => 'Elipsa se inscrie intr-un dreptunghi (x, y, latime, inaltime). Elipsa lata = latime > inaltime.',
            'Poligon moze imati koliko god tacaka zelis. Probaj da napravis zvezdicu sa 10 tacaka!' => 'Poligonul poate avea cate puncte doresti. Incearca sa faci o steluta cu 10 puncte!',
            'Jelka sa kuglicama! Dodaj jos kuglica ili napravi sneg (bele krugove).' => 'Brad cu globuri! Adauga mai multe globuri sau fa zapada (cercuri albe).',
            'Font.render() pravi sliku od teksta, a blit() je crta na prozor. Probaj razne velicine i boje!' => 'Font.render() creeaza o imagine din text, iar blit() o deseneaza pe fereastra. Incearca diverse marimi si culori!',
            'Vizit karta! Promeni ime i informacije da bude tvoja karta.' => 'Carte de vizita! Schimba numele si informatiile ca sa fie cartea ta.',
            'Nisan je uvek centriran jer koristimo cx i cy. Probaj da promenis SIRINA i VISINA!' => 'Tinta este mereu centrata deoarece folosim cx si cy. Incearca sa schimbi LATIME si INALTIME!',
            'Tri kruga su ravnomerno rasporedjeni jer koristimo SIRINA // 4. Dodaj cetvrti krug!' => 'Trei cercuri sunt distribuite uniform deoarece folosim LATIME // 4. Adauga al patrulea cerc!',
            'Olimpijski krugovi! Sve pozicije su izracunate relativno od centra (cx, cy).' => 'Cercurile olimpice! Toate pozitiile sunt calculate relativ fata de centru (cx, cy).',
            'range(8) daje brojeve 0,1,2,...,7. Koristimo i da racunamo x poziciju svakog kruga.' => 'range(8) da numerele 0,1,2,...,7. Folosim i pentru a calcula pozitia x a fiecarui cerc.',
            'Boja se menja jer koristimo i za racunanje crvene komponente!' => 'Culoarea se schimba deoarece folosim i pentru calcularea componentei rosii!',
            'Dve petlje = mreza! red i kolona odredjuju poziciju svakog kruga.' => 'Doua bucle = retea! rand si coloana determina pozitia fiecarui cerc.',
            'Sahovska tabla sa 8x8 polja! (red + kolona) % 2 menja boju naizmenicno.' => 'Tabla de sah cu 8x8 casute! (rand + coloana) % 2 schimba culoarea alternativ.',
            'Krugovi se crtaju od najviseg ka najmanjem. Svaki ima drugaciju boju!' => 'Cercurile se deseneaza de la cel mai mare la cel mai mic. Fiecare are o culoare diferita!',
            'Spirala! Koristimo math.cos i math.sin za kruzhno kretanje, a udaljenost raste.' => 'Spirala! Folosim math.cos si math.sin pentru miscare circulara, iar distanta creste.',
            'Duga se crta kao niz sve manjih krugova, pa se donji deo prekrije pravougaonikom boje neba.' => 'Curcubeul se deseneaza ca un sir de cercuri din ce in ce mai mici, apoi partea de jos se acopera cu un dreptunghi de culoarea cerului.',
            'i % 2 == 0 proverava da li je i parno. Parni crtaju krug, neparni kvadrat.' => 'i % 2 == 0 verifica daca i este par. Cei pari deseneaza cerc, cei impari patrat.',
            'Nocni grad! random.randint daje slucajne brojeve. Svaki put se generise isti grad jer koristimo seed(42).' => 'Orasul de noapte! random.randint da numere aleatoare. De fiecare data se genereaza acelasi oras deoarece folosim seed(42).',
            'Definisemo funkciju jednom, a koristimo je koliko zelimo! Parametar velicina menja velicinu drveta.' => 'Definim functia o singura data si o folosim de cate ori dorim! Parametrul marime schimba marimea copacului.',
            'Tri razlicite kuce jednom funkcijom! Svaka ima svoju boju i velicinu.' => 'Trei case diferite cu o singura functie! Fiecare are propria culoare si marime.',
            'Akvarijum sa ribama, biljkama i mehurima! Svaka riba je nacrtana jednim pozivom funkcije.' => 'Acvariu cu pesti, plante si bule! Fiecare peste este desenat cu un singur apel de functie.',
            'Nacrtaj ogradu sa 10 stubova pomocu for petlje.' => 'Deseneaza un gard cu 10 stalpi folosind bucla for.',
            'Koristeci petlje, nacrtaj piramidu od blokova.' => 'Folosind bucle, deseneaza o piramida din blocuri.',
            'Budi kreativan! Koristi petlje, razne boje i oblike.' => 'Fii creativ! Foloseste bucle, diverse culori si forme.',
            'Dopuni kod da nacrtas zastavu sa tri trake jednake visine.' => 'Completeaza codul pentru a desena steagul cu trei dungi de aceeasi inaltime.',
            'Nacrtaj smajlija koristeci krugove i linije.' => 'Deseneaza un smiley folosind cercuri si linii.',
            'Napravi svog robota! Koristi razne boje i velicine.' => 'Creeaza-ti propriul robot! Foloseste diverse culori si marimi.',
            'Nacrtaj sneska koristeci krugove, pravougaonike i poligone!' => 'Deseneaza un om de zapada folosind cercuri, dreptunghiuri si poligoane!',
            'Budi kreativan! Dodaj planine, drvece, oblake...' => 'Fii creativ! Adauga munti, copaci, nori...',
            'Slobodan izbor! Koristi sve sto si naucio.' => 'Alegere libera! Foloseste tot ce ai invatat.',
            'Napravi svoju jedinstvenu sliku! Koristi sve sto si naucio: oblike, petlje, funkcije i tekst.' => 'Creeaza-ti propria imagine unica! Foloseste tot ce ai invatat: forme, bucle, functii si text.',

            // === PYTHON COMMENTS ===
            '# Napravi prozor 400x300 piksela' => '# Creeaza o fereastra de 400x300 pixeli',
            '# Oboji pozadinu svetlo plavom bojom' => '# Coloreaza fundalul cu albastru deschis',
            '# Prikazi sve na ekranu' => '# Afiseaza totul pe ecran',
            '# bela pozadina' => '# fundal alb',
            '# Crvena horizontalna linija' => '# Linie orizontala rosie',
            '# Zelena vertikalna linija' => '# Linie verticala verde',
            '# Plava dijagonalna linija' => '# Linie diagonala albastra',
            '# Zidovi kuce' => '# Peretii casei',
            '# gore' => '# sus',
            '# levo' => '# stanga',
            '# desno' => '# dreapta',
            '# dole' => '# jos',
            '# Krov' => '# Acoperis',
            '# Vrata' => '# Usa',
            '# Popunjen crveni pravougaonik' => '# Dreptunghi rosu umplut',
            '# Samo okvir' => '# Doar contur',
            '# Zeleni kvadrat' => '# Patrat verde',
            '# Popunjen narandzasti krug' => '# Cerc portocaliu umplut',
            '# Kruznica' => '# Circumferinta',
            '# Mali crveni krug' => '# Cerc mic rosu',
            '# siva pozadina' => '# fundal gri',
            '# Telo semafora' => '# Corpul semaforului',
            '# Crveno svetlo' => '# Lumina rosie',
            '# Zuto svetlo' => '# Lumina galbena',
            '# Zeleno svetlo' => '# Lumina verde',
            '# Stubic' => '# Stalp',
            '# Siroka elipsa' => '# Elipsa lata',
            '# Visoka elipsa' => '# Elipsa inalta',
            '# Elipsa samo okvir' => '# Elipsa doar contur',
            '# Trougao' => '# Triunghi',
            '# Petougao' => '# Pentagon',
            '# Dijamant/romb' => '# Diamant/romb',
            '# Stablo' => '# Trunchiul',
            '# Tri zelena trougla' => '# Trei triunghiuri verzi',
            '# Zvezdica na vrhu' => '# Steluta in varf',
            '# Kuglice' => '# Globuri',
            '# nebo' => '# cer',
            '# Napravi font' => '# Creeaza fontul',
            '# Renderuj tekst' => '# Randeaza textul',
            '# Nacrtaj na prozoru na poziciji' => '# Deseneaza pe fereastra la pozitia',
            '# Okvir' => '# Rama',
            '# Dekorativna linija' => '# Linie decorativa',
            '# Fontovi' => '# Fonturi',
            '# Ime' => '# Numele',
            '# Informacije' => '# Informatii',
            '# Centar prozora' => '# Centrul ferestrei',
            '# Nisan (target)' => '# Tinta (target)',
            '# Linije krsta' => '# Liniile crucii',
            '# Tri jednaka kruga, ravnomerno rasporedjeni' => '# Trei cercuri egale, distribuite uniform',
            '# razmak' => '# spatiere',
            '# poluprecnik kruga' => '# raza cercului',
            '# razmak izmedju krugova' => '# spatiul dintre cercuri',
            '# Gornji red:' => '# Randul de sus:',
            '# Donji red:' => '# Randul de jos:',
            '# 8 krugova u redu' => '# 8 cercuri in rand',
            '# svaki krug je 60 piksela desnije' => '# fiecare cerc este cu 60 pixeli mai la dreapta',
            '# Krugovi koji postaju sve crveniji' => '# Cercuri care devin din ce in ce mai rosii',
            '# od 0 do 225' => '# de la 0 la 225',
            '# Mreza krugova 8x8' => '# Retea de cercuri 8x8',
            '# Naizmenicne boje' => '# Culori alternante',
            '# velicina jednog polja' => '# marimea unui camp',
            '# svetla' => '# deschis',
            '# tamna' => '# inchis',
            '# crna pozadina' => '# fundal negru',
            '# Koncentricni krugovi' => '# Cercuri concentrice',
            '# Spirala od tacaka' => '# Spirala din puncte',
            '# Boje duge' => '# Culorile curcubeului',
            '# Prekrij donji deo nebom' => '# Acopera partea de jos cu cer',
            '# Oblak' => '# Nor',
            '# Naizmenicno krugovi i kvadrati' => '# Alternativ cercuri si patrate',
            '# nocno nebo' => '# cerul noptatii',
            '# Zvezde' => '# Stele',
            '# Zgrade razlicitih visina' => '# Cladiri de diverse inaltimi',
            '# isti rezultat svaki put' => '# acelasi rezultat de fiecare data',
            '# Prozori na zgradama' => '# Ferestre pe cladiri',
            '# 70% prozora je upaljeno' => '# 70% din ferestre sunt aprinse',
            '# Trava' => '# Iarba',
            '# Crtamo vise drveca pozivom iste funkcije!' => '# Desenam mai multi copaci apeland aceeasi functie!',
            '# Oblaci' => '# Nori',
            '# Zidovi' => '# Pereti',
            '# Vrata' => '# Usa',
            '# Prozor' => '# Fereastra',
            '# Naslov' => '# Titlul',
            '# trava' => '# iarba',
            '# kod za crtanje drveta na poziciji' => '# codul pentru desenarea copacului la pozitia',
            '# Telo (elipsa)' => '# Corpul (elipsa)',
            '# Rep (trougao)' => '# Coada (triunghi)',
            '# Oko' => '# Ochiul',
            '# Pozadina vode' => '# Fundalul apei',
            '# Pesak na dnu' => '# Nisipul de pe fund',
            '# Biljke' => '# Plante',
            '# Ribe' => '# Pesti',
            '# Mehurici' => '# Bule',
            '# Tvoj zavrsni projekat!' => '# Proiectul tau final!',
            '# Definisi funkcije za ponavljajuce elemente:' => '# Defineste functii pentru elementele repetitive:',
            '# Nacrtaj pozadinu:' => '# Deseneaza fundalul:',
            '# Koristi petlje za ponavljanje:' => '# Foloseste bucle pentru repetare:',
            '# Dodaj tekst (naslov i potpis):' => '# Adauga text (titlu si semnatura):',
            '# Crvena traka (gore)' => '# Dunga rosie (sus)',
            '# Plava traka (sredina)' => '# Dunga albastra (mijloc)',
            '# Bela traka (dole)' => '# Dunga alba (jos)',
            '# Glava' => '# Capul',
            '# Telo' => '# Corpul',
            '# Ruke' => '# Mainile',
            '# Noge' => '# Picioarele',
            '# Oci i dugmad' => '# Ochii si butoanele',
            '# Mesec' => '# Luna',
            '# Planine ili drvo dole' => '# Munti sau copac jos',
            '# Ograda:' => '# Gardul:',
            '# Piramida od blokova' => '# Piramida din blocuri',
            '# Tvoj obrazac ovde!' => '# Modelul tau aici!',
            '# Tvoj crtez ovde!' => '# Desenul tau aici!',
            '# svetlo plavo nebo' => '# cerul albastru deschis',
            '# tamno plavo nebo' => '# cerul albastru inchis',

            // === PYTHON STRINGS ===
            "'Pygame!'" => "'Pygame!'",
            "'Ucimo da crtamo'" => "'Invatam sa desenam'",
            "'Petar Petrovic'" => "'Petar Petrovic'",
            "'Ucenik 7. razreda'" => "'Elev in clasa a 7-a'",
            "'OS Zarko Zrenjanin'" => "'OS Zarko Zrenjanin'",
            "'Omiljeni predmet: Informatika'" => "'Materia preferata: Informatica'",
            "'Moje selo'" => "'Satul meu'",
            "'Moj akvarijum'" => "'Acvariul meu'",

            // Variable names
            'SIRINA' => 'LATIME',
            'VISINA' => 'INALTIME',
            'prozor' => 'fereastra',
            'sirina' => 'latime',
            'visina' => 'inaltime',
            'boja' => 'culoare',
            'debljina' => 'grosime',
            'velicina' => 'marime',
            'poluprecnik' => 'raza',
            'nacrtaj_drvo' => 'deseneaza_copac',
            'nacrtaj_oblak' => 'deseneaza_nor',
            'nacrtaj_kucu' => 'deseneaza_casa',
            'nacrtaj_ribu' => 'deseneaza_peste',
            'nacrtaj_mehur' => 'deseneaza_bula',
            'nacrtaj_biljku' => 'deseneaza_planta',
            'boja_zida' => 'culoare_perete',
            'boja_krova' => 'culoare_acoperis',
            'naslov' => 'titlu',
            'podnaslov' => 'subtitlu',
            'tekst_ime' => 'text_nume',
            'font_veliki' => 'font_mare',
            'font_mali' => 'font_mic',
            'font_ime' => 'font_nume',
            'font_info' => 'font_info',
            'za_krug' => 'pt_cerc',
            'ugao' => 'unghi',
            'udaljenost' => 'distanta',
            'boje' => 'culori',
            'svetla' => 'deschis',
            'tamna' => 'inchis',
            'red' => 'rand',
            'kolona' => 'coloana',

            // Misc
            'Zadatak 1:' => 'Exercitiul 1:',
            'Zadatak 2:' => 'Exercitiul 2:',
            'Zadatak 3:' => 'Exercitiul 3:',
            'Zastava Srbije' => 'Steagul Serbiei',
            'Lice' => 'Fata',
            'Robot' => 'Robot',
            'Sneskovic' => 'Om de zapada',
            'Nocno nebo' => 'Cerul noptii',
            'Tvoj izbor' => 'Alegerea ta',
            'Ograda' => 'Gard',
            'Piramida od blokova' => 'Piramida din blocuri',
            'Tvoj obrazac' => 'Modelul tau',
            'Ideje:' => 'Idei:',
            'grad, automobil, cvet, zivotinja, tvoja soba...' => 'oras, automobil, floare, animal, camera ta...',
        ];

        $keys = array_keys($t);
        $values = array_values($t);
        array_multisort(array_map('strlen', $keys), SORT_DESC, $keys, $values);

        return str_replace($keys, $values, $content);
    }

    public function run(): void
    {
        // Clean existing
        $chapters = Chapter::where('course_id', $this->dstCourseId)->get();
        foreach ($chapters as $ch) {
            foreach ($ch->subchapters as $sub) {
                $sub->lessons()->delete();
            }
            $ch->subchapters()->delete();
        }
        $chapters->each->delete();

        // Copy from Serbian
        $srcChapters = Chapter::where('course_id', $this->srcCourseId)->orderBy('order')->get();

        foreach ($srcChapters as $srcCh) {
            $roCh = Chapter::create([
                'course_id' => $this->dstCourseId,
                'title' => $this->chapterTitles[$srcCh->title] ?? $srcCh->title,
                'order' => $srcCh->order,
            ]);

            foreach ($srcCh->subchapters()->orderBy('order')->get() as $srcSub) {
                $roSub = Subchapter::create([
                    'chapter_id' => $roCh->id,
                    'title' => $this->subchapterTitles[$srcSub->title] ?? $srcSub->title,
                    'order' => $srcSub->order,
                ]);

                foreach ($srcSub->lessons()->orderBy('order')->get() as $srcLesson) {
                    Lesson::create([
                        'course_id' => $this->dstCourseId,
                        'subchapter_id' => $roSub->id,
                        'title' => $this->lessonTitles[$srcLesson->title] ?? $srcLesson->title,
                        'content' => $this->translateContent($srcLesson->content),
                        'order' => $srcLesson->order,
                        'is_assignment' => $srcLesson->is_assignment,
                    ]);
                }
            }
        }

        echo "Curs Pygame in romana creat cu succes! 4 capitole, 12 lectii.\n";
    }
}
