<?php

namespace Database\Seeders;

use App\Models\Chapter;
use App\Models\Subchapter;
use App\Models\Lesson;
use Illuminate\Database\Seeder;

class PythonOsnoveRomanianSeeder extends Seeder
{
    private int $srcCourseId = 14;
    private int $dstCourseId = 15;

    private array $chapterTitles = [
        'Upoznavanje sa Pythonom' => 'Cunoasterea Python',
        'Grananje - if i else' => 'Ramificarea - if si else',
        'Petlje - ponavljanje' => 'Bucle - repetarea',
        'Liste' => 'Liste',
        'Funkcije' => 'Functii',
    ];

    private array $subchapterTitles = [
        'Prve naredbe' => 'Primele comenzi',
        'Donosenje odluka' => 'Luarea deciziilor',
        'for i while' => 'for si while',
        'Rad sa listama' => 'Lucrul cu liste',
        'Pravljenje funkcija' => 'Crearea functiilor',
    ];

    private array $lessonTitles = [
        'Sta je Python i naredba print' => 'Ce este Python si comanda print',
        'Promenljive' => 'Variabile',
        'Ucitavanje podataka - input()' => 'Citirea datelor - input()',
        'Domaci: Print, promenljive i input' => 'Tema: Print, variabile si input',
        'Naredba if' => 'Comanda if',
        'if-else i elif' => 'if-else si elif',
        'Logicki operatori (and, or, not)' => 'Operatori logici (and, or, not)',
        'Domaci: Grananje' => 'Tema: Ramificarea',
        'Petlja for i range()' => 'Bucla for si range()',
        'Petlja while' => 'Bucla while',
        'Ugnjezdene petlje' => 'Bucle imbricate',
        'Domaci: Petlje' => 'Tema: Bucle',
        'Sta su liste?' => 'Ce sunt listele?',
        'Prolazak kroz listu' => 'Parcurgerea listei',
        'Stringovi (niske)' => 'Stringuri (siruri de caractere)',
        'Domaci: Liste i stringovi' => 'Tema: Liste si stringuri',
        'Definisanje i pozivanje funkcija' => 'Definirea si apelarea functiilor',
        'Funkcije - napredni primeri' => 'Functii - exemple avansate',
        'Zavrsni projekat: Mini program' => 'Proiect final: Mini program',
    ];

    private function translateContent(string $content): string
    {
        $t = [
            // ========== LONG PARAGRAPHS ==========
            'Python je jedan od najpoznatijih programskih jezika na svetu. Koriste ga programeri u Google-u, NASA-i, YouTube-u i mnogim igrama!' => 'Python este unul dintre cele mai cunoscute limbaje de programare din lume. Il folosesc programatorii de la Google, NASA, YouTube si in multe jocuri!',
            'Mi cemo ga koristiti da naucimo osnove programiranja. Naredbe se pisu u editoru, a kada kliknes <strong>Run</strong>, racunar ih izvrsi redom od gore ka dole.' => 'Noi il vom folosi pentru a invata bazele programarii. Comenzile se scriu in editor, iar cand apesi <strong>Run</strong>, calculatorul le executa in ordine de sus in jos.',
            'je naredba koja ispisuje tekst ili brojeve na ekran. Tekst se stavlja pod navodnike, a brojevi bez navodnika.' => 'este comanda care afiseaza text sau numere pe ecran. Textul se pune intre ghilimele, iar numerele fara ghilimele.',
            'Mozemo koristiti i jednostruke' => 'Putem folosi si ghilimele simple',
            'navodnike - oba rade isto.' => 'ambele functioneaza la fel.',
            'Svaki <code>print()</code> ispisuje u novi red. Mozemo ispisati i prazan red sa <code>print()</code> bez teksta.' => 'Fiecare <code>print()</code> afiseaza pe un rand nou. Putem afisa si un rand gol cu <code>print()</code> fara text.',
            'Python moze i da racuna! Kada ne stavimo navodnike, Python izracuna rezultat:' => 'Python poate si sa calculeze! Cand nu punem ghilimele, Python calculeaza rezultatul:',
            'Promenljiva je kao kutija sa imenom u koju mozes da stavis neku vrednost. Kasnije mozes da koristis ime kutije umesto same vrednosti.' => 'Variabila este ca o cutie cu un nume in care poti pune o valoare. Mai tarziu poti folosi numele cutiei in loc de valoarea insasi.',
            'Promenljivu pravimo sa znakom <code>=</code>. Sa leve strane je ime, a sa desne vrednost.' => 'Variabila o cream cu semnul <code>=</code>. In stanga este numele, iar in dreapta valoarea.',
            'Kada zelimo da ubacimo promenljivu u tekst, koristimo <strong>f-string</strong>. Stavimo <code>f</code> ispred navodnika, a promenljivu u viticaste zagrade <code>{}</code>:' => 'Cand dorim sa inseram o variabila in text, folosim <strong>f-string</strong>. Punem <code>f</code> inainte de ghilimele, iar variabila in acolade <code>{}</code>:',
            'Ime moze sadrzati slova, brojeve i donju crtu' => 'Numele poate contine litere, cifre si liniuta de jos',
            'ne sme</strong> pocinjati brojem' => 'nu trebuie</strong> sa inceapa cu o cifra',
            'Python razlikuje velika i mala slova' => 'Python face diferenta intre litere mari si mici',
            'su razlicite promenljive' => 'sunt variabile diferite',
            'Koristi opisna imena:' => 'Foloseste nume descriptive:',
            'je bolje od' => 'este mai bun decat',
            'Do sada smo sami pisali vrednosti u kodu. Ali sta ako zelimo da korisnik unese svoj podatak? Za to koristimo' => 'Pana acum am scris singuri valorile in cod. Dar ce facem daca dorim ca utilizatorul sa introduca propriile date? Pentru asta folosim',
            'pauzira program i ceka da korisnik nesto ukuca. Ono sto korisnik ukuca sacuva se kao tekst (string).' => 'pune programul pe pauza si asteapta ca utilizatorul sa tasteze ceva. Ce tasteaza utilizatorul se salveaza ca text (string).',
            'uvek vraca tekst (string), cak i ako korisnik ukuca broj! Da bismo racunali sa tim brojem, moramo ga pretvoriti u broj sa' => 'returneaza intotdeauna text (string), chiar daca utilizatorul tasteaza un numar! Pentru a calcula cu acel numar, trebuie sa il convertim in numar cu',
            '(ceo broj) ili' => '(numar intreg) sau',
            '(decimalni).' => '(numar zecimal).',
            'Mozemo spojiti input i int u jedan red:' => 'Putem combina input si int intr-un singur rand:',
            'U zivotu stalno donosimo odluke: "Ako pada kisa, uzmi kisobran." U Pythonu isto mozemo!' => 'In viata luam decizii in permanenta: "Daca ploua, ia umbrela." In Python putem face la fel!',
            'Naredba <code>if</code> proverava uslov i izvrsava kod samo ako je uslov tacan.' => 'Comanda <code>if</code> verifica conditia si executa codul doar daca conditia este adevarata.',
            'Kod unutar if-a mora biti uvucen (4 razmaka ili Tab). To je Python-ov nacin da zna koji kod pripada if-u.' => 'Codul din interiorul if-ului trebuie indentat (4 spatii sau Tab). Acesta este modul Python de a sti ce cod apartine if-ului.',
            'Za poredjenje koristimo <code>==</code> (dva jednako), a za dodelu vrednosti <code>=</code> (jedno jednako)!' => 'Pentru comparatie folosim <code>==</code> (doua egal), iar pentru atribuirea valorii <code>=</code> (un singur egal)!',
            'se izvrsava kada uslov u <code>if</code> nije tacan. Kao u zivotu: "Ako pada kisa, uzmi kisobran. Inace, idi bez kisobrana."' => 'se executa cand conditia din <code>if</code> nu este adevarata. Ca in viata: "Daca ploua, ia umbrela. Altfel, mergi fara umbrela."',
            'Kada imamo vise od dva izbora, koristimo <code>elif</code> (skracenica od "else if"):' => 'Cand avem mai mult de doua optiuni, folosim <code>elif</code> (prescurtare de la "else if"):',
            'Python proverava uslove redom odozgo. Cim nadje tacan, izvrsava taj blok i preskace ostale.' => 'Python verifica conditiile in ordine de sus in jos. Imediat ce gaseste una adevarata, executa acel bloc si le sare pe celelalte.',
            'Ponekad trebamo proveriti vise uslova istovremeno. Za to koristimo logicke operatore.' => 'Uneori trebuie sa verificam mai multe conditii simultan. Pentru asta folosim operatorii logici.',
            'Kao u zivotu: "Ako imam pare AND imam vremena, idem u bioskop."' => 'Ca in viata: "Daca am bani AND am timp, merg la cinema."',
            '"Ako imam kartu OR sam na listi, ulazim na koncert."' => '"Daca am bilet OR sunt pe lista, intru la concert."',
            'Sta ako treba da ispises "Zdravo" 100 puta? Da pises 100 print naredbi? Naravno da ne! Koristimo <strong>petlju</strong> (loop) - naredbu koja ponavlja kod odredjeni broj puta.' => 'Ce faci daca trebuie sa afisezi "Buna" de 100 de ori? Sa scrii 100 de comenzi print? Bineinteles ca nu! Folosim o <strong>bucla</strong> (loop) - o comanda care repeta codul de un numar specificat de ori.',
            'daje brojeve: 0, 1, 2, 3, 4 (5 brojeva, ali pocinje od 0!).' => 'da numerele: 0, 1, 2, 3, 4 (5 numere, dar incepe de la 0!).',
            'ponavlja kod tacno odredjeni broj puta. Ali sta ako ne znamo unapred koliko puta treba ponoviti? Na primer: "Pitaj korisnika dok ne pogodi broj." Za to koristimo' => 'repeta codul de un numar exact de ori. Dar ce facem daca nu stim dinainte de cate ori trebuie sa repetam? De exemplu: "Intreaba utilizatorul pana cand ghiceste numarul." Pentru asta folosim',
            'While ponavlja kod SVE DOK je uslov tacan. Cim uslov postane netacan, petlja se zavrsava.' => 'While repeta codul ATAT TIMP CAT conditia este adevarata. Imediat ce conditia devine falsa, bucla se termina.',
            'Petlju mozemo staviti unutar druge petlje. Za svaki krug spoljne petlje, unutrasnja petlja se izvrsi cela.' => 'Putem pune o bucla in interiorul altei bucle. Pentru fiecare tura a buclei exterioare, bucla interioara se executa complet.',
            'Lista je uredjen niz podataka. Zamisli je kao policu za knjige - svaka knjiga ima svoje mesto (indeks), pocevsi od 0.' => 'Lista este un sir ordonat de date. Imagineaz-o ca un raft de carti - fiecare carte are locul sau (index), incepand de la 0.',
            'Najcesci posao sa listom je da prodjemo kroz sve elemente i uradimo nesto sa svakim. To radimo sa <code>for</code> petljom.' => 'Cea mai frecventa operatie cu o lista este sa parcurgem toate elementele si sa facem ceva cu fiecare. Facem asta cu bucla <code>for</code>.',
            'String (niska) je niz karaktera - tekst. U Pythonu, string se ponasa slicno listi: ima duzinu, mozemo pristupiti svakom karakteru po indeksu, i prolaziti petljom.' => 'Stringul (sirul de caractere) este o secventa de caractere - text. In Python, stringul se comporta similar unei liste: are lungime, putem accesa fiecare caracter dupa index si parcurge cu o bucla.',
            'Funkcija je blok koda sa imenom koji mozemo pozvati koliko god puta zelimo. Kao recept u kuhinji - napises ga jednom, a koristis uvek kad treba.' => 'Functia este un bloc de cod cu un nume pe care il putem apela de cate ori dorim. Ca o reteta in bucatarie - o scrii o data si o folosesti ori de cate ori ai nevoie.',
            'vraca vrednost iz funkcije. Kao kada pitas nekoga "koliko je 5+3?" i on ti vrati odgovor "8".' => 'returneaza o valoare din functie. Ca atunci cand intrebi pe cineva "cat face 5+3?" si iti raspunde "8".',
            'Napravi jedan od sledecih programa koristeci sve sto si naucio: print, input, promenljive, if/else, petlje, liste i funkcije.' => 'Creeaza unul dintre urmatoarele programe folosind tot ce ai invatat: print, input, variabile, if/else, bucle, liste si functii.',
            'Funkcija je blok koda koji ima ime i moze da primi parametre. Definisemo je sa <code>def</code>:' => 'Functia este un bloc de cod care are un nume si poate primi parametri. O definim cu <code>def</code>:',
            'Kada crtas slozenije crteze, kod postaje dugacak i nepregledan. <strong>Funkcije</strong> nam pomazu da organizujemo kod' => 'Cand desenezi lucruri mai complexe, codul devine lung si greu de citit. <strong>Functiile</strong> ne ajuta sa organizam codul',

            // ========== SECTION HEADINGS ==========
            'Sta je Python i naredba print' => 'Ce este Python si comanda print',
            'Naredba print()' => 'Comanda print()',
            'Jednostruki i dvostruki navodnici' => 'Ghilimele simple si duble',
            'Vise print naredbi' => 'Mai multe comenzi print',
            'Racunanje sa print' => 'Calcule cu print',
            'Zapamti' => 'Retine',
            'Pravljenje promenljivih' => 'Crearea variabilelor',
            'Koriscenje promenljivih u racunanju' => 'Folosirea variabilelor in calcule',
            'f-string: Ubacivanje promenljivih u tekst' => 'f-string: Inserarea variabilelor in text',
            'Pravila za imena promenljivih' => 'Regulile pentru numele variabilelor',
            'Funkcija input()' => 'Functia input()',
            'input() i brojevi' => 'input() si numere',
            'Krace pisanje: int(input(...))' => 'Scriere prescurtata: int(input(...))',
            'Naredba if' => 'Comanda if',
            'Kako radi if?' => 'Cum functioneaza if?',
            'Operatori poredjenja' => 'Operatori de comparatie',
            'if-else: Ako... inace...' => 'if-else: Daca... altfel...',
            'elif: Vise uslova' => 'elif: Mai multe conditii',
            'Primer: Paran ili neparan' => 'Exemplu: Par sau impar',
            'Logicki operatori (and, or, not)' => 'Operatori logici (and, or, not)',
            'and - oba uslova moraju biti tacna' => 'and - ambele conditii trebuie sa fie adevarate',
            'or - bar jedan uslov mora biti tacan' => 'or - cel putin o conditie trebuie sa fie adevarata',
            'not - obrce uslov' => 'not - inverseaza conditia',
            'Petlja for i range()' => 'Bucla for si range()',
            'for petlja' => 'bucla for',
            'range() sa razlicitim parametrima' => 'range() cu diferiti parametri',
            'Primer: Odbrojavanje' => 'Exemplu: Numaratoare inversa',
            'Petlja while' => 'Bucla while',
            'Kako radi while?' => 'Cum functioneaza while?',
            'Primer: Pogodi broj' => 'Exemplu: Ghiceste numarul',
            'Sabiranje dok korisnik ne unese 0' => 'Adunare pana cand utilizatorul introduce 0',
            'for ili while?' => 'for sau while?',
            'Ugnjezdene petlje' => 'Bucle imbricate',
            'Primer: Zvezdice' => 'Exemplu: Stelute',
            'Primer: Pravougaonik od zvezdica' => 'Exemplu: Dreptunghi din stelute',
            'Sta su liste?' => 'Ce sunt listele?',
            'Menjanje, dodavanje, brisanje' => 'Modificare, adaugare, stergere',
            'Korisne funkcije za liste' => 'Functii utile pentru liste',
            'Prolazak kroz listu' => 'Parcurgerea listei',
            'Racunanje sa listom' => 'Calcule cu lista',
            'Filtriranje liste' => 'Filtrarea listei',
            'Stringovi (niske)' => 'Stringuri (siruri de caractere)',
            'Prolazak kroz string' => 'Parcurgerea stringului',
            'Korisne metode za stringove' => 'Metode utile pentru stringuri',
            'Definisanje i pozivanje funkcija' => 'Definirea si apelarea functiilor',
            'Pravljenje funkcije - def' => 'Crearea functiei - def',
            'Funkcije sa return' => 'Functii cu return',
            'Primer: Funkcija za proveru parnosti' => 'Exemplu: Functie pentru verificarea paritatii',
            'Funkcije - napredni primeri' => 'Functii - exemple avansate',
            'Funkcija sa podrazumevanom vrednoscu' => 'Functie cu valoare implicita',
            'Primer: Mini dnevnik ocena' => 'Exemplu: Mini catalog de note',
            'Pregled' => 'Prezentare',
            'Zavrsni projekat: Mini program' => 'Proiect final: Mini program',
            'Opcija 1: Kviz igra' => 'Optiunea 1: Joc de quiz',
            'Opcija 2: Lista zadataka (To-Do)' => 'Optiunea 2: Lista de sarcini (To-Do)',
            'Opcija 3: Tvoj izbor' => 'Optiunea 3: Alegerea ta',

            // ========== DOMACI HEADINGS & TEXT ==========
            'Domaci: Print, promenljive i input' => 'Tema: Print, variabile si input',
            'Domaci: Grananje' => 'Tema: Ramificarea',
            'Domaci: Petlje' => 'Tema: Bucle',
            'Domaci: Liste i stringovi' => 'Tema: Liste si stringuri',
            'Zadatak 1:' => 'Exercitiul 1:',
            'Zadatak 2:' => 'Exercitiul 2:',
            'Zadatak 3:' => 'Exercitiul 3:',
            'Vizit karta' => 'Carte de vizita',
            'Ucitaj ime, prezime i razred od korisnika, pa ispisi vizit kartu.' => 'Citeste numele, prenumele si clasa de la utilizator, apoi afiseaza cartea de vizita.',
            'Digitron' => 'Calculator',
            'Ucitaj dva broja i ispisi zbir, razliku, proizvod i kolicnik.' => 'Citeste doua numere si afiseaza suma, diferenta, produsul si catul.',
            'Godine' => 'Varsta',
            'Ucitaj ime i godinu rodjenja. Izracunaj koliko korisnik ima godina i ispisi recenicu.' => 'Citeste numele si anul nasterii. Calculeaza cati ani are utilizatorul si afiseaza o propozitie.',
            'Deljivost' => 'Divizibilitate',
            'Ucitaj broj i proveri da li je deljiv sa 3, sa 5, ili sa oba.' => 'Citeste un numar si verifica daca este divizibil cu 3, cu 5 sau cu ambele.',
            'Kviz' => 'Quiz',
            'Napravi kviz sa 3 pitanja. Na kraju ispisi koliko tacnih odgovora je korisnik dao.' => 'Creeaza un quiz cu 3 intrebari. La sfarsit afiseaza cate raspunsuri corecte a dat utilizatorul.',
            'Kalkulator' => 'Calculator',
            'Napravi jednostavan digitron: ucitaj dva broja i operaciju (+, -, *, /), pa ispisi rezultat.' => 'Creeaza un calculator simplu: citeste doua numere si operatia (+, -, *, /), apoi afiseaza rezultatul.',
            'Tablica mnozenja' => 'Tabla inmultirii',
            'Ucitaj broj od korisnika i ispisi tablicu mnozenja za taj broj (od 1 do 10).' => 'Citeste un numar de la utilizator si afiseaza tabla inmultirii pentru acel numar (de la 1 la 10).',
            'Zbir prvih N brojeva' => 'Suma primelor N numere',
            'Ucitaj N i izracunaj zbir brojeva od 1 do N.' => 'Citeste N si calculeaza suma numerelor de la 1 la N.',
            'Faktorijel' => 'Factorial',
            'Ucitaj N i izracunaj N! (faktorijel = 1 * 2 * 3 * ... * N). Primer: 5! = 120.' => 'Citeste N si calculeaza N! (factorial = 1 * 2 * 3 * ... * N). Exemplu: 5! = 120.',
            'Prosek ocena' => 'Media notelor',
            'Ucitaj 5 ocena od korisnika, stavi ih u listu, pa ispisi prosek, najmanju i najvecu ocenu.' => 'Citeste 5 note de la utilizator, pune-le intr-o lista, apoi afiseaza media, nota minima si nota maxima.',
            'Palindrom' => 'Palindrom',
            'Ucitaj rec i proveri da li je palindrom (cita se isto s leva i s desna). Primeri: ana, radar, level.' => 'Citeste un cuvant si verifica daca este palindrom (se citeste la fel de la stanga la dreapta). Exemple: ana, radar, level.',
            'Najduza rec' => 'Cel mai lung cuvant',
            'Ucitaj 5 reci i ispisi koja je najduza i koliko slova ima.' => 'Citeste 5 cuvinte si afiseaza care este cel mai lung si cate litere are.',
            'Napravi kviz sa 5 pitanja. Broji poene, na kraju ispisi rezultat i ocenu (5 tacnih = 5, 4 tacnih = 4, itd).' => 'Creeaza un quiz cu 5 intrebari. Numara punctele, la sfarsit afiseaza rezultatul si nota (5 corecte = 5, 4 corecte = 4, etc.).',
            'Napravi program gde korisnik moze da dodaje, prikazuje i brise zadatke.' => 'Creeaza un program unde utilizatorul poate adauga, afisa si sterge sarcini.',
            'Napravi bilo koji program! Mora da koristi: bar jednu funkciju, bar jednu petlju, bar jedan if/else, i bar jednu listu.' => 'Creeaza orice program! Trebuie sa foloseasca: cel putin o functie, cel putin o bucla, cel putin un if/else si cel putin o lista.',

            // ========== TABLE HEADERS ==========
            'Kod' => 'Cod',
            'Sta ispisuje' => 'Ce afiseaza',
            'Zasto' => 'De ce',
            'Racuna, jer nema navodnika' => 'Calculeaza, deoarece nu are ghilimele',
            'Ispisuje tekst, jer ima navodnika' => 'Afiseaza text, deoarece are ghilimele',
            'Tekst pod navodnicima' => 'Text intre ghilimele',
            'Funkcija' => 'Functia',
            'Sta radi' => 'Ce face',
            'Primer' => 'Exemplu',
            'Ucitava tekst od korisnika' => 'Citeste text de la utilizator',
            'Pretvara u ceo broj' => 'Converteste in numar intreg',
            'Pretvara u decimalni broj' => 'Converteste in numar zecimal',
            'Operator' => 'Operator',
            'Znacenje' => 'Semnificatie',
            'Rezultat' => 'Rezultat',
            'Jednako' => 'Egal',
            'Razlicito' => 'Diferit',
            'Vece od' => 'Mai mare decat',
            'Manje od' => 'Mai mic decat',
            'Vece ili jednako' => 'Mai mare sau egal',
            'Manje ili jednako' => 'Mai mic sau egal',
            'Naredba' => 'Comanda',
            'Kada se izvrsava' => 'Cand se executa',
            'Kada je uslov tacan (True)' => 'Cand conditia este adevarata (True)',
            'Kada prethodni uslovi nisu tacni, a ovaj jeste' => 'Cand conditiile anterioare nu sunt adevarate, iar aceasta este',
            'Kada nijedan prethodni uslov nije tacan' => 'Cand nicio conditie anterioara nu este adevarata',
            'Oba moraju biti tacna' => 'Ambele trebuie sa fie adevarate',
            'Bar jedan mora biti tacan' => 'Cel putin una trebuie sa fie adevarata',
            'Obrce (True' => 'Inverseaza (True',
            'Poziv' => 'Apel',
            'Brojevi' => 'Numere',
            'Objasnjenje' => 'Explicatie',
            'Od 0 do 4 (5 brojeva)' => 'De la 0 la 4 (5 numere)',
            'Od 1 do 5' => 'De la 1 la 5',
            'Od 0 do 8, korak 2' => 'De la 0 la 8, pas 2',
            'Odbrojavanje' => 'Numaratoare inversa',
            'Petlja' => 'Bucla',
            'Kada koristimo' => 'Cand folosim',
            'Znamo unapred koliko puta' => 'Stim dinainte de cate ori',
            'Ispisi 10 puta, tablica mnozenja' => 'Afiseaza de 10 ori, tabla inmultirii',
            'Ne znamo koliko puta, zavisi od uslova' => 'Nu stim de cate ori, depinde de conditie',
            'Dok ne pogodi, dok ne unese 0' => 'Pana cand ghiceste, pana cand introduce 0',
            'Broj elemenata' => 'Numarul de elemente',
            'Zbir elemenata' => 'Suma elementelor',
            'Najmanji' => 'Cel mai mic',
            'Najveci' => 'Cel mai mare',
            'Sortirana kopija' => 'Copie sortata',
            'Dodaj na kraj' => 'Adauga la sfarsit',
            'Obrisi prvo x' => 'Sterge primul x',
            'Sva velika slova' => 'Toate litere mari',
            'Sva mala slova' => 'Toate litere mici',
            'Broji pojavljivanja' => 'Numara aparitiile',
            'Zamenjuje a sa b' => 'Inlocuieste a cu b',
            'Proverava da li sadrzi' => 'Verifica daca contine',
            'Pojam' => 'Termen',
            'Definise funkciju' => 'Defineste functia',
            'Parametar' => 'Parametru',
            'Vrednost koju funkcija prima' => 'Valoarea pe care o primeste functia',
            'Argument' => 'Argument',
            'Vrednost koju prosledjujemo' => 'Valoarea pe care o transmitem',
            'Vraca vrednost iz funkcije' => 'Returneaza o valoare din functie',
            'Pozivanje' => 'Apelare',
            'Pokrecemo funkciju' => 'Lansam functia',

            // ========== CODE EXERCISE INSTRUCTIONS ==========
            'Pokreni program. Sta se ispisuje? Probaj da promenis tekst u navodnicima.' => 'Ruleaza programul. Ce se afiseaza? Incearca sa schimbi textul dintre ghilimele.',
            'Oba nacina su ispravna. Koristi onaj koji ti se vise svidja!' => 'Ambele moduri sunt corecte. Foloseste-l pe cel care iti place mai mult!',
            'Svaki print ispisuje u novi red. print() bez teksta pravi prazan red.' => 'Fiecare print afiseaza pe un rand nou. print() fara text creeaza un rand gol.',
            'Racunar racuna bez navodnika. Sa navodnicima bi ispisao tekst "5 + 3" umesto broja 8.' => 'Calculatorul calculeaza fara ghilimele. Cu ghilimele ar afisa textul "5 + 3" in loc de numarul 8.',
            'Promenljive cuvaju vrednosti. Ime se stavlja levo, vrednost desno od znaka =.' => 'Variabilele stocheaza valori. Numele se pune in stanga, valoarea in dreapta semnului =.',
            'Promenljive mozemo koristiti u racunanju. Rezultat mozemo sacuvati u novu promenljivu.' => 'Variabilele le putem folosi in calcule. Rezultatul il putem salva intr-o variabila noua.',
            'f-string pocinje sa f i koristi {} za ubacivanje promenljivih ili racunanja u tekst.' => 'f-string incepe cu f si foloseste {} pentru inserarea variabilelor sau calculelor in text.',
            'Kada pokrenes, pojavice se prozor gde mozes da ukucas svoje ime.' => 'Cand rulezi, va aparea o fereastra unde poti tasta numele tau.',
            'int() pretvara tekst u ceo broj. Bez toga ne mozemo racunati!' => 'int() converteste textul in numar intreg. Fara asta nu putem calcula!',
            'int(input(...)) je skracenica - ucitava tekst i odmah ga pretvara u broj.' => 'int(input(...)) este o prescurtare - citeste textul si il converteste imediat in numar.',
            'Pokreni sa razlicitim brojevima. Poruka o voznji se prikazuje samo ako je godina >= 18.' => 'Ruleaza cu numere diferite. Mesajul despre sofat se afiseaza doar daca varsta >= 18.',
            'Uvek se izvrsava JEDAN od dva bloka - ili if ili else, nikad oba.' => 'Intotdeauna se executa UNUL din doua blocuri - fie if, fie else, niciodata ambele.',
            'and: OBA uslova moraju biti tacna. Ako je jedan netacan, ceo izraz je netacan.' => 'and: AMBELE conditii trebuie sa fie adevarate. Daca una este falsa, intreaga expresie este falsa.',
            'or: Dovoljno je da JEDAN uslov bude tacan.' => 'or: Este suficient ca UNA singura conditie sa fie adevarata.',
            'not obrce True u False i obrnuto.' => 'not inverseaza True in False si invers.',
            'i menja vrednost u svakom krugu: 0, 1, 2, 3, 4. Isprobaj sa range(10)!' => 'i schimba valoarea la fiecare tura: 0, 1, 2, 3, 4. Incearca cu range(10)!',
            'range(1, 11) daje 1,2,...,10. Poslednji broj (11) se ne ukljucuje!' => 'range(1, 11) da 1,2,...,10. Ultimul numar (11) nu este inclus!',
            'range(10, 0, -1) broji od 10 do 1, smanjuje za 1 u svakom koraku.' => 'range(10, 0, -1) numara de la 10 la 1, scade cu 1 la fiecare pas.',
            'Petlja se ponavlja dok je broj > 0. Svaki put smanjujemo broj za 1.' => 'Bucla se repeta cat timp numar > 0. De fiecare data scadem numarul cu 1.',
            'While se ponavlja dok korisnik ne pogodi. Svaki put mu kazemo da li je broj veci ili manji.' => 'While se repeta pana cand utilizatorul ghiceste. De fiecare data ii spunem daca numarul este mai mare sau mai mic.',
            'Ucitavamo brojeve dok korisnik ne unese 0, pa ispisujemo zbir.' => 'Citim numere pana cand utilizatorul introduce 0, apoi afisam suma.',
            'Spoljna petlja (i) ide po redovima, unutrasnja (j) po kolonama.' => 'Bucla exterioara (i) merge pe randuri, interioara (j) pe coloane.',
            '"* " * 3 daje "* * * ". Mnozenje teksta brojem ponavlja tekst!' => '"* " * 3 da "* * * ". Inmultirea textului cu un numar repeta textul!',
            'Spoljna petlja = redovi, unutrasnja = kolone.' => 'Bucla exterioara = randuri, interioara = coloane.',
            'Indeks pocinje od 0! ocene[0] je prvi, ocene[1] drugi...' => 'Indexul incepe de la 0! note[0] este primul, note[1] al doilea...',
            'append() dodaje na kraj, remove() brise prvo pojavljivanje.' => 'append() adauga la sfarsit, remove() sterge prima aparitie.',
            'for ime in imena: uzima svaki element iz liste, jedan po jedan.' => 'for nume in numere_lista: ia fiecare element din lista, unul cate unul.',
            'Mozemo sabirati rucno sa petljom, ili koristiti sum() i len().' => 'Putem aduna manual cu o bucla, sau folosi sum() si len().',
            'Kombinujemo for i if da filtriramo elemente.' => 'Combinam for si if pentru a filtra elementele.',
            'String radi kao lista karaktera. Indeks pocinje od 0.' => 'Stringul functioneaza ca o lista de caractere. Indexul incepe de la 0.',
            'for slovo in rec: prolazi kroz svaki karakter teksta.' => 'for litera in cuvant: parcurge fiecare caracter al textului.',
            'def pravi funkciju. Jednom je napisemo, a mozemo je pozvati koliko god puta zelimo.' => 'def creeaza o functie. O scriem o data si o putem apela de cate ori dorim.',
            'return vraca vrednost. Mozemo je sacuvati u promenljivu ili odmah koristiti u print.' => 'return returneaza o valoare. O putem salva intr-o variabila sau folosi direct in print.',
            'Funkcija vraca True ili False. Koristimo je u if uslovu.' => 'Functia returneaza True sau False. O folosim in conditia if.',
            'pozdrav ima podrazumevanu vrednost "Zdravo". Ako ne prosledimo drugi argument, koristi se podrazumevana.' => 'salut are valoarea implicita "Buna". Daca nu transmitem al doilea argument, se foloseste valoarea implicita.',
            'Funkcije pomazu da organizujemo kod. Svaka radi jednu stvar.' => 'Functiile ajuta sa organizam codul. Fiecare face un singur lucru.',
            'Ucitaj podatke i ispisi ih u lepom formatu.' => 'Citeste datele si afiseaza-le intr-un format frumos.',
            'Ispisi rezultate svih operacija u formatu: a + b = rezultat.' => 'Afiseaza rezultatele tuturor operatiilor in formatul: a + b = rezultat.',
            'Izracunaj godine tako sto od 2026 oduzmes godinu rodjenja.' => 'Calculeaza varsta scazand anul nasterii din 2026.',
            'Koristi % (ostatak) i if/elif/else.' => 'Foloseste % (rest) si if/elif/else.',
            'Dodaj jos dva pitanja o geografiji. Broji tacne odgovore.' => 'Adauga inca doua intrebari de geografie. Numara raspunsurile corecte.',
            'Koristi if/elif da proveris koju operaciju je korisnik izabrao.' => 'Foloseste if/elif pentru a verifica ce operatie a ales utilizatorul.',
            'Koristi for i in range(1, 11).' => 'Foloseste for i in range(1, 11).',
            'Saberi sve brojeve od 1 do n koristeci for petlju.' => 'Aduna toate numerele de la 1 la n folosind bucla for.',
            'Slicno zbiru, ali umesto + koristi *.' => 'Similar sumei, dar in loc de + foloseste *.',
            'Koristi sum(), len(), min(), max().' => 'Foloseste sum(), len(), min(), max().',
            'rec[::-1] obrce string. "ana"[::-1] daje "ana".' => 'cuv[::-1] inverseaza stringul. "ana"[::-1] da "ana".',
            'Pronadji rec sa najvecim len().' => 'Gaseste cuvantul cu cel mai mare len().',
            'Koristi funkciju postavi_pitanje za svako pitanje. Dodaj jos 4 pitanja!' => 'Foloseste functia pune_intrebare pentru fiecare intrebare. Adauga inca 4 intrebari!',
            'Dopuni program: dodaj opciju za brisanje zadatka.' => 'Completeaza programul: adauga optiunea de stergere a sarcinii.',
            'Budi kreativan! Koristi sve sto si naucio.' => 'Fii creativ! Foloseste tot ce ai invatat.',

            // ========== PYTHON COMMENTS ==========
            '# Ovo je komentar - racunar ga ignorise' => '# Acesta este un comentariu - calculatorul il ignora',
            '# Sve posle znaka # je komentar' => '# Tot ce urmeaza dupa semnul # este comentariu',
            '# jednostruki navodnici' => '# ghilimele simple',
            '# dvostruki navodnici' => '# ghilimele duble',
            '# i ovako radi' => '# si asa functioneaza',
            '# prazan red' => '# rand gol',
            '# sabiranje' => '# adunare',
            '# oduzimanje' => '# scadere',
            '# mnozenje' => '# inmultire',
            '# deljenje' => '# impartire',
            '# stepenovanje' => '# ridicare la putere',
            '# Mozemo sacuvati rezultat u novu promenljivu' => '# Putem salva rezultatul intr-o variabila noua',
            '# Moze i racunanje unutar {}' => '# Putem calcula si in interiorul {}',
            '# pretvaramo tekst u ceo broj' => '# convertim textul in numar intreg',
            '# % je operator ostatka pri deljenju' => '# % este operatorul restului impartirii',
            '# Ako je ostatak 0, broj je deljiv sa 2 (paran)' => '# Daca restul este 0, numarul este divizibil cu 2 (par)',
            '# smanjujemo broj' => '# scadem numarul',
            '# Ispisi vizit kartu' => '# Afiseaza cartea de vizita',
            '# Primer ispisa:' => '# Exemplu de afisare:',
            '# Ispisi sva 4 racuna sa rezultatima' => '# Afiseaza toate cele 4 calcule cu rezultate',
            '# Primer: 8 + 3 = 11' => '# Exemplu: 8 + 3 = 11',
            '# Izracunaj godine (trenutna godina je 2026)' => '# Calculeaza varsta (anul curent este 2026)',
            '# Ispisi: Ime, ti imas X godina.' => '# Afiseaza: Nume, tu ai X ani.',
            '# Proveri deljivost sa 3 i sa 5' => '# Verifica divizibilitatea cu 3 si cu 5',
            '# Primer: 15 je deljiv i sa 3 i sa 5' => '# Exemplu: 15 este divizibil si cu 3 si cu 5',
            '# Primer: 9 je deljiv samo sa 3' => '# Exemplu: 9 este divizibil doar cu 3',
            '# Primer: 10 je deljiv samo sa 5' => '# Exemplu: 10 este divizibil doar cu 5',
            '# Primer: 7 nije deljiv ni sa 3 ni sa 5' => '# Exemplu: 7 nu este divizibil nici cu 3 nici cu 5',
            '# Dodaj jos 2 pitanja' => '# Adauga inca 2 intrebari',
            '# Koristi if/elif za svaku operaciju' => '# Foloseste if/elif pentru fiecare operatie',
            '# Pazi na deljenje nulom!' => '# Atentie la impartirea cu zero!',
            '# Ispisi: broj x 1 = ...' => '# Afiseaza: numar x 1 = ...',
            '# Koristi for petlju da saberes 1+2+3+...+n' => '# Foloseste bucla for pentru a aduna 1+2+3+...+n',
            '# Koristi for petlju da pomnozis 1*2*3*...*n' => '# Foloseste bucla for pentru a inmulti 1*2*3*...*n',
            '# Ispisi prosek, min, max' => '# Afiseaza media, min, max',
            '# Rucno racunanje proseka' => '# Calcularea manuala a mediei',
            '# Ili krace:' => '# Sau mai scurt:',
            '# Izdvajamo samo petice' => '# Selectam doar notele de 5',
            '# rec[::-1] obrce string' => '# cuv[::-1] inverseaza stringul',
            '# Proveri da li je rec jednaka obrnutoj' => '# Verifica daca cuvantul este egal cu inversul',
            '# Nadji najduzu rec' => '# Gaseste cel mai lung cuvant',
            '# Koristi len() za duzinu svake reci' => '# Foloseste len() pentru lungimea fiecarui cuvant',
            '# Definisanje funkcije' => '# Definirea functiei',
            '# Pozivanje funkcije' => '# Apelarea functiei',
            '# Koristimo return vrednost' => '# Folosim valoarea returnata',
            '# Testiranje' => '# Testare',
            '# Glavni program' => '# Programul principal',
            '# Dodaj opciju 3 - brisanje' => '# Adauga optiunea 3 - stergere',
            '# Tvoj mini program' => '# Mini programul tau',
            '# Ideje: igra pogadjanja, statistika ocena,' => '# Idei: joc de ghicit, statistica notelor,',
            '# generator sifara, konvertor valuta...' => '# generator de parole, convertor de valute...',
            '# Dodaj jos 4 pitanja...' => '# Adauga inca 4 intrebari...',

            // ========== PYTHON STRINGS ==========
            "'Zdravo svete!'" => "'Salut lume!'",
            "'Ja ucim Python.'" => "'Invat Python.'",
            "'Zdravo!'" => "'Buna!'",
            "'Ja sam Python.'" => "'Eu sunt Python.'",
            "'Ime: Ana'" => "'Nume: Ana'",
            "'Razred: 6'" => "'Clasa: 6'",
            "'Skola: OS Zarko Zrenjanin'" => "'Scoala: OS Zarko Zrenjanin'",
            "'Kako se zoves? '" => "'Cum te cheama? '",
            "f'Zdravo, {ime}!'" => "f'Buna, {nume}!'",
            "f'Zdravo, ja sam {ime}!'" => "f'Buna, eu sunt {nume}!'",
            "f'Imam {godine} godina i idem u {razred}. razred.'" => "f'Am {varsta} ani si sunt in clasa {clasa}.'",
            "f'Sledece godine cu imati {godine + 1} godina.'" => "f'Anul viitor voi avea {varsta + 1} ani.'",
            "'Koliko imas godina? '" => "'Cati ani ai? '",
            "f'Ti imas {godine} godina.'" => "f'Tu ai {varsta} ani.'",
            "f'Za 5 godina ces imati {godine + 5} godina.'" => "f'Peste 5 ani vei avea {varsta + 5} ani.'",
            "'Unesi prvi broj: '" => "'Introdu primul numar: '",
            "'Unesi drugi broj: '" => "'Introdu al doilea numar: '",
            "'Koliko je stepeni napolju? '" => "'Cate grade sunt afara? '",
            "'Toplo je! Obuci kratke rukave.'" => "'E cald! Imbraca-te cu maneci scurte.'",
            "'Hladno je! Obuci jaknu.'" => "'E frig! Imbraca-te cu geaca.'",
            "'Unesi ocenu (1-5): '" => "'Introdu nota (1-5): '",
            "'Odlican!'" => "'Excelent!'",
            "'Vrlo dobar!'" => "'Foarte bine!'",
            "'Dobar.'" => "'Bine.'",
            "'Dovoljan.'" => "'Suficient.'",
            "'Nedovoljan.'" => "'Insuficient.'",
            "'Unesi broj: '" => "'Introdu un numar: '",
            "f'{broj} je paran.'" => "f'{numar} este par.'",
            "f'{broj} je neparan.'" => "f'{numar} este impar.'",
            "'Koliko imas godina? '" => "'Cati ani ai? '",
            "'Koja ti je ocena iz matematike? '" => "'Ce nota ai la matematica? '",
            "'Mozes na takmicenje!'" => "'Poti participa la concurs!'",
            "'Ne ispunjavas oba uslova.'" => "'Nu indeplinesti ambele conditii.'",
            "'Koji je dan? (pon/uto/sre/cet/pet/sub/ned) '" => "'Ce zi este? (lun/mar/mie/joi/vin/sam/dum) '",
            "'sub'" => "'sam'",
            "'ned'" => "'dum'",
            "'Vikend je! Nema skole!'" => "'E weekend! Nu e scoala!'",
            "'Radni dan. Idi u skolu!'" => "'Zi lucratoare. Mergi la scoala!'",
            "'Da li pada kisa? (da/ne) '" => "'Ploua? (da/nu) '",
            "'da'" => "'da'",
            "'Mozemo napolje!'" => "'Putem iesi afara!'",
            "'Ostani unutra.'" => "'Ramai inauntru.'",
            "'Zdravo'" => "'Buna'",
            "'Pogodi broj (1-10): '" => "'Ghiceste numarul (1-10): '",
            "'Previse malo!'" => "'Prea mic!'",
            "'Previse veliko!'" => "'Prea mare!'",
            "'Pokusaj ponovo: '" => "'Incearca din nou: '",
            "'Bravo, pogodio/la si!'" => "'Bravo, ai ghicit!'",
            "'Unesi broj (0 za kraj): '" => "'Introdu un numar (0 pentru sfarsit): '",
            "f'Zbir svih unetih brojeva: {zbir}'" => "f'Suma tuturor numerelor introduse: {suma}'",
            "'Zdravo, {ime}!'" => "'Buna, {nume}!'",
            "'Dobrodosao/la u Python!'" => "'Bine ai venit in Python!'",
            "'Glavni grad Srbije?'" => "'Capitala Serbiei?'",
            "'Beograd'" => "'Belgrad'",
            "'Tacno!'" => "'Corect!'",
            "'Netacno! Odgovor je Beograd.'" => "'Gresit! Raspunsul este Belgrad.'",
            "f'Imas {tacnih} od 3 tacnih odgovora.'" => "f'Ai {corecte} din 3 raspunsuri corecte.'",
            "'Punoletan/na si!'" => "'Esti major/a!'",
            "'Mozes da vozis auto.'" => "'Poti conduce masina.'",
            "'Hvala sto si koristio program.'" => "'Multumim ca ai folosit programul.'",
            "f'Ocena {nova_ocena} dodata.'" => "f'Nota {nota_noua} adaugata.'",
            "'Ocena mora biti izmedju 1 i 5!'" => "'Nota trebuie sa fie intre 1 si 5!'",
            "'Nema ocena.'" => "'Nu sunt note.'",
            "'Nema zadataka.'" => "'Nu sunt sarcini.'",
            "'Novi zadatak: '" => "'Sarcina noua: '",
            "'Dodato!'" => "'Adaugat!'",
            "'Cao!'" => "'Pa!'",
            "'Izbor: '" => "'Alegere: '",
            "'Koliko redova? '" => "'Cate randuri? '",
            "'Koliko kolona? '" => "'Cate coloane? '",
            "'Za koji broj? '" => "'Pentru ce numar? '",
            "'Unesi N: '" => "'Introdu N: '",
            "'Ime: '" => "'Nume: '",
            "'Prezime: '" => "'Prenume: '",
            "'Razred: '" => "'Clasa: '",
            "'Prvi broj: '" => "'Primul numar: '",
            "'Drugi broj: '" => "'Al doilea numar: '",
            "'Koje godine si rodjen/a? '" => "'In ce an te-ai nascut? '",
            "'Operacija (+, -, *, /): '" => "'Operatia (+, -, *, /): '",
            "'Unesi rec: '" => "'Introdu un cuvant: '",
            "'Ana'" => "'Ana'",
            "'Marko'" => "'Marko'",
            "'Jovana'" => "'Jovana'",
            "'Stefan'" => "'Stefan'",
            "Zdravo, " => "Buna, ",
            "Dobrodosao/la" => "Bine ai venit",

            // ========== PYTHON VARIABLE NAMES ==========
            "ime = " => "nume = ",
            "{ime}" => "{nume}",
            "ime)" => "nume)",
            "godine = " => "varsta = ",
            "{godine}" => "{varsta}",
            "godine +" => "varsta +",
            "razred = " => "clasa = ",
            "{razred}" => "{clasa}",
            "ocene = " => "note = ",
            "[ocene" => "[note",
            "ocene)" => "note)",
            "ocene]" => "note]",
            "ocena = " => "nota = ",
            "ocena ==" => "nota ==",
            "{ocena}" => "{nota}",
            "broj = " => "numar = ",
            "{broj}" => "{numar}",
            "broj %" => "numar %",
            "broj >" => "numar >",
            "broj -" => "numar -",
            "broj)" => "numar)",
            "zbir = " => "suma = ",
            "{zbir}" => "{suma}",
            "zbir)" => "suma)",
            "faktorijel = " => "factorial = ",
            "{faktorijel}" => "{factorial}",
            "faktorijel)" => "factorial)",
            "tacnih = " => "corecte = ",
            "tacnih +" => "corecte +",
            "{tacnih}" => "{corecte}",
            "tacan = " => "corect = ",
            "pokusaj = " => "incercare = ",
            "pokusaj !=" => "incercare !=",
            "pokusaj <" => "incercare <",
            "pokusaj)" => "incercare)",
            "nova_ocena" => "nota_noua",
            "moje_ocene" => "notele_mele",
            "rezultat = " => "rezultat = ",
            "samoglasnici" => "vocale",
            "petice = " => "cinci = ",
            "{petice}" => "{cinci}",
            "pozdravi(" => "saluta(",
            "def pozdravi" => "def saluta",
            "postavi_pitanje" => "pune_intrebare",
            "def je_paran" => "def este_par",
            "je_paran(" => "este_par(",
            "prikazi_statistiku" => "afiseaza_statistica",
            "def dodaj_ocenu" => "def adauga_nota",
            "dodaj_ocenu(" => "adauga_nota(",
            "prikazi_meni" => "afiseaza_meniu",
            "prikazi_zadatke" => "afiseaza_sarcini",
            "zadaci = " => "sarcini = ",
            "zadaci)" => "sarcini)",
            "(zadaci" => "(sarcini",
            "zadatak = " => "sarcina = ",
            "zadatak)" => "sarcina)",
            "poeni =" => "puncte =",
            "poeni)" => "puncte)",
            "{poeni}" => "{puncte}",
            "tekst = " => "text = ",
            "temperatura = " => "temperatura = ",
            "imena = " => "numere_lista = ",
            "for ime in imena" => "for num in numere_lista",
            "Zdravo, {ime}" => "Buna, {num}",
            "reci = " => "cuvinte = ",
            "reci)" => "cuvinte)",
            "(reci" => "(cuvinte",

            // ========== REMAINING PRINT FORMATS ==========
            "'Odbrojavanje:'" => "'Numaratoare inversa:'",
            "'START!'" => "'START!'",
            "'Kraj!'" => "'Sfarsit!'",
            "'Kraj petlje.'" => "'Sfarsitul buclei.'",
            "f'{broj} x {i} = {broj * i}'" => "f'{numar} x {i} = {numar * i}'",

            // ========== MENU STRINGS ==========
            "'\\n=== MOJI ZADACI ==='" => "'\\n=== SARCINILE MELE ==='",
            "'1. Prikazi zadatke'" => "'1. Afiseaza sarcinile'",
            "'2. Dodaj zadatak'" => "'2. Adauga sarcina'",
            "'3. Obrisi zadatak'" => "'3. Sterge sarcina'",
            "'4. Izlaz'" => "'4. Iesire'",
        ];

        // Add HTML-encoded variants for strings inside code exercise attributes
        $encoded = [
            // Encoded print strings (&#039; = single quote in HTML attributes)
            "&#039;Zdravo svete!&#039;" => "&#039;Salut lume!&#039;",
            "&#039;Ja ucim Python.&#039;" => "&#039;Invat Python.&#039;",
            "&#039;Zdravo!&#039;" => "&#039;Buna!&#039;",
            "&#039;Ja sam Python.&#039;" => "&#039;Eu sunt Python.&#039;",
            "&#039;Ime: Ana&#039;" => "&#039;Nume: Ana&#039;",
            "&#039;Razred: 6&#039;" => "&#039;Clasa: 6&#039;",
            "&#039;Skola: OS Zarko Zrenjanin&#039;" => "&#039;Scoala: OS Zarko Zrenjanin&#039;",
            "&#039;Kako se zoves? &#039;" => "&#039;Cum te cheama? &#039;",
            "&#039;Koliko imas godina? &#039;" => "&#039;Cati ani ai? &#039;",
            "&#039;Unesi prvi broj: &#039;" => "&#039;Introdu primul numar: &#039;",
            "&#039;Unesi drugi broj: &#039;" => "&#039;Introdu al doilea numar: &#039;",
            "&#039;Koliko je stepeni napolju? &#039;" => "&#039;Cate grade sunt afara? &#039;",
            "&#039;Toplo je! Obuci kratke rukave.&#039;" => "&#039;E cald! Imbraca-te cu maneci scurte.&#039;",
            "&#039;Hladno je! Obuci jaknu.&#039;" => "&#039;E frig! Imbraca-te cu geaca.&#039;",
            "&#039;Unesi ocenu (1-5): &#039;" => "&#039;Introdu nota (1-5): &#039;",
            "&#039;Odlican!&#039;" => "&#039;Excelent!&#039;",
            "&#039;Vrlo dobar!&#039;" => "&#039;Foarte bine!&#039;",
            "&#039;Dobar.&#039;" => "&#039;Bine.&#039;",
            "&#039;Dovoljan.&#039;" => "&#039;Suficient.&#039;",
            "&#039;Nedovoljan.&#039;" => "&#039;Insuficient.&#039;",
            "&#039;Unesi broj: &#039;" => "&#039;Introdu un numar: &#039;",
            "&#039;Koja ti je ocena iz matematike? &#039;" => "&#039;Ce nota ai la matematica? &#039;",
            "&#039;Mozes na takmicenje!&#039;" => "&#039;Poti participa la concurs!&#039;",
            "&#039;Ne ispunjavas oba uslova.&#039;" => "&#039;Nu indeplinesti ambele conditii.&#039;",
            "&#039;Koji je dan? (pon/uto/sre/cet/pet/sub/ned) &#039;" => "&#039;Ce zi este? (lun/mar/mie/joi/vin/sam/dum) &#039;",
            "&#039;Vikend je! Nema skole!&#039;" => "&#039;E weekend! Nu e scoala!&#039;",
            "&#039;Radni dan. Idi u skolu!&#039;" => "&#039;Zi lucratoare. Mergi la scoala!&#039;",
            "&#039;Da li pada kisa? (da/ne) &#039;" => "&#039;Ploua? (da/nu) &#039;",
            "&#039;Mozemo napolje!&#039;" => "&#039;Putem iesi afara!&#039;",
            "&#039;Ostani unutra.&#039;" => "&#039;Ramai inauntru.&#039;",
            "&#039;Punoletan/na si!&#039;" => "&#039;Esti major/a!&#039;",
            "&#039;Mozes da vozis auto.&#039;" => "&#039;Poti conduce masina.&#039;",
            "&#039;Hvala sto si koristio program.&#039;" => "&#039;Multumim ca ai folosit programul.&#039;",
            "&#039;Pogodi broj (1-10): &#039;" => "&#039;Ghiceste numarul (1-10): &#039;",
            "&#039;Previse malo!&#039;" => "&#039;Prea mic!&#039;",
            "&#039;Previse veliko!&#039;" => "&#039;Prea mare!&#039;",
            "&#039;Pokusaj ponovo: &#039;" => "&#039;Incearca din nou: &#039;",
            "&#039;Bravo, pogodio/la si!&#039;" => "&#039;Bravo, ai ghicit!&#039;",
            "&#039;Unesi broj (0 za kraj): &#039;" => "&#039;Introdu un numar (0 pentru sfarsit): &#039;",
            "&#039;Odbrojavanje:&#039;" => "&#039;Numaratoare inversa:&#039;",
            "&#039;Kraj!&#039;" => "&#039;Sfarsit!&#039;",
            "&#039;Zdravo, &#039;" => "&#039;Buna, &#039;",
            "&#039;Zdravo&#039;" => "&#039;Buna&#039;",
            "&#039;Zdravo, ja sam " => "&#039;Buna, eu sunt ",
            "&#039;Dobrodosao/la u Python!&#039;" => "&#039;Bine ai venit in Python!&#039;",
            "&#039;Glavni grad Srbije? &#039;" => "&#039;Capitala Serbiei? &#039;",
            "&#039;Beograd&#039;" => "&#039;Belgrad&#039;",
            "&#039;Tacno!&#039;" => "&#039;Corect!&#039;",
            "&#039;Netacno! Odgovor je Beograd.&#039;" => "&#039;Gresit! Raspunsul este Belgrad.&#039;",
            "&#039;Ocena mora biti izmedju 1 i 5!&#039;" => "&#039;Nota trebuie sa fie intre 1 si 5!&#039;",
            "&#039;Nema ocena.&#039;" => "&#039;Nu sunt note.&#039;",
            "&#039;Nema zadataka.&#039;" => "&#039;Nu sunt sarcini.&#039;",
            "&#039;Novi zadatak: &#039;" => "&#039;Sarcina noua: &#039;",
            "&#039;Dodato!&#039;" => "&#039;Adaugat!&#039;",
            "&#039;Cao!&#039;" => "&#039;Pa!&#039;",
            "&#039;Izbor: &#039;" => "&#039;Alegere: &#039;",
            "&#039;Koliko redova? &#039;" => "&#039;Cate randuri? &#039;",
            "&#039;Koliko kolona? &#039;" => "&#039;Cate coloane? &#039;",
            "&#039;Za koji broj? &#039;" => "&#039;Pentru ce numar? &#039;",
            "&#039;Unesi N: &#039;" => "&#039;Introdu N: &#039;",
            "&#039;Ime: &#039;" => "&#039;Nume: &#039;",
            "&#039;Prezime: &#039;" => "&#039;Prenume: &#039;",
            "&#039;Razred: &#039;" => "&#039;Clasa: &#039;",
            "&#039;Prvi broj: &#039;" => "&#039;Primul numar: &#039;",
            "&#039;Drugi broj: &#039;" => "&#039;Al doilea numar: &#039;",
            "&#039;Koje godine si rodjen/a? &#039;" => "&#039;In ce an te-ai nascut? &#039;",
            "&#039;Operacija (+, -, *, /): &#039;" => "&#039;Operatia (+, -, *, /): &#039;",
            "&#039;Unesi rec: &#039;" => "&#039;Introdu un cuvant: &#039;",
            "&#039;Informatika&#039;" => "&#039;Informatica&#039;",

            // Encoded HTML operators
            "pokusaj &lt;" => "incercare &lt;",
            "godine &gt;=" => "varsta &gt;=",
            "godina &gt;=" => "varsta &gt;=",
            "ocena ==" => "nota ==",
            "broj % 2" => "numar % 2",

            // Variables in encoded contexts
            "Zbir svih unetih brojeva:" => "Suma tuturor numerelor introduse:",
            "Zbir brojeva od 1 do" => "Suma numerelor de la 1 la",
            "Ispisi Zdravo" => "Afiseaza Buna",
            "zadaci.append" => "sarcini.append",
            "len(zadaci)" => "len(sarcini)",
            "enumerate(zadaci" => "enumerate(sarcini",

            // More encoded variants
            'print(&quot;Zdravo!&quot;)' => 'print(&quot;Buna!&quot;)',
            'print(&quot;Ja sam Python.&quot;)' => 'print(&quot;Eu sunt Python.&quot;)',
            "print(godine)" => "print(varsta)",
            "print(razred)" => "print(clasa)",
            "tacnih odgovora" => "raspunsuri corecte",
            "Prosek: {prosek" => "Media: {media",
            "Prosek (krace):" => "Media (prescurtat):",
            'vrednost &quot;Zdravo&quot;' => 'valoarea implicita &quot;Buna&quot;',
            "prosledimo drugi argument" => "transmitem al doilea argument",
            "koristi se podrazumevana" => "se foloseste valoarea implicita",
            "prosek:.2f" => "media:.2f",
            "prosek = zbir" => "media = suma",
            "prosek)" => "media)",

            // Remaining stragglers
            ">Zdravo</td>" => ">Buna</td>",
            "Sledece godine cu imati" => "Anul viitor voi avea",
            "godina." => "ani.",
            "{i}: Zdravo!" => "{i}: Buna!",
            "Kraj petlje." => "Sfarsitul buclei.",
            "Zbir: {suma}" => "Suma: {suma}",
            "Prosek: {sum(note)" => "Media: {sum(note)",
            ". razred." => ".",
            "Zbir:" => "Suma:",
            "Prosek:" => "Media:",
            "Broj oc" => "Numarul de not",
        ];

        $t = array_merge($t, $encoded);

        $keys = array_keys($t);
        $values = array_values($t);
        array_multisort(array_map('strlen', $keys), SORT_DESC, $keys, $values);

        return str_replace($keys, $values, $content);
    }

    public function run(): void
    {
        $chapters = Chapter::where('course_id', $this->dstCourseId)->get();
        foreach ($chapters as $ch) {
            foreach ($ch->subchapters as $sub) { $sub->lessons()->delete(); }
            $ch->subchapters()->delete();
        }
        $chapters->each->delete();

        $srcChapters = Chapter::where('course_id', $this->srcCourseId)->orderBy('order')->get();

        foreach ($srcChapters as $srcCh) {
            $roCh = Chapter::create([
                'course_id' => $this->dstCourseId,
                'title' => $this->chapterTitles[$srcCh->title] ?? $srcCh->title,
                'order' => $srcCh->order,
            ]);

            foreach ($srcCh->subchapters()->orderBy('order')->get() as $srcSub) {
                $roSub = Subchapter::create([
                    'chapter_id' => $roCh->id,
                    'title' => $this->subchapterTitles[$srcSub->title] ?? $srcSub->title,
                    'order' => $srcSub->order,
                ]);

                foreach ($srcSub->lessons()->orderBy('order')->get() as $srcLesson) {
                    Lesson::create([
                        'course_id' => $this->dstCourseId,
                        'subchapter_id' => $roSub->id,
                        'title' => $this->lessonTitles[$srcLesson->title] ?? $srcLesson->title,
                        'content' => $this->translateContent($srcLesson->content),
                        'order' => $srcLesson->order,
                        'is_assignment' => $srcLesson->is_assignment,
                    ]);
                }
            }
        }

        echo "Curs Python de baza in romana creat! 5 capitole, 15 lectii.\n";
    }
}
