<?php

namespace Database\Seeders;

use App\Models\Chapter;
use App\Models\Course;
use App\Models\Lesson;
use App\Models\Subchapter;
use Illuminate\Database\Seeder;

class PythonCourseSeeder extends Seeder
{
    public function run(): void
    {
        $course = Course::create([
            'school_id' => 3,
            'name' => 'Osnove programiranja u Python-u',
            'description' => 'Kurs za potpune pocetnike. Naucicete da programirate od nule — korak po korak, sa mnogo primera i vezbi.',
        ]);

        // Chapter 1
        $ch1 = Chapter::create(['course_id' => $course->id, 'title' => 'Uvod u programiranje', 'order' => 1]);
        $sc1_1 = Subchapter::create(['chapter_id' => $ch1->id, 'title' => 'Sta je programiranje?', 'order' => 1]);
        $sc1_2 = Subchapter::create(['chapter_id' => $ch1->id, 'title' => 'Tvoj prvi program', 'order' => 2]);

        // Chapter 2
        $ch2 = Chapter::create(['course_id' => $course->id, 'title' => 'Promenljive i tipovi podataka', 'order' => 2]);
        $sc2_1 = Subchapter::create(['chapter_id' => $ch2->id, 'title' => 'Sta su promenljive?', 'order' => 1]);
        $sc2_2 = Subchapter::create(['chapter_id' => $ch2->id, 'title' => 'Tipovi podataka', 'order' => 2]);
        $sc2_3 = Subchapter::create(['chapter_id' => $ch2->id, 'title' => 'Unos podataka - input()', 'order' => 3]);

        // Chapter 3
        $ch3 = Chapter::create(['course_id' => $course->id, 'title' => 'Racunanje i operatori', 'order' => 3]);
        $sc3_1 = Subchapter::create(['chapter_id' => $ch3->id, 'title' => 'Matematicki operatori', 'order' => 1]);
        $sc3_2 = Subchapter::create(['chapter_id' => $ch3->id, 'title' => 'Rad sa tekstom', 'order' => 2]);

        // Chapter 4
        $ch4 = Chapter::create(['course_id' => $course->id, 'title' => 'Odlucivanje — if/else', 'order' => 4]);
        $sc4_1 = Subchapter::create(['chapter_id' => $ch4->id, 'title' => 'Uslovi i poredjenje', 'order' => 1]);
        $sc4_2 = Subchapter::create(['chapter_id' => $ch4->id, 'title' => 'if, elif i else', 'order' => 2]);

        // Chapter 5
        $ch5 = Chapter::create(['course_id' => $course->id, 'title' => 'Ponavljanje — petlje', 'order' => 5]);
        $sc5_1 = Subchapter::create(['chapter_id' => $ch5->id, 'title' => 'for petlja', 'order' => 1]);
        $sc5_2 = Subchapter::create(['chapter_id' => $ch5->id, 'title' => 'while petlja', 'order' => 2]);

        $this->lesson($course, $sc1_1, 'Sta je programiranje?', 1, $this->lesson1_1());
        $this->lesson($course, $sc1_2, 'Tvoj prvi pravi program', 1, $this->lesson1_2());
        $this->lesson($course, $sc2_1, 'Sta su promenljive?', 1, $this->lesson2_1());
        $this->lesson($course, $sc2_2, 'Tipovi podataka — brojevi i tekst', 1, $this->lesson2_2());
        $this->lesson($course, $sc2_3, 'Razgovor sa kompjuterom — input()', 1, $this->lesson2_3());
        $this->lesson($course, $sc3_1, 'Python kao kalkulator', 1, $this->lesson3_1());
        $this->lesson($course, $sc3_2, 'Igranje sa tekstom', 1, $this->lesson3_2());
        $this->lesson($course, $sc4_1, 'Da ili ne? — uslovi', 1, $this->lesson4_1());
        $this->lesson($course, $sc4_2, 'Vise izbora — elif', 1, $this->lesson4_2());
        $this->lesson($course, $sc5_1, 'Ponavljanje — for petlja', 1, $this->lesson5_1());
        $this->lesson($course, $sc5_2, 'Ponavljaj dok... — while petlja', 1, $this->lesson5_2());
    }

    private function lesson($course, $subchapter, $title, $order, $content): void
    {
        Lesson::create([
            'course_id' => $course->id,
            'subchapter_id' => $subchapter->id,
            'title' => $title,
            'order' => $order,
            'content' => $content,
        ]);
    }

    private function lesson1_1(): string { return '<h1>Sta je programiranje?</h1><p>Zamisli da imas robota koji radi SVE sto mu kazes — ali samo ako mu objasnis tacno kako. Ne mozes mu reci "napravi dorucak" jer on ne zna sta je dorucak. Moras mu reci:</p><ol><li>Otvori frizider</li><li>Uzmi jaja</li><li>Zatvori frizider</li><li>Ukljuci ringlu</li><li>Stavi tiganj na ringlu</li><li>Razbij jaje u tiganj</li></ol><p>E, to je programiranje! <strong>Ti si sef, a kompjuter je robot koji slusa tvoje komande.</strong> Ali moras da mu kazes TACNO sta da radi, korak po korak.</p><h2>Zasto Python?</h2><p>Postoji mnogo programskih jezika. Mi cemo uciti <strong>Python</strong> jer:</p><ul><li>Najlaksi je za pocetnike — cita se skoro kao engleski</li><li>Koriste ga profesionalci u celom svetu (Google, Instagram, NASA...)</li><li>Moze se nauciti brzo uz puno zabave</li></ul><h2>Kako izgleda Python program?</h2><p>Evo najjednostavnijeg programa na svetu. Klikni <strong>Run</strong> da ga pokrenes:</p><div data-code-exercise="" startercode="print(\'Zdravo, svete!\')" instructions="Klikni Run i vidi sta se desava. Ovo je tvoj prvi program!"></div><p><code>print()</code> je komanda koja kaze kompjuteru: <strong>"Ispisi ovo na ekranu"</strong>. Tekst stavljamo izmedju navodnika.</p><h2>Probaj sam</h2><p>Promeni tekst izmedju navodnika da kompjuter ispise tvoje ime:</p><div data-code-exercise="" startercode="print(\'ovde napisi svoje ime\')" instructions="Zameni tekst izmedju navodnika svojim imenom. Ne zaboravi navodnike!"></div>'; }

    private function lesson1_2(): string { return '<h1>Tvoj prvi pravi program</h1><p>Sada znamo da <code>print()</code> ispisuje tekst. Ali pravi programi imaju VISE linija — kao recept koji ima vise koraka.</p><h2>Vise linija</h2><p>Kompjuter cita program ODOZGO NA DOLE, jednu liniju po jednu:</p><div data-code-exercise="" startercode="print(\'Zdravo!\')&#10;print(\'Ja sam kompjuter.\')&#10;print(\'Ucim da programiram u Python-u.\')&#10;print(\'Ovo je moj prvi program sa vise linija!\')" instructions="Pokreni i pogledaj redosled. Svaki print() ispisuje novi red."></div><h2>Prazne linije</h2><p>Mozes dodati prazan red koristeci <code>print()</code> bez teksta:</p><div data-code-exercise="" startercode="print(\'=== MOJ PROFIL ===\')&#10;print()&#10;print(\'Ime: Ana\')&#10;print(\'Razred: 6-1\')&#10;print(\'Hobi: programiranje\')&#10;print()&#10;print(\'==================\')" instructions="Pogledaj kako print() bez teksta pravi prazan red. Promeni podatke da budu tvoji!"></div><h2>Tvoj red: Licna karta</h2><p>Napravi program koji ispisuje tvoju "licnu kartu":</p><div data-code-exercise="" startercode="# Napravi svoju licnu kartu!&#10;print(\'Ime: ...\')&#10;print(\'Prezime: ...\')&#10;# Dodaj jos redova..." instructions="Napravi program koji ispisuje tvoje podatke."></div><h2>Greske — i to je OK!</h2><p>Sta se desi ako zaboravis navodnike?</p><div data-code-exercise="" startercode="print(Zdravo)" instructions="Pokreni ovaj program sa greskom. Procitaj poruku — sta kaze?"></div><p>Crvena poruka je <strong>greska</strong> (error). Greske su normalne! Vazno je da naucis da ih citas.</p><p><strong>Zapamti:</strong> Tekst se UVEK stavlja izmedju navodnika: <code>\'tekst\'</code> ili <code>"tekst"</code></p>'; }

    private function lesson2_1(): string { return '<h1>Sta su promenljive?</h1><p>Zamisli kutije u koje stavljas stvari. Na svaku kutiju napises ime da znas sta je unutra:</p><ul><li>Kutija <strong>ime</strong> — unutra pise "Ana"</li><li>Kutija <strong>godine</strong> — unutra je broj 12</li><li>Kutija <strong>razred</strong> — unutra pise "6-1"</li></ul><p>U programiranju, te kutije se zovu <strong>promenljive</strong>. Promenljiva ima IME i VREDNOST.</p><div data-code-exercise="" startercode="# Pravimo tri kutije (promenljive)&#10;ime = \'Ana\'&#10;godine = 12&#10;razred = \'6-1\'&#10;&#10;print(\'Ime:\', ime)&#10;print(\'Godine:\', godine)&#10;print(\'Razred:\', razred)" instructions="Pokreni program. Promeni vrednosti da budu tvoji podaci."></div><h2>Zasto se zovu PROMENLJIVE?</h2><p>Zato sto im mozes promeniti vrednost!</p><div data-code-exercise="" startercode="bodovi = 0&#10;print(\'Na pocetku imam\', bodovi, \'bodova\')&#10;&#10;bodovi = 10&#10;print(\'Posle prvog zadatka imam\', bodovi, \'bodova\')&#10;&#10;bodovi = 25&#10;print(\'Posle drugog zadatka imam\', bodovi, \'bodova\')" instructions="Pogledaj kako se vrednost menja u toku programa."></div><h2>Pravila za imena</h2><ul><li>Koriste se mala slova: <code>ime</code>, <code>godine</code></li><li>Vise reci spajamo donjom crtom: <code>omiljeni_predmet</code></li><li>Ne sme da pocne brojem: <code>1razred</code> ne radi</li><li>Nema razmaka: <code>moje ime</code> ne radi</li></ul><h2>Tvoj red</h2><div data-code-exercise="" startercode="# Popuni podatke o najboljem drugu/drugarici&#10;ime_druga = \'...\'&#10;godine_druga = 0&#10;omiljeni_sport = \'...\'&#10;omiljena_boja = \'...\'&#10;&#10;print(\'Moj najbolji drug:\')&#10;print(\'Ime:\', ime_druga)&#10;# Dodaj ispis za ostale" instructions="Popuni vrednosti i dodaj print() za svaku promenljivu."></div>'; }

    private function lesson2_2(): string { return '<h1>Tipovi podataka — brojevi i tekst</h1><p>Python razlikuje tri osnovna tipa:</p><table><tr><th>Tip</th><th>Sta je?</th><th>Primer</th></tr><tr><td><strong>int</strong></td><td>Ceo broj</td><td>5, 100, -3</td></tr><tr><td><strong>float</strong></td><td>Decimalni broj</td><td>3.14, 2.5</td></tr><tr><td><strong>str</strong></td><td>Tekst (string)</td><td>\'zdravo\', "Ana"</td></tr></table><h2>Kako znamo koji je tip?</h2><div data-code-exercise="" startercode="a = 5&#10;b = 3.14&#10;c = \'zdravo\'&#10;&#10;print(a, \'— tip:\', type(a))&#10;print(b, \'— tip:\', type(b))&#10;print(c, \'— tip:\', type(c))&#10;&#10;# PAZNJA: broj u navodnicima je TEKST!&#10;d = \'100\'&#10;print(d, \'— tip:\', type(d))" instructions="Pokreni i pogledaj tipove. \'100\' je tekst, ne broj!"></div><h2>Vazno: broj u navodnicima NIJE broj!</h2><div data-code-exercise="" startercode="broj = 100&#10;tekst = \'100\'&#10;&#10;print(broj + broj)   # 200 — racunanje&#10;print(tekst + tekst) # \'100100\' — spajanje teksta!" instructions="Vidi razliku! Brojevi se sabiraju, tekst se spaja!"></div><h2>Pretvaranje tipova</h2><ul><li><code>int(\'42\')</code> — tekst u ceo broj</li><li><code>float(\'3.14\')</code> — tekst u decimalni broj</li><li><code>str(42)</code> — broj u tekst</li></ul><div data-code-exercise="" startercode="tekst = \'25\'&#10;broj = int(tekst)&#10;print(broj + 10)  # 35&#10;&#10;godine = 12&#10;poruka = \'Imam \' + str(godine) + \' godina\'&#10;print(poruka)" instructions="Pogledaj kako pretvaranje radi."></div>'; }

    private function lesson2_3(): string { return '<h1>Razgovor sa kompjuterom — input()</h1><p>Do sada smo mi pisali sve podatke. Ali sta ako zelimo da KORISNIK unese nesto?</p><div data-code-exercise="" startercode="ime = input(\'Kako se zoves? \')&#10;print(\'Zdravo, \' + ime + \'! Drago mi je!\')" instructions="Pokreni, ukucaj svoje ime i pritisni OK."></div><p><code>input()</code> pauzira program i ceka da korisnik nesto ukuca.</p><h2>Paznja: input() uvek vraca TEKST</h2><p>Cak i kad ukucas broj, input() ga cuva kao tekst! Zato moramo da pretvorimo:</p><div data-code-exercise="" startercode="# OVAKO JE ISPRAVNO:&#10;godine = int(input(\'Koliko imas godina? \'))&#10;print(\'Ti imas\', godine, \'godina.\')&#10;print(\'Sledece godine ces imati\', godine + 1, \'godina!\')" instructions="int(input(...)) pretvara unos u broj!"></div><h2>Recept za unos</h2><ul><li>Tekst: <code>ime = input(\'Unesi ime: \')</code></li><li>Ceo broj: <code>broj = int(input(\'Unesi broj: \'))</code></li><li>Decimalni: <code>broj = float(input(\'Unesi broj: \'))</code></li></ul><h2>Tvoj red: Anketa</h2><div data-code-exercise="" startercode="print(\'=== ANKETA ===\')&#10;print()&#10;ime = input(\'Kako se zoves? \')&#10;# Dodaj pitanja:&#10;# - Koliko imas godina? (int)&#10;# - Omiljeni predmet?&#10;# - Omiljeni film?&#10;# - Omiljena hrana?&#10;print()&#10;print(\'=== REZULTATI ===\')&#10;print(\'Ime:\', ime)&#10;# Ispisi ostale" instructions="Dovrsi anketu — dodaj pitanja i ispisi sve odgovore."></div>'; }

    private function lesson3_1(): string { return '<h1>Python kao kalkulator</h1><p>Python moze da racuna umesto tebe!</p><table><tr><th>Operator</th><th>Znacenje</th><th>Primer</th><th>Rezultat</th></tr><tr><td><code>+</code></td><td>Sabiranje</td><td>5 + 3</td><td>8</td></tr><tr><td><code>-</code></td><td>Oduzimanje</td><td>10 - 4</td><td>6</td></tr><tr><td><code>*</code></td><td>Mnozenje</td><td>6 * 7</td><td>42</td></tr><tr><td><code>/</code></td><td>Deljenje</td><td>15 / 4</td><td>3.75</td></tr><tr><td><code>//</code></td><td>Celobrojno deljenje</td><td>15 // 4</td><td>3</td></tr><tr><td><code>%</code></td><td>Ostatak</td><td>15 % 4</td><td>3</td></tr><tr><td><code>**</code></td><td>Stepenovanje</td><td>2 ** 3</td><td>8</td></tr></table><div data-code-exercise="" startercode="print(\'5 + 3 =\', 5 + 3)&#10;print(\'10 - 4 =\', 10 - 4)&#10;print(\'6 * 7 =\', 6 * 7)&#10;print(\'15 / 4 =\', 15 / 4)&#10;print(\'15 // 4 =\', 15 // 4)&#10;print(\'15 % 4 =\', 15 % 4)&#10;print(\'2 ** 3 =\', 2 ** 3)" instructions="Pokreni i uporedi rezultate sa tabelom."></div><h2>Kalkulator sa unosom</h2><div data-code-exercise="" startercode="a = float(input(\'Unesi prvi broj: \'))&#10;b = float(input(\'Unesi drugi broj: \'))&#10;print()&#10;print(a, \'+\', b, \'=\', a + b)&#10;print(a, \'-\', b, \'=\', a - b)&#10;print(a, \'*\', b, \'=\', a * b)&#10;print(a, \'/\', b, \'=\', a / b)" instructions="Unesi dva broja i vidi sve operacije!"></div><h2>Tvoj red: Povrsina pravougaonika</h2><div data-code-exercise="" startercode="a = float(input(\'Unesi stranicu a: \'))&#10;b = float(input(\'Unesi stranicu b: \'))&#10;&#10;# Izracunaj:&#10;# povrsina = a * b&#10;# obim = 2 * a + 2 * b&#10;# Ispisi rezultate" instructions="Izracunaj i ispisi povrsinu i obim pravougaonika."></div>'; }

    private function lesson3_2(): string { return '<h1>Igranje sa tekstom</h1><h2>Spajanje teksta</h2><div data-code-exercise="" startercode="ime = \'Ana\'&#10;prezime = \'Petrovic\'&#10;&#10;puno_ime = ime + \' \' + prezime&#10;print(puno_ime)&#10;&#10;# f-string — najlaksi nacin&#10;godine = 12&#10;print(f\'Zovem se {ime} {prezime} i imam {godine} godina.\')" instructions="Pokreni i vidi dva nacina za spajanje teksta. f-string je najlaksi!"></div><h2>Sta sve mozes sa tekstom?</h2><div data-code-exercise="" startercode="rec = \'programiranje\'&#10;&#10;print(\'Veliko:\', rec.upper())&#10;print(\'Malo:\', rec.lower())&#10;print(\'Duzina:\', len(rec), \'slova\')&#10;print(\'Prvo slovo:\', rec[0])&#10;print(\'Poslednje slovo:\', rec[-1])&#10;print(\'Prva 3 slova:\', rec[0:3])&#10;print(\'ha\' * 5)&#10;print(\'-\' * 30)" instructions="Isprobaj sve operacije sa tekstom!"></div><h2>Tvoj red: Generator nadimaka</h2><div data-code-exercise="" startercode="ime = input(\'Unesi svoje ime: \')&#10;&#10;# Ispisi:&#10;# - Ime velikim slovima&#10;# - Ime malim slovima&#10;# - Koliko slova ima (len)&#10;# - Prva 3 slova&#10;# - Ime ponovljeno 3 puta&#10;# - Ime naopako (hint: ime[::-1])" instructions="Dovrsi program. Hint za naopako: ime[::-1]"></div>'; }

    private function lesson4_1(): string { return '<h1>Da ili ne? — uslovi</h1><p>Kompjuter odgovara sa DA (True) ili NE (False):</p><table><tr><th>Znak</th><th>Znacenje</th><th>Primer</th><th>Rezultat</th></tr><tr><td><code>==</code></td><td>Jednako?</td><td>5 == 5</td><td>True</td></tr><tr><td><code>!=</code></td><td>Razlicito?</td><td>5 != 3</td><td>True</td></tr><tr><td><code>&gt;</code></td><td>Vece?</td><td>10 > 3</td><td>True</td></tr><tr><td><code>&lt;</code></td><td>Manje?</td><td>2 < 1</td><td>False</td></tr><tr><td><code>&gt;=</code></td><td>Vece ili jednako?</td><td>5 >= 5</td><td>True</td></tr><tr><td><code>&lt;=</code></td><td>Manje ili jednako?</td><td>3 <= 2</td><td>False</td></tr></table><div data-code-exercise="" startercode="print(\'5 == 5:\', 5 == 5)&#10;print(\'5 == 3:\', 5 == 3)&#10;print(\'10 > 3:\', 10 > 3)&#10;print(\'2 < 1:\', 2 < 1)&#10;&#10;uzrast = 12&#10;print(\'Vise od 10?\', uzrast > 10)&#10;print(\'Tacno 15?\', uzrast == 15)" instructions="Pokreni i pogledaj True/False odgovore."></div><h2>if — kompjuter odlucuje</h2><div data-code-exercise="" startercode="uzrast = int(input(\'Koliko imas godina? \'))&#10;&#10;if uzrast >= 18:&#10;    print(\'Mozes da vozis auto!\')&#10;&#10;if uzrast < 18:&#10;    print(\'Jos ne mozes da vozis, sacekaj jos\', 18 - uzrast, \'godina.\')" instructions="Unesi razlicite godine i vidi sta se ispisuje."></div><h2>if + else</h2><div data-code-exercise="" startercode="lozinka = input(\'Unesi lozinku: \')&#10;&#10;if lozinka == \'python123\':&#10;    print(\'Tacna lozinka! Dobrodosao!\')&#10;else:&#10;    print(\'Pogresna lozinka! Pokusaj ponovo.\')" instructions="Unesi \'python123\' pa probaj nesto drugo."></div>'; }

    private function lesson4_2(): string { return '<h1>Vise izbora — elif</h1><p>Sta kad imamo VISE od dva izbora? Ocena nije samo "prosao" ili "pao"!</p><div data-code-exercise="" startercode="bodovi = int(input(\'Koliko bodova na testu? (0-100) \'))&#10;&#10;if bodovi >= 90:&#10;    print(\'Ocena: 5 — Odlican!\')&#10;elif bodovi >= 75:&#10;    print(\'Ocena: 4 — Vrlo dobar\')&#10;elif bodovi >= 60:&#10;    print(\'Ocena: 3 — Dobar\')&#10;elif bodovi >= 50:&#10;    print(\'Ocena: 2 — Dovoljan\')&#10;else:&#10;    print(\'Ocena: 1 — Nedovoljan\')" instructions="Unesi razlicite bodove: 95, 80, 65, 55, 30"></div><h2>Tvoj red: Vremenski savetnik</h2><div data-code-exercise="" startercode="temp = int(input(\'Koliko je stepeni napolju? \'))&#10;&#10;# Ispod 0: \'Jako hladno! Ostani unutra.\'&#10;# 0-10: \'Hladno, obucni jaknu i sal.\'&#10;# 11-20: \'Prijatno, lagana jakna.\'&#10;# 21-30: \'Lepo vreme, uzivaj!\'&#10;# Preko 30: \'Vrucina! Pij puno vode.\'" instructions="Dovrsi sa if/elif/else. Testiraj: -5, 5, 15, 25, 35"></div><h2>Tvoj red: Kalkulator sa menijem</h2><div data-code-exercise="" startercode="print(\'=== KALKULATOR ===\')&#10;print(\'1. Sabiranje\')&#10;print(\'2. Oduzimanje\')&#10;print(\'3. Mnozenje\')&#10;print(\'4. Deljenje\')&#10;print()&#10;izbor = input(\'Izaberi operaciju (1-4): \')&#10;a = float(input(\'Prvi broj: \'))&#10;b = float(input(\'Drugi broj: \'))&#10;&#10;# Koristi if/elif/else za racunanje" instructions="Napravi kalkulator sa 4 operacije!"></div>'; }

    private function lesson5_1(): string { return '<h1>Ponavljanje — for petlja</h1><p>Sta ako zelimo da ispisemo "Zdravo" 10 puta? Umesto 10 linija, koristimo <strong>petlju</strong>!</p><div data-code-exercise="" startercode="for i in range(5):&#10;    print(\'Zdravo! Ovo je ponavljanje broj\', i + 1)" instructions="Pokreni i vidi ponavljanje. Promeni 5 u 10."></div><h2>Sta je range()?</h2><ul><li><code>range(5)</code> — brojevi 0, 1, 2, 3, 4</li><li><code>range(1, 6)</code> — brojevi 1, 2, 3, 4, 5</li><li><code>range(0, 11, 2)</code> — parni: 0, 2, 4, 6, 8, 10</li></ul><div data-code-exercise="" startercode="print(\'range(5):\')&#10;for i in range(5):&#10;    print(i, end=\' \')&#10;print()&#10;print()&#10;print(\'range(1, 6):\')&#10;for i in range(1, 6):&#10;    print(i, end=\' \')&#10;print()&#10;print()&#10;print(\'Parni do 10:\')&#10;for i in range(0, 11, 2):&#10;    print(i, end=\' \')" instructions="Pogledaj razlicite nacine koristenja range()."></div><h2>Tablica mnozenja</h2><div data-code-exercise="" startercode="broj = 7&#10;print(f\'Tablica mnozenja za {broj}:\')&#10;print()&#10;for i in range(1, 11):&#10;    print(f\'{broj} x {i} = {broj * i}\')" instructions="Pokreni tablicu. Promeni 7 u neki drugi broj."></div><h2>Tvoj red: Zbir brojeva</h2><div data-code-exercise="" startercode="koliko = int(input(\'Koliko brojeva unosis? \'))&#10;zbir = 0&#10;&#10;for i in range(koliko):&#10;    # Pitaj za broj i dodaj u zbir&#10;    pass  # zameni ovu liniju&#10;&#10;print(\'Zbir je:\', zbir)" instructions="Zameni \'pass\'. Hint: broj = int(input(...)) pa zbir = zbir + broj"></div>'; }

    private function lesson5_2(): string { return '<h1>Ponavljaj dok... — while petlja</h1><p><code>for</code> ponavlja tacno odredjen broj puta. Ali sta ako ne znamo koliko? Primer: "Pitaj za lozinku SVE DOK ne pogodi."</p><div data-code-exercise="" startercode="tajna = \'python\'&#10;&#10;odgovor = input(\'Unesi lozinku: \')&#10;&#10;while odgovor != tajna:&#10;    print(\'Pogresno! Pokusaj ponovo.\')&#10;    odgovor = input(\'Unesi lozinku: \')&#10;&#10;print(\'Bravo! Pogodio si!\')" instructions="Pokusaj da pogodis. Hint: tajna je \'python\'"></div><h2>Odbrojavanje</h2><div data-code-exercise="" startercode="broj = 10&#10;&#10;while broj > 0:&#10;    print(broj, \'...\')&#10;    broj = broj - 1&#10;&#10;print(\'START!\')" instructions="Pogledaj odbrojavanje. Promeni 10 u 5."></div><h2>Tvoj red: Igra pogadjanja</h2><p>Kompjuter "zamisli" broj od 1 do 20, a ti pogadjaj. Posle svakog pokusaja kaze "Veci" ili "Manji".</p><div data-code-exercise="" startercode="tajna_broj = 14&#10;pokusaji = 0&#10;&#10;print(\'Zamislio sam broj od 1 do 20!\')&#10;&#10;# Napravi while petlju:&#10;# 1. Pitaj za broj&#10;# 2. Broji pokusaje&#10;# 3. Ako prevelik: \'Manji!\'&#10;# 4. Ako premali: \'Veci!\'&#10;# 5. Ako pogodi: \'Bravo!\'" instructions="Dovrsi igru. Koristi while, input(), if/elif/else."></div><h2>Sta smo naucili u ovom kursu?</h2><ul><li><strong>print()</strong> — ispisuje na ekran</li><li><strong>Promenljive</strong> — kutije za podatke (int, float, str)</li><li><strong>input()</strong> — unos od korisnika</li><li><strong>Operatori</strong> — racunanje (+, -, *, /, //, %, **)</li><li><strong>if/elif/else</strong> — odlucivanje</li><li><strong>for petlja</strong> — ponavljanje odredjen broj puta</li><li><strong>while petlja</strong> — ponavljanje dok je uslov tacan</li></ul><p><strong>Svaka cast sto si stigao do kraja! Sada znas osnove programiranja!</strong></p>'; }
}
