<?php

namespace Database\Seeders;

use App\Models\Chapter;
use App\Models\Course;
use App\Models\Lesson;
use App\Models\Subchapter;
use Illuminate\Database\Seeder;

class PythonCourseRoSeeder extends Seeder
{
    public function run(): void
    {
        $course = Course::create([
            'school_id' => 3,
            'name' => 'Bazele programării în Python',
            'description' => 'Curs pentru începători absolut. Veți învăța să programați de la zero — pas cu pas, cu multe exemple și exerciții.',
        ]);

        $ch1 = Chapter::create(['course_id' => $course->id, 'title' => 'Introducere în programare', 'order' => 1]);
        $sc1_1 = Subchapter::create(['chapter_id' => $ch1->id, 'title' => 'Ce este programarea?', 'order' => 1]);
        $sc1_2 = Subchapter::create(['chapter_id' => $ch1->id, 'title' => 'Primul tău program', 'order' => 2]);

        $ch2 = Chapter::create(['course_id' => $course->id, 'title' => 'Variabile și tipuri de date', 'order' => 2]);
        $sc2_1 = Subchapter::create(['chapter_id' => $ch2->id, 'title' => 'Ce sunt variabilele?', 'order' => 1]);
        $sc2_2 = Subchapter::create(['chapter_id' => $ch2->id, 'title' => 'Tipuri de date', 'order' => 2]);
        $sc2_3 = Subchapter::create(['chapter_id' => $ch2->id, 'title' => 'Citirea datelor - input()', 'order' => 3]);

        $ch3 = Chapter::create(['course_id' => $course->id, 'title' => 'Calcule și operatori', 'order' => 3]);
        $sc3_1 = Subchapter::create(['chapter_id' => $ch3->id, 'title' => 'Operatori matematici', 'order' => 1]);
        $sc3_2 = Subchapter::create(['chapter_id' => $ch3->id, 'title' => 'Lucrul cu text', 'order' => 2]);

        $ch4 = Chapter::create(['course_id' => $course->id, 'title' => 'Luarea deciziilor — if/else', 'order' => 4]);
        $sc4_1 = Subchapter::create(['chapter_id' => $ch4->id, 'title' => 'Condiții și comparații', 'order' => 1]);
        $sc4_2 = Subchapter::create(['chapter_id' => $ch4->id, 'title' => 'if, elif și else', 'order' => 2]);

        $ch5 = Chapter::create(['course_id' => $course->id, 'title' => 'Repetare — bucle', 'order' => 5]);
        $sc5_1 = Subchapter::create(['chapter_id' => $ch5->id, 'title' => 'Bucla for', 'order' => 1]);
        $sc5_2 = Subchapter::create(['chapter_id' => $ch5->id, 'title' => 'Bucla while', 'order' => 2]);

        $this->lesson($course, $sc1_1, 'Ce este programarea?', 1, $this->lesson1_1());
        $this->lesson($course, $sc1_2, 'Primul tău program adevărat', 1, $this->lesson1_2());
        $this->lesson($course, $sc2_1, 'Ce sunt variabilele?', 1, $this->lesson2_1());
        $this->lesson($course, $sc2_2, 'Tipuri de date — numere și text', 1, $this->lesson2_2());
        $this->lesson($course, $sc2_3, 'Discuție cu calculatorul — input()', 1, $this->lesson2_3());
        $this->lesson($course, $sc3_1, 'Python ca un calculator', 1, $this->lesson3_1());
        $this->lesson($course, $sc3_2, 'Jocuri cu textul', 1, $this->lesson3_2());
        $this->lesson($course, $sc4_1, 'Da sau nu? — condiții', 1, $this->lesson4_1());
        $this->lesson($course, $sc4_2, 'Mai multe opțiuni — elif', 1, $this->lesson4_2());
        $this->lesson($course, $sc5_1, 'Repetare — bucla for', 1, $this->lesson5_1());
        $this->lesson($course, $sc5_2, 'Repetă cât timp... — bucla while', 1, $this->lesson5_2());
    }

    private function lesson($course, $subchapter, $title, $order, $content): void
    {
        Lesson::create([
            'course_id' => $course->id,
            'subchapter_id' => $subchapter->id,
            'title' => $title,
            'order' => $order,
            'content' => $content,
        ]);
    }

    private function lesson1_1(): string { return '<h1>Ce este programarea?</h1><p>Imaginează-ți că ai un robot care face TOT ce-i spui — dar doar dacă îi explici exact cum. Nu poți să-i spui "fă micul dejun" pentru că el nu știe ce înseamnă. Trebuie să-i spui:</p><ol><li>Deschide frigiderul</li><li>Ia ouăle</li><li>Închide frigiderul</li><li>Aprinde aragazul</li><li>Pune tigaia pe aragaz</li><li>Sparge oul în tigaie</li></ol><p>Asta este programarea! <strong>Tu ești șeful, iar calculatorul este robotul care ascultă comenzile tale.</strong> Dar trebuie să-i spui EXACT ce să facă, pas cu pas.</p><h2>De ce Python?</h2><p>Există multe limbaje de programare. Noi vom învăța <strong>Python</strong> pentru că:</p><ul><li>Este cel mai ușor pentru începători — se citește aproape ca engleza</li><li>Îl folosesc profesioniștii din toată lumea (Google, Instagram, NASA...)</li><li>Se poate învăța rapid și cu multă distracție</li></ul><h2>Cum arată un program Python?</h2><p>Iată cel mai simplu program din lume. Apasă <strong>Run</strong> pentru a-l rula:</p><div data-code-exercise="" startercode="print(\'Salut, lume!\')" instructions="Apasă Run și vezi ce se întâmplă. Acesta este primul tău program!"></div><p><code>print()</code> este comanda care spune calculatorului: <strong>"Afișează asta pe ecran"</strong>. Textul pe care vrem să-l afișăm îl punem între ghilimele.</p><h2>Încearcă singur</h2><p>Schimbă textul dintre ghilimele pentru ca calculatorul să afișeze numele tău:</p><div data-code-exercise="" startercode="print(\'scrie aici numele tău\')" instructions="Înlocuiește textul dintre ghilimele cu numele tău. Nu uita ghilimelele!"></div>'; }

    private function lesson1_2(): string { return '<h1>Primul tău program adevărat</h1><p>Acum știm că <code>print()</code> afișează text. Dar programele adevărate au MAI MULTE linii — ca o rețetă de gătit cu mai mulți pași.</p><h2>Mai multe linii</h2><p>Calculatorul citește programul DE SUS ÎN JOS, o linie pe rând:</p><div data-code-exercise="" startercode="print(\'Salut!\')&#10;print(\'Eu sunt un calculator.\')&#10;print(\'Învăț să programez în Python.\')&#10;print(\'Acesta este primul meu program cu mai multe linii!\')" instructions="Rulează și observă ordinea. Fiecare print() afișează un rând nou."></div><h2>Rânduri goale</h2><p>Poți adăuga un rând gol folosind <code>print()</code> fără text:</p><div data-code-exercise="" startercode="print(\'=== PROFILUL MEU ===\')&#10;print()&#10;print(\'Nume: Ana\')&#10;print(\'Clasa: a 6-a\')&#10;print(\'Hobby: programare\')&#10;print()&#10;print(\'==================\')" instructions="Vezi cum print() fără text creează un rând gol. Schimbă datele cu ale tale!"></div><h2>Rândul tău: Carte de identitate</h2><p>Creează un program care afișează "cartea ta de identitate":</p><div data-code-exercise="" startercode="# Creează cartea ta de identitate!&#10;print(\'Nume: ...\')&#10;print(\'Prenume: ...\')&#10;# Adaugă mai multe rânduri..." instructions="Creează un program care afișează datele tale."></div><h2>Erori — și asta e OK!</h2><p>Ce se întâmplă dacă uiți ghilimelele?</p><div data-code-exercise="" startercode="print(Salut)" instructions="Rulează acest program cu eroare. Citește mesajul — ce spune?"></div><p>Mesajul roșu este o <strong>eroare</strong> (error). Erorile sunt normale! Important este să înveți să le citești.</p><p><strong>Reține:</strong> Textul se pune ÎNTOTDEAUNA între ghilimele: <code>\'text\'</code> sau <code>"text"</code></p>'; }

    private function lesson2_1(): string { return '<h1>Ce sunt variabilele?</h1><p>Imaginează-ți niște cutii în care pui lucruri. Pe fiecare cutie scrii un nume ca să știi ce este înăuntru:</p><ul><li>Cutia <strong>nume</strong> — înăuntru scrie "Ana"</li><li>Cutia <strong>varsta</strong> — înăuntru este numărul 12</li><li>Cutia <strong>clasa</strong> — înăuntru scrie "6-A"</li></ul><p>În programare, aceste cutii se numesc <strong>variabile</strong>. O variabilă are un NUME și o VALOARE.</p><div data-code-exercise="" startercode="# Facem trei cutii (variabile)&#10;nume = \'Ana\'&#10;varsta = 12&#10;clasa = \'6-A\'&#10;&#10;print(\'Nume:\', nume)&#10;print(\'Vârsta:\', varsta)&#10;print(\'Clasa:\', clasa)" instructions="Rulează programul. Schimbă valorile cu datele tale."></div><h2>De ce se numesc VARIABILE?</h2><p>Pentru că le poți schimba valoarea!</p><div data-code-exercise="" startercode="puncte = 0&#10;print(\'La început am\', puncte, \'puncte\')&#10;&#10;puncte = 10&#10;print(\'După prima sarcină am\', puncte, \'puncte\')&#10;&#10;puncte = 25&#10;print(\'După a doua sarcină am\', puncte, \'puncte\')" instructions="Observă cum se schimbă valoarea variabilei \'puncte\'."></div><h2>Reguli pentru numele variabilelor</h2><ul><li>Se folosesc litere mici: <code>nume</code>, <code>varsta</code></li><li>Mai multe cuvinte se leagă cu underscore: <code>materie_preferata</code></li><li>Nu poate începe cu cifră: <code>1clasa</code> nu funcționează</li><li>Fără spații: <code>numele meu</code> nu funcționează</li></ul><h2>Rândul tău</h2><div data-code-exercise="" startercode="# Completează datele celui mai bun prieten&#10;nume_prieten = \'...\'&#10;varsta_prieten = 0&#10;sport_preferat = \'...\'&#10;culoare_preferata = \'...\'&#10;&#10;print(\'Cel mai bun prieten:\')&#10;print(\'Nume:\', nume_prieten)&#10;# Adaugă print() pentru restul" instructions="Completează valorile și adaugă print() pentru fiecare variabilă."></div>'; }

    private function lesson2_2(): string { return '<h1>Tipuri de date — numere și text</h1><p>Python diferențiază trei tipuri de bază:</p><table><tr><th>Tip</th><th>Ce este?</th><th>Exemplu</th></tr><tr><td><strong>int</strong></td><td>Număr întreg</td><td>5, 100, -3</td></tr><tr><td><strong>float</strong></td><td>Număr zecimal</td><td>3.14, 2.5</td></tr><tr><td><strong>str</strong></td><td>Text (string)</td><td>\'salut\', "Ana"</td></tr></table><h2>Cum aflăm tipul?</h2><div data-code-exercise="" startercode="a = 5&#10;b = 3.14&#10;c = \'salut\'&#10;&#10;print(a, \'— tip:\', type(a))&#10;print(b, \'— tip:\', type(b))&#10;print(c, \'— tip:\', type(c))&#10;&#10;# ATENȚIE: un număr între ghilimele este TEXT!&#10;d = \'100\'&#10;print(d, \'— tip:\', type(d))" instructions="Rulează și observă tipurile. \'100\' este text, nu număr!"></div><h2>Important: un număr între ghilimele NU este număr!</h2><div data-code-exercise="" startercode="numar = 100&#10;text = \'100\'&#10;&#10;print(numar + numar)   # 200 — calcul&#10;print(text + text)     # \'100100\' — concatenare!" instructions="Vezi diferența! Numerele se adună, textul se lipește!"></div><h2>Convertirea tipurilor</h2><ul><li><code>int(\'42\')</code> — text în număr întreg</li><li><code>float(\'3.14\')</code> — text în număr zecimal</li><li><code>str(42)</code> — număr în text</li></ul><div data-code-exercise="" startercode="text = \'25\'&#10;numar = int(text)&#10;print(numar + 10)  # 35&#10;&#10;varsta = 12&#10;mesaj = \'Am \' + str(varsta) + \' ani\'&#10;print(mesaj)" instructions="Vezi cum funcționează convertirea."></div>'; }

    private function lesson2_3(): string { return '<h1>Discuție cu calculatorul — input()</h1><p>Până acum noi am scris toate datele în program. Dar dacă vrem ca UTILIZATORUL să introducă ceva?</p><div data-code-exercise="" startercode="nume = input(\'Cum te cheamă? \')&#10;print(\'Salut, \' + nume + \'! Îmi pare bine!\')" instructions="Rulează, tastează numele tău și apasă OK."></div><p><code>input()</code> oprește programul și așteaptă ca utilizatorul să tasteze ceva.</p><h2>Atenție: input() returnează întotdeauna TEXT</h2><p>Chiar dacă tastezi un număr, input() îl salvează ca text! De aceea trebuie să convertim:</p><div data-code-exercise="" startercode="# AȘA ESTE CORECT:&#10;varsta = int(input(\'Câți ani ai? \'))&#10;print(\'Tu ai\', varsta, \'ani.\')&#10;print(\'Anul viitor vei avea\', varsta + 1, \'ani!\')" instructions="int(input(...)) convertește intrarea în număr!"></div><h2>Rețeta pentru citirea datelor</h2><ul><li>Text: <code>nume = input(\'Introdu numele: \')</code></li><li>Număr întreg: <code>nr = int(input(\'Introdu un număr: \'))</code></li><li>Număr zecimal: <code>nr = float(input(\'Introdu un număr: \'))</code></li></ul><h2>Rândul tău: Anchetă</h2><div data-code-exercise="" startercode="print(\'=== ANCHETĂ ===\')&#10;print()&#10;nume = input(\'Cum te cheamă? \')&#10;# Adaugă întrebări:&#10;# - Câți ani ai? (int)&#10;# - Materia preferată?&#10;# - Filmul preferat?&#10;# - Mâncarea preferată?&#10;print()&#10;print(\'=== REZULTATE ===\')&#10;print(\'Nume:\', nume)&#10;# Afișează restul" instructions="Completează ancheta — adaugă întrebări și afișează răspunsurile."></div>'; }

    private function lesson3_1(): string { return '<h1>Python ca un calculator</h1><p>Python poate calcula în locul tău!</p><table><tr><th>Operator</th><th>Semnificație</th><th>Exemplu</th><th>Rezultat</th></tr><tr><td><code>+</code></td><td>Adunare</td><td>5 + 3</td><td>8</td></tr><tr><td><code>-</code></td><td>Scădere</td><td>10 - 4</td><td>6</td></tr><tr><td><code>*</code></td><td>Înmulțire</td><td>6 * 7</td><td>42</td></tr><tr><td><code>/</code></td><td>Împărțire</td><td>15 / 4</td><td>3.75</td></tr><tr><td><code>//</code></td><td>Împărțire întreagă</td><td>15 // 4</td><td>3</td></tr><tr><td><code>%</code></td><td>Rest</td><td>15 % 4</td><td>3</td></tr><tr><td><code>**</code></td><td>Ridicare la putere</td><td>2 ** 3</td><td>8</td></tr></table><div data-code-exercise="" startercode="print(\'5 + 3 =\', 5 + 3)&#10;print(\'10 - 4 =\', 10 - 4)&#10;print(\'6 * 7 =\', 6 * 7)&#10;print(\'15 / 4 =\', 15 / 4)&#10;print(\'15 // 4 =\', 15 // 4)&#10;print(\'15 % 4 =\', 15 % 4)&#10;print(\'2 ** 3 =\', 2 ** 3)" instructions="Rulează și compară rezultatele cu tabelul."></div><h2>Calculator cu introducere date</h2><div data-code-exercise="" startercode="a = float(input(\'Introdu primul număr: \'))&#10;b = float(input(\'Introdu al doilea număr: \'))&#10;print()&#10;print(a, \'+\', b, \'=\', a + b)&#10;print(a, \'-\', b, \'=\', a - b)&#10;print(a, \'*\', b, \'=\', a * b)&#10;print(a, \'/\', b, \'=\', a / b)" instructions="Introdu două numere și vezi toate operațiile!"></div><h2>Rândul tău: Aria dreptunghiului</h2><div data-code-exercise="" startercode="a = float(input(\'Introdu latura a: \'))&#10;b = float(input(\'Introdu latura b: \'))&#10;&#10;# Calculează:&#10;# aria = a * b&#10;# perimetrul = 2 * a + 2 * b&#10;# Afișează rezultatele" instructions="Calculează și afișează aria și perimetrul dreptunghiului."></div>'; }

    private function lesson3_2(): string { return '<h1>Jocuri cu textul</h1><h2>Concatenarea textului</h2><div data-code-exercise="" startercode="nume = \'Ana\'&#10;prenume = \'Popescu\'&#10;&#10;nume_complet = nume + \' \' + prenume&#10;print(nume_complet)&#10;&#10;# f-string — cel mai ușor mod&#10;varsta = 12&#10;print(f\'Mă cheamă {nume} {prenume} și am {varsta} ani.\')" instructions="Rulează și vezi două moduri de a combina text. f-string este cel mai ușor!"></div><h2>Ce poți face cu textul?</h2><div data-code-exercise="" startercode="cuvant = \'programare\'&#10;&#10;print(\'Majuscule:\', cuvant.upper())&#10;print(\'Minuscule:\', cuvant.lower())&#10;print(\'Lungime:\', len(cuvant), \'litere\')&#10;print(\'Prima literă:\', cuvant[0])&#10;print(\'Ultima literă:\', cuvant[-1])&#10;print(\'Primele 3 litere:\', cuvant[0:3])&#10;print(\'ha\' * 5)&#10;print(\'-\' * 30)" instructions="Încearcă toate operațiile cu text!"></div><h2>Rândul tău: Generator de porecle</h2><div data-code-exercise="" startercode="nume = input(\'Introdu numele tău: \')&#10;&#10;# Afișează:&#10;# - Numele cu majuscule&#10;# - Numele cu minuscule&#10;# - Câte litere are (len)&#10;# - Primele 3 litere&#10;# - Numele repetat de 3 ori&#10;# - Numele invers (hint: nume[::-1])" instructions="Completează programul. Hint pentru invers: nume[::-1]"></div>'; }

    private function lesson4_1(): string { return '<h1>Da sau nu? — condiții</h1><p>Calculatorul răspunde cu DA (True) sau NU (False):</p><table><tr><th>Semn</th><th>Semnificație</th><th>Exemplu</th><th>Rezultat</th></tr><tr><td><code>==</code></td><td>Egal?</td><td>5 == 5</td><td>True</td></tr><tr><td><code>!=</code></td><td>Diferit?</td><td>5 != 3</td><td>True</td></tr><tr><td><code>&gt;</code></td><td>Mai mare?</td><td>10 > 3</td><td>True</td></tr><tr><td><code>&lt;</code></td><td>Mai mic?</td><td>2 < 1</td><td>False</td></tr><tr><td><code>&gt;=</code></td><td>Mai mare sau egal?</td><td>5 >= 5</td><td>True</td></tr><tr><td><code>&lt;=</code></td><td>Mai mic sau egal?</td><td>3 <= 2</td><td>False</td></tr></table><div data-code-exercise="" startercode="print(\'5 == 5:\', 5 == 5)&#10;print(\'5 == 3:\', 5 == 3)&#10;print(\'10 > 3:\', 10 > 3)&#10;print(\'2 < 1:\', 2 < 1)&#10;&#10;varsta = 12&#10;print(\'Mai mare de 10?\', varsta > 10)&#10;print(\'Exact 15?\', varsta == 15)" instructions="Rulează și observă răspunsurile True/False."></div><h2>if — calculatorul decide</h2><div data-code-exercise="" startercode="varsta = int(input(\'Câți ani ai? \'))&#10;&#10;if varsta >= 18:&#10;    print(\'Poți conduce mașina!\')&#10;&#10;if varsta < 18:&#10;    print(\'Încă nu poți conduce, mai așteaptă\', 18 - varsta, \'ani.\')" instructions="Introdu diferite vârste și vezi ce se afișează."></div><h2>if + else</h2><div data-code-exercise="" startercode="parola = input(\'Introdu parola: \')&#10;&#10;if parola == \'python123\':&#10;    print(\'Parolă corectă! Bine ai venit!\')&#10;else:&#10;    print(\'Parolă greșită! Încearcă din nou.\')" instructions="Introdu \'python123\' apoi încearcă altceva."></div>'; }

    private function lesson4_2(): string { return '<h1>Mai multe opțiuni — elif</h1><p>Ce facem când avem MAI MULT de două opțiuni? Nota la școală nu este doar "trecut" sau "picat"!</p><div data-code-exercise="" startercode="puncte = int(input(\'Câte puncte ai luat la test? (0-100) \'))&#10;&#10;if puncte >= 90:&#10;    print(\'Nota: 10 — Excelent!\')&#10;elif puncte >= 75:&#10;    print(\'Nota: 8 — Foarte bine\')&#10;elif puncte >= 60:&#10;    print(\'Nota: 7 — Bine\')&#10;elif puncte >= 50:&#10;    print(\'Nota: 5 — Suficient\')&#10;else:&#10;    print(\'Nota: 3 — Insuficient\')" instructions="Introdu diferite punctaje: 95, 80, 65, 55, 30"></div><h2>Rândul tău: Consilier meteo</h2><div data-code-exercise="" startercode="temp = int(input(\'Câte grade sunt afară? \'))&#10;&#10;# Sub 0: \'Foarte frig! Stai înăuntru.\'&#10;# 0-10: \'Frig, ia geacă și fular.\'&#10;# 11-20: \'Plăcut, geacă ușoară.\'&#10;# 21-30: \'Vreme frumoasă, bucură-te!\'&#10;# Peste 30: \'Caniculă! Bea multă apă.\'" instructions="Completează cu if/elif/else. Testează: -5, 5, 15, 25, 35"></div><h2>Rândul tău: Calculator cu meniu</h2><div data-code-exercise="" startercode="print(\'=== CALCULATOR ===\')&#10;print(\'1. Adunare\')&#10;print(\'2. Scădere\')&#10;print(\'3. Înmulțire\')&#10;print(\'4. Împărțire\')&#10;print()&#10;alegere = input(\'Alege operația (1-4): \')&#10;a = float(input(\'Primul număr: \'))&#10;b = float(input(\'Al doilea număr: \'))&#10;&#10;# Folosește if/elif/else pentru calcul" instructions="Creează un calculator cu 4 operații!"></div>'; }

    private function lesson5_1(): string { return '<h1>Repetare — bucla for</h1><p>Ce facem dacă vrem să afișăm "Salut" de 10 ori? În loc de 10 linii, folosim o <strong>buclă</strong>!</p><div data-code-exercise="" startercode="for i in range(5):&#10;    print(\'Salut! Aceasta este repetarea numărul\', i + 1)" instructions="Rulează și observă repetarea. Schimbă 5 în 10."></div><h2>Ce este range()?</h2><ul><li><code>range(5)</code> — numerele 0, 1, 2, 3, 4</li><li><code>range(1, 6)</code> — numerele 1, 2, 3, 4, 5</li><li><code>range(0, 11, 2)</code> — pare: 0, 2, 4, 6, 8, 10</li></ul><div data-code-exercise="" startercode="print(\'range(5):\')&#10;for i in range(5):&#10;    print(i, end=\' \')&#10;print()&#10;print()&#10;print(\'range(1, 6):\')&#10;for i in range(1, 6):&#10;    print(i, end=\' \')&#10;print()&#10;print()&#10;print(\'Numere pare până la 10:\')&#10;for i in range(0, 11, 2):&#10;    print(i, end=\' \')" instructions="Observă diferitele moduri de utilizare ale range()."></div><h2>Tabla înmulțirii</h2><div data-code-exercise="" startercode="numar = 7&#10;print(f\'Tabla înmulțirii pentru {numar}:\')&#10;print()&#10;for i in range(1, 11):&#10;    print(f\'{numar} x {i} = {numar * i}\')" instructions="Rulează tabla. Schimbă 7 cu alt număr."></div><h2>Rândul tău: Suma numerelor</h2><div data-code-exercise="" startercode="cate = int(input(\'Câte numere introduci? \'))&#10;suma = 0&#10;&#10;for i in range(cate):&#10;    # Cere un număr și adaugă-l la sumă&#10;    pass  # înlocuiește această linie&#10;&#10;print(\'Suma este:\', suma)" instructions="Înlocuiește \'pass\'. Hint: nr = int(input(...)) apoi suma = suma + nr"></div>'; }

    private function lesson5_2(): string { return '<h1>Repetă cât timp... — bucla while</h1><p><code>for</code> repetă de un număr exact de ori. Dar dacă nu știm de câte ori? Exemplu: "Cere parola CÂT TIMP nu ghicește."</p><div data-code-exercise="" startercode="secret = \'python\'&#10;&#10;raspuns = input(\'Introdu parola: \')&#10;&#10;while raspuns != secret:&#10;    print(\'Greșit! Încearcă din nou.\')&#10;    raspuns = input(\'Introdu parola: \')&#10;&#10;print(\'Bravo! Ai ghicit!\')" instructions="Încearcă să ghicești. Hint: secretul este \'python\'"></div><h2>Numărătoare inversă</h2><div data-code-exercise="" startercode="numar = 10&#10;&#10;while numar > 0:&#10;    print(numar, \'...\')&#10;    numar = numar - 1&#10;&#10;print(\'START!\')" instructions="Observă numărătoarea. Schimbă 10 în 5."></div><h2>Rândul tău: Jocul de ghicit</h2><p>Calculatorul "gândește" un număr de la 1 la 20, iar tu ghicești. După fiecare încercare, spune "Mai mare" sau "Mai mic".</p><div data-code-exercise="" startercode="numar_secret = 14&#10;incercari = 0&#10;&#10;print(\'Am gândit un număr de la 1 la 20!\')&#10;&#10;# Creează o buclă while care:&#10;# 1. Cere un număr&#10;# 2. Numără încercările&#10;# 3. Dacă e prea mare: \'Mai mic!\'&#10;# 4. Dacă e prea mic: \'Mai mare!\'&#10;# 5. Dacă ghicește: \'Bravo!\'" instructions="Completează jocul. Folosește while, input(), if/elif/else."></div><h2>Ce am învățat în acest curs?</h2><ul><li><strong>print()</strong> — afișează pe ecran</li><li><strong>Variabile</strong> — cutii pentru date (int, float, str)</li><li><strong>input()</strong> — citirea datelor de la utilizator</li><li><strong>Operatori</strong> — calcule (+, -, *, /, //, %, **)</li><li><strong>if/elif/else</strong> — luarea deciziilor</li><li><strong>Bucla for</strong> — repetare de un număr dat de ori</li><li><strong>Bucla while</strong> — repetare cât timp condiția este adevărată</li></ul><p><strong>Felicitări că ai ajuns până la capăt! Acum cunoști bazele programării!</strong></p>'; }
}
