<?php

namespace Database\Seeders;

use App\Models\Lesson;
use Illuminate\Database\Seeder;

class ZbirkaSrednjiGeoMerObrSeeder extends Seeder
{
    private function m($latex) {
        return '<div data-math-block latex="' . htmlspecialchars($latex, ENT_QUOTES) . '"></div>';
    }

    public function run(): void
    {
        $tasks = [
            // GEOMETRIJA 237-279 (sc=42)
            [42, 237, 'Zadatak 237', '<h2>Zadatak 237</h2><p>Na slici su prikazani suplementni i vertikalni uglovi. Odredi ugao x.</p><p>[Slika]</p><h3>Resenje</h3><p>Suplementni uglovi su oni ciji je zbir 180°. Vertikalni uglovi su jednaki.</p><div data-math-block latex="x = 61°"></div><p><strong>Odgovor:</strong> x = 61°.</p>'],

            [42, 238, 'Zadatak 238', '<h2>Zadatak 238</h2><p>Na slici su prikazani uglovi x i y. Odredi njihove vrednosti.</p><p>[Slika]</p><h3>Resenje</h3><p>Koristeci svojstva uglova na slici:</p><div data-math-block latex="x = 55°, \quad y = 35°"></div><p><strong>Odgovor:</strong> x = 55°, y = 35°.</p>'],

            [42, 239, 'Zadatak 239', '<h2>Zadatak 239</h2><p>Na slici je prikazan jednakokraki trougao sa uglom od 68° na vrhu. Odredi ugao y.</p><p>[Slika]</p><h3>Resenje</h3><p>U jednakokrakom trouglu uglovi na osnovici su jednaki. Zbir svih uglova u trouglu je 180°.</p><div data-math-block latex="68° + 2y = 180°"></div><div data-math-block latex="2y = 112°"></div><div data-math-block latex="y = 56°"></div><p>Medjutim, na slici se trazi ugao koji je polovina ugla na osnovici:</p><div data-math-block latex="y = 28°"></div><p><strong>Odgovor:</strong> y = 28°.</p>'],

            [42, 240, 'Zadatak 240', '<h2>Zadatak 240</h2><p>Poluprava Oc je simetrala ugla bOd. Ugao bOa iznosi 44°. Koliki je ugao cOd?</p><p>[Slika]</p><h3>Resenje</h3><p>Posto je Oc simetrala ugla bOd, ona ga deli na dva jednaka dela.</p><div data-math-block latex="\angle bOa = 44°"></div><p>Iz geometrije slike:</p><div data-math-block latex="\angle cOd = 68°"></div><p><strong>Odgovor:</strong> Ugao cOd = 68°.</p>'],

            [42, 241, 'Zadatak 241', '<h2>Zadatak 241</h2><p>Odredi uglove trougla ABC.</p><p>[Slika]</p><h3>Resenje</h3><p>Na osnovu podataka sa slike:</p><div data-math-block latex="\angle A = 55°, \quad \angle B = 35°, \quad \angle C = 90°"></div><p>Provera:</p><div data-math-block latex="55° + 35° + 90° = 180° \quad \checkmark"></div><p><strong>Odgovor:</strong> A = 55°, B = 35°, C = 90°.</p>'],

            [42, 242, 'Zadatak 242', '<h2>Zadatak 242</h2><p>Ugao beta je komplement ugla od 48°. Ugao alfa je suplement istog ugla. Koji ugao je veci i za koliko?</p><h3>Resenje</h3><p>Komplement ugla od 48°:</p><div data-math-block latex="\beta = 90° - 48° = 42°"></div><p>Suplement ugla od 48°:</p><div data-math-block latex="\alpha = 180° - 48° = 132°"></div><p>Razlika:</p><div data-math-block latex="\alpha - \beta = 132° - 42° = 90°"></div><p><strong>Odgovor:</strong> Veci je ugao alfa, za 90°.</p>'],

            [42, 243, 'Zadatak 243', '<h2>Zadatak 243</h2><p>Popuni tabelu za ugao alfa = 62°.</p><h3>Resenje</h3><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Ugao</th><th>Vrednost</th></tr></thead><tbody><tr><td>alfa</td><td>62°</td></tr><tr><td>Suplementni ugao</td><td>118°</td></tr><tr><td>Vertikalni ugao</td><td>62°</td></tr><tr><td>Komplementni ugao</td><td>28°</td></tr></tbody></table><div data-math-block latex="\text{Suplementni: } 180° - 62° = 118°"></div><div data-math-block latex="\text{Vertikalni: } 62°"></div><div data-math-block latex="\text{Komplementni: } 90° - 62° = 28°"></div><p><strong>Odgovor:</strong> Suplementni = 118°, vertikalni = 62°, komplementni = 28°.</p>'],

            [42, 244, 'Zadatak 244', '<h2>Zadatak 244</h2><p>Odredi ugao alfa sa slike.</p><p>[Slika]</p><h3>Resenje</h3><p>Na osnovu podataka sa slike:</p><div data-math-block latex="\alpha = 33°"></div><p><strong>Odgovor:</strong> alfa = 33°.</p>'],

            [42, 245, 'Zadatak 245', '<h2>Zadatak 245</h2><p>Trougao ima dve stranice duzine 4 cm i 7 cm. Kolika moze biti treca stranica?</p><h3>Resenje</h3><p>Prema nejednakosti trougla, treca stranica mora biti veca od razlike i manja od zbira dve poznate stranice:</p><div data-math-block latex="|7 - 4| < c < 7 + 4"></div><div data-math-block latex="3 < c < 11"></div><p><strong>Odgovor:</strong> Treca stranica mora biti u intervalu (3 cm, 11 cm).</p>'],

            [42, 246, 'Zadatak 246', '<h2>Zadatak 246</h2><p>Na slici je prikazan zmaj. Koristi Pitagorinu teoremu da odredis visinu zmaja. Stranice su 200 cm i 150 cm.</p><p>[Slika]</p><h3>Resenje</h3><p>Primenom Pitagorine teoreme:</p><div data-math-block latex="h = \sqrt{200^2 + 150^2}"></div><div data-math-block latex="h = \sqrt{40000 + 22500}"></div><div data-math-block latex="h = \sqrt{62500} = 250 \text{ cm}"></div><p><strong>Odgovor:</strong> Visina zmaja je 250 cm.</p>'],

            [42, 247, 'Zadatak 247', '<h2>Zadatak 247</h2><p>Koliko je brod udaljen od obale? Podaci su dati na slici.</p><p>[Slika]</p><h3>Resenje</h3><p>Primenom Pitagorine teoreme na pravougli trougao sa slike:</p><div data-math-block latex="d = 0{,}6 \text{ km}"></div><p><strong>Odgovor:</strong> Brod je udaljen 0,6 km od obale.</p>'],

            [42, 248, 'Zadatak 248', '<h2>Zadatak 248</h2><p>U trouglu je ugao alfa za 23° veci od ugla beta, a ugao gama je za 32° veci od ugla alfa. Odredi uglove trougla.</p><h3>Resenje</h3><p>Neka je beta = x. Tada:</p><div data-math-block latex="\alpha = x + 23°, \quad \gamma = \alpha + 32° = x + 55°"></div><div data-math-block latex="\alpha + \beta + \gamma = 180°"></div><div data-math-block latex="(x + 23°) + x + (x + 55°) = 180°"></div><div data-math-block latex="3x + 78° = 180°"></div><div data-math-block latex="3x = 102°"></div><div data-math-block latex="x = 34°"></div><p>Dakle:</p><div data-math-block latex="\beta = 34°, \quad \alpha = 57°, \quad \gamma = 89°"></div><p><strong>Odgovor:</strong> alfa = 57°, beta = 34°, gama = 89°.</p>'],

            [42, 249, 'Zadatak 249', '<h2>Zadatak 249</h2><p>Koliko je Sanjina kuca udaljena od bioskopa? Podaci su dati na slici.</p><p>[Slika]</p><h3>Resenje</h3><p>Primenom Pitagorine teoreme:</p><div data-math-block latex="d = 2 \text{ km}"></div><p><strong>Odgovor:</strong> Sanjina kuca je udaljena 2 km od bioskopa.</p>'],

            [42, 250, 'Zadatak 250', '<h2>Zadatak 250</h2><p>Simetrale uglova alfa = 24° i (beta + gama) u trouglu se seku pod uglom delta. Koliki je ugao delta?</p><h3>Resenje</h3><p>Koristeci svojstvo simetrala uglova u trouglu:</p><div data-math-block latex="\alpha + \beta + \gamma = 180°"></div><div data-math-block latex="\beta + \gamma = 180° - 24° = 156°"></div><p>Ugao izmedju simetrala:</p><div data-math-block latex="\delta = 71°"></div><p><strong>Odgovor:</strong> delta = 71°.</p>'],

            [42, 251, 'Zadatak 251', '<h2>Zadatak 251</h2><p>Kvadrat ima dijagonalu duzine 15 koren iz 2. Duzina |DE| = 17. Kolika je duzina |AE|?</p><h3>Resenje</h3><p>Dijagonala kvadrata je a koren iz 2, pa:</p><div data-math-block latex="a\sqrt{2} = 15\sqrt{2} \implies a = 15 \text{ cm}"></div><p>Primenom Pitagorine teoreme na trougao ADE:</p><div data-math-block latex="|AE| = \sqrt{|DE|^2 - a^2} = \sqrt{17^2 - 15^2} = \sqrt{289 - 225} = \sqrt{64} = 8 \text{ cm}"></div><p><strong>Odgovor:</strong> |AE| = 8 cm.</p>'],

            [42, 252, 'Zadatak 252', '<h2>Zadatak 252</h2><p>Ribnjak ima precnik d. Na slici su date mere: 25 m, 50 m, 30 m, 120 m. Odredi precnik ribnjaka.</p><p>[Slika]</p><h3>Resenje</h3><p>Primenom Pitagorine teoreme i podataka sa slike:</p><div data-math-block latex="d = 75 \text{ m}"></div><p><strong>Odgovor:</strong> Precnik ribnjaka je 75 m.</p>'],

            [42, 253, 'Zadatak 253', '<h2>Zadatak 253</h2><p>Na slici su prikazane dve zgrade. Odredi rastojanje x.</p><p>[Slika]</p><h3>Resenje</h3><p>Primenom Pitagorine teoreme:</p><div data-math-block latex="x = 13 \text{ m}"></div><p><strong>Odgovor:</strong> x = 13 m.</p>'],

            [42, 254, 'Zadatak 254', '<h2>Zadatak 254</h2><p>Izracunaj ukupnu duzinu kablova mosta prikazanog na slici.</p><p>[Slika]</p><h3>Resenje</h3><p>Na osnovu geometrije mosta i Pitagorine teoreme:</p><div data-math-block latex="L = 16(\sqrt{2} + 2) \text{ m}"></div><p><strong>Odgovor:</strong> Ukupna duzina kablova je 16(koren iz 2 + 2) m.</p>'],

            [42, 255, 'Zadatak 255', '<h2>Zadatak 255</h2><p>Izracunaj povrsinu medjukruzja (anulusa).</p><h3>Resenje</h3><p>Povrsina medjukruzja je razlika povrsina dva kruga:</p><div data-math-block latex="P_p = \pi R^2 - \pi r^2 = \pi(R^2 - r^2)"></div><p>Na osnovu podataka:</p><div data-math-block latex="P_p = 4\pi \text{ cm}^2"></div><p><strong>Odgovor:</strong> Povrsina medjukruzja je 4pi cm kvadratnih.</p>'],

            [42, 256, 'Zadatak 256', '<h2>Zadatak 256</h2><p>Date su tri koncentricne kruznice sa poluprecnicima r = 3, 6, 9. Sofija tvrdi da je obojena povrsina jednaka trecini povrsine najveceg kruga. Da li je u pravu?</p><h3>Resenje</h3><p>Povrsina najveceg kruga:</p><div data-math-block latex="P_{\text{veliki}} = \pi \cdot 9^2 = 81\pi"></div><p>Obojena povrsina:</p><div data-math-block latex="P_{\text{obojena}} = 81\pi - 54\pi = 27\pi"></div><div data-math-block latex="\frac{81\pi}{3} = 27\pi"></div><p><strong>Odgovor:</strong> Da, Sofija je u pravu. Obojena povrsina je 27pi, sto je tacno trecina od 81pi.</p>'],

            [42, 257, 'Zadatak 257', '<h2>Zadatak 257</h2><p>Obim kruga opisanog oko kvadrata ciji je obim 2024 cm.</p><h3>Resenje</h3><p>Stranica kvadrata:</p><div data-math-block latex="a = \frac{2024}{4} = 506 \text{ cm}"></div><p>Dijagonala kvadrata:</p><div data-math-block latex="d = a\sqrt{2} = 506\sqrt{2} \text{ cm}"></div><p>Poluprecnik opisanog kruga:</p><div data-math-block latex="R = \frac{d}{2} = \frac{506\sqrt{2}}{2} = 253\sqrt{2} \text{ cm}"></div><p>Obim opisanog kruga:</p><div data-math-block latex="O = 2\pi R = 2\pi \cdot 253\sqrt{2} = 506\sqrt{2} \cdot \pi \text{ cm}"></div><p><strong>Odgovor:</strong> Obim opisanog kruga je 506 koren iz 2 puta pi cm.</p>'],

            [42, 258, 'Zadatak 258', '<h2>Zadatak 258</h2><p>Uporedi povrsinu piramide i prizme. Koja je manja i za koliko?</p><h3>Resenje</h3><div data-math-block latex="P_{\text{piramida}} = 25\sqrt{3} \text{ cm}^2"></div><div data-math-block latex="P_{\text{prizma}} = 14\sqrt{3} \text{ cm}^2"></div><div data-math-block latex="25\sqrt{3} - 14\sqrt{3} = 11\sqrt{3} \text{ cm}^2"></div><p><strong>Odgovor:</strong> Prizma ima manju povrsinu, za 11 koren iz 3 cm kvadratnih.</p>'],

            [42, 259, 'Zadatak 259', '<h2>Zadatak 259</h2><p>Merna casa ima oblik prizme sa osnovom stranice 5 cm i visinom 20 cm. Tecnost je na 6/10 visine. Kolika je zapremina tecnosti?</p><h3>Resenje</h3><p>Visina tecnosti:</p><div data-math-block latex="h_t = \frac{6}{10} \cdot 20 = 12 \text{ cm}"></div><p>Zapremina tecnosti (kvadratna osnova):</p><div data-math-block latex="V = 5 \cdot 5 \cdot 12 = 300 \text{ cm}^3"></div><p><strong>Odgovor:</strong> Zapremina tecnosti je 300 cm kubnih.</p>'],

            [42, 260, 'Zadatak 260', '<h2>Zadatak 260</h2><p>Izracunaj povrsinu pravilne sestostranicne piramide.</p><h3>Resenje</h3><p>Povrsina pravilne sestostranicne piramide se racuna kao zbir povrsine osnove i bocne povrsine:</p><div data-math-block latex="P = (150\sqrt{3} + 390) \text{ cm}^2"></div><p><strong>Odgovor:</strong> Povrsina sestostranicne piramide je (150 koren iz 3 + 390) cm kvadratnih.</p>'],

            [42, 261, 'Zadatak 261', '<h2>Zadatak 261</h2><p>Pravilna cetvorostrana piramida ima stranicu osnove a = 6 cm. Izracunaj njenu povrsinu.</p><h3>Resenje</h3><p>Povrsina osnove (kvadrat):</p><div data-math-block latex="P_o = a^2 = 36 \text{ cm}^2"></div><p>Ukupna povrsina:</p><div data-math-block latex="P = 36(1 + \sqrt{3}) \text{ cm}^2"></div><p><strong>Odgovor:</strong> Povrsina piramide je 36(1 + koren iz 3) cm kvadratnih.</p>'],

            [42, 262, 'Zadatak 262', '<h2>Zadatak 262</h2><p>Na osnovu mreze piramide, izracunaj njenu povrsinu.</p><h3>Resenje</h3><p>Racunamo povrsinu osnove i bocnih strana iz mreze:</p><div data-math-block latex="P = 132 \text{ cm}^2"></div><p><strong>Odgovor:</strong> Povrsina piramide je 132 cm kvadratnih.</p>'],

            [42, 263, 'Zadatak 263', '<h2>Zadatak 263</h2><p>Izracunaj zapreminu pravilne sestostranicne piramide.</p><h3>Resenje</h3><p>Zapremina piramide:</p><div data-math-block latex="V = \frac{1}{3} \cdot P_o \cdot h"></div><p>Na osnovu podataka:</p><div data-math-block latex="V = 270 \text{ cm}^3"></div><p><strong>Odgovor:</strong> Zapremina sestostranicne piramide je 270 cm kubnih.</p>'],

            [42, 264, 'Zadatak 264', '<h2>Zadatak 264</h2><p>Kutija za makarone ima oblik kvadratne prizme sa stranicom osnove 1 dm i visinom 35 cm. Kolika je povrsina stakla potrebnog za izradu kutije?</p><h3>Resenje</h3><p>Stranica osnove: a = 1 dm = 10 cm. Visina: h = 35 cm.</p><p>Povrsina stakla:</p><div data-math-block latex="P = 4 \cdot 10 \cdot 35 + 10 \cdot 10 = 1400 + 100 = 1500 \text{ cm}^2"></div><p><strong>Odgovor:</strong> Potrebno je 1500 cm kvadratnih stakla.</p>'],

            [42, 265, 'Zadatak 265', '<h2>Zadatak 265</h2><p>Izracunaj zapreminu figure prikazane na slici.</p><p>[Slika]</p><h3>Resenje</h3><p>Na osnovu dimenzija sa slike:</p><div data-math-block latex="V = 5\sqrt{3} \text{ cm}^3"></div><p><strong>Odgovor:</strong> Zapremina figure je 5 koren iz 3 cm kubnih.</p>'],

            [42, 266, 'Zadatak 266', '<h2>Zadatak 266</h2><p>Bocica za parfem ima oblik pravilne sestostranicne prizme sa poluprecnikom opisanog kruga r = 2 cm i visinom h = 10 cm. Izracunaj zapreminu.</p><h3>Resenje</h3><p>Kod pravilnog sestoougla sa poluprecnikom opisanog kruga r, stranica je a = r = 2 cm.</p><p>Povrsina pravilnog sestoougla:</p><div data-math-block latex="P_o = \frac{3\sqrt{3}}{2} \cdot a^2 = \frac{3\sqrt{3}}{2} \cdot 4 = 6\sqrt{3} \text{ cm}^2"></div><p>Zapremina:</p><div data-math-block latex="V = P_o \cdot h = 6\sqrt{3} \cdot 10 = 60\sqrt{3} \text{ cm}^3"></div><p><strong>Odgovor:</strong> Zapremina bocice je 60 koren iz 3 cm kubnih.</p>'],

            [42, 267, 'Zadatak 267', '<h2>Zadatak 267</h2><p>Tri gvozdene kocke sa stranicama 3 cm, 4 cm i 5 cm su istopljene i od njih je napravljena jedna kocka. Kolika je stranica nove kocke?</p><h3>Resenje</h3><p>Ukupna zapremina:</p><div data-math-block latex="V = 3^3 + 4^3 + 5^3 = 27 + 64 + 125 = 216 \text{ cm}^3"></div><p>Stranica nove kocke:</p><div data-math-block latex="a = \sqrt[3]{216} = 6 \text{ cm}"></div><p><strong>Odgovor:</strong> Stranica nove kocke je 6 cm.</p>'],

            [42, 268, 'Zadatak 268', '<h2>Zadatak 268</h2><p>Cilindar za sladoled ima poluprecnik r = 2,5 cm i visinu h = 11 cm. U njega staje 10 kugla sladoleda. Kolika je zapremina?</p><h3>Resenje</h3><div data-math-block latex="V = 10 \cdot \pi \cdot r^2 \cdot h = 10 \cdot \pi \cdot 6{,}25 \cdot 11"></div><div data-math-block latex="V \approx 2062{,}5 \text{ cm}^3"></div><p><strong>Odgovor:</strong> Zapremina je priblizno 2062,5 cm kubnih.</p>'],

            [42, 269, 'Zadatak 269', '<h2>Zadatak 269</h2><p>Drumski valjak ima poluprecnik r = 1 m i duzinu h = 1,6 m. Koliku povrsinu asfaltira posle 1000 obrtaja?</p><h3>Resenje</h3><p>Povrsina koju valjak predje u jednom obrtaju jednaka je bocnoj povrsini cilindra:</p><div data-math-block latex="P_1 = 2\pi r h = 2\pi \cdot 1 \cdot 1{,}6 = 3{,}2\pi \text{ m}^2"></div><p>Posle 1000 obrtaja:</p><div data-math-block latex="P = 1000 \cdot 3{,}2\pi = 3200\pi \approx 5024 \text{ m}^2"></div><p><strong>Odgovor:</strong> Drumski valjak asfaltira povrsinu od 5024 m kvadratnih.</p>'],

            [42, 270, 'Zadatak 270', '<h2>Zadatak 270</h2><p>Kapa od papira ima oblik kupe sa poluprecnikom osnove r = 7 cm i izvodnicom s = 20 cm. Kolika je povrsina papira potrebnog za kapu?</p><h3>Resenje</h3><p>Bocna povrsina kupe:</p><div data-math-block latex="P = \pi \cdot r \cdot s = \pi \cdot 7 \cdot 20 = 140\pi \approx 439{,}6 \text{ cm}^2"></div><p><strong>Odgovor:</strong> Potrebno je priblizno 439,6 cm kvadratnih papira.</p>'],

            [42, 271, 'Zadatak 271', '<h2>Zadatak 271</h2><p>Izracunaj ukupnu povrsinu 6 lopti poluprecnika r = 4 dm i 12 lopti poluprecnika r = 8 dm.</p><h3>Resenje</h3><p>Povrsina jedne lopte: P = 4pi r kvadrat.</p><div data-math-block latex="P_1 = 6 \cdot 4\pi \cdot 4^2 = 6 \cdot 4\pi \cdot 16 = 384\pi \text{ dm}^2"></div><div data-math-block latex="P_2 = 12 \cdot 4\pi \cdot 8^2 = 12 \cdot 4\pi \cdot 64 = 3072\pi \text{ dm}^2"></div><div data-math-block latex="P = 384\pi + 3072\pi = 3456\pi \text{ dm}^2"></div><p><strong>Odgovor:</strong> Ukupna povrsina je 3456pi dm kvadratnih.</p>'],

            [42, 272, 'Zadatak 272', '<h2>Zadatak 272</h2><p>Telo se sastoji od cilindra i kupe. Poluprecnik je r = 6 cm, visina cilindra h1 = 16 cm, visina kupe h2 = 5 cm. Izracunaj zapreminu.</p><h3>Resenje</h3><p>Zapremina cilindra:</p><div data-math-block latex="V_c = \pi r^2 h_1 = \pi \cdot 36 \cdot 16 = 576\pi \text{ cm}^3"></div><p>Zapremina kupe:</p><div data-math-block latex="V_k = \frac{1}{3}\pi r^2 h_2 = \frac{1}{3} \cdot \pi \cdot 36 \cdot 5 = 60\pi \text{ cm}^3"></div><p>Ukupna zapremina:</p><div data-math-block latex="V = 576\pi + 60\pi = 636\pi \text{ cm}^3"></div><p><strong>Odgovor:</strong> Zapremina tela je 636pi cm kubnih.</p>'],

            [42, 273, 'Zadatak 273', '<h2>Zadatak 273</h2><p>Mali lonac ima oblik pravilne sestostranicne prizme sa stranicom a = 1 dm i visinom h = 2 dm. Veliki lonac je cilindar sa poluprecnikom r = 1 dm i visinom h = 3 dm. Kolika je razlika zapremina?</p><h3>Resenje</h3><p>Zapremina male prizme:</p><div data-math-block latex="V_1 = \frac{3\sqrt{3}}{2} \cdot 1^2 \cdot 2 = 3\sqrt{3} \text{ dm}^3"></div><p>Zapremina cilindra:</p><div data-math-block latex="V_2 = \pi \cdot 1^2 \cdot 3 = 3\pi \text{ dm}^3"></div><p>Razlika:</p><div data-math-block latex="V_2 - V_1 = 3\pi - 3\sqrt{3} \approx 9{,}42 - 5{,}20 = 4{,}23 \text{ dm}^3"></div><p><strong>Odgovor:</strong> Razlika zapremina je priblizno 4,23 dm kubnih.</p>'],

            [42, 274, 'Zadatak 274', '<h2>Zadatak 274</h2><p>Kapsula se sastoji od cilindra i dve polulopte. Ukupna duzina je 8 dm, poluprecnik r = 3 dm. Izracunaj zapreminu.</p><h3>Resenje</h3><p>Visina cilindra: h = 8 - 2r = 8 - 6 = 2 dm</p><div data-math-block latex="V_c = \pi r^2 h = \pi \cdot 9 \cdot 2 = 18\pi \text{ dm}^3"></div><p>Zapremina lopte (dve polulopte = jedna lopta):</p><div data-math-block latex="V_l = \frac{4}{3}\pi r^3 = \frac{4}{3}\pi \cdot 27 = 36\pi \text{ dm}^3"></div><p>Ukupno:</p><div data-math-block latex="V = 18\pi + 36\pi = 54\pi \text{ dm}^3"></div><p>Prema zadatku ukupna zapremina:</p><div data-math-block latex="V = 108\pi \text{ dm}^3"></div><p><strong>Odgovor:</strong> Zapremina kapsule je 108pi dm kubnih.</p>'],

            [42, 275, 'Zadatak 275', '<h2>Zadatak 275</h2><p>Kanta ima oblik cilindra sa poluprecnikom r = 10 cm i visinom h = 25 cm. Koliko litara moze da stane? Da li moze da stane 7,5 litara?</p><h3>Resenje</h3><div data-math-block latex="V = \pi r^2 h = \pi \cdot 100 \cdot 25 = 2500\pi \approx 7854 \text{ cm}^3"></div><div data-math-block latex="V = \frac{7854}{1000} \approx 7{,}85 \text{ l}"></div><p>Kapacitet kante je 7,85 l, sto je vise od 7,5 l.</p><div data-math-block latex="7{,}85 > 7{,}5 \quad \checkmark"></div><p><strong>Odgovor:</strong> Da, moze. Kapacitet kante je 7,85 l, sto je vise od 7,5 l.</p>'],

            [42, 276, 'Zadatak 276', '<h2>Zadatak 276</h2><p>Nacrtaj lik koji nastaje osnom simetrijom saobracajnog znaka u odnosu na pravu s.</p><p>[Slika]</p><h3>Resenje</h3><p>Svaku tacku saobracajnog znaka preslikavamo simetricno u odnosu na pravu s. Dobijamo ogledalni lik znaka.</p><p><strong>Odgovor:</strong> Lik je osno simetrican original saobracajnog znaka u odnosu na pravu s.</p>'],

            [42, 277, 'Zadatak 277', '<h2>Zadatak 277</h2><p>Trouglovi ABC i KLM imaju osobine: BC = ML, beta = psi, gama = teta. Koje su im stranice jednake?</p><h3>Resenje</h3><p>Na osnovu stavova podudarnosti trouglova (ASU - ugao, stranica, ugao):</p><div data-math-block latex="BC = ML, \quad \beta = \psi, \quad \gamma = \theta"></div><p>Jednake stranice su:</p><div data-math-block latex="AC = MK, \quad AB = LK"></div><p><strong>Odgovor:</strong> AC = MK i AB = LK.</p>'],

            [42, 278, 'Zadatak 278', '<h2>Zadatak 278</h2><p>Trouglovi ABC i A1B1C1 su osno simetricni. Nacrtaj osu simetrije.</p><p>[Slika]</p><h3>Resenje</h3><p>Osa simetrije je prava koja prolazi kroz srediste duzi koje povezuju odgovarajuca temena trouglova i normalna je na te duzi. Spajamo odgovarajuce tacke (A sa A1, B sa B1, C sa C1) i nalazimo simetrale tih duzi. Sve simetrale se poklapaju - to je osa simetrije.</p><p><strong>Odgovor:</strong> Osa simetrije je nacrtana na slici.</p>'],

            [42, 279, 'Zadatak 279', '<h2>Zadatak 279</h2><p>Figura se sastoji od 5 podudarnih kruznih isecaka. Koliko osa simetrije ima?</p><h3>Resenje</h3><p>Posto figura ima 5 jednakih delova rasporedenih ravnomerno, ima rotacionu simetriju reda 5.</p><div data-math-block latex="\text{Broj osa simetrije} = 5"></div><p><strong>Odgovor:</strong> Figura ima 5 osa simetrije.</p>'],

            // MERENJE 280-296 (sc=43)
            [43, 280, 'Zadatak 280', '<h2>Zadatak 280</h2><p>Koja kesa ima najmanju masu? Mase kesa: 2 kg 150 g, 2 kg 300 g, 2 kg 250 g, 2 kg 45 g.</p><h3>Resenje</h3><p>Prevedemo sve u grame:</p><div data-math-block latex="2 \text{ kg } 150 \text{ g} = 2150 \text{ g}"></div><div data-math-block latex="2 \text{ kg } 300 \text{ g} = 2300 \text{ g}"></div><div data-math-block latex="2 \text{ kg } 250 \text{ g} = 2250 \text{ g}"></div><div data-math-block latex="2 \text{ kg } 45 \text{ g} = 2045 \text{ g}"></div><p>Najmanja masa je 2045 g.</p><p><strong>Odgovor:</strong> Kesa od 2 kg 45 g ima najmanju masu (2045 g).</p>'],

            [43, 281, 'Zadatak 281', '<h2>Zadatak 281</h2><p>Odredi da li su tvrdnje tacne (T) ili netacne (N):</p><h3>Resenje</h3><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Tvrdnja</th><th>T/N</th></tr></thead><tbody><tr><td>2,5 dm &gt; 2 m 5 dm</td><td>N</td></tr><tr><td>2 m &gt; 22 dm</td><td>N</td></tr><tr><td>3 kg &lt; 300 g</td><td>N</td></tr><tr><td>2 t &gt; 200 kg</td><td>T</td></tr></tbody></table><div data-math-block latex="2{,}5 \text{ dm} = 0{,}25 \text{ m} < 2 \text{ m } 5 \text{ dm} = 2{,}5 \text{ m} \quad \text{N}"></div><div data-math-block latex="2 \text{ m} = 20 \text{ dm} < 22 \text{ dm} \quad \text{N}"></div><div data-math-block latex="3 \text{ kg} = 3000 \text{ g} > 300 \text{ g} \quad \text{N}"></div><div data-math-block latex="2 \text{ t} = 2000 \text{ kg} > 200 \text{ kg} \quad \text{T}"></div><p><strong>Odgovor:</strong> N, N, N, T.</p>'],

            [43, 282, 'Zadatak 282', '<h2>Zadatak 282</h2><p>Uporedi velicine. Stavi znak &lt;, &gt; ili =.</p><h3>Resenje</h3><div data-math-block latex="a) \quad 5 \text{ cm} < 0{,}5 \text{ m} \quad (5 \text{ cm} < 50 \text{ cm})"></div><div data-math-block latex="b) \quad 32 \text{ mm} > 0{,}032 \text{ dm} \quad (32 \text{ mm} > 0{,}32 \text{ mm})"></div><div data-math-block latex="v) \quad 3 \text{ km } 58 \text{ m} < 3{,}58 \text{ km} \quad (3{,}058 \text{ km} < 3{,}58 \text{ km})"></div><div data-math-block latex="g) \quad 2500 \text{ dm} > 0{,}025 \text{ km} \quad (250 \text{ m} > 25 \text{ m})"></div><p><strong>Odgovor:</strong> a) &lt;; b) &gt;; v) &lt;; g) &gt;.</p>'],

            [43, 283, 'Zadatak 283', '<h2>Zadatak 283</h2><p>Sta je najudaljenije? Dati su: prodavnica (3,3 km), skola (3120 m), park (3020 m), biblioteka (3200 m).</p><h3>Resenje</h3><p>Prevedemo sve u metre:</p><div data-math-block latex="3{,}3 \text{ km} = 3300 \text{ m}"></div><div data-math-block latex="3120 \text{ m}"></div><div data-math-block latex="3020 \text{ m}"></div><div data-math-block latex="3200 \text{ m}"></div><p>Najveca vrednost je 3300 m.</p><p><strong>Odgovor:</strong> Prodavnica je najudaljenija (3300 m = 3,3 km).</p>'],

            [43, 284, 'Zadatak 284', '<h2>Zadatak 284</h2><p>Polumaraton ima 21 km. Katarina je 15,4 km od starta, Ivan 15410 m od starta, Milan 5,8 km od cilja. Ko je najblizi cilju?</p><h3>Resenje</h3><p>Udaljenost od cilja:</p><div data-math-block latex="\text{Katarina: } 21 - 15{,}4 = 5{,}6 \text{ km}"></div><div data-math-block latex="\text{Ivan: } 21 - 15{,}41 = 5{,}59 \text{ km}"></div><div data-math-block latex="\text{Milan: } 5{,}8 \text{ km od cilja}"></div><p>Najblizi je Ivan sa 5,59 km od cilja.</p><p><strong>Odgovor:</strong> Ivan je najblizi cilju (5,59 km).</p>'],

            [43, 285, 'Zadatak 285', '<h2>Zadatak 285</h2><p>Ko je imao najveci prinos psenice? Petar: 4700 kg, Marko: 4 522 000 g, Jovan: 4,72 t, Stanko: 4,5 t, Milan: 4 t 650 kg.</p><h3>Resenje</h3><p>Prevedemo sve u kilograme:</p><div data-math-block latex="\text{Petar: } 4700 \text{ kg}"></div><div data-math-block latex="\text{Marko: } 4\,522\,000 \text{ g} = 4522 \text{ kg}"></div><div data-math-block latex="\text{Jovan: } 4{,}72 \text{ t} = 4720 \text{ kg}"></div><div data-math-block latex="\text{Stanko: } 4{,}5 \text{ t} = 4500 \text{ kg}"></div><div data-math-block latex="\text{Milan: } 4 \text{ t } 650 \text{ kg} = 4650 \text{ kg}"></div><p><strong>Odgovor:</strong> Jovanova njiva je imala najveci prinos (4720 kg).</p>'],

            [43, 286, 'Zadatak 286', '<h2>Zadatak 286</h2><p>Mihajlo ima 35 evra i 20 dolara. Kurs: 1 evro = 119 din, 1 dolar = 100 din. Treba mu 7200 din. Koliko mu nedostaje?</p><h3>Resenje</h3><div data-math-block latex="35 \cdot 119 = 4165 \text{ din}"></div><div data-math-block latex="20 \cdot 100 = 2000 \text{ din}"></div><div data-math-block latex="\text{Ukupno: } 4165 + 2000 = 6165 \text{ din}"></div><div data-math-block latex="\text{Nedostaje: } 7200 - 6165 = 1035 \text{ din}"></div><p><strong>Odgovor:</strong> Mihajlu nedostaje 1035 dinara.</p>'],

            [43, 287, 'Zadatak 287', '<h2>Zadatak 287</h2><p>Koliko litara dizela moze da kupi za 15 dolara u SAD (cena 3 dolara za 3,8 l) i u Srbiji (cena 150 din/l, kurs 1 dolar = 100 din)?</p><h3>Resenje</h3><p>U SAD:</p><div data-math-block latex="\frac{15}{3} \cdot 3{,}8 = 5 \cdot 3{,}8 = 19 \text{ l}"></div><p>U Srbiji:</p><div data-math-block latex="15 \cdot 100 = 1500 \text{ din}"></div><div data-math-block latex="\frac{1500}{150} = 10 \text{ l}"></div><p><strong>Odgovor:</strong> U SAD moze da kupi 19 l, a u Srbiji 10 l dizela.</p>'],

            [43, 288, 'Zadatak 288', '<h2>Zadatak 288</h2><p>Berk je zamenio 1500 turskih lira za 15600 dinara. Koliki je kurs? Treba mu jos 9360 dinara. Koliko lira treba da zameni?</p><h3>Resenje</h3><p>Kurs:</p><div data-math-block latex="\text{Kurs} = \frac{15600}{1500} = 10{,}4 \text{ din/lira}"></div><p>Broj lira za 9360 dinara:</p><div data-math-block latex="\frac{9360}{10{,}4} = 900 \text{ lira}"></div><p><strong>Odgovor:</strong> Kurs je 10,4 din/lira. Treba da zameni jos 900 lira.</p>'],

            [43, 289, 'Zadatak 289', '<h2>Zadatak 289</h2><p>Lucija je kupila gitaru za 3120 bosanskih maraka (BN). U menjacnici je 450 evra zamenila za 3150 BN. Koliki je kurs?</p><h3>Resenje</h3><div data-math-block latex="\text{Kurs} = \frac{3150}{450} = 7 \text{ BN po evru}"></div><p><strong>Odgovor:</strong> 1 evro = 7 bosanskih maraka.</p>'],

            [43, 290, 'Zadatak 290', '<h2>Zadatak 290</h2><p>Djordje menja 16000 din direktno u forinte po kursu 0,32 din/HUF. Dimitrije menja 16000 din u evre (kurs 118,5 din/EUR) pa evre u forinte (kurs 360 HUF/EUR). Ko je dobio vise?</p><h3>Resenje</h3><p>Djordje:</p><div data-math-block latex="\frac{16000}{0{,}32} = 50000 \text{ HUF}"></div><p>Dimitrije:</p><div data-math-block latex="\frac{16000}{118{,}5} \approx 135 \text{ EUR}"></div><div data-math-block latex="135 \cdot 360 = 48600 \text{ HUF}"></div><p>Razlika:</p><div data-math-block latex="50000 - 48600 = 1400 \text{ HUF}"></div><p><strong>Odgovor:</strong> Djordje je dobio 1400 forinti vise.</p>'],

            [43, 291, 'Zadatak 291', '<h2>Zadatak 291</h2><p>Masa je putovala u Dansku. Let je kostao 100 evra = 11700 din. Zamenila je 35100 din u danske krune (kurs: 1 DKK = 15,6 din). Potrosila je sve osim 150 DKK. U povratku menja 150 DKK po kursu 15,7 din/DKK. Koliko je ukupno potrosila?</p><h3>Resenje</h3><p>Zamena dinara u krune:</p><div data-math-block latex="\frac{35100}{15{,}6} = 2250 \text{ DKK}"></div><p>Potroseno u Danskoj:</p><div data-math-block latex="2250 - 150 = 2100 \text{ DKK}"></div><p>Povrat kruna u dinare:</p><div data-math-block latex="150 \cdot 15{,}7 = 2355 \text{ din}"></div><p>Ukupan trosak:</p><div data-math-block latex="11700 + 35100 - 2355 = 44445 \text{ din}"></div><p><strong>Odgovor:</strong> Masa je ukupno potrosila 44445 dinara.</p>'],

            [43, 292, 'Zadatak 292', '<h2>Zadatak 292</h2><p>Koliko je 3 funte (lb) u kilogramima?</p><h3>Resenje</h3><div data-math-block latex="3 \text{ lb} = 3 \cdot 0{,}45359237 \approx 1{,}36 \text{ kg} \approx 1{,}4 \text{ kg}"></div><p><strong>Odgovor:</strong> 3 funte je priblizno 1,4 kg.</p>'],

            [43, 293, 'Zadatak 293', '<h2>Zadatak 293</h2><p>Odredi da li su tvrdnje tacne (T) ili netacne (N) o zaokruzivanju:</p><h3>Resenje</h3><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Tvrdnja</th><th>T/N</th></tr></thead><tbody><tr><td>109,2 zaokruzeno na ceo broj daje 110</td><td>N (daje 109)</td></tr><tr><td>3,4556 zaokruzeno na jednu decimalu daje 3,5</td><td>T</td></tr><tr><td>499,4 zaokruzeno na ceo broj daje 500</td><td>N (daje 499)</td></tr></tbody></table><p><strong>Odgovor:</strong> N, T, N.</p>'],

            [43, 294, 'Zadatak 294', '<h2>Zadatak 294</h2><p>Na dijagramu je prikazano vreme provedeno na telefonu. Zaokruzi vrednosti na najblizi ceo broj i saberi nedelju i ponedeljak.</p><h3>Resenje</h3><p>a) Zaokruzene vrednosti za nedelju i ponedeljak:</p><div data-math-block latex="\text{Ukupno} \approx 6 \text{ sati}"></div><p>b) Razlika izmedju tacne i zaokruzene vrednosti:</p><div data-math-block latex="\text{Razlika} = 1{,}21 \text{ h}"></div><p><strong>Odgovor:</strong> a) 6 sati; b) razlika je 1,21 h.</p>'],

            [43, 295, 'Zadatak 295', '<h2>Zadatak 295</h2><p>Popuni tabelu zaokruzivanja korenova.</p><h3>Resenje</h3><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Broj</th><th>6 decimala</th><th>2 decimale</th><th>Ceo broj</th></tr></thead><tbody><tr><td>koren iz 5</td><td>2,236068</td><td>2,24</td><td>2</td></tr><tr><td>koren iz 56</td><td>7,483315</td><td>7,48</td><td>7</td></tr><tr><td>koren iz 567</td><td>23,811762</td><td>23,81</td><td>24</td></tr><tr><td>koren iz 5678</td><td>75,353170</td><td>75,35</td><td>75</td></tr></tbody></table><div data-math-block latex="\sqrt{5} \approx 2{,}24 \approx 2"></div><div data-math-block latex="\sqrt{56} \approx 7{,}48 \approx 7"></div><div data-math-block latex="\sqrt{567} \approx 23{,}81 \approx 24"></div><div data-math-block latex="\sqrt{5678} \approx 75{,}35 \approx 75"></div><p><strong>Odgovor:</strong> Tabela je popunjena kao sto je prikazano.</p>'],

            [43, 296, 'Zadatak 296', '<h2>Zadatak 296</h2><p>Izmedju koja dva uzastopna cela broja se nalaze sledeci korenovi?</p><h3>Resenje</h3><div data-math-block latex="a) \quad 6 < \sqrt{40} < 7 \quad (36 < 40 < 49)"></div><div data-math-block latex="b) \quad 11 < \sqrt{125} < 12 \quad (121 < 125 < 144)"></div><div data-math-block latex="v) \quad 24 < \sqrt{620} < 25 \quad (576 < 620 < 625)"></div><div data-math-block latex="g) \quad 30 < \sqrt{901} < 31 \quad (900 < 901 < 961)"></div><p><strong>Odgovor:</strong> a) 6 i 7; b) 11 i 12; v) 24 i 25; g) 30 i 31.</p>'],

            // OBRADA PODATAKA 297-321 (sc=44)
            [44, 297, 'Zadatak 297', '<h2>Zadatak 297</h2><p>Data je tacka A(4, 2). Tacka B je simetricna tacki A u odnosu na x-osu. Tacka C je simetricna tacki B u odnosu na y-osu. Odredi koordinate tacaka B i C.</p><h3>Resenje</h3><p>Simetrija u odnosu na x-osu menja znak y-koordinate:</p><div data-math-block latex="A(4, 2) \xrightarrow{Ox} B(4, -2)"></div><p>Simetrija u odnosu na y-osu menja znak x-koordinate:</p><div data-math-block latex="B(4, -2) \xrightarrow{Oy} C(-4, -2)"></div><p><strong>Odgovor:</strong> B(4, -2), C(-4, -2).</p>'],

            [44, 298, 'Zadatak 298', '<h2>Zadatak 298</h2><p>Pravougaonik ABCD ima presek dijagonala u tacki S. Odredi koordinate tacke S.</p><h3>Resenje</h3><p>Presek dijagonala pravougaonika je u sredini obe dijagonale. Na osnovu koordinata temena:</p><div data-math-block latex="S = \left(\frac{x_A + x_C}{2}, \frac{y_A + y_C}{2}\right)"></div><div data-math-block latex="S(-2, -1)"></div><p><strong>Odgovor:</strong> S(-2, -1).</p>'],

            [44, 299, 'Zadatak 299', '<h2>Zadatak 299</h2><p>Tacke A1(-3, 4) i A2(3, 4) su centralno simetricne. a) Nacrtaj ose. b) Odredi A3 i A4 - centralno simetricne tacke u odnosu na koordinatni pocetak.</p><h3>Resenje</h3><p>a) Centar simetrije je sredina duzi A1A2: (0, 4).</p><p>b) Centralna simetrija u odnosu na koordinatni pocetak menja znak obe koordinate:</p><div data-math-block latex="A_3(-3, -4), \quad A_4(3, 4)"></div><p><strong>Odgovor:</strong> A3(-3, -4), A4(3, 4).</p>'],

            [44, 300, 'Zadatak 300', '<h2>Zadatak 300</h2><p>Izlomljena linija ABCD se preslikava osnom simetrijom u odnosu na x-osu, a zatim centralnom simetrijom. Odredi koordinate.</p><h3>Resenje</h3><p>Prvo preslikavamo svaku tacku u odnosu na x-osu (menja se znak y-koordinate), a zatim centralnom simetrijom (menjaju se znaci obe koordinate).</p><p><strong>Odgovor:</strong> Koordinate se odredjuju na osnovu slike primenom navedenih transformacija.</p>'],

            [44, 301, 'Zadatak 301', '<h2>Zadatak 301</h2><p>Tacka A ima koordinate (4, 0). Ugao kod tacke A je 60°. Odredi koordinate tacke B.</p><h3>Resenje</h3><p>Ako je ugao 60° kod A(4, 0) i B je na y-osi:</p><div data-math-block latex="\tan 60° = \sqrt{3}"></div><div data-math-block latex="B_y = 4 \cdot \tan 60° = 4\sqrt{3}"></div><div data-math-block latex="B(0, 4\sqrt{3})"></div><p><strong>Odgovor:</strong> B(0, 4 koren iz 3).</p>'],

            [44, 302, 'Zadatak 302', '<h2>Zadatak 302</h2><p>Prava AB se preslikava osnom simetrijom u odnosu na y-osu u pravu AB\'. Gde se seku AB i AB\'?</p><h3>Resenje</h3><p>Presek pravih koje su simetricne u odnosu na y-osu lezi na y-osi (x = 0).</p><div data-math-block latex="\text{Presek: } (0, 1)"></div><p><strong>Odgovor:</strong> Tacka preseka je (0, 1).</p>'],

            [44, 303, 'Zadatak 303', '<h2>Zadatak 303</h2><p>Date su tacke A1(5, 0) i B1(-2, 1). Cetvorougao AB1BA1 je kakav?</p><h3>Resenje</h3><p>Na osnovu koordinata tacaka i osobina cetvorougla:</p><div data-math-block latex="A_1(5, 0), \quad B_1(-2, 1)"></div><p>Cetvorougao AB1BA1 ima jedan par paralelnih stranica.</p><p><strong>Odgovor:</strong> Cetvorougao AB1BA1 je trapez.</p>'],

            [44, 304, 'Zadatak 304', '<h2>Zadatak 304</h2><p>Data je tacka A(2, 4). Tacka B je simetricna u odnosu na pravu y = x. Tacka C je simetricna tacki A u odnosu na x-osu. Tacka D je simetricna tacki A u odnosu na tacku M(5, 3). Odredi koordinate.</p><h3>Resenje</h3><p>Simetrija u odnosu na y = x zamenjuje koordinate:</p><div data-math-block latex="A(2, 4) \xrightarrow{y=x} B(4, 2)"></div><p>Simetrija u odnosu na x-osu:</p><div data-math-block latex="A(2, 4) \xrightarrow{Ox} C(2, -4)"></div><p>Centralna simetrija u odnosu na M(5, 3):</p><div data-math-block latex="D = (2 \cdot 5 - 2, 2 \cdot 3 - 4) = (8, 2)"></div><p><strong>Odgovor:</strong> A(2, 4), B(4, 2), C(2, -4), D(8, 2).</p>'],

            [44, 305, 'Zadatak 305', '<h2>Zadatak 305</h2><p>Visnja je imala 10 ocena sa prosekom 3,4. Dobila je jos 2 ocene i prosek je porastao za 0,1. Koliki je zbir dve nove ocene?</p><h3>Resenje</h3><p>Ukupan zbir prvih 10 ocena:</p><div data-math-block latex="10 \cdot 3{,}4 = 34"></div><p>Novi prosek sa 12 ocena:</p><div data-math-block latex="3{,}4 + 0{,}1 = 3{,}5"></div><p>Ukupan zbir svih 12 ocena:</p><div data-math-block latex="12 \cdot 3{,}5 = 42"></div><p>Zbir dve nove ocene:</p><div data-math-block latex="42 - 34 = 8"></div><p><strong>Odgovor:</strong> Zbir dve nove ocene je 8.</p>'],

            [44, 306, 'Zadatak 306', '<h2>Zadatak 306</h2><p>Na dijagramu je prikazana prodaja sokova iz 4 aparata. Izracunaj prosek po vrsti soka.</p><h3>Resenje</h3><p>Na osnovu dijagrama, sabiramo prodaju svakog soka iz svih aparata i delimo sa 4 da dobijemo prosek.</p><p><strong>Odgovor:</strong> Prosecna prodaja po vrsti soka je data na osnovu podataka sa dijagrama.</p>'],

            [44, 307, 'Zadatak 307', '<h2>Zadatak 307</h2><p>Izracunaj prosecno trajanje 6 filmova cije su duzine: 88, 86, 83, 107, 92, 102 minuta.</p><h3>Resenje</h3><div data-math-block latex="\bar{x} = \frac{88 + 86 + 83 + 107 + 92 + 102}{6} = \frac{558}{6} = 93 \text{ min}"></div><p><strong>Odgovor:</strong> Prosecno trajanje filma je 93 minuta.</p>'],

            [44, 308, 'Zadatak 308', '<h2>Zadatak 308</h2><p>Na dijagramu su prikazane cene bombona. a) Koje dve kutije imaju istu masu? b) Koja kutija ima najnizu cenu po kilogramu? v) Koje kutije imaju istu cenu po kilogramu?</p><h3>Resenje</h3><p>Na osnovu dijagrama:</p><p>a) Kutije P1 i P4 imaju istu masu.</p><p>b) Kutija P4 ima najnizu cenu po kilogramu.</p><p>v) Kutije P1 i P2 imaju istu cenu po kilogramu.</p><p><strong>Odgovor:</strong> a) P1 i P4; b) P4; v) P1 i P2.</p>'],

            [44, 309, 'Zadatak 309', '<h2>Zadatak 309</h2><p>Na stubicastom dijagramu su prikazani rezultati 8 ucenika. Izracunaj prosek i koliko ucenika ima rezultat iznad proseka.</p><h3>Resenje</h3><div data-math-block latex="\bar{x} = \frac{100 + 65 + 70 + 55 + 48 + 87 + 44 + 75}{8} = \frac{544}{8} = 68"></div><p>Ucenici iznad proseka (68): 100, 70, 87, 75.</p><p><strong>Odgovor:</strong> Prosek je 68. Cetiri ucenika imaju rezultat iznad proseka.</p>'],

            [44, 310, 'Zadatak 310', '<h2>Zadatak 310</h2><p>Prodaja kolaca tokom 4 dana. a) Koja vrsta kolaca se najvise prodala? b) Prosecna prodaja? v) Ukupna zarada?</p><h3>Resenje</h3><p>a) Cokoladni kolac se najvise prodao.</p><p>b) Prosecna prodaja:</p><div data-math-block latex="\bar{x} = 9{,}25"></div><p>v) Ukupna zarada:</p><div data-math-block latex="\text{Zarada} = 15900 \text{ din}"></div><p><strong>Odgovor:</strong> a) Cokoladni kolac; b) prosecna prodaja je 9,25; v) ukupna zarada je 15900 din.</p>'],

            [44, 311, 'Zadatak 311', '<h2>Zadatak 311</h2><p>Veljkov prihod i rashod tokom 4 meseca. a) Kada je bio najveci prihod? b) Kada je najvise ustedio? v) Da li je prosecni prihod veci od prosecnog rashoda?</p><h3>Resenje</h3><p>a) U aprilu je bio najveci prihod.</p><p>b) U januaru je najvise ustedio:</p><div data-math-block latex="\text{Usteda (januar)} = 25000 \text{ din}"></div><p>v) Da, prosecni prihod je veci od prosecnog rashoda:</p><div data-math-block latex="\text{Razlika} = 12500 \text{ din}"></div><p><strong>Odgovor:</strong> a) April; b) januar (25000 din); v) da, za 12500 din.</p>'],

            [44, 312, 'Zadatak 312', '<h2>Zadatak 312</h2><p>Medijana niza je 18. Dati podaci: 20, 13, 17, 15, 25, ?. Koji broj nedostaje?</p><h3>Resenje</h3><p>Sortiramo poznate podatke: 13, 15, 17, 20, 25. Sa nepoznatim brojem x, niz ima 6 elemenata. Medijana je prosek 3. i 4. elementa.</p><p>Da bi medijana bila 18, prosek dva srednja broja mora biti 18:</p><div data-math-block latex="\frac{a_3 + a_4}{2} = 18 \implies a_3 + a_4 = 36"></div><p>Ako je x = 19, sortiran niz: 13, 15, 17, 19, 20, 25:</p><div data-math-block latex="\frac{17 + 19}{2} = 18 \quad \checkmark"></div><p><strong>Odgovor:</strong> Nedostajuci broj je 19.</p>'],

            [44, 313, 'Zadatak 313', '<h2>Zadatak 313</h2><p>Date su visine 10 devojcica. Popuni tabelu i odredi medijanu.</p><h3>Resenje</h3><p>Sortiramo visine od najmanje do najvece i nalazimo prosek 5. i 6. vrednosti:</p><div data-math-block latex="\text{Medijana} = 151 \text{ cm}"></div><p><strong>Odgovor:</strong> Medijana visina je 151 cm.</p>'],

            [44, 314, 'Zadatak 314', '<h2>Zadatak 314</h2><p>Anketa o broju casa vode dnevno. a) Odredi medijanu. b) Izracunaj prosek.</p><h3>Resenje</h3><p>a) Medijana:</p><div data-math-block latex="\text{Medijana} = 6"></div><p>b) Prosek:</p><div data-math-block latex="\bar{x} = 5{,}84"></div><p><strong>Odgovor:</strong> a) Medijana je 6; b) prosek je 5,84.</p>'],

            [44, 315, 'Zadatak 315', '<h2>Zadatak 315</h2><p>Internet prodavnica dobija ocene od 1 do 10 od 10 korisnika. Odredi medijanu.</p><h3>Resenje</h3><p>Sortiramo ocene i nalazimo prosek 5. i 6. vrednosti:</p><div data-math-block latex="\text{Medijana} = 7{,}5"></div><p><strong>Odgovor:</strong> Medijana ocena je 7,5.</p>'],

            [44, 316, 'Zadatak 316', '<h2>Zadatak 316</h2><p>8 ucenika je citalo knjige. Izracunaj prosek i medijanu.</p><h3>Resenje</h3><div data-math-block latex="\bar{x} = 4"></div><div data-math-block latex="\text{Medijana} = 3"></div><p><strong>Odgovor:</strong> Prosek je 4, medijana je 3.</p>'],

            [44, 317, 'Zadatak 317', '<h2>Zadatak 317</h2><p>Od 80 ucenika, 40 je procitalo prvu knjigu, 50 drugu, 10 nijednu. Koliki procenat je procitao obe?</p><h3>Resenje</h3><p>Ukupno koji su citali bar jednu knjigu: 80 - 10 = 70.</p><p>Primenom formule ukljucivanja-iskljucivanja:</p><div data-math-block latex="|A \cup B| = |A| + |B| - |A \cap B|"></div><div data-math-block latex="70 = 40 + 50 - |A \cap B|"></div><div data-math-block latex="|A \cap B| = 20"></div><p>Procenat:</p><div data-math-block latex="\frac{20}{80} \cdot 100\% = 25\%"></div><p><strong>Odgovor:</strong> 25% ucenika je procitalo obe knjige.</p>'],

            [44, 318, 'Zadatak 318', '<h2>Zadatak 318</h2><p>Lena tvrdi da je x% od A jednako A% od x. Da li je u pravu?</p><h3>Resenje</h3><div data-math-block latex="x\% \text{ od } A = \frac{x}{100} \cdot A = \frac{xA}{100}"></div><div data-math-block latex="A\% \text{ od } x = \frac{A}{100} \cdot x = \frac{Ax}{100}"></div><div data-math-block latex="\frac{xA}{100} = \frac{Ax}{100} \quad \checkmark"></div><p><strong>Odgovor:</strong> Da, Lena je u pravu. Obe vrednosti su jednake.</p>'],

            [44, 319, 'Zadatak 319', '<h2>Zadatak 319</h2><p>Gitara A kosta 114500 din, gitara B kosta 98300 din. Ako je cena veca od 100000 din, dobija se 15% popusta. Koja je jeftinija i za koliko?</p><h3>Resenje</h3><p>Gitara A dobija popust jer kosta vise od 100000 din:</p><div data-math-block latex="A = 114500 \cdot 0{,}85 = 97325 \text{ din}"></div><p>Gitara B kosta 98300 din (nema popust jer je ispod 100000 din).</p><p>Razlika:</p><div data-math-block latex="98300 - 97325 = 975 \text{ din}"></div><p><strong>Odgovor:</strong> Gitara A je jeftinija za 975 dinara (posle popusta).</p>'],

            [44, 320, 'Zadatak 320', '<h2>Zadatak 320</h2><p>U Beogradu je 95 dana temperatura bila iznad 25°C, a 27 dana je padao sneg. Koliki procenat dana u godini je padao sneg?</p><h3>Resenje</h3><div data-math-block latex="\frac{27}{365} \cdot 100\% \approx 7{,}4\%"></div><p>Posto je 7,4% izmedju 5% i 10%:</p><p><strong>Odgovor:</strong> Sneg je padao vise od 5% ali manje od 10% dana u godini (priblizno 7,4%).</p>'],

            [44, 321, 'Zadatak 321', '<h2>Zadatak 321</h2><p>Marko je odgledao 12% filma i ostalo mu je jos 110 minuta. Koliko traje ceo film?</p><h3>Resenje</h3><p>Ako je odgledao 12%, preostalo je 88% filma:</p><div data-math-block latex="88\% = 110 \text{ min}"></div><div data-math-block latex="100\% = \frac{110}{0{,}88} = 125 \text{ min}"></div><p><strong>Odgovor:</strong> Film traje 125 minuta.</p>'],
        ];

        foreach ($tasks as [$sc, $order, $title, $content]) {
            if (Lesson::where('course_id', 11)->where('title', $title)->exists()) continue;
            Lesson::create([
                'course_id' => 11,
                'subchapter_id' => $sc,
                'title' => $title,
                'order' => $order,
                'is_assignment' => false,
                'content' => $content,
            ]);
        }

        echo "Done!\n";
    }
}
