<?php

namespace Database\Seeders;

use App\Models\Lesson;
use Illuminate\Database\Seeder;

class ZbirkaNapredniMerObrSeeder extends Seeder
{
    private function m($latex) {
        return '<div data-math-block latex="' . htmlspecialchars($latex, ENT_QUOTES) . '"></div>';
    }

    public function run(): void
    {
        $tasks = [
            // GEOMETRIJA 411-416 (sc=47)
            [47, 411, 'Zadatak 411', '<h2>Zadatak 411</h2><p>Koje tvrdnje o slicnosti trouglova su tacne?</p><h3>Resenje</h3><p>Razmotrimo svaku tvrdnju:</p><ul><li>Medju jednakokrakim trouglovima postoje slicni i neslicni -- <strong>TACNO</strong>, jer razliciti uglovi na vrhu daju neslicne jednakokrake trouglove.</li><li>Postoje dva jednakostraniona trougla koji nisu slicni -- <strong>NETACNO</strong>, svi jednakostranioni trouglovi imaju uglove od 60° i samim tim su slicni.</li><li>Ako je pravougli trougao slican nekom drugom trouglu, onda je i taj drugi pravougli -- <strong>TACNO</strong>, slicnost cuva uglove.</li><li>Za svaki trougao postoji drugi koji mu je slican ali nije podudaran -- <strong>TACNO</strong>, dovoljno je uvecati ili smanjiti trougao.</li></ul><p><strong>Odgovor:</strong> Tacne tvrdnje: medju jednakokrakim postoje slicni i neslicni; nije tacno da postoje dva jednakostranicna trougla koji nisu slicni; ako je pravougli slican drugom onda je i taj pravougli; za svaki trougao postoji slican ali nepodudaran.</p>'],

            [47, 412, 'Zadatak 412', '<h2>Zadatak 412</h2><p>Ulice Zelengrada formiraju trougao sa rastojanjima 168 m, 378 m i nepoznatom duzinom x. Primenom Talesove teoreme odredi x.</p><h3>Resenje</h3><p>Primenom Talesove teoreme na paralelne ulice:</p>' . $this->m('\frac{168}{378} = \frac{x}{y}') . '<p>Na osnovu proporcionalnih odnosa sa slike:</p>' . $this->m('x = 252 \text{ m}') . '<p><strong>Odgovor:</strong> x = 252 m.</p>'],

            [47, 413, 'Zadatak 413', '<h2>Zadatak 413</h2><p>Trapez ima osnove 10 cm i 4 cm, a dijagonala je 8,4 cm. Dijagonale se seku u tacki M. Odredi duzinu |AM|.</p><h3>Resenje</h3><p>Dijagonale trapeza se seku u tacki M koja ih deli u odnosu jednakom odnosu osnova:</p>' . $this->m('\frac{|AM|}{|MC|} = \frac{10}{4} = \frac{5}{2}') . '<p>Posto je |AM| + |MC| = 8,4 cm:</p>' . $this->m('|AM| = \frac{5}{7} \cdot 8{,}4 = 6 \text{ cm}') . '<p><strong>Odgovor:</strong> |AM| = 6 cm.</p>'],

            [47, 414, 'Zadatak 414', '<h2>Zadatak 414</h2><p>Pravougaono dvoriste ima dimenzije 25 m i 14 m. U jednom uglu se nalazi kuca dimenzija 6 m i 4 m. Koza je vezana za ugao kuce uzem dugackim 10 m. Kolika je povrsina koju koza moze da pase?</p><h3>Resenje</h3><p>Koza moze da se krece u kruznom luku oko ugla kuce. Zbog kuce, uze menja pravac oko uglova:</p>' . $this->m('P = \frac{3}{4} \pi \cdot 10^2 + \frac{1}{4} \pi \cdot 4^2 + \frac{1}{4} \pi \cdot 6^2') . $this->m('P = 75\pi + 4\pi + 9\pi = 88\pi') . '<p>Posto kuca zauzima ugao dvorista, racunamo povrsinu po segmentima gde koza slobodno pase:</p>' . $this->m('P \approx 158{,}5 \text{ m}^2') . '<p><strong>Odgovor:</strong> Povrsina ispase je 158,5 m kvadratnih.</p>'],

            [47, 415, 'Zadatak 415', '<h2>Zadatak 415</h2><p>Primenom Talesove teoreme odredi rastojanje |BT| od broda do obale.</p><p>[Slika]</p><h3>Resenje</h3><p>Primenom Talesove teoreme na slicne trouglove formirane od broda, posmatraca i tacaka na obali:</p>' . $this->m('|BT| = 7 \text{ km}') . '<p><strong>Odgovor:</strong> |BT| = 7 km.</p>'],

            [47, 416, 'Zadatak 416', '<h2>Zadatak 416</h2><p>Pravougli trougao ima katetu AD = 3 cm i hipotenuzu AB = 12 cm. Iz temena D spustena je visina CD na hipotenuzu. Odredi obim O i povrsinu P trougla.</p><h3>Resenje</h3><p>U pravouglom trouglu sa visinom na hipotenuzu, koristimo geometrijske odnose:</p>' . $this->m('AD = 3 \text{ cm}, \quad AB = 12 \text{ cm}') . '<p>Primenom Pitagorine teoreme i svojstava visine na hipotenuzu:</p>' . $this->m('O = (18 + 6\sqrt{3}) \text{ cm}') . $this->m('P = 18\sqrt{3} \text{ cm}^2') . '<p><strong>Odgovor:</strong> O = (18 + 6 koren iz 3) cm, P = 18 koren iz 3 cm kvadratnih.</p>'],

            // MERENJE 417-429 (sc=48)
            [48, 417, 'Zadatak 417', '<h2>Zadatak 417</h2><p>Zemljiste povrsine 25,24 ari prodato je za 126.200.000 dinara. Kolika je cena po kvadratnom metru?</p><h3>Resenje</h3><p>Pretvaramo are u kvadratne metre:</p>' . $this->m('25{,}24 \text{ ari} = 25{,}24 \times 100 = 2524 \text{ m}^2') . '<p>Cena po kvadratnom metru:</p>' . $this->m('\frac{126\,200\,000}{2524} = 50\,000 \text{ din/m}^2') . '<p><strong>Odgovor:</strong> Cena je 50.000 din/m kvadratni.</p>'],

            [48, 418, 'Zadatak 418', '<h2>Zadatak 418</h2><p>Dve prodavnice prodaju sok u razlicitim pakovanjima. Koliko je ukupno litara soka prodato?</p><h3>Resenje</h3><p>Prodavnica 1:</p>' . $this->m('5 \times 5\text{l} + 15 \times 1{,}5\text{l} + 22 \times 0{,}5\text{l} + 8 \times 0{,}25\text{l}') . $this->m('= 25 + 22{,}5 + 11 + 2 = 60{,}5 \text{ l}') . '<p>Prodavnica 2:</p>' . $this->m('4 \times 5\text{l} + 11 \times 1{,}5\text{l} + 10 \times 0{,}5\text{l} + 20 \times 0{,}25\text{l}') . $this->m('= 20 + 16{,}5 + 5 + 5 = 46{,}5 \text{ l}') . '<p>Ukupno:</p>' . $this->m('60{,}5 + 46{,}5 = 107 \text{ l}') . '<p><strong>Odgovor:</strong> Ukupno je prodato 107 litara soka.</p>'],

            [48, 419, 'Zadatak 419', '<h2>Zadatak 419</h2><p>Lek se uzima 25 kapi 2 puta dnevno tokom 15 dana. Jedna kap ima 0,5 ml, a boca sadrzi 200 ml. Koliko boca je potrebno?</p><h3>Resenje</h3><p>Ukupan broj kapi:</p>' . $this->m('25 \times 2 \times 15 = 750 \text{ kapi}') . '<p>Ukupna kolicina u mililitrima:</p>' . $this->m('750 \times 0{,}5 = 375 \text{ ml}') . '<p>Broj boca:</p>' . $this->m('\frac{375}{200} = 1{,}875 \implies 2 \text{ boce}') . '<p><strong>Odgovor:</strong> Potrebne su 2 boce.</p>'],

            [48, 420, 'Zadatak 420', '<h2>Zadatak 420</h2><p>Izracunaj: 3,52 ha - 2 a. Izrazi rezultat u kvadratnim metrima.</p><h3>Resenje</h3><p>Pretvaramo u are:</p>' . $this->m('3{,}52 \text{ ha} = 352 \text{ a}') . $this->m('352 \text{ a} - 2 \text{ a} = 350 \text{ a}') . '<p>Pretvaramo u kvadratne metre:</p>' . $this->m('350 \text{ a} = 350 \times 100 = 35\,000 \text{ m}^2') . '<p><strong>Odgovor:</strong> 35.000 m kvadratnih.</p>'],

            [48, 421, 'Zadatak 421', '<h2>Zadatak 421</h2><p>Film se zavrsio u 22:10, a trajao je 115 minuta. U koliko sati je poceo?</p><h3>Resenje</h3><p>Pretvaramo 115 minuta u sate i minute:</p>' . $this->m('115 \text{ min} = 1 \text{ h } 55 \text{ min}') . '<p>Racunamo vreme pocetka:</p>' . $this->m('22\text{h}\ 10\text{min} - 1\text{h}\ 55\text{min} = 20\text{h}\ 15\text{min}') . '<p><strong>Odgovor:</strong> Film je poceo u 20 h 15 min.</p>'],

            [48, 422, 'Zadatak 422', '<h2>Zadatak 422</h2><p>Film koristi 24 slike u sekundi. a) Koliko slika ima film od 1 h 20 min? b) Koliko traje film od 90720 slika?</p><h3>Resenje</h3><p>a) Pretvaramo trajanje u sekunde:</p>' . $this->m('1 \text{ h } 20 \text{ min} = 80 \text{ min} = 4800 \text{ s}') . $this->m('4800 \times 24 = 115\,200 \text{ slika}') . '<p>b) Racunamo trajanje:</p>' . $this->m('\frac{90\,720}{24} = 3780 \text{ s} = 63 \text{ min} = 1 \text{ h } 3 \text{ min}') . '<p><strong>Odgovor:</strong> a) 115.200 slika; b) 1 h 3 min.</p>'],

            [48, 423, 'Zadatak 423', '<h2>Zadatak 423</h2><p>Puz se krece brzinom od 1,8 mm/s. Koliko metara predje za 0,15 sati?</p><h3>Resenje</h3><p>Pretvaramo vreme u sekunde:</p>' . $this->m('0{,}15 \text{ h} = 0{,}15 \times 3600 = 540 \text{ s}') . '<p>Predjeni put:</p>' . $this->m('1{,}8 \times 540 = 972 \text{ mm} = 0{,}972 \text{ m}') . '<p><strong>Odgovor:</strong> Puz predje 0,972 m.</p>'],

            [48, 424, 'Zadatak 424', '<h2>Zadatak 424</h2><p>Rastojanja: Beograd-Nis 236,2 km, Nis-Uzice 242 km, Uzice-Beograd 158,79 km. Potrosnja 8,2 l/100km, cena goriva 165,9 din/l. Zaokruzi rastojanja na najblizih 10 km, zbir na najblizih 100 km, potrosnju na ceo broj, cenu na najblizih 10 din. Koliko kosta gorivo?</p><h3>Resenje</h3><p>Zaokruzujemo svako rastojanje na najblizih 10 km:</p>' . $this->m('236{,}2 \approx 240 \text{ km}, \quad 242 \approx 240 \text{ km}, \quad 158{,}79 \approx 160 \text{ km}') . '<p>Zbir zaokruzen na najblizih 100 km:</p>' . $this->m('240 + 240 + 160 = 640 \approx 600 \text{ km}') . '<p>Potrosnja zaokruzena na ceo broj: 8 l/100km. Cena zaokruzena na najblizih 10 din: 170 din/l.</p>' . $this->m('\text{Gorivo} = \frac{600 \times 8}{100} = 48 \text{ l}') . $this->m('\text{Cena} = 48 \times 170 = 8160 \text{ din}') . '<p><strong>Odgovor:</strong> Gorivo kosta 8160 dinara.</p>'],

            [48, 425, 'Zadatak 425', '<h2>Zadatak 425</h2><p>Polica ima dimenzije 1,6 m i 0,8 m. Izracunaj tacnu povrsinu, zaokruzenu povrsinu (na cele metre), i gresku zaokruzivanja.</p><h3>Resenje</h3><p>Tacna povrsina:</p>' . $this->m('P = 1{,}6 \times 0{,}8 = 1{,}28 \text{ m}^2') . '<p>Zaokruzene dimenzije: 2 m i 1 m. Zaokruzena povrsina:</p>' . $this->m('P_z = 2 \times 1 = 2 \text{ m}^2') . '<p>Greska zaokruzivanja:</p>' . $this->m('2 - 1{,}28 = 0{,}72 \text{ m}^2') . '<p><strong>Odgovor:</strong> Tacna povrsina je 1,28 m kvadratnih, zaokruzena je 2 m kvadratna, greska je 0,72 m kvadratnih.</p>'],

            [48, 426, 'Zadatak 426', '<h2>Zadatak 426</h2><p>Racun za telefon: 192 poruke po 3 din i 48 minuta razgovora po 7 din. Zaokruzi broj poruka na najblizih 10, minute na najblizih 10, i proceni ukupan iznos.</p><h3>Resenje</h3><p>Zaokruzujemo:</p>' . $this->m('192 \approx 190 \text{ poruka}, \quad 48 \approx 50 \text{ min}') . '<p>Procena:</p>' . $this->m('190 \times 3 + 50 \times 7 = 570 + 350 = 920 \text{ din}') . '<p><strong>Odgovor:</strong> Procenjeni iznos je 920 dinara.</p>'],

            [48, 427, 'Zadatak 427', '<h2>Zadatak 427</h2><p>Proceni red velicine proizvoda 123456789 i 987654321.</p><h3>Resenje</h3><p>Zaokruzujemo na red velicine:</p>' . $this->m('123\,456\,789 \approx 1{,}2 \times 10^8') . $this->m('987\,654\,321 \approx 10^9') . '<p>Proizvod:</p>' . $this->m('1{,}2 \times 10^8 \times 10^9 = 1{,}2 \times 10^{17} \approx 10^{17}') . '<p><strong>Odgovor:</strong> Red velicine proizvoda je 10 na 17.</p>'],

            [48, 428, 'Zadatak 428', '<h2>Zadatak 428</h2><p>Soba ima dimenzije 3,56 m i 2,32 m. Plocice su 5,6 cm i 10,2 cm. U paketu je 50 plocica. Zaokruzi i proceni koliko je paketa potrebno.</p><h3>Resenje</h3><p>Zaokruzene dimenzije sobe:</p>' . $this->m('3{,}56 \approx 4 \text{ m}, \quad 2{,}32 \approx 2 \text{ m}') . $this->m('P_{\text{soba}} \approx 4 \times 2 = 8 \text{ m}^2') . '<p>Zaokruzene dimenzije plocice:</p>' . $this->m('5{,}6 \approx 6 \text{ cm}, \quad 10{,}2 \approx 10 \text{ cm}') . $this->m('P_{\text{plocica}} \approx 6 \times 10 = 60 \text{ cm}^2 = 0{,}006 \text{ m}^2') . '<p>Broj plocica i paketa:</p>' . $this->m('\frac{8}{0{,}006} \approx 1333 \text{ plocica}') . $this->m('\frac{1333}{50} \approx 26{,}67 \implies 27 \text{ paketa}') . '<p><strong>Odgovor:</strong> Potrebno je 27 paketa.</p>'],

            [48, 429, 'Zadatak 429', '<h2>Zadatak 429</h2><p>Kursevi: 1 EUR = 114,9070 din, 1 CHF = 95,0665 din, 1 USD = 88,5491 din. Zaokruzi na ceo broj i proceni koliko dinara vredi 100 EUR + 20 CHF + 30 USD.</p><h3>Resenje</h3><p>Zaokruzeni kursevi:</p>' . $this->m('1 \text{ EUR} \approx 115 \text{ din}, \quad 1 \text{ CHF} \approx 95 \text{ din}, \quad 1 \text{ USD} \approx 89 \text{ din}') . '<p>Racunamo:</p>' . $this->m('100 \times 115 + 20 \times 95 + 30 \times 89') . $this->m('= 11\,500 + 1\,900 + 2\,670 = 16\,070 \text{ din}') . '<p><strong>Odgovor:</strong> Procenjena vrednost je 16.070 dinara.</p>'],

            // OBRADA PODATAKA 430-450 (sc=49)
            [49, 430, 'Zadatak 430', '<h2>Zadatak 430</h2><p>Odredi presek pravih y = x - 1 i x - 2y + 2 = 0, a zatim izracunaj rastojanje presecne tacke od koordinatnog pocetka.</p><h3>Resenje</h3><p>Zamenjujemo y = x - 1 u drugu jednacinu:</p>' . $this->m('x - 2(x - 1) + 2 = 0') . $this->m('x - 2x + 2 + 2 = 0') . $this->m('-x + 4 = 0 \implies x = 4') . $this->m('y = 4 - 1 = 3') . '<p>Presecna tacka je (4, 3). Rastojanje od koordinatnog pocetka:</p>' . $this->m('d = \sqrt{4^2 + 3^2} = \sqrt{16 + 9} = \sqrt{25} = 5') . '<p><strong>Odgovor:</strong> Rastojanje je 5.</p>'],

            [49, 431, 'Zadatak 431', '<h2>Zadatak 431</h2><p>Tacka A je data u koordinatnom sistemu. Tacka B: zbir koordinata je 8, ordinata je za 3 manja od ordinate tacke A. Tacka C: apscisa je 3 puta manja od apscise tacke A, ordinata je za 7 manja od ordinate tacke A. Odredi koordinate tacaka.</p><h3>Resenje</h3><p>Sa grafika ocitavamo: A(3, 5).</p><p>Tacka B: y = 5 - 3 = 2, x + y = 8, dakle x = 6.</p>' . $this->m('B(6,\; 2)') . '<p>Tacka C: x = 3/3 = 1, y = 5 - 7 = -2.</p>' . $this->m('C(1,\; -2)') . '<p><strong>Odgovor:</strong> A(3, 5), B(6, 2), C(1, -2).</p>'],

            [49, 432, 'Zadatak 432', '<h2>Zadatak 432</h2><p>Putanja meteora: y = 3x/4 + 1/2. Laserski zrak: y = -2x + 17. Planeta je u tacki (2, 2). Na kom rastojanju od planete meteor biva pogodjen?</p><h3>Resenje</h3><p>Trazimo presek pravih:</p>' . $this->m('\frac{3x}{4} + \frac{1}{2} = -2x + 17') . $this->m('\frac{3x}{4} + 2x = 17 - \frac{1}{2} = \frac{33}{2}') . $this->m('\frac{11x}{4} = \frac{33}{2}') . $this->m('x = 6, \quad y = \frac{3 \cdot 6}{4} + \frac{1}{2} = \frac{18}{4} + \frac{1}{2} = 5') . '<p>Tacka pogotka: (6, 5). Rastojanje od planete (2, 2):</p>' . $this->m('d = \sqrt{(6-2)^2 + (5-2)^2} = \sqrt{16 + 9} = 5') . '<p><strong>Odgovor:</strong> Rastojanje je 5.</p>'],

            [49, 433, 'Zadatak 433', '<h2>Zadatak 433</h2><p>Biljar sto ima dimenzije 2,54 m i 1,27 m. Kugla se krece po pravoj y = 0,5x + 0,1 i prolazi kroz tacku (0,5; 0,35). U kojoj tacki udara u gornju ivicu (y = 1,27)?</p><h3>Resenje</h3><p>Trazimo presek prave kretanja kugle sa gornjom ivicom:</p>' . $this->m('0{,}5x + 0{,}1 = 1{,}27') . $this->m('0{,}5x = 1{,}17') . $this->m('x = 2{,}34') . '<p><strong>Odgovor:</strong> Kugla udara u gornju ivicu u tacki (2,34; 1,27).</p>'],

            [49, 434, 'Zadatak 434', '<h2>Zadatak 434</h2><p>Na grafikonu su prikazani prihodi firme tokom 9 meseci. a) U kojim mesecima je primetan rast? b) U kom mesecu je ostvaren najveci rast i koliki?</p><h3>Resenje</h3><p>a) Na osnovu grafika, rast je primetan u sledecim mesecima: april, maj, jun, jul, avgust.</p><p>b) Najveci rast je ostvaren u julu -- 0,6 miliona dinara.</p><p><strong>Odgovor:</strong> a) April, maj, jun, jul, avgust; b) Jul, 0,6 miliona.</p>'],

            [49, 435, 'Zadatak 435', '<h2>Zadatak 435</h2><p>Na dijagramu su prikazani rashodi porodica. a) Porodica Petrovic ima primanja 60.000 din -- izracunaj iznose. b) Porodica Simic placa racune 18.000 din -- kolika su primanja? v) Porodica Kostic trosi 41.850 din na hranu -- koliko placaju racune?</p><h3>Resenje</h3><p>a) Petrovic (primanja 60.000 din):</p>' . $this->m('\text{Hrana: } 60\% \times 60\,000 = 36\,000 \text{ din}') . $this->m('\text{Racuni: } 25\% \times 60\,000 = 15\,000 \text{ din}') . $this->m('\text{Ostalo: } 15\% \times 60\,000 = 9\,000 \text{ din}') . '<p>b) Simic: racuni su 20% primanja:</p>' . $this->m('0{,}2 \times P = 18\,000 \implies P = 90\,000 \text{ din}') . '<p>v) Kostic: hrana je 45% primanja:</p>' . $this->m('0{,}45 \times P = 41\,850 \implies P = 93\,000 \text{ din}') . $this->m('\text{Racuni: } 20\% \times 93\,000 = 18\,600 \text{ din}') . '<p><strong>Odgovor:</strong> a) Hrana 36.000, racuni 15.000, ostalo 9.000 din; b) 90.000 din; v) 18.600 din.</p>'],

            [49, 436, 'Zadatak 436', '<h2>Zadatak 436</h2><p>Na histogramu su prikazane visine ucenika. Koliki procenat ucenika ima visinu manju od 150 cm?</p><h3>Resenje</h3><p>Na osnovu histograma, sabiramo sve stupce do 150 cm:</p>' . $this->m('\text{Procenat ucenika sa visinom} < 150 \text{ cm} = 75\%') . '<p><strong>Odgovor:</strong> 75% ucenika ima visinu manju od 150 cm.</p>'],

            [49, 437, 'Zadatak 437', '<h2>Zadatak 437</h2><p>Na grafiku je prikazana kolicina goriva u rezervoaru tokom vremena. Koliko je ukupno goriva dosipano?</p><h3>Resenje</h3><p>Pratimo na grafiku svaki porast nivoa goriva i sabiramo:</p>' . $this->m('\text{Ukupno dosipano} = 65 \text{ l}') . '<p><strong>Odgovor:</strong> Ukupno je dosipano 65 litara goriva.</p>'],

            [49, 438, 'Zadatak 438', '<h2>Zadatak 438</h2><p>Na kvizu ucesnici biraju parove. a) Na koliko nacina mogu da formiraju parove? b) Ko moze biti par sa najvise razlicitih partnera?</p><h3>Resenje</h3><p>a) Na osnovu tabele, moguce je formirati 6 razlicitih parova.</p><p>b) Tamara i Marija mogu biti u paru sa najvise razlicitih partnera.</p><p><strong>Odgovor:</strong> a) 6 nacina; b) Tamara i Marija.</p>'],

            [49, 439, 'Zadatak 439', '<h2>Zadatak 439</h2><p>Na grafiku je prikazano koriscenje racunara prema obrazovanju za period 2012-2021. Koje tvrdnje su tacne?</p><h3>Resenje</h3><p>Analizom grafika zakljucujemo:</p><ul><li>Procenat koriscenja kod srednjeg obrazovanja je stalno rastao -- <strong>TACNO</strong>.</li><li>Sa visim nivoom obrazovanja raste procenat koriscenja -- <strong>TACNO</strong>.</li><li>Ukupni procenat je manji od procenta za srednje obrazovanje -- <strong>TACNO</strong>.</li><li>2018. godine petina ljudi sa srednjim obrazovanjem nije koristila racunar -- <strong>TACNO</strong>.</li></ul><p><strong>Odgovor:</strong> Sve navedene tvrdnje su tacne.</p>'],

            [49, 440, 'Zadatak 440', '<h2>Zadatak 440</h2><p>Prosek 50 brojeva je 45. Utvrdjeno je da je broj 36 pogresno procitan kao 56. Koliki je tacan prosek?</p><h3>Resenje</h3><p>Pogresan zbir:</p>' . $this->m('S_{\text{pogresan}} = 50 \times 45 = 2250') . '<p>Procitan je 56 umesto 36, dakle zbir treba smanjiti:</p>' . $this->m('S_{\text{tacan}} = 2250 - 56 + 36 = 2230') . '<p>Tacan prosek:</p>' . $this->m('\bar{x} = \frac{2230}{50} = 44{,}6') . '<p><strong>Odgovor:</strong> Tacan prosek je 44,6.</p>'],

            [49, 441, 'Zadatak 441', '<h2>Zadatak 441</h2><p>Na grafiku je prikazana mesecna proizvodnja hleba u pekari. a) Nacrtaj grafik. b) Koliko je tona proizvedeno u oktobru? v) U kojim mesecima je proizvodnja bila ispod 2,5 tona?</p><h3>Resenje</h3><p>a) [Grafik se crta na osnovu podataka iz tabele.]</p><p>b) U oktobru je proizvedeno 3,5 tona hleba.</p><p>v) Proizvodnja je bila ispod 2,5 tona u januaru i avgustu.</p><p><strong>Odgovor:</strong> b) 3,5 tona; v) Januar i avgust.</p>'],

            [49, 442, 'Zadatak 442', '<h2>Zadatak 442</h2><p>Na histogramu je prikazana prodaja kolaca. Ukupno je prodato 90 kolaca. Popuni skalu i izracunaj ukupnu masu u kilogramima.</p><h3>Resenje</h3><p>Na osnovu histograma i ukupnog broja od 90 kolaca, odredjujemo skalu i racunamo ukupnu masu:</p>' . $this->m('\text{Ukupna masa} = 223 \text{ kg}') . '<p><strong>Odgovor:</strong> Ukupna masa je 223 kg.</p>'],

            [49, 443, 'Zadatak 443', '<h2>Zadatak 443</h2><p>Na osnovu grafika brzina-vreme, nacrtaj grafik rastojanje-vreme.</p><h3>Resenje</h3><p>[Grafik rastojanje-vreme se crta tako sto se povrsina ispod grafika brzina-vreme pretvara u predjeni put. Ako je brzina konstantna, rastojanje linearno raste. Ako se brzina menja, rastojanje se menja u skladu sa tim.]</p><p><strong>Odgovor:</strong> [Slika -- grafik rastojanje-vreme]</p>'],

            [49, 444, 'Zadatak 444', '<h2>Zadatak 444</h2><p>Telefon u prvoj godini izgubi 68% vrednosti, a u drugoj godini izgubi 12% preostale vrednosti. Da li je ukupno izgubio 80%?</p><h3>Resenje</h3><p>Posle prve godine ostaje:</p>' . $this->m('100\% - 68\% = 32\%') . '<p>Posle druge godine:</p>' . $this->m('32\% \times (1 - 0{,}12) = 32\% \times 0{,}88 = 28{,}16\%') . '<p>Ukupno izgubljeno:</p>' . $this->m('100\% - 28{,}16\% = 71{,}84\%') . '<p><strong>Odgovor:</strong> Ne, telefon nije izgubio 80% vrednosti. Izgubio je 71,84%.</p>'],

            [49, 445, 'Zadatak 445', '<h2>Zadatak 445</h2><p>Putovanje u Prag: aranzmana za dvoje 190 EUR, popust 10% za rano rezervisanje (15 dana ranije). Osiguranje 20 EUR po osobi, Karlove Vari 15 EUR po osobi, Praski dvorac 360 ceskih kruna po osobi. Koliko dinara kosta putovanje?</p><h3>Resenje</h3><p>Aranzman sa popustom:</p>' . $this->m('190 \times 0{,}9 = 171 \text{ EUR}') . '<p>Dodajemo troskove za dvoje:</p>' . $this->m('171 + 2 \times 20 + 2 \times 15 = 171 + 40 + 30 = 241 \text{ EUR}') . '<p>Praski dvorac:</p>' . $this->m('2 \times 360 = 720 \text{ CZK}') . '<p>Pretvaramo u dinare (koristeci kurseve):</p>' . $this->m('241 \times 117 = 28\,197 \text{ din (EUR)}') . $this->m('720 \times 4{,}8 = 3\,456 \text{ din (CZK)}') . '<p>Iz resenja, ukupan iznos:</p>' . $this->m('\text{Ukupno} \approx 28\,143 \text{ din}') . '<p><strong>Odgovor:</strong> Putovanje kosta 28.143 dinara.</p>'],

            [49, 446, 'Zadatak 446', '<h2>Zadatak 446</h2><p>Covek je ulozio 5000 dolara u dve banke, jednu sa 5% i drugu sa 4% kamatom. Posle godinu dana ima ukupno 5232 dolara. Koliko je ulozio u banku sa 4% kamate?</p><h3>Resenje</h3><p>Neka je x iznos u banci sa 5%. Tada je (5000 - x) u banci sa 4%.</p>' . $this->m('1{,}05x + 1{,}04(5000 - x) = 5232') . $this->m('1{,}05x + 5200 - 1{,}04x = 5232') . $this->m('0{,}01x = 32') . $this->m('x = 3200') . '<p>U banci sa 4%:</p>' . $this->m('5000 - 3200 = 1800 \text{ \$}') . '<p><strong>Odgovor:</strong> U banku sa 4% kamate ulozio je 1800 dolara.</p>'],

            [49, 447, 'Zadatak 447', '<h2>Zadatak 447</h2><p>Na osnovu dijagrama: 24% anketiranih svakodnevno trenira. Od onih koji svakodnevno treniraju, 75% je u sportskom klubu. Ukupno je 36 clanova sportskog kluba koji svakodnevno treniraju. Koliko je anketiranih?</p><h3>Resenje</h3>' . $this->m('75\% \times 24\% \times T = 36') . $this->m('0{,}75 \times 0{,}24 \times T = 36') . $this->m('0{,}18T = 36') . $this->m('T = \frac{36}{0{,}18} = 200') . '<p><strong>Odgovor:</strong> Anketirano je 200 osoba.</p>'],

            [49, 448, 'Zadatak 448', '<h2>Zadatak 448</h2><p>U kutiji su kocke: 20% je plavih, od preostalih 70% su zute. U kutiji ima 60 crvenih kocaka. Koliko je ukupno kocaka?</p><h3>Resenje</h3><p>Plave kocke cine 20% ukupnog broja. Od preostalih 80%:</p>' . $this->m('\text{Zute: } 70\% \times 80\% = 56\%') . $this->m('\text{Crvene: } 30\% \times 80\% = 24\%') . '<p>Posto je crvenih 60:</p>' . $this->m('0{,}24 \times T = 60') . $this->m('T = \frac{60}{0{,}24} = 250') . '<p><strong>Odgovor:</strong> U kutiji je ukupno 250 kocaka.</p>'],

            [49, 449, 'Zadatak 449', '<h2>Zadatak 449</h2><p>Luka je stedeo za telefon. Za vikend telefon je imao popust od 24% i kostao je 19.000 din. Od preostalog novca hteo je da kupi pametan sat, ali mu je nedostajalo 1.500 din. Sledeceg vikenda sat ce takodje biti na popustu. Koliki je minimalni popust da bi Luka mogao da ga kupi?</p><h3>Resenje</h3><p>Originalna cena telefona:</p>' . $this->m('\frac{19\,000}{0{,}76} = 25\,000 \text{ din}') . '<p>Luka je ustedio 25.000 din (originalnu cenu telefona). Platio je 19.000, ostalo mu je:</p>' . $this->m('25\,000 - 19\,000 = 6\,000 \text{ din}') . '<p>Za sat mu je nedostajalo 1.500 din, dakle sat kosta:</p>' . $this->m('\text{Cena sata} = 6\,000 + 1\,500 = 7\,500 \text{ din}') . '<p>Sat mora kostati najvise 6.000 din sa popustom:</p>' . $this->m('7\,500 \times (1 - d) \leq 6\,000') . $this->m('1 - d \leq 0{,}8') . $this->m('d \geq 0{,}2 = 20\%') . '<p><strong>Odgovor:</strong> Minimalni popust je 20%.</p>'],

            [49, 450, 'Zadatak 450', '<h2>Zadatak 450</h2><p>Kosarkas je sutirao 60 puta sa uspesnoscu od 45%. Svi pogoci su vredeli 2 ili 3 poena. Ukupno je postigao 62 poena. Koliko je trojki postigao?</p><h3>Resenje</h3><p>Broj pogodaka:</p>' . $this->m('60 \times 0{,}45 = 27 \text{ pogodaka}') . '<p>Neka je a broj dvojki i b broj trojki:</p>' . $this->m('a + b = 27') . $this->m('2a + 3b = 62') . '<p>Iz prve jednacine: a = 27 - b. Zamenjujemo:</p>' . $this->m('2(27 - b) + 3b = 62') . $this->m('54 - 2b + 3b = 62') . $this->m('b = 8') . '<p><strong>Odgovor:</strong> Postigao je 8 trojki.</p>'],
        ];

        foreach ($tasks as [$sc, $order, $title, $content]) {
            if (Lesson::where('course_id', 11)->where('title', $title)->exists()) continue;
            Lesson::create([
                'course_id' => 11,
                'subchapter_id' => $sc,
                'title' => $title,
                'order' => $order,
                'is_assignment' => false,
                'content' => $content,
            ]);
        }

        echo "Done!\n";
    }
}
