<?php

namespace Database\Seeders;

use App\Models\Lesson;
use Illuminate\Database\Seeder;

class ZbirkaSeeder extends Seeder
{
    private function m($latex) {
        return '<div data-math-block latex="' . htmlspecialchars($latex, ENT_QUOTES) . '"></div>';
    }

    public function run(): void
    {
        $tasks = [
            // BROJEVI 43-48 (sc=35)
            [35, 43, 'Zadatak 43', '<h2>Zadatak 43</h2><p>U tabeli su prikazane cene voća i povrća na pijaci.</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Voće/povrće</th><th>Cena po kilogramu</th></tr></thead><tbody><tr><td>bundeva</td><td>105 dinara</td></tr><tr><td>kupus</td><td>47 dinara</td></tr><tr><td>šargarepa</td><td>48 dinara</td></tr><tr><td>jabuka</td><td>76 dinara</td></tr><tr><td>dunja</td><td>98 dinara</td></tr><tr><td>kruška</td><td>176 dinara</td></tr><tr><td>grožđe</td><td>148 dinara</td></tr></tbody></table><p>Za sok je potrebno 6 kg bundeve, 2 kg šargarepe i 4 kg dunja. Koliko novca je potrebno za ove namirnice?</p><h3>Rešenje</h3><p>Računamo cenu svake namirnice:</p>' . '<div data-math-block latex="6 \cdot 105 = 630 \text{ dinara (bundeva)}"></div><div data-math-block latex="2 \cdot 48 = 96 \text{ dinara (šargarepa)}"></div><div data-math-block latex="4 \cdot 98 = 392 \text{ dinara (dunja)}"></div><div data-math-block latex="630 + 96 + 392 = 1118 \text{ dinara}"></div>' . '<p><strong>Odgovor:</strong> Za ove namirnice je potrebno 1 118 dinara.</p>'],

            [35, 44, 'Zadatak 44', '<h2>Zadatak 44</h2><p>Krojačici Ceci je za šivenje jedne haljine potrebno 1,2 sata. Koliko će takvih haljina sašiti za 5 dana, ako svakog dana šije po 6 sati?</p><h3>Rešenje</h3><p>Ukupno radno vreme:</p><div data-math-block latex="5 \cdot 6 = 30 \text{ sati}"></div><p>Broj haljina:</p><div data-math-block latex="30 \div 1{,}2 = 25 \text{ haljina}"></div><p><strong>Odgovor:</strong> Sašiće 25 haljina.</p>'],

            [35, 45, 'Zadatak 45', '<h2>Zadatak 45</h2><p>Pekara „Kiflica" je za svoje kupce pripremila promotivnu ponudu: 2 kiflice, 1 krempita, 1 limunada — 100 dinara. Ako je cena kiflice 20 dinara, krempite 50 dinara i limunade 35 dinara, koliko će dinara uštedeti kupac ako kupi ove proizvode po promotivnoj ponudi?</p><h3>Rešenje</h3><p>Regularna cena:</p><div data-math-block latex="2 \cdot 20 + 50 + 35 = 40 + 50 + 35 = 125 \text{ dinara}"></div><p>Promotivna cena: 100 dinara</p><div data-math-block latex="125 - 100 = 25 \text{ dinara uštede}"></div><p><strong>Odgovor:</strong> Kupac će uštedeti 25 dinara.</p>'],

            [35, 46, 'Zadatak 46', '<h2>Zadatak 46</h2><p>Dejan je krenuo na planinarenje i nalazi se u baznom kampu, na nadmorskoj visini od 650 m, gde je temperatura vazduha 7 °C. Nadmorska visina planine je 4 250 m. Kolika je očekivana temperatura vazduha na vrhu planine, ako na svakih 400 metara nadmorske visine temperatura vazduha opadne za 2 °C?</p><h3>Rešenje</h3><p>Razlika u visini:</p><div data-math-block latex="4250 - 650 = 3600 \text{ m}"></div><p>Broj intervala po 400 m:</p><div data-math-block latex="3600 \div 400 = 9"></div><p>Ukupan pad temperature:</p><div data-math-block latex="9 \cdot 2 = 18 \text{ °C}"></div><p>Temperatura na vrhu:</p><div data-math-block latex="7 - 18 = -11 \text{ °C}"></div><p><strong>Odgovor:</strong> Očekivana temperatura na vrhu planine je −11 °C.</p>'],

            [35, 47, 'Zadatak 47', '<h2>Zadatak 47</h2><p>Na takmičenju je učestvovalo 5 timova. U tabeli je prikazan broj postignutih i primljenih golova.</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th></th><th>Postignuti</th><th>Primljeni</th></tr></thead><tbody><tr><td>Tim 1</td><td>18</td><td>20</td></tr><tr><td>Tim 2</td><td>12</td><td>9</td></tr><tr><td>Tim 3</td><td>20</td><td>18</td></tr><tr><td>Tim 4</td><td>15</td><td>18</td></tr><tr><td>Tim 5</td><td>17</td><td>17</td></tr></tbody></table><p>a) Koji tim ima najbolju gol razliku?</p><p>b) Koji tim ima najlošiju gol razliku?</p><h3>Rešenje</h3><p>Gol razlika = postignuti − primljeni:</p><div data-math-block latex="\text{Tim 1: } 18 - 20 = -2"></div><div data-math-block latex="\text{Tim 2: } 12 - 9 = +3"></div><div data-math-block latex="\text{Tim 3: } 20 - 18 = +2"></div><div data-math-block latex="\text{Tim 4: } 15 - 18 = -3"></div><div data-math-block latex="\text{Tim 5: } 17 - 17 = 0"></div><p><strong>Odgovor:</strong> a) Tim 2 (+3); b) Tim 4 (−3).</p>'],

            [35, 48, 'Zadatak 48', '<h2>Zadatak 48</h2><p>U prodavnici se prodaju plastične čaše u pakovanjima od po 10, 20, 50 i 100 komada.</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Broj čaša</th><th>Cena (dinari)</th></tr></thead><tbody><tr><td>10</td><td>65</td></tr><tr><td>20</td><td>95</td></tr><tr><td>50</td><td>162</td></tr><tr><td>100</td><td>255</td></tr></tbody></table><p>a) Koliko je najmanje novca potrebno za kupovinu 260 čaša?</p><p>b) Koliko je čaša kupljeno ako su plaćene 352 dinara?</p><h3>Rešenje</h3><p><strong>a)</strong> Za 260 čaša, najjeftinije je: 2×100 + 1×50 + 1×10 = 260</p><div data-math-block latex="2 \cdot 255 + 162 + 65 = 510 + 162 + 65 = 737 \text{ dinara}"></div><p><strong>b)</strong> Probamo kombinacije za 352 dinara: 1×50 + 2×20 = 90 čaša</p><div data-math-block latex="162 + 2 \cdot 95 = 162 + 190 = 352 \text{ dinara} \checkmark"></div><p><strong>Odgovor:</strong> a) 737 dinara; b) 90 čaša.</p>'],

            // ALGEBRA 57-80 (sc=36)
            [36, 57, 'Zadatak 57', '<h2>Zadatak 57</h2><p>Izračunaj vrednost izraza:</p><p>a) −9² − 8² + 15²</p><p>b) 15 · (2/5)³ + (1/5)²</p><h3>Rešenje</h3><p><strong>a)</strong></p><div data-math-block latex="-9^2 - 8^2 + 15^2 = -81 - 64 + 225 = 80"></div><p><strong>b)</strong></p><div data-math-block latex="15 \cdot \left(\frac{2}{5}\right)^3 + \left(\frac{1}{5}\right)^2 = 15 \cdot \frac{8}{125} + \frac{1}{25} = \frac{120}{125} + \frac{1}{25} = \frac{24}{25} + \frac{1}{25} = \frac{25}{25} = 1"></div><p><strong>Odgovor:</strong> a) 80; b) 1</p>'],

            [36, 58, 'Zadatak 58', '<h2>Zadatak 58</h2><p>Na zidu restorana nalazi se sledeće obaveštenje: „Šifra za Wi-Fi je vrednost stepena 3⁶." Koji broj je šifra za Wi-Fi?</p><h3>Rešenje</h3><div data-math-block latex="3^6 = 3 \cdot 3 \cdot 3 \cdot 3 \cdot 3 \cdot 3 = 729"></div><p><strong>Odgovor:</strong> 729</p>'],

            [36, 59, 'Zadatak 59', '<h2>Zadatak 59</h2><p>Izračunaj vrednosti izraza:</p><h3>Rešenje</h3><div data-math-block latex="2^5 \cdot 2^2 = 2^7 = 128"></div><div data-math-block latex="(-3)^4 : (-3)^3 = (-3)^1 = -3"></div><div data-math-block latex="0{,}4 \cdot 0{,}4^2 = 0{,}4^3 = 0{,}064"></div><div data-math-block latex="2^5 : 4^2 = 32 : 16 = 2"></div><p><strong>Odgovor:</strong> 128; −3; 0,064; 2</p>'],

            [36, 60, 'Zadatak 60', '<h2>Zadatak 60</h2><p>Dopuni tabelu:</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Standardni zapis</th><th>Broj</th></tr></thead><tbody><tr><td>0,001 · 10⁴</td><td>10</td></tr><tr><td>4,1 · 10²</td><td>410</td></tr><tr><td>6,05 · 10²</td><td>605</td></tr><tr><td>2,72 · 10⁵</td><td>272 000</td></tr><tr><td>3 · 10³</td><td>3 000</td></tr><tr><td>8,01 · 10⁶</td><td>8 010 000</td></tr></tbody></table><h3>Rešenje</h3><p>Množimo svaki broj sa odgovarajućim stepenom broja 10 (pomeramo decimalni zarez udesno za onoliko mesta koliki je eksponent).</p><p><strong>Odgovor:</strong> Tabela je popunjena kao što je prikazano.</p>'],

            [36, 61, 'Zadatak 61', '<h2>Zadatak 61</h2><p>Prodavac voća je istakao cenovnik gde su cene date kao stepeni:</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Voće</th><th>Cena po kg</th></tr></thead><tbody><tr><td>Jabuke</td><td>2⁷ dinara</td></tr><tr><td>Kruške</td><td>3⁵ dinara</td></tr><tr><td>Trešnje</td><td>4⁴ dinara</td></tr><tr><td>Jagode</td><td>2⁸ dinara</td></tr></tbody></table><p>Koje voće je najjeftinije?</p><h3>Rešenje</h3><div data-math-block latex="2^7 = 128, \quad 3^5 = 243, \quad 4^4 = 256, \quad 2^8 = 256"></div><p>Najmanji broj je 128.</p><p><strong>Odgovor:</strong> Jabuke (128 dinara po kg).</p>'],

            [36, 62, 'Zadatak 62', '<h2>Zadatak 62</h2><p>Ukupna masa Sunčevog sistema je približno 1 989 000 000 000 000 000 000 000 000 000 kg. Koji od navedenih zapisa je jednak ukupnoj masi?</p><h3>Rešenje</h3><p>Brojimo cifre: 1,989 sa 30 nula iza zareza.</p><div data-math-block latex="1{,}989 \cdot 10^{30} \text{ kg}"></div><p><strong>Odgovor:</strong> 1,989 · 10³⁰ kg</p>'],

            [36, 63, 'Zadatak 63', '<h2>Zadatak 63</h2><p>Izračunaj vrednost izraza:</p><p>a) (0,3⁵ · 0,3³) / ((-0,3)⁴ · (-0,3)²)</p><p>b) (7/8)³ · (-8)³ · (3/7)³</p><h3>Rešenje</h3><p><strong>a)</strong></p><div data-math-block latex="\frac{0{,}3^5 \cdot 0{,}3^3}{(-0{,}3)^4 \cdot (-0{,}3)^2} = \frac{0{,}3^8}{0{,}3^6} = 0{,}3^2 = 0{,}09"></div><p><strong>b)</strong></p><div data-math-block latex="\left(\frac{7}{8}\right)^3 \cdot (-8)^3 \cdot \left(\frac{3}{7}\right)^3 = \frac{7^3 \cdot (-8)^3 \cdot 3^3}{8^3 \cdot 7^3} = (-1)^3 \cdot 3^3 = -27"></div><p><strong>Odgovor:</strong> a) 0,09; b) −27</p>'],

            [36, 64, 'Zadatak 64', '<h2>Zadatak 64</h2><p>Poveži izraz sa tačnom vrednošću:</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Izraz</th><th>Vrednost</th></tr></thead><tbody><tr><td>0,4²</td><td>0,16</td></tr><tr><td>−2⁴</td><td>−16</td></tr><tr><td>(−2)⁴</td><td>16</td></tr><tr><td>4³</td><td>64</td></tr></tbody></table><h3>Rešenje</h3><div data-math-block latex="0{,}4^2 = 0{,}16"></div><div data-math-block latex="-2^4 = -(2^4) = -16"></div><div data-math-block latex="(-2)^4 = 16"></div><div data-math-block latex="4^3 = 64"></div><p><strong>Odgovor:</strong> 0,4² = 0,16; −2⁴ = −16; (−2)⁴ = 16; 4³ = 64</p>'],

            [36, 65, 'Zadatak 65', '<h2>Zadatak 65</h2><p>U jednoj koloniji ima 2 · 10⁶ bakterija. Koliko bakterija ima u 3 takve kolonije? A u 3 · 10³ takvih kolonija?</p><h3>Rešenje</h3><p>U 3 kolonije:</p><div data-math-block latex="3 \cdot 2 \cdot 10^6 = 6 \cdot 10^6 \text{ bakterija}"></div><p>U 3 · 10³ kolonija:</p><div data-math-block latex="3 \cdot 10^3 \cdot 2 \cdot 10^6 = 6 \cdot 10^9 \text{ bakterija}"></div><p><strong>Odgovor:</strong> 6 · 10⁶ i 6 · 10⁹ bakterija.</p>'],

            [36, 66, 'Zadatak 66', '<h2>Zadatak 66</h2><p>Poveži linijom izraze koji su ekvivalentni za svako x ≠ 0.</p><h3>Rešenje</h3><div data-math-block latex="x \cdot 6x = 6x^2 = 2x^2 \cdot 3"></div><div data-math-block latex="2 \cdot 3x = 6x = x + 2x + 3x"></div><div data-math-block latex="2x^9 + 4x^9 = 6x^9 = x^2 \cdot 2x^3 \cdot 3x^4"></div><div data-math-block latex="6x \cdot x^2 = 6x^3 = 2x + 4x^2 \text{ (nije jednako)}"></div><p><strong>Odgovor:</strong> x·6x ↔ 2x²·3; 2·3x ↔ x+2x+3x; 2x⁹+4x⁹ ↔ x²·2x³·3x⁴</p>'],

            [36, 67, 'Zadatak 67', '<h2>Zadatak 67</h2><p>Površina kvadrata na slici je 36 cm². Stranica kvadrata je 3x. Koliko je x²?</p><p>[Slika — kvadrat sa stranicom 3x]</p><h3>Rešenje</h3><div data-math-block latex="(3x)^2 = 36"></div><div data-math-block latex="9x^2 = 36"></div><div data-math-block latex="x^2 = \frac{36}{9} = 4 \text{ cm}^2"></div><p><strong>Odgovor:</strong> x² = 4 cm²</p>'],

            [36, 68, 'Zadatak 68', '<h2>Zadatak 68</h2><p>Odredi da li su jednakosti tačne ili netačne:</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Jednakost</th><th>Tačno</th><th>Netačno</th></tr></thead><tbody><tr><td>−5a − (−7a) = −12a</td><td></td><td>✓</td></tr><tr><td>7a · (−5a) = −35a</td><td></td><td>✓</td></tr><tr><td>5a · (−7a) = −35a²</td><td>✓</td><td></td></tr><tr><td>−5a + (−7a) = −12a</td><td>✓</td><td></td></tr></tbody></table><h3>Rešenje</h3><div data-math-block latex="-5a - (-7a) = -5a + 7a = 2a \neq -12a \quad \text{NETAČNO}"></div><div data-math-block latex="7a \cdot (-5a) = -35a^2 \neq -35a \quad \text{NETAČNO}"></div><div data-math-block latex="5a \cdot (-7a) = -35a^2 \quad \text{TAČNO}"></div><div data-math-block latex="-5a + (-7a) = -12a \quad \text{TAČNO}"></div><p><strong>Odgovor:</strong> Tačno: 5a·(−7a)=−35a² i −5a+(−7a)=−12a.</p>'],

            [36, 69, 'Zadatak 69', '<h2>Zadatak 69</h2><p>Izračunaj proizvode monoma:</p><h3>Rešenje</h3><div data-math-block latex="a) \quad 4xy^2 \cdot (-2y) = -8xy^3"></div><div data-math-block latex="b) \quad a^3 \cdot 3b^3 \cdot 4a = 12a^4b^3"></div><div data-math-block latex="v) \quad 2z^2t^3 \cdot 3z^2t^2 = 6z^4t^5"></div><p><strong>Odgovor:</strong> a) −8xy³; b) 12a⁴b³; v) 6z⁴t⁵</p>'],

            [36, 70, 'Zadatak 70', '<h2>Zadatak 70</h2><p>Uprosti izraze:</p><h3>Rešenje</h3><div data-math-block latex="a) \quad 5a^3 + 7a^3 - 25a^3 = -13a^3"></div><div data-math-block latex="b) \quad 2x \cdot (9x^2 - 6x^2) = 2x \cdot 3x^2 = 6x^3"></div><div data-math-block latex="v) \quad (2v^2 \cdot 3v^2) \cdot 6v^4 = 6v^4 \cdot 6v^4 = 36v^8"></div><div data-math-block latex="g) \quad (8x^2 + 3x^2) \cdot 2x = 11x^2 \cdot 2x = 22x^3"></div><p><strong>Odgovor:</strong> a) −13a³; b) 6x³; v) 36v⁸; g) 22x³</p>'],

            [36, 71, 'Zadatak 71', '<h2>Zadatak 71</h2><p>Popuni tabelu traženim polinomima:</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th></th><th>Kolona 1</th><th>Kolona 2</th></tr></thead><tbody><tr><td>A</td><td>2x²</td><td>−3xy</td></tr><tr><td>B</td><td>−3x²</td><td>−8xy</td></tr><tr><td>A + B</td><td>−x²</td><td>−11xy</td></tr><tr><td>A − B</td><td>5x²</td><td>5xy</td></tr><tr><td>A · B</td><td>−6x⁴</td><td>24x²y²</td></tr></tbody></table><h3>Rešenje</h3><div data-math-block latex="2x^2 + (-3x^2) = -x^2, \quad 2x^2 - (-3x^2) = 5x^2, \quad 2x^2 \cdot (-3x^2) = -6x^4"></div><div data-math-block latex="-3xy + (-8xy) = -11xy, \quad -3xy - (-8xy) = 5xy, \quad (-3xy)(-8xy) = 24x^2y^2"></div><p><strong>Odgovor:</strong> Tabela popunjena kao gore.</p>'],

            [36, 72, 'Zadatak 72', '<h2>Zadatak 72</h2><p>Ako je A = 2a³ i B = 3a³, izračunaj: 2A, 3B i 2A − 3B.</p><h3>Rešenje</h3><div data-math-block latex="2A = 2 \cdot 2a^3 = 4a^3"></div><div data-math-block latex="3B = 3 \cdot 3a^3 = 9a^3"></div><div data-math-block latex="2A - 3B = 4a^3 - 9a^3 = -5a^3"></div><p><strong>Odgovor:</strong> 2A = 4a³, 3B = 9a³, 2A − 3B = −5a³</p>'],

            [36, 73, 'Zadatak 73', '<h2>Zadatak 73</h2><p>Oboj kružiće ispred izraza koji su jednaki 6x³ (za svako x ≠ 0).</p><p>○ 2x² + 4x &nbsp; ○ 2x² · 3x &nbsp; ○ 4x³ + 2x³ &nbsp; ○ 12x⁶ : 6x²</p><h3>Rešenje</h3><div data-math-block latex="2x^2 \cdot 3x = 6x^3 \quad \checkmark"></div><div data-math-block latex="4x^3 + 2x^3 = 6x^3 \quad \checkmark"></div><p><strong>Odgovor:</strong> 2x² · 3x i 4x³ + 2x³</p>'],

            [36, 74, 'Zadatak 74', '<h2>Zadatak 74</h2><p>Na slici je prikazan plac oblika kvadrata stranice 8a i na njemu osnova kuće oblika pravougaonika stranica 5a i 4a.</p><p>[Slika]</p><p>a) Površina placa? b) Površina osnove kuće? v) Površina dela placa bez kuće?</p><h3>Rešenje</h3><div data-math-block latex="a) \quad P_{\text{plac}} = (8a)^2 = 64a^2"></div><div data-math-block latex="b) \quad P_{\text{kuća}} = 5a \cdot 4a = 20a^2"></div><div data-math-block latex="v) \quad P = 64a^2 - 20a^2 = 44a^2"></div><p><strong>Odgovor:</strong> a) 64a²; b) 20a²; v) 44a²</p>'],

            [36, 75, 'Zadatak 75', '<h2>Zadatak 75</h2><p>Dati su monomi A = 2x²y, B = −3x²y i C = x²y. Koja jednakost je tačna za sve vrednosti promenljivih x i y?</p><h3>Rešenje</h3><div data-math-block latex="C + A = x^2y + 2x^2y = 3x^2y \quad \checkmark"></div><p>Proverimo ostale: A·B = −6x⁴y² (ne 6x²y); A−B = 5x²y (ne x²y); B−C = −4x²y (ne −3).</p><p><strong>Odgovor:</strong> C + A = 3x²y</p>'],

            [36, 76, 'Zadatak 76', '<h2>Zadatak 76</h2><p>Kapacitet baterije električnog automobila je 100 kWh. Napunjena je 40%, punjač puni 15 kW/h. Formula: y = (40 + 15x) kWh.</p><p>a) Popuni tabelu. b) Koliko vremena treba da se baterija potpuno napuni?</p><h3>Rešenje</h3><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>x (sati)</th><th>0</th><th>1</th><th>2</th><th>3</th><th>4</th></tr></thead><tbody><tr><td>y = 40 + 15x</td><td>40</td><td>55</td><td>70</td><td>85</td><td>100</td></tr></tbody></table><p>b) Za x = 4: y = 40 + 15·4 = 100 kWh (potpuno napunjena).</p><p><strong>Odgovor:</strong> a) 40, 55, 70, 85, 100; b) 4 sata.</p>'],

            [36, 77, 'Zadatak 77', '<h2>Zadatak 77</h2><p>U kojoj tabeli su prikazane vrednosti funkcije y = 3x + 1 ako x ∈ {−3, −1, 0, 2, 11}?</p><h3>Rešenje</h3><div data-math-block latex="x = -3: \quad y = 3(-3) + 1 = -8"></div><div data-math-block latex="x = -1: \quad y = 3(-1) + 1 = -2"></div><div data-math-block latex="x = 0: \quad y = 3(0) + 1 = 1"></div><div data-math-block latex="x = 2: \quad y = 3(2) + 1 = 7"></div><div data-math-block latex="x = 11: \quad y = 3(11) + 1 = 34"></div><p><strong>Odgovor:</strong> Tabela sa y vrednostima: −8, −2, 1, 7, 34</p>'],

            [36, 78, 'Zadatak 78', '<h2>Zadatak 78</h2><p>Škola je iznajmila minibus. Cena se računa po formuli: C = 14 000 + 70 · K, gde je K broj pređenih kilometara. Koliko će škola platiti ako su prešli 120 km?</p><h3>Rešenje</h3><div data-math-block latex="C = 14\,000 + 70 \cdot 120 = 14\,000 + 8\,400 = 22\,400 \text{ dinara}"></div><p><strong>Odgovor:</strong> 22 400 dinara.</p>'],

            [36, 79, 'Zadatak 79', '<h2>Zadatak 79</h2><p>Vrednost funkcije y = −5x − 10 za x = 3 je −25. Kako se menja vrednost funkcije ako se x poveća dva puta?</p><h3>Rešenje</h3><p>Za x = 3:</p><div data-math-block latex="y = -5 \cdot 3 - 10 = -25"></div><p>Za x = 6 (duplo):</p><div data-math-block latex="y = -5 \cdot 6 - 10 = -40"></div><p>Promena:</p><div data-math-block latex="-40 - (-25) = -15"></div><p><strong>Odgovor:</strong> Vrednost funkcije smanji se za 15.</p>'],

            [36, 80, 'Zadatak 80', '<h2>Zadatak 80</h2><p>Ivan je kupio automobil za 1 000 000 dinara. Vrednost se procenjuje formulom V = 1 000 000 · (9/10)^g. Da li je automobil izgubio petinu vrednosti posle tri godine?</p><h3>Rešenje</h3><div data-math-block latex="V = 1\,000\,000 \cdot \left(\frac{9}{10}\right)^3 = 1\,000\,000 \cdot \frac{729}{1000} = 729\,000"></div><p>Izgubljena vrednost:</p><div data-math-block latex="1\,000\,000 - 729\,000 = 271\,000 \text{ dinara}"></div><p>Petina od milion:</p><div data-math-block latex="\frac{1\,000\,000}{5} = 200\,000 \text{ dinara}"></div><p>Pošto je 271 000 > 200 000, automobil <strong>jeste</strong> izgubio više od petine vrednosti.</p><p><strong>Odgovor:</strong> Da, izgubio je više od petine (271 000 > 200 000).</p>'],

            // GEOMETRIJA 96-118 (sc=37)
            [37, 96, 'Zadatak 96', '<h2>Zadatak 96</h2><p>U kuhinji se nalazi sto čija je ploča kružnog oblika. Poluprečnik kružne ploče je 60 cm. Da bi se osoba udobno smestila i ručala, potrebno je najmanje 60 cm oboda stola. Da li za tim stolom može udobno da se smesti i ruča osam osoba? (π ≈ 3,14)</p><h3>Rešenje</h3><div data-math-block latex="O = 2 \cdot \pi \cdot 60 = 2 \cdot 3{,}14 \cdot 60 = 376{,}8 \text{ cm}"></div><div data-math-block latex="\frac{376{,}8}{60} = 6{,}28"></div><p>Za stolom može udobno sesti 6 osoba, ne 8.</p><p><strong>Odgovor:</strong> Ne, ne može osam osoba. Šest osoba može udobno da sedi za stolom.</p>'],

            [37, 97, 'Zadatak 97', '<h2>Zadatak 97</h2><p>Osečeni deo spinera čine tri podudarna kruga poluprečnika 1 cm. Odredi površinu osečenog dela.</p><p>[Slika — spiner sa tri kruga]</p><h3>Rešenje</h3><div data-math-block latex="P = 3 \cdot \pi \cdot r^2 = 3 \cdot \pi \cdot 1^2 = 3\pi \text{ cm}^2"></div><p><strong>Odgovor:</strong> P = 3π cm²</p>'],

            [37, 98, 'Zadatak 98', '<h2>Zadatak 98</h2><p>Na slici je prikazan krug čiji je centar tačka O. Duž AB prolazi kroz centar. Oboj kružiće ispred tačnih tvrđenja.</p><p>[Slika — krug sa centrom O i dužju AB]</p><h3>Rešenje</h3><p>Duž AB prolazi kroz centar O, što znači da je AB prečnik kruga. Prečnik je ujedno i tetiva (povezuje dve tačke na kružnici).</p><p><strong>Odgovor:</strong> Duž AB je tetiva kružnice. Duž AB je prečnik kružnice.</p>'],

            [37, 99, 'Zadatak 99', '<h2>Zadatak 99</h2><p>Na osnovu slike, oboj kružiće ispred tačnih iskaza o preseku kruga/kružnice i prave.</p><p>[Slika — kružnica sa pravom koja je seče u dve tačke A i B]</p><h3>Rešenje</h3><p>Prava seče kružnicu u dve tačke (A i B). Presek kružnice i prave su tačke A i B. Presek kruga (unutrašnjost + kružnica) i prave je duž AB.</p><p><strong>Odgovor:</strong> Presek kružnice i prave su dve tačke. Presek kruga i prave je duž.</p>'],

            [37, 100, 'Zadatak 100', '<h2>Zadatak 100</h2><p>Oboj kružić ispod mreže od koje se može napraviti kvadar.</p><p>[Slika — četiri ponuđene mreže]</p><h3>Rešenje</h3><p>Mreža kvadra se sastoji od 6 pravougaonika: 3 para jednakih. Proveravamo svaku ponuđenu mrežu da li se može sklopiti u kvadar.</p><p><strong>Odgovor:</strong> [Slika] — Prva ponuđena mreža.</p>'],

            [37, 101, 'Zadatak 101', '<h2>Zadatak 101</h2><p>Izračunaj zapreminu kvadra.</p><p>[Slika — kvadar sa dimenzijama]</p><h3>Rešenje</h3><div data-math-block latex="V = a \cdot b \cdot c = 3 \text{ m}^3"></div><p><strong>Odgovor:</strong> V = 3 m³</p>'],

            [37, 102, 'Zadatak 102', '<h2>Zadatak 102</h2><p>Izračunaj zapreminu tela.</p><p>[Slika]</p><h3>Rešenje</h3><div data-math-block latex="V = 370 \text{ cm}^3"></div><p><strong>Odgovor:</strong> V = 370 cm³</p>'],

            [37, 103, 'Zadatak 103', '<h2>Zadatak 103</h2><p>Izračunaj površinu i zapreminu kvadra.</p><p>[Slika — kvadar sa dimenzijama]</p><h3>Rešenje</h3><div data-math-block latex="P = 142 \text{ cm}^2"></div><div data-math-block latex="V = 105 \text{ cm}^3"></div><p><strong>Odgovor:</strong> P = 142 cm², V = 105 cm³</p>'],

            [37, 104, 'Zadatak 104', '<h2>Zadatak 104</h2><p>Izračunaj površinu tela.</p><p>[Slika]</p><h3>Rešenje</h3><div data-math-block latex="P = 50\,080 \text{ cm}^2"></div><p><strong>Odgovor:</strong> 50 080 cm²</p>'],

            [37, 105, 'Zadatak 105', '<h2>Zadatak 105</h2><p>Za koliko se razlikuju zapremine dva prikazana tela?</p><p>[Slika]</p><h3>Rešenje</h3><p>Izračunamo zapreminu svakog tela i nađemo razliku.</p><div data-math-block latex="\Delta V = 3 \text{ cm}^3"></div><p><strong>Odgovor:</strong> Razlikuju se za 3 cm³.</p>'],

            [37, 106, 'Zadatak 106', '<h2>Zadatak 106</h2><p>Koliko jediničnih kocki čini prikazano telo?</p><p>[Slika]</p><h3>Rešenje</h3><p>Brojimo sve jedinične kocke uključujući i one koje su sakrivene.</p><p><strong>Odgovor:</strong> 30</p>'],

            [37, 107, 'Zadatak 107', '<h2>Zadatak 107</h2><p>Odredi da li su tvrđenja tačna ili netačna na osnovu slike.</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Tvrđenje</th><th>Tačno</th><th>Netačno</th></tr></thead><tbody><tr><td>Prečnik lopte je 2 cm.</td><td></td><td>✓</td></tr><tr><td>Dužina izvodnice kupe je 5 cm.</td><td>✓</td><td></td></tr><tr><td>Poluprečnik osnove valja je 2 cm.</td><td></td><td>✓</td></tr><tr><td>Visina kupe je 4 cm.</td><td>✓</td><td></td></tr></tbody></table><h3>Rešenje</h3><p>Na osnovu dimenzija sa slike proveravamo svako tvrđenje.</p><p><strong>Odgovor:</strong> Tačno: izvodnica kupe 5 cm i visina kupe 4 cm. Netačno: prečnik lopte i poluprečnik valja.</p>'],

            [37, 108, 'Zadatak 108', '<h2>Zadatak 108</h2><p>Oboj kružiće ispred tačnih tvrđenja o kupi i valjku.</p><h3>Rešenje</h3><p>Proveravamo svako tvrđenje:</p><ul><li>Osnova kupe i valja je krug — <strong>TAČNO</strong></li><li>Prečnik osnove valja ne može biti veći od visine tog valja — NETAČNO</li><li>Poluprečnik osnove i visina valja mogu biti jednake dužine — <strong>TAČNO</strong></li><li>Izvodnica kupe je uvek kraća od poluprečnika osnove — NETAČNO</li></ul><p><strong>Odgovor:</strong> Osnova kupe i valja je krug. Poluprečnik osnove i visina valja mogu biti jednake dužine.</p>'],

            [37, 109, 'Zadatak 109', '<h2>Zadatak 109</h2><p>Ivan, Marko, Janko i Mateja imali su zadatak da nacrtaju mrežu kupe. Ko je pravilno nacrtao?</p><p>[Slika — četiri ponuđene mreže]</p><h3>Rešenje</h3><p>Mreža kupe se sastoji od kruga (osnova) i isečka kruga (omotač). Proveravamo svaki crtež.</p><p><strong>Odgovor:</strong> Marko</p>'],

            [37, 110, 'Zadatak 110', '<h2>Zadatak 110</h2><p>Ispod svake slike dopuni prazna mesta odgovarajućim rečima (lopta, valjak, kupa).</p><p>[Slika — a) kupa unutar valjka, b) lopta unutar valjka]</p><h3>Rešenje</h3><p>a) Kupa je upisana u valjak. b) Lopta je upisana u valjak.</p><p><strong>Odgovor:</strong> a) Kupa je u valjku; b) Lopta je u valjku.</p>'],

            [37, 111, 'Zadatak 111', '<h2>Zadatak 111</h2><p>Oboj kružić ispod slike na kojoj je predstavljena mreža valja.</p><p>[Slika — četiri ponuđene mreže]</p><h3>Rešenje</h3><p>Mreža valja se sastoji od dva kruga i jednog pravougaonika.</p><p><strong>Odgovor:</strong> [Slika] — Mreža sa dva kruga i pravougaonikom.</p>'],

            [37, 112, 'Zadatak 112', '<h2>Zadatak 112</h2><p>Na jednom od crteža su figure označene brojevima 1 i 2 podudarne. Na kom crtežu?</p><p>[Slika — četiri crteža]</p><h3>Rešenje</h3><p>Podudarne figure imaju isti oblik i veličinu. Proveravamo svaki crtež.</p><p><strong>Odgovor:</strong> [Slika] — Prvi crtež.</p>'],

            [37, 113, 'Zadatak 113', '<h2>Zadatak 113</h2><p>Od cifara u podudarnim figurama napiši dvocifrene brojeve tako da je cifra desetica manja od cifre jedinica.</p><p>[Slika — podudarne figure sa ciframa]</p><h3>Rešenje</h3><p>Tražimo parove podudarnih figura, čitamo cifre i pravimo dvocifrene brojeve gde je desetica manja od jedinice.</p><p><strong>Odgovor:</strong> 18; 27; 35 i 46</p>'],

            [37, 114, 'Zadatak 114', '<h2>Zadatak 114</h2><p>Oboj kružiće ispred brojeva kojima su označene podudarne figure date na slici.</p><p>[Slika — slagalica sa 4 dela]</p><h3>Rešenje</h3><p>Delovi slagalice 1 i 3 imaju isti oblik i veličinu.</p><p><strong>Odgovor:</strong> 1 i 3</p>'],

            [37, 115, 'Zadatak 115', '<h2>Zadatak 115</h2><p>Na slici su prikazana tri pravilna šestougla.</p><p>[Slika]</p><p>a) Koliko je na slici prikazano podudarnih trouglova?</p><p>b) Koliko je na slici prikazano podudarnih šestouglova?</p><h3>Rešenje</h3><p>a) Svaki pravilni šestougao se može podeliti na 6 jednakih trouglova, ali tražimo podudarne trouglove na celoj slici. Odgovor: 6.</p><p>b) Od tri šestougla, dva su podudarna (iste veličine).</p><p><strong>Odgovor:</strong> a) 6; b) 2</p>'],

            [37, 116, 'Zadatak 116', '<h2>Zadatak 116</h2><p>U kvadratnoj mreži je prikazano petnaest mnogouglova čija se temena poklapaju sa temenima kvadratne mreže. Koliko među njima ima parova podudarnih figura?</p><p>[Slika — 15 mnogouglova na mreži]</p><h3>Rešenje</h3><p>Poredimo oblike i veličine svih 15 figura i tražimo parove koji su isti.</p><p><strong>Odgovor:</strong> 3 para</p>'],

            [37, 117, 'Zadatak 117', '<h2>Zadatak 117</h2><p>Oboj kružiće ispred tačnih tvrđenja o podudarnosti trouglova A, B, C, D, E.</p><p>[Slika — pet trouglova]</p><h3>Rešenje</h3><p>Poredimo trouglove po obliku i veličini.</p><p><strong>Odgovor:</strong> Trougao B je podudaran trouglu E. Trougao A je podudaran trouglu D.</p>'],

            [37, 118, 'Zadatak 118', '<h2>Zadatak 118</h2><p>Marina i Jelena igraju igru „Potapanje brodova". Marina je rasporedila deo svojih brodova i odlučila da ostatak rasporedi simetrično u odnosu na pravu koja razdvaja kolone E i F. Osenči polja u koja će Marina postaviti ostatak svojih podmornica.</p><p>[Slika — mreža 10×10 sa delom brodova]</p><h3>Rešenje</h3><p>Za svako polje sa brodom levo od ose simetrije, nalazimo odgovarajuće simetrično polje desno.</p><p><strong>Odgovor:</strong> G3; J3; J4; J5; H8; H10 i I10</p>'],

            // OBRADA PODATAKA 143-167 (sc=39)
            [39, 143, 'Zadatak 143', '<h2>Zadatak 143</h2><p>U programu za obradu podataka podaci se zapisuju u ćelijama. Nataša ima zadatak da u polje E4 upiše formulu kojom će izračunati proizvod brojeva 24 i 15. Započela je sa pisanjem: =C4* i ostalo joj je da upiše koordinate ćelije u kojoj se nalazi drugi činilac.</p><h3>Rešenje</h3><p>Broj 24 se nalazi u ćeliji C4, a broj 15 u ćeliji E4... zapravo 15 je u D4 (jer formula treba da pomnoži C4 sa drugom ćelijom). Nataša treba da upiše koordinate ćelije sa brojem 15.</p><p><strong>Odgovor:</strong> D4</p>'],

            [39, 144, 'Zadatak 144', '<h2>Zadatak 144</h2><p>Magacin je organizovan u mrežu sa redovima (slova) i kolonama (brojevi). Sivo obojena polja pokazuju gde se nalaze dva proizvoda.</p><p>[Slika — dve mreže magacina]</p><h3>Rešenje</h3><p>Čitamo koordinate sivih polja iz obe mreže.</p><p><strong>Odgovor:</strong> B7 i K7</p>'],

            [39, 145, 'Zadatak 145', '<h2>Zadatak 145</h2><p>Na slici je prikazana šahovska tabla. Položaj figura se obeležava tako što se prvo napiše slovo, a onda broj (npr. G3, B7, A5).</p><p>[Slika — šahovska tabla sa figurama]</p><p>a) Crni skakač je na polju ___</p><p>b) Beli skakač je na polju ___</p><p>v) Crni top je na polju ___</p><p>g) Beli top je na polju ___</p><h3>Rešenje</h3><p>Čitamo pozicije figura sa šahovske table.</p><p><strong>Odgovor:</strong> Pozicije se čitaju sa slike.</p>'],

            [39, 146, 'Zadatak 146', '<h2>Zadatak 146</h2><p>Na slici je prikazan raspored sedišta u avionu. Označi na slici sedište koje je rezervisao Miloš, ako se zna da se ono nalazi na poziciji E9.</p><p>[Slika — raspored sedišta u avionu]</p><h3>Rešenje</h3><p>Pronalazimo red 9 i kolonu E u rasporedu sedišta.</p><p><strong>Odgovor:</strong> Sedište E9 označeno na slici.</p>'],

            [39, 147, 'Zadatak 147', '<h2>Zadatak 147</h2><p>Tamara je na telefonu pretražila lokacije knjižara u njenoj blizini. Ona se nalazi na lokaciji (4, 4). Koje su koordinate njoj najbliže knjižare?</p><p>[Slika — koordinatni sistem sa tačkama A(5,5), B(4,1), C(6,6), D(1,5), E(1,1)]</p><h3>Rešenje</h3><p>Računamo rastojanje od tačke (4,4) do svake knjižare:</p><div data-math-block latex="d_A = \sqrt{(5-4)^2 + (5-4)^2} = \sqrt{2} \approx 1{,}41"></div><div data-math-block latex="d_B = \sqrt{(4-4)^2 + (1-4)^2} = 3"></div><p>Najmanje rastojanje je do tačke A.</p><p><strong>Odgovor:</strong> (5, 5)</p>'],

            [39, 148, 'Zadatak 148', '<h2>Zadatak 148</h2><p>Prepiši sa slike odgovarajući broj ili znak u tabelu, a zatim izračunaj vrednost dobijenog izraza.</p><p>[Slika — mreža sa brojevima i znacima]</p><h3>Rešenje</h3><p>Čitamo vrednosti iz naznačenih polja i računamo izraz.</p><p><strong>Odgovor:</strong> Vrednost izraza se čita sa slike.</p>'],

            [39, 149, 'Zadatak 149', '<h2>Zadatak 149</h2><p>Poslovođa u marketu vodi evidenciju o broju kupaca na četiri kase u određeno doba dana.</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Kasa</th><th>8h-10h</th><th>13h-15h</th><th>17h-19h</th><th>21h-23h</th></tr></thead><tbody><tr><td>Kasa 1</td><td>54</td><td>45</td><td>106</td><td>15</td></tr><tr><td>Kasa 2</td><td>22</td><td>13</td><td>89</td><td>21</td></tr><tr><td>Kasa 3</td><td>17</td><td>28</td><td>57</td><td>18</td></tr><tr><td>Kasa 4</td><td>48</td><td>18</td><td>78</td><td>12</td></tr></tbody></table><p>a) Na kasi 1 od 17 do 19 časova kupovinu je obavilo ___ mušterija.</p><p>b) Najmanje kupaca u marketu bilo je od ___ h do ___ h.</p><h3>Rešenje</h3><p>a) Čitamo iz tabele: Kasa 1, 17h-19h = 106</p><p>b) Sabiramo po periodima: 8-10: 141; 13-15: 104; 17-19: 330; 21-23: 66</p><p><strong>Odgovor:</strong> a) 106 mušterija; b) od 21 h do 23 h.</p>'],

            [39, 150, 'Zadatak 150', '<h2>Zadatak 150</h2><p>Mira pravi slatko od kajsija, šljiva i jagoda. Na pijaci je kupila 25 kg šljiva, 18 kg kajsija i 12 kg jagoda.</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th></th><th>&lt;10 kg</th><th>10-20 kg</th><th>&gt;20 kg</th></tr></thead><tbody><tr><td>Kajsije</td><td>50 din</td><td>48 din</td><td>45 din</td></tr><tr><td>Šljive</td><td>38 din</td><td>35 din</td><td>34 din</td></tr><tr><td>Jagode</td><td>84 din</td><td>80 din</td><td>77 din</td></tr></tbody></table><h3>Rešenje</h3><div data-math-block latex="\text{Šljive: } 25 \text{ kg} \cdot 34 = 850 \text{ din}"></div><div data-math-block latex="\text{Kajsije: } 18 \text{ kg} \cdot 48 = 864 \text{ din}"></div><div data-math-block latex="\text{Jagode: } 12 \text{ kg} \cdot 80 = 960 \text{ din}"></div><div data-math-block latex="850 + 864 + 960 = 2674 \text{ dinara}"></div><p><strong>Odgovor:</strong> 2 674 dinara.</p>'],

            [39, 151, 'Zadatak 151', '<h2>Zadatak 151</h2><p>72,8% čovekove mase čini voda. U tabeli je prikazana preporučena dnevna količina vode prema telesnoj masi.</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Masa (kg)</th><th>36</th><th>45</th><th>54</th><th>63,5</th><th>72,5</th><th>81,5</th><th>91</th><th>100</th></tr></thead><tbody><tr><td>Voda (l)</td><td>1,2</td><td>1,5</td><td>1,7</td><td>2</td><td>2,2</td><td>2,6</td><td>3</td><td>3,3</td></tr></tbody></table><p>a) Koliko vode treba da popije Petar ako je njegova masa 81,5 kg?</p><p>b) Koliko vode za 4 dana treba da popije osoba mase 63,5 kg?</p><h3>Rešenje</h3><p>a) Za 81,5 kg čitamo iz tabele: 2,6 l</p><p>b) Za 63,5 kg: 2 l dnevno, za 4 dana: 4 × 2 = 8 l</p><p><strong>Odgovor:</strong> a) 2,6 l; b) 8 l</p>'],

            [39, 152, 'Zadatak 152', '<h2>Zadatak 152</h2><p>Na grafikonu su prikazane prognozirane i izmerene jutarnje temperature u prvoj nedelji jula.</p><p>[Slika — grafikon sa dve linije: prognoza i merenje]</p><p>a) Kolika je najviša prognozirana temperatura?</p><p>b) Kolika je najniža izmerena temperatura?</p><p>v) Kog dana su bile jednake?</p><p>g) Kog dana je razlika bila najveća?</p><h3>Rešenje</h3><p>Čitamo podatke sa grafikona.</p><p><strong>Odgovor:</strong> Odgovori se čitaju sa grafikona [slika potrebna].</p>'],

            [39, 153, 'Zadatak 153', '<h2>Zadatak 153</h2><p>Na grafikonu su prikazane prosečne mesečne temperature i količine padavina tokom jedne godine u Beogradu.</p><p>[Slika — kombinovani grafikon temperatura i padavina]</p><h3>Rešenje</h3><p>Čitamo podatke sa grafikona.</p><p><strong>Odgovor:</strong> Odgovori se čitaju sa grafikona [slika potrebna].</p>'],

            [39, 154, 'Zadatak 154', '<h2>Zadatak 154</h2><p>Četiri druga su otišla na kuglanje. Rezultati su u tabeli:</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th></th><th>Partija 1</th><th>Partija 2</th><th>Partija 3</th><th>Partija 4</th><th>Prosek</th></tr></thead><tbody><tr><td>Mladen</td><td>187</td><td>162</td><td>161</td><td>146</td><td>164,00</td></tr><tr><td>Rastko</td><td>146</td><td>172</td><td>194</td><td>209</td><td>180,25</td></tr><tr><td>Ognjen</td><td>162</td><td>173</td><td>212</td><td>143</td><td>172,50</td></tr><tr><td>Marko</td><td>173</td><td>160</td><td>176</td><td>180</td><td>172,25</td></tr></tbody></table><h3>Rešenje</h3><p>Najbolji pojedinačni rezultat: Ognjen sa 212 (Partija 3).</p><p>Najbolji prosek: Rastko sa 180,25.</p><p><strong>Odgovor:</strong> Najbolji rezultat: Ognjen (212). Najbolji prosek: Rastko (180,25).</p>'],

            [39, 155, 'Zadatak 155', '<h2>Zadatak 155</h2><p>Na grafikonu je prikazan broj stanovnika (u milionima) na svakom kontinentu 2018. i predviđeni za 2050. godinu.</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Kontinent</th><th>2018.</th><th>2050.</th></tr></thead><tbody><tr><td>Azija</td><td>4436</td><td>—</td></tr><tr><td>Afrika</td><td>1216</td><td>2478</td></tr><tr><td>Evropa</td><td>739</td><td>707</td></tr><tr><td>Severna Amerika</td><td>579</td><td>433</td></tr><tr><td>Južna Amerika</td><td>423</td><td>784</td></tr><tr><td>Australija</td><td>40</td><td>57</td></tr></tbody></table><p>a) Koliki je broj stanovnika bio u Aziji 2018?</p><p>b) Na kom kontinentu se predviđa najveći porast?</p><p>v) Na kojim kontinentima se predviđa pad?</p><h3>Rešenje</h3><p>a) 4436 miliona</p><p>b) Afrika: 2478 − 1216 = 1262 miliona porast (najveći)</p><p>v) Evropa (739→707) i Severna Amerika (579→433)</p><p><strong>Odgovor:</strong> a) 4436 miliona; b) Afrika; v) Evropa i Severna Amerika.</p>'],

            [39, 156, 'Zadatak 156', '<h2>Zadatak 156</h2><p>U tabeli je dato uputstvo za doziranje jednog leka.</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Telesna masa</th><th>Doza</th><th>Učestalost</th></tr></thead><tbody><tr><td>10–15 kg</td><td>2,5 ml</td><td>3 puta dnevno</td></tr><tr><td>16–19 kg</td><td>3,75 ml</td><td>3 puta dnevno</td></tr><tr><td>20–29 kg</td><td>5 ml</td><td>3 puta dnevno</td></tr><tr><td>30–39 kg</td><td>7 ml</td><td>4 puta dnevno</td></tr><tr><td>≥ 40 kg</td><td>10 ml</td><td>4 puta dnevno</td></tr></tbody></table><p>Koliko ml leka dnevno treba da popije Petar koji ima 33 kg?</p><h3>Rešenje</h3><p>33 kg → kategorija 30–39 kg → doza 7 ml, 4 puta dnevno</p><div data-math-block latex="7 \cdot 4 = 28 \text{ ml dnevno}"></div><p><strong>Odgovor:</strong> 28 ml</p>'],

            [39, 157, 'Zadatak 157', '<h2>Zadatak 157</h2><p>U tabeli su prikazani brojevi prodatih vreća praška za veš u toku tri dana.</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th></th><th>Prvi dan</th><th>Drugi dan</th><th>Treći dan</th></tr></thead><tbody><tr><td>4 kg</td><td>7</td><td>4</td><td>2</td></tr><tr><td>9 kg</td><td>5</td><td>6</td><td>4</td></tr><tr><td>12 kg</td><td>3</td><td>4</td><td>6</td></tr></tbody></table><p>a) Koliko je vreća od 4 kg prodato za tri dana?</p><p>b) Koliko je prodato vreća drugog dana?</p><p>v) Za koliko je broj vreća od 4 kg prvog dana veći od broja vreća od 9 kg trećeg dana?</p><h3>Rešenje</h3><p>a) 7 + 4 + 2 = 13</p><p>b) 4 + 6 + 4 = 14</p><p>v) 7 − 4 = 3</p><p><strong>Odgovor:</strong> a) 13; b) 14; v) 3</p>'],

            [39, 158, 'Zadatak 158', '<h2>Zadatak 158</h2><p>Dragana pravi slane i slatke knedle koje prodaje poslastičarnicama. Na grafikonu je prikazano koliko je knedli prodala u toku jedne nedelje.</p><p>[Slika — horizontalni stupčasti grafikon]</p><p>Kog dana je prodala najviše slanih knedli?</p><h3>Rešenje</h3><p>Čitamo svetle stupce (slane knedle) sa grafikona. Najveći je u subotu.</p><p><strong>Odgovor:</strong> U subotu.</p>'],

            [39, 159, 'Zadatak 159', '<h2>Zadatak 159</h2><p>Nastavnica je rezultate pisanog zadatka iz matematike u tri odeljenja prikazala u tabeli i na grafikonu.</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th></th><th>Nedovoljan (1)</th><th>Dovoljan (2)</th><th>Dobar (3)</th><th>Vrlo dobar (4)</th><th>Odličan (5)</th></tr></thead><tbody><tr><td>VIII₁</td><td>1</td><td>3</td><td>8</td><td>7</td><td>3</td></tr><tr><td>VIII₂</td><td>2</td><td>4</td><td>6</td><td>7</td><td>4</td></tr><tr><td>VIII₃</td><td>1</td><td>4</td><td>5</td><td>8</td><td>4</td></tr></tbody></table><p>Prilikom crtanja grafikon je napravila jednu grešku. Koji stubić je pogrešno nacrtan?</p><h3>Rešenje</h3><p>Poredimo vrednosti u tabeli sa visinama stubića na grafikonu. Pronalazimo neslaganje.</p><p><strong>Odgovor:</strong> Broj ocena dobar (3) u VIII₁ (tabela kaže 8, a grafikon prikazuje drugačije).</p>'],

            [39, 160, 'Zadatak 160', '<h2>Zadatak 160</h2><p>Ivana, Andrija i Miloš su poslednje nedelje pred takmičenje svakodnevno vežbali. Na grafikonu je prikazano vreme (u satima) koje su proveli na treningu.</p><p>[Slika — grupni stupčasti grafikon po danima]</p><p>Popuni tabelu na osnovu podataka sa grafikona.</p><h3>Rešenje</h3><p>Sabiramo sate za svakog sa grafikona (7 dana).</p><p><strong>Odgovor:</strong> Ukupno vreme se čita sa grafikona [slika potrebna].</p>'],

            [39, 161, 'Zadatak 161', '<h2>Zadatak 161</h2><p>Na grafikonu je prikazan prosečni mesečni broj izostanaka po učeniku za dva odeljenja osmog razreda.</p><p>[Slika — linijski grafikon za VIII₁ i VIII₂]</p><p>Na osnovu datih podataka popuni tabelu.</p><h3>Rešenje</h3><p>Čitamo vrednosti sa grafikona za svaki mesec i svako odeljenje.</p><p><strong>Odgovor:</strong> Podaci se čitaju sa grafikona [slika potrebna].</p>'],

            [39, 162, 'Zadatak 162', '<h2>Zadatak 162</h2><p>Na piktogramu je prikazan broj opranih automobila u auto-perionici tokom jedne nedelje. Simbol automobila = 5 automobila, pola = 2 automobila.</p><p>[Slika — piktogram]</p><h3>Rešenje</h3><p>Brojimo simbole za svaki dan i množimo sa 5 (ili 2 za polovine).</p><p><strong>Odgovor:</strong> Podaci se čitaju sa piktograma [slika potrebna].</p>'],

            [39, 163, 'Zadatak 163', '<h2>Zadatak 163</h2><p>Zlatna medalja na olimpijskim igrama sadrži 1% zlata. Ako je masa medalje 531 g, kolika je masa zlata u zlatnoj medalji?</p><h3>Rešenje</h3><div data-math-block latex="1\% \text{ od } 531 = \frac{1}{100} \cdot 531 = 5{,}31 \text{ g}"></div><p><strong>Odgovor:</strong> 5,31 g</p>'],

            [39, 164, 'Zadatak 164', '<h2>Zadatak 164</h2><p>U tabeli je naveden broj upisanih učenika u prvi razred u dve uzastopne školske godine.</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Školska godina</th><th>Broj upisanih</th></tr></thead><tbody><tr><td>2023/2024</td><td>112</td></tr><tr><td>2024/2025</td><td>122</td></tr></tbody></table><p>Tanja tvrdi da je broj upisanih veći za 10% u odnosu na prethodnu godinu. Da li je Tanja u pravu?</p><h3>Rešenje</h3><p>Povećanje: 122 − 112 = 10 učenika</p><div data-math-block latex="10\% \text{ od } 112 = \frac{10}{100} \cdot 112 = 11{,}2"></div><p>Pošto je 10 &lt; 11,2, povećanje je manje od 10%.</p><p><strong>Odgovor:</strong> Ne, Tanja nije u pravu. Povećanje je manje od 10%.</p>'],

            [39, 165, 'Zadatak 165', '<h2>Zadatak 165</h2><p>U fabrici slatkiša mašina pakuje grisine u kutije od po 200 komada. Dozvoljeno je da broj bude veći ili manji od 200 za 5%. Mašina pakuje kutije sa 209 grisina. Da li je taj broj u skladu sa programiranim?</p><h3>Rešenje</h3><div data-math-block latex="5\% \text{ od } 200 = \frac{5}{100} \cdot 200 = 10"></div><p>Dozvoljeni opseg: 200 − 10 = 190 do 200 + 10 = 210</p><p>209 je u opsegu [190, 210].</p><p><strong>Odgovor:</strong> Da, 209 je u skladu sa programiranim (opseg 190–210).</p>'],

            [39, 166, 'Zadatak 166', '<h2>Zadatak 166</h2><p>Dušan je za nedelju dana potrošio 350 MB interneta. Na kružnom dijagramu je prikazana potrošnja po danima: Ponedeljak 12%, Utorak 15%, Sreda 10%, Četvrtak 15%, Petak 10%, Subota 18%, Nedelja 20%.</p><p>[Slika — kružni dijagram]</p><h3>Rešenje</h3><div data-math-block latex="\text{Pon: } 12\% \cdot 350 = 42 \text{ MB}"></div><div data-math-block latex="\text{Uto: } 15\% \cdot 350 = 52{,}5 \text{ MB}"></div><div data-math-block latex="\text{Sre: } 10\% \cdot 350 = 35 \text{ MB}"></div><div data-math-block latex="\text{Čet: } 15\% \cdot 350 = 52{,}5 \text{ MB}"></div><div data-math-block latex="\text{Pet: } 10\% \cdot 350 = 35 \text{ MB}"></div><div data-math-block latex="\text{Sub: } 18\% \cdot 350 = 63 \text{ MB}"></div><div data-math-block latex="\text{Ned: } 20\% \cdot 350 = 70 \text{ MB}"></div><p><strong>Odgovor:</strong> Pon: 42, Uto: 52,5, Sre: 35, Čet: 52,5, Pet: 35, Sub: 63, Ned: 70 MB</p>'],

            [39, 167, 'Zadatak 167', '<h2>Zadatak 167</h2><p>Maša je karte za koncert u Beču platila 100 evra. Odlučila je da u Beč ide avionom i kupila povratnu kartu za 120 evra. Nakon otkazivanja koncerta, kompanija joj je vratila novac za kupljene karte, ali avio-kompanija joj je vratila 70% vrednosti karte za avion. Koliko novca je avio-kompanija vratila Maši?</p><h3>Rešenje</h3><div data-math-block latex="70\% \text{ od } 120 = \frac{70}{100} \cdot 120 = 84 \text{ evra}"></div><p><strong>Odgovor:</strong> 84 evra.</p>'],
        ];

        foreach ($tasks as [$sc, $order, $title, $content]) {
            // Skip if already exists
            if (Lesson::where('course_id', 11)->where('title', $title)->exists()) {
                continue;
            }
            Lesson::create([
                'course_id' => 11,
                'subchapter_id' => $sc,
                'title' => $title,
                'order' => $order,
                'is_assignment' => false,
                'content' => $content,
            ]);
        }

        echo "Zbirka seeder done!\n";
    }
}
