<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

use App\Models\Lesson;

$lessons = Lesson::where('course_id', 9)->get();

// Serbian → Romanian replacements for startercode and instructions
$replacements = [
    // Code comments and print strings (longer first!)
    "DOMACI ZADATAK: Predstavi se!" => "TEMA PENTRU ACASA: Prezinta-te!",
    "DOMACI ZADATAK: Poster za omiljeni film/seriju/igricu" => "TEMA PENTRU ACASA: Poster pentru filmul/serialul/jocul preferat",
    "DOMACI ZADATAK: Moj ljubimac" => "TEMA PENTRU ACASA: Animalul meu de companie",
    "DOMACI ZADATAK: Detektiv tipova" => "TEMA PENTRU ACASA: Detectivul tipurilor",
    "DOMACI ZADATAK: Intervju" => "TEMA PENTRU ACASA: Interviu",
    "DOMACI ZADATAK: Prodavnica" => "TEMA PENTRU ACASA: Magazin",
    "DOMACI ZADATAK: Sifrovana poruka" => "TEMA PENTRU ACASA: Mesaj cifrat",
    "DOMACI ZADATAK: Kviz" => "TEMA PENTRU ACASA: Quiz",
    "DOMACI ZADATAK: Restoran" => "TEMA PENTRU ACASA: Restaurant",
    "DOMACI ZADATAK: Crtanje" => "TEMA PENTRU ACASA: Desen",
    "DOMACI ZADATAK: Igrica pogadjanja!" => "TEMA PENTRU ACASA: Jocul de ghicit!",
    "Ovo je tvoj ZAVRSNI projekat!" => "Acesta este PROIECTUL tau FINAL!",
    "Napravi program koji ispisuje 5 recenica o tebi" => "Creaza un program care afiseaza 5 propozitii despre tine",
    "Koristi print() za svaku recenicu" => "Foloseste print() pentru fiecare propozitie",
    "Tvoj kod ide ovde:" => "Codul tau vine aici:",
    "Koristi print('*' * 30) za dekorativne linije" => "Foloseste print('*' * 30) pentru linii decorative",
    "Koristi print() za prazan red" => "Foloseste print() pentru rand gol",
    "Tvoj kod:" => "Codul tau:",
    "Tvoj kod ovde" => "Codul tau aici",
    "Napravi 6 promenljivih i ispisi ih sa f-stringom" => "Creaza 6 variabile si afiseaza-le cu f-string",
    "Ispisi sve koristeci f-string:" => "Afiseaza tot folosind f-string:",
    "Dodaj ispis za svaku promenljivu" => "Adauga afisare pentru fiecare variabila",
    "Napravi po 3 promenljive svakog tipa" => "Creaza cate 3 variabile de fiecare tip",
    "3 cela broja (int):" => "3 numere intregi (int):",
    "dodaj jos 2..." => "adauga inca 2...",
    "3 decimalna broja (float):" => "3 numere zecimale (float):",
    "3 teksta (str):" => "3 texte (str):",
    "Ispisi svaku sa tipom:" => "Afiseaza fiecare cu tipul:",
    "Dodaj za ostale..." => "Adauga pentru restul...",
    "Dodaj pitanje za godinu rodjenja (int)" => "Adauga intrebare pentru anul nasterii (int)",
    "Izracunaj godine: 2026 - godina_rodjenja" => "Calculeaza varsta: 2026 - anul_nasterii",
    "Dodaj pitanje za omiljenu hranu (str)" => "Adauga intrebare pentru mancarea preferata (str)",
    "Dodaj pitanje za sate za kompjuterom (float)" => "Adauga intrebare pentru ore la calculator (float)",
    "Izracunaj sate nedeljno" => "Calculeaza orele saptamanale",
    "Ispisi ostale rezultate sa f-stringom" => "Afiseaza restul rezultatelor cu f-string",
    "Dodaj pitanja za mleko i cokoladu" => "Adauga intrebari pentru lapte si ciocolata",
    "Izracunaj ukupnu cenu" => "Calculeaza pretul total",
    "Ispisi ukupno" => "Afiseaza totalul",
    "Pitaj koliko novca kupac daje" => "Intreaba cati bani da cumparatorul",
    "Izracunaj kusur ili koliko fali" => "Calculeaza restul sau cat mai lipseste",
    "Ispisi ime naopako" => "Afiseaza numele invers",
    "Ispisi svako drugo slovo" => "Afiseaza fiecare a doua litera",
    "Ispisi velikim slovima sa tackama" => "Afiseaza cu majuscule cu puncte",
    "Ispisi koliko slova ima" => "Afiseaza cate litere are",
    "Ispisi prvo i poslednje slovo" => "Afiseaza prima si ultima litera",
    "Dodaj jos 4 pitanja po istom principu" => "Adauga inca 4 intrebari dupa acelasi principiu",
    "Koristi if/elif/else da postavis cenu" => "Foloseste if/elif/else pentru a seta pretul",
    "Na osnovu izbora" => "In functie de alegere",
    "Pitaj za desert i pice" => "Intreaba pentru desert si bautura",
    "Ispisi ukupan racun" => "Afiseaza nota totala",
    "1. Kvadrat 5x5" => "1. Patrat 5x5",
    "2. Trougao (1 zvezdica, pa 2, pa 3...)" => "2. Triunghi (1 steluta, apoi 2, apoi 3...)",
    "3. Obrnuti trougao (5 zvezdica, pa 4, pa 3...)" => "3. Triunghi inversat (5 stelute, apoi 4, apoi 3...)",
    "Napravi petlju za 5 pokusaja" => "Creaza o bucla pentru 5 incercari",
    "U svakom pokusaju:" => "La fiecare incercare:",
    "Pitaj za broj" => "Cere un numar",
    "Povecaj pokusaje za 1" => "Creste incercarile cu 1",
    "Proveri: veci, manji ili pogodak?" => "Verifica: mai mare, mai mic sau ghicit?",
    "Ako pogodi: ispisi bravo i prekini petlju" => "Daca ghiceste: afiseaza bravo si opreste bucla",
    "Ako nije pogodio posle 5 pokusaja:" => "Daca nu a ghicit dupa 5 incercari:",
    "ispisi koji je broj bio" => "afiseaza care a fost numarul",

    // Print strings
    "'Zdravo, svete!'" => "'Salut, lume!'",
    "'Zdravo!'" => "'Salut!'",
    "'Zdravo, ja sam'" => "'Salut, eu sunt'",
    "'Zdravo, '" => "'Salut, '",
    "'Zdravo! Ja sam kompjuter.'" => "'Salut! Eu sunt un calculator.'",
    "'Ucim da programiram u Python-u.'" => "'Invat sa programez in Python.'",
    "'Ovo je moj prvi program sa vise linija!'" => "'Acesta este primul meu program cu mai multe linii!'",
    "'=== MOJ PROFIL ==='" => "'=== PROFILUL MEU ==='",
    "'Ime: Ana'" => "'Nume: Ana'",
    "'Razred: 6'" => "'Clasa: 6'",
    "'Hobi: programiranje'" => "'Hobby: programare'",
    "'ovde napisi svoje ime'" => "'scrie aici numele tau'",
    "'Ime:'" => "'Nume:'",
    "'Godine:'" => "'Varsta:'",
    "'Razred:'" => "'Clasa:'",
    "Ime:" => "Nume:",
    "Godine:" => "Varsta:",
    "Razred:" => "Clasa:",
    "'Moj najbolji drug:'" => "'Cel mai bun prieten:'",
    "'Dodaj ispis za ostale'" => "'Adauga afisare pentru restul'",
    "'Na pocetku imam'" => "'La inceput am'",
    "'bodova'" => "'puncte'",
    "'Posle prvog zadatka imam'" => "'Dupa prima sarcina am'",
    "'Posle drugog zadatka imam'" => "'Dupa a doua sarcina am'",
    "bodovi" => "puncte",
    "'Pocinjem igru! Imam'" => "'Incep jocul! Am'",
    "'Resio sam prvi zadatak! Sada imam'" => "'Am rezolvat prima sarcina! Acum am'",
    "'Resio sam i drugi! Sada imam'" => "'Am rezolvat si a doua! Acum am'",
    "'Bonus! Sada imam'" => "'Bonus! Acum am'",
    "'Pogledajmo sta je u kutijama'" => "'Sa vedem ce este in cutii'",
    "'Pravimo tri kutije (promenljive)'" => "'Facem trei cutii (variabile)'",
    "'Ana'" => "'Ana'",
    "# Popuni podatke o najboljem drugu/drugarici" => "# Completeaza datele celui mai bun prieten",
    "ime_druga" => "nume_prieten",
    "godine_druga" => "varsta_prieten",
    "omiljeni_sport" => "sport_preferat",
    "omiljena_boja" => "culoare_preferata",
    "omiljena_hrana" => "mancare_preferata",
    "omiljeni_predmet" => "materie_preferata",
    "# Probaj da napravi" => "# Incearca sa creezi",
    "moje_ime" => "numele_meu",
    "moj_razred" => "clasa_mea",
    "moja_godina" => "varsta_mea",
    "'Ja sam'" => "'Eu sunt'",
    "'Idem u'" => "'Sunt in'",
    "'razred'" => "'clasa'",
    "'Imam'" => "'Am'",
    "'godina'" => "'ani'",
    "Kako se zoves" => "Cum te cheama",
    "'Drago mi je!'" => "'Imi pare bine!'",
    "Koliko imas godina" => "Cati ani ai",
    "'Ti imas'" => "'Tu ai'",
    "'godina.'" => "'ani.'",
    "'Sledece godine ces imati'" => "'Anul viitor vei avea'",
    "'godina!'" => "'ani!'",
    "Koliko" => "Cate",
    "'Unesi'" => "'Introdu'",
    "Unesi" => "Introdu",
    "Izaberi" => "Alege",
    "# Dodaj" => "# Adauga",
    "# Ispisi" => "# Afiseaza",
    "# Napravi" => "# Creaza",
    "# Tvoj" => "# Al tau",
    "# ispisi" => "# afiseaza",
    "'=== INTERVJU ==='" => "'=== INTERVIU ==='",
    "'=== REZULTATI ==='" => "'=== REZULTATE ==='",
    "'=== ANKETA ==='" => "'=== ANCHETA ==='",
    "'=== PRODAVNICA ==='" => "'=== MAGAZIN ==='",
    "'=== MENI ==='" => "'=== MENIU ==='",
    "'=== KVIZ ==='" => "'=== QUIZ ==='",
    "Cena hleba" => "Pretul painii",
    "Koji je glavni grad Srbije" => "Care este capitala Romaniei",
    "'Beograd'" => "'Bucuresti'",
    "Tacan odgovor je Beograd" => "Raspunsul corect este Bucuresti",
    "'Tacno!'" => "'Corect!'",
    "'Netacno!" => "'Gresit!",
    "poeni" => "puncte_quiz",
    "Osvojio si" => "Ai obtinut",
    "od 5 poena" => "din 5 puncte",
    "'Pica — 500 din'" => "'Pizza — 25 lei'",
    "'Pasta — 400 din'" => "'Paste — 20 lei'",
    "'Cevapi — 450 din'" => "'Mici — 22 lei'",
    "'Salata — 300 din'" => "'Salata — 15 lei'",
    "'Supa — 250 din'" => "'Supa — 12 lei'",
    "Izaberi jelo (1-5)" => "Alege felul (1-5)",
    "Koji je tvoj omiljeni" => "Care este preferatul tau",
    "Koliko je stepeni napolju" => "Cate grade sunt afara",
    "Koje su sanse za kisu" => "Care sunt sansele de ploaie",
    "Koliko bodova na testu" => "Cate puncte la test",
    "'Kvadrat:'" => "'Patrat:'",
    "'Trougao:'" => "'Triunghi:'",
    "'Obrnuti trougao:'" => "'Triunghi inversat:'",
    "Zamislio sam broj od 1 do 20" => "Am gandit un numar de la 1 la 20",
    "Zelis li ponovo" => "Vrei sa joci din nou",
    "'da'" => "'da'",
    "Hvala sto si igrao" => "Multumesc ca ai jucat",
    "'Bravo!'" => "'Bravo!'",
    "'Veci!'" => "'Mai mare!'",
    "'Manji!'" => "'Mai mic!'",
    "pokusaji" => "incercari",
    "pogodio" => "ghicit",
    "tajni_broj" => "numar_secret",
    "# Zameni komentare" => "# Inlocuieste comentariile",
    "prosecna_ocena" => "media_notelor",
    "ime_grada" => "nume_oras",
    "broj_ucenika" => "numar_elevi",
    "broj_telefona" => "numar_telefon",
    "moj_broj" => "numarul_meu",
    "'O MENI'" => "'DESPRE MINE'",
    "'============================='" => "'=============================='",
    "print('Originalno:" => "print('Original:",
    "godine_rodjenja" => "anul_nasterii",
    "# ovde stavi koliko imas godina" => "# aici pune cati ani ai",
    "# ovde napisi svoj razred" => "# aici scrie clasa ta",
    "# ovde napisi svoje ime" => "# aici scrie numele tau",
    "tezina" => "greutate",
    "voli_da" => "ii_place_sa",
    "ime_ljubimca" => "nume_animal",
    "godine_ljubimca" => "varsta_animal",
    "hleb" => "paine",
    "racun" => "nota",
    "Moj" => "Al meu",
    "vrsta" => "tip_animal",
];

foreach ($lessons as $lesson) {
    $content = $lesson->content;

    // Sort by length descending to replace longer strings first
    uksort($replacements, function($a, $b) {
        return strlen($b) - strlen($a);
    });

    foreach ($replacements as $sr => $ro) {
        $content = str_replace($sr, $ro, $content);
    }

    $lesson->content = $content;
    $lesson->save();
    echo "Fixed lesson {$lesson->id} - {$lesson->title}\n";
}

echo "\nDone!\n";
